phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probationary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Prov. for Public Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Prov. for Public Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exempt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delegated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular Public Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <valueField>$Source.State__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Provider State</description>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>License_Renewal_Fee__c</fullName>
        <description>TO DELETE . NOT IN USE. To be deleted as per story LEAD-2099</description>
        <label>License Renewal Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>License_Upgrade_Fee__c</fullName>
        <description>TO DELETE . NOT IN USE. To be deleted as per story LEAD-2099</description>
        <label>License Upgrade Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_License_Fee__c</fullName>
        <description>TO DELETE . NOT IN USE. To be deleted as per story LEAD-2099</description>
        <label>New License Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Assigned_User_Email__c</fullName>
        <description>Email address for the record&apos;s assigned user. Will be updated via a field update every time the record is updated and/or created</description>
        <inlineHelpText>Email address for the record&apos;s assigned user</inlineHelpText>
        <label>Assigned User Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Caring_For_Children_Not_Related__c</fullName>
        <label>Caring For Children Not Related</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Caring_for_other_peoples_children_Hr_Wk__c</fullName>
        <inlineHelpText>Caring for other people’s children in your home with a valid license (Daycare center/nursery school) - Hours per Week</inlineHelpText>
        <label>Other Children -Daycare/Nursery - Hrs/Wk</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Caring_for_other_peoples_children_Month__c</fullName>
        <inlineHelpText>Caring for other people’s children in your home with a valid license (Daycare center/nursery school) - Months</inlineHelpText>
        <label>Other Children -Daycare/Nursery - Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Caring_for_other_peoples_children_Years__c</fullName>
        <inlineHelpText>Caring for other people’s children in your home with a valid license (Daycare center/nursery school) - Years</inlineHelpText>
        <label>Other Children -Daycare/Nursery - Years</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Caring_for_your_own_children_Hrs_Week__c</fullName>
        <inlineHelpText>Hours per week of caring for your own children</inlineHelpText>
        <label>Caring for your own children - Hrs/Week</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probationary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Missing_Elements_For_Licensor_2__c</fullName>
        <label>Missing Elements For Licensor</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Provider Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Licensing_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>FCC_Change_of_Household</fullName>
        <active>true</active>
        <label>FCC Change of Household</label>
    </recordTypes>
    <recordTypes>
        <fullName>FCC_Renewal</fullName>
        <active>true</active>
        <label>FCC Renewal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TestLicensingTransactionTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class EEC_TestLicensingTransactionTrigger {

    static testMethod void testLicensingTransactionTrigger() {
        EEC_TestUtil.mockLeadConfig('Family Child Care', null);
        Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.MockCity());
        RecordType r = [select Id from RecordType where DeveloperName='FCC_Change_of_Household' and sobjecttype='Licensing_Transaction__c'];
        Licensing_Transaction__c lic = new Licensing_Transaction__c(RecordTypeId=r.Id,Status__c='Submitted', Provider__c=accnt.Id,Submitter__c=Userinfo.getUserId());
        lic.Assigned_User_Email__c = 'test@email.com';
        insert lic;
        EEC_TestUtil.mockHouseHold(lic, accnt);
        
    }
    
    //      Licensing_Transaction__c ltResult = [Select Missing_Elements_For_Licensor_2__c From Licensing_Transaction__c where id= :lic.id];
    //    system.assertEquals(ltResult.Missing_Elements_For_Licensor_2__c, 'Status Incorrect - License Expiration Date not filled -License Issue Date not filled - License Requested not filled - License Type not filled - Exp. / Training Not Reviewed - Licensee CORI Missing - SORI Missing - Licensee DCF Missing - Other Info Not Reviewed - Conditions Not Finalized - Need Manager Approval');
  
   static testMethod void testMissingElementsForLicensor() {
    
        Lead_Configuration__c ld = new Lead_Configuration__c();
        ld.name = 'FCC Assistant';
        ld.New_License_Fee__c = 75;
        ld.License_Renewal_Fee__c = 25;
        ld.License_Upgrade_Fee__c = 25;
        ld.RecordTypeId = [select Id from RecordType where Name='Per Provider Type' and sobjecttype='Lead_Configuration__c'].Id;
        insert ld;
    
   
        Account a = new Account();
        a.Name = 'Test FCC Assistant';
        a.RecordTypeId = [select Id from RecordType where SobjectType = 'Account' and Name = 'FCC Assistant'].id;
        a.License_Status__c = 'Not Licensed';
        a.License_Type__c = 'Regular Assistant';
        a.Preferred_Language__c = 'English';
        a.Provider_Address_1__c = '1212';
        a.Provider_Email__c = 'test@test.com';
        a.State__c = 'MA';
        a.Provider_City__c = EEC_TestUtil.mockCity().Id;
        a.Provider_Zip_Code__c = '90270';
        a.Config_Record__c = ld.id;
        insert a;
        RecordType r = [select Id from RecordType where Name='FCC Assistant New License' and sobjecttype='Licensing_Transaction__c'];
        Licensing_Transaction__c FCCAssistlic = new Licensing_Transaction__c(RecordTypeId=r.Id,Status__c='Submitted', Provider__c=a.Id,Submitter__c=Userinfo.getUserId());
        FCCAssistlic.Caring_For_Children_Not_Related__c = '2';
        FCCAssistlic.Caring_for_other_peoples_children_Hr_Wk__c = 2;
        FCCAssistlic.Caring_for_other_peoples_children_Month__c = 2;
        FCCAssistlic.Caring_for_other_peoples_children_Years__c = 2;
        FCCAssistlic.Caring_for_your_own_children_Hrs_Week__c = 2;
        FCCAssistlic.Caring_for_your_own_children_Months__c = 2;
        FCCAssistlic.Caring_for_other_peoples_children_Years__c = 2;
        FCCAssistlic.Caring_for_your_own_children_Years__c = 2;
        FCCAssistlic.Other_Children_Kindergarten_Hrs_Week__c = 2;
        FCCAssistlic.Other_Children_Kindergarten_Months__c =2;         
        FCCAssistlic.Other_Children_Kindergarten_Years__c = 2;
        FCCAssistlic.Charged_or_Arrested_for_Crime__c = 'No';
        FCCAssistlic.Dealings_with_Child_Prot_Child_Welfar__c = 'No';
        FCCAssistlic.Abused_or_neglected_a_child__c = 'No';
        FCCAssistlic.Use_of_Alcoholic_Bev_Narcotics_Drugs__c ='No';
        FCCAssistlic.Restraining_Order_Issued__c ='No';
        FCCAssistlic.Registering_as_Sex_Offender__c ='No';
        FCCAssistlic.Took_Medication_Administration_Training__c ='No';
        FCCAssistlic.Took_Transportation_Training__c ='No';
        FCCAssistlic.Took_SIDS_Training__c = 'No';
        FCCAssistlic.Took_USDA_Nutrition_Training__c ='No';
        FCCAssistlic.Took_FCC_Orientation_Module_1__c = 'No';
        FCCAssistlic.CPR_Certified__c ='No';
        FCCAssistlic.First_Aid_Certified__c ='No';
        FCCAssistlic.Taken_Intro_to_EEC_in_Mass_Orientation__c = 'No';
        FCCAssistlic.Daily_Routine_and_Activities__c ='Test Routines';
        FCCAssistlic.Medical_Emergency_Steps__c = 'Test Medical Emergency steps';
        FCCAssistlic.Steps_for_Guiding_Child_Behavior__c = 'Test steps for guiding child behavior';
        
        test.startTest();
        insert FCCAssistlic; 
       
        update FCCAssistlic;
        test.stopTest();
       
       Licensing_Transaction__c ltResult = [Select Missing_Elements_For_Licensor_2__c From Licensing_Transaction__c where id= :FCCAssistlic.id];
        
       if(ltResult != null){
           
        // Boolean result=ltResult.Missing_Elements_For_Licensor_2__c.contains('Status Incorrect - License Expiration Date not filled -License Issue Date not filled - License Requested not filled - License Type not filled - Exp. / Training Not Reviewed - Licensee CORI Missing - SORI Missing - Licensee DCF Missing - Other Info Not Reviewed - Conditions Not Finalized - Need Manager Approval');
         system.assertEquals(ltResult.Missing_Elements_For_Licensor_2__c != null,true); 
       }

      



  
    }
   /*static testMethod void testLTRenewal() {
        EEC_TestUtil.mockLeadConfig('Family Child Care', null);
        Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.MockCity());
        RecordType r = [select Id from RecordType where DeveloperName='FCC_Renewal' and sobjecttype='Licensing_Transaction__c'];
        Licensing_Transaction__c lic = new Licensing_Transaction__c(RecordTypeId=r.Id,Status__c='Submitted', Provider__c=accnt.Id,Submitter__c=Userinfo.getUserId());
        insert lic;
        EEC_TestUtil.mockHouseHold(lic, accnt);
        
    }
    
    static testMethod void testLTChangeOfHousehold() {
        Account accnt = EEC_TestUtil.loadLicenseTransaction();
        RecordType r = [select Id from RecordType where DeveloperName='FCC_Change_of_Household' and sobjecttype='Licensing_Transaction__c'];
        Licensing_Transaction__c lic = new Licensing_Transaction__c(RecordTypeId=r.Id,Status__c='Submitted', Provider__c=accnt.Id,Submitter__c=Userinfo.getUserId());
        insert lic;
        EEC_TestUtil.mockHouseHold(lic, accnt);
        
    }*/
    
}