phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Provider_With_Licensing_Transaction__c</fullName>
        <formula>IF(
OR(

 RecordType.Name = &quot;Group Care&quot;,
 RecordType.Name = &quot;Temporary Shelter&quot;,
 RecordType.Name = &quot;Adoption Agency&quot;,
 RecordType.Name = &quot;Foster Care Agency&quot;,
 RecordType.Name = &quot;Large Group&quot;,
 RecordType.Name = &quot;Small Group&quot;,
 RecordType.Name = &quot;Family Child Care&quot;,
 RecordType.Name = &quot;FCC Assistant&quot;

),

TRUE,

FALSE
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Provider With Licensing Transaction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <description>Provider.Status</description>
        <label>Provider Status</label>
        <picklist>
            <controllingField>License_Status__c</controllingField>
            <picklistValues>
                <fullName>Application To Be Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended to PPM Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New application in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Enrollment Freeze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-open in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Status under review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Renewal_Workflow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is check by the daily Renewal batch if Expiration Date of the license is in 120 days. When checked, it&apos;ll trigger a workflow that sends emails / reminders</description>
        <label>Start Renewal Workflow</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_BatchFCCLicenseRenewal.cls
global class EEC_BatchFCCLicenseRenewal implements Database.Batchable <sObject>{
    
    String pQuery = '';
    global EEC_BatchFCCLicenseRenewal(String query)
    {
        this.pQuery =  query;
    }
    
    global EEC_BatchFCCLicenseRenewal()
    {
        this.pQuery =  'Select Id,name,Start_Renewal_Workflow__c,License_Status__c,Renewal_date__c,Recordtype.Name,Is_Provider_With_Licensing_Transaction__c, OwnerId,Provider_Status__c from Account  where License_Status__c = \'Licensed\' ' +
                                                               ' and (Recordtype.Name = \'Family Child Care\' OR Recordtype.Name = \'FCC Assistant\' '+ 
            												   ' OR Recordtype.Name = \'Group Care\' ' +
                                                         	   ' OR Recordtype.Name = \'Adoption Agency\' ' +
                                                         	   ' OR Recordtype.Name = \'Temporary Shelter\' ' +
                                                               ' OR Recordtype.Name = \'Foster Care Agency\' ' +
                                                               ' OR Recordtype.Name = \'Large Group\' ' +    
                                                         	   ' OR Recordtype.Name = \'Small Group\') ';
         //for testing for Ben
         //this.pQuery = 'Select id,name,Start_Renewal_Workflow__c,Renewal_date__c,Recordtype.Name,Is_Provider_With_Licensing_Transaction__c, OwnerId,License_Status__c from Account where id =\'0012100000LKWEZ\' ';                                                	   
    }
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator(pQuery);
    } 
     
    global void execute(Database.BatchableContext BC, List <Account> providerList)
    {    
        Set<Id> provIds = new Set<Id>();
        Date cDate =  System.today();
        List<Account> providerupdatelist = new List<Account>();
        List<Task> providerTasks = new List<Task>();
                        
        for(Account provider : providerList){
            
            Task tsk = new Task();
            tsk.WhatId = provider.Id;
            tsk.OwnerId = provider.OwnerId;
            tsk.Status = 'Not Started';
            tsk.Priority = 'High';
          
          //FCC Assistant Update
          
          if(provider.Renewal_date__c != null && provider.License_Status__c != null)
          system.debug('MMMM'+provider.Renewal_date__c.addDays(30)+cdate+provider.License_Status__c);
          {                                                      
            if (cdate == provider.Renewal_date__c.addDays(30) && provider.License_Status__c=='Licensed' &&!provider.License_Status__c.contains('freeze') &&(provider.Recordtype.Name == 'Group Care'
                || provider.Recordtype.Name == 'Adoption Agency' || provider.Recordtype.Name == 'Foster Care Agency' || provider.Recordtype.Name == 'Small Group' || provider.Recordtype.Name == 'Large Group')){
               
               tsk.Subject = Provider.name + ' - Renewal Application Not Submitted - 30 days after expiration notice';
               tsk.ActivityDate = Date.today().addDays(2);
               tsk.Priority = 'Normal';
               if(provider.Recordtype.Name == 'FCC Assistant')
                       tsk.Priority = 'High';  
            }
            
            else{
                if (cdate == provider.Renewal_date__c && provider.License_Status__c=='Licensed' && (provider.Recordtype.Name == 'Group Care'|| 
                   provider.Recordtype.Name == 'Adoption Agency' || provider.Recordtype.Name == 'Foster Care Agency' || provider.Recordtype.Name == 'Small Group' || provider.Recordtype.Name == 'Large Group')){
                   tsk.Subject = Provider.name + ' - Renewal Application Not Submitted - On expiration date notice';
                   tsk.ActivityDate = Date.today().addDays(2);
                }
                else if (cdate == provider.Renewal_date__c.addDays(-30) && provider.License_Status__c=='Licensed' && Provider.Is_Provider_With_Licensing_Transaction__c==true ){
                   
                       tsk.Priority = 'Normal';
                   tsk.Subject = Provider.name + ' - Renewal Application Not Submitted - 30 days prior expiration notice';
                   tsk.ActivityDate = Date.today().addDays(5);
                
                }
                else{
                  List<Licensing_Transaction__c>  r =[SELECT Id, Provider__c FROM Licensing_Transaction__c 
                                                    WHERE Provider__c  = :provider.Id 
                                                    AND (Recordtype.Name = 'FCC Renewal' 
                                                         OR Recordtype.Name = 'FCC Assistant Renewal'
                                                         OR Recordtype.Name = 'GSA Renewal'
                                                         OR Recordtype.Name = 'Placement Renewal'
                                                         OR Recordtype.Name = 'Residential Renewal') 
                                                    AND (Submission_Date__c >= :cDate - 365 ) 
                                                    AND status__c in ('Submitted','Under Review','Pending Manager Approval','Approved By Manager','Closed (License Issued / Updated)')];
                  
                  if ((provider.Renewal_date__c.addDays(45) >= cDate) && Provider.Is_Provider_With_Licensing_Transaction__c==true && (provider.Renewal_date__c.addDays(-120) <= cDate) && r.size() == 0 && provider.License_Status__c == 'Licensed' /*-- F. Lecoq / 03/15/2016 - LEAD3432 -- && provider.Start_Renewal_Workflow__c == false*/ ){                     
                     system.debug('MMMMM'+provider.Renewal_date__c+Provider.Is_Provider_With_Licensing_Transaction__c+Provider.License_Status__c);
                     provider.Start_Renewal_Workflow__c = true;
                  }
                 else{
                     provider.Start_Renewal_Workflow__c = false;
                 }
                } 
             } 
             providerupdatelist.add(provider);
             providerTasks.add(tsk);
          }
             
         }
                       
        if (providerupdatelist <> null && providerupdatelist.size() > 0){
               
            Database.update(providerupdatelist);
            Database.insert(providerTasks);
        }
       
    }  
    
    global void finish(Database.BatchableContext BC)
    {
        
    }
}