phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Foster_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Foster Parent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Cases</description>
        <label>Investigation</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This investigation is associated with another provider.</errorMessage>
            <filterItems>
                <field>Investigation__c.Provider_No__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Associated Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Program Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact_Role__c.object
<CustomObject>
    <description>This is a junction object between a provider and contact. A single contact may play multiple roles for a provider like Owner, Administrator etc.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact to which contact role is associated with.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Formula__c</fullName>
        <formula>AND (
OR ( ISBLANK(Start_Role_Licensing_Transaction__c),  ISPICKVAL(Start_Role_Licensing_Transaction__r.Status__c, &quot;Closed (License Issued / Updated)&quot;), ISPICKVAL(Start_Role_Licensing_Transaction__r.Status__c, &quot;Closed (Processed)&quot;))
,
OR(
AND(ISBLANK( Start_Date__c ), ISBLANK( End_Date__c )),
AND(ISBLANK( End_Date__c), Start_Date__c &lt;= TODAY()),
AND(Start_Date__c &lt;= TODAY(), End_Date__c &gt;= TODAY())
))</formula>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Account to which the contact is associated with.</description>
        <label>Provider / Umbrella</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Role that the contact plays for the provider associated.</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Director / Administrative Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Additional_Inspection_Item_Name__c</fullName>
        <description>Allow user to name this additional inspection item</description>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Associated_regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For non standard items, this lookup allows the user to select the regulation associated with this inspection item.</description>
        <label>Associated regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <description>Date the corrective actions were or will be implemented. This information should be provided by the provider when filling the answer of statement of non-compliance.</description>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inspection_Item_Name__c</fullName>
        <formula>Standard_Inspection_Item__r.Name</formula>
        <label>Visit Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <inlineHelpText>Mention here the date the corrective actions were implemented or the expected date of completion</inlineHelpText>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <inlineHelpText>Describe here the non-compliance</inlineHelpText>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Non_Compliant_Item_Regulation__c.object
<CustomObject>
    <description>Junction between non compliant items and regulations so multiple regulations can be added to one non-compliant item.</description>
    <fields>
        <fullName>Non_Compliant_Item__c</fullName>
        <label>Non Compliant Item</label>
        <referenceTo>Non_Compliant__c</referenceTo>
        <relationshipLabel>Associated Regulations</relationshipLabel>
        <relationshipName>Non_Compliant_Item_Regulations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Non Compliant Item Regulations</relationshipLabel>
        <relationshipName>Non_Compliant_Item_Regulations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non Compliant Item Regulation</label>
    <nameField>
        <displayFormat>NC-R-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Regulation_Number__c</fullName>
        <formula>IF(CONTAINS(Name,&quot;_&quot;),LEFT(Name,LEN(Name)-9),Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Regulation Number</label>
        <type>Text</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_GenerateInvestigationPDFBase.cls
public abstract with sharing class EEC_GenerateInvestigationPDFBase {    

    private Investigation__c inv;

    public EEC_GenerateInvestigationPDFBase(ApexPages.StandardController ctr){
        inv = [
            SELECT Provider_No__c,Name, Provider_No__r.Name,
            (SELECT CaseNumber, CreatedDate FROM Cases__r),
            (SELECT ID FROM Inspections__r), 
            (SELECT ID FROM Non_Compliant_Item__r)
            FROM Investigation__c 
            WHERE Id = :ctr.getId()
        ]; 
    } 
    
    public class InvestigationVisitChecklistItemWrapper {
        public Inspection_Item__c inspectionItem { get; set; }
        public String standardRegulations { get; set; }
        public Non_Compliant__c nonCompliantItem { get; set; }
        
        public InvestigationVisitChecklistItemWrapper(Inspection_Item__c inspItem, Non_Compliant__c nc, String regs) {
            this.inspectionItem = inspItem;
            this.standardRegulations = regs;
            this.nonCompliantItem = nc;
        }
    } 
    
    private static Map<ID, Standard_Inspection_Item__c> standardInspectionItems = new Map<ID, Standard_Inspection_Item__c>([
            SELECT Id, (SELECT Regulation__r.Name, Regulation__r.Regulation_Number__c FROM Junction_InspRegs__r) 
            FROM Standard_Inspection_Item__c]);
    
    public Contact getDirectorContact() {
        Account acc = [select id,RecordTypeId,RecordType.Name from Account where id=:inv.Provider_No__c];
    if(acc.RecordType.Name == 'FCC Assistant'){
       List<Contact> acrs = [
            SELECT Salutation, FirstName, LastName 
            FROM Contact 
            WHERE AccountID = :inv.Provider_No__c AND Role__c = 'Director' 
            ORDER BY CreatedDate DESC 
            LIMIT 1
        ];
        
        if(acrs.size() > 0) {
            return acrs.get(0);
        }
        else{
          List<Contact> acrs1 = [
            SELECT Salutation, FirstName, Contact.LastName 
            FROM Contact 
            WHERE AccountID = :inv.Provider_No__c AND Role__c like 'Main Contact%' 
            ORDER BY CreatedDate DESC 
            LIMIT 1];
            if(acrs1.size() > 0) {
              return acrs1.get(0);
            }
        }
    }else{
       List<Contact_Role__c> acrs = [
            SELECT Contact__c FROM Contact_Role__c 
            WHERE Provider__c = :inv.Provider_No__c AND Role__c = 'Executive Director' AND Current_Formula__c =true
            ORDER BY CreatedDate DESC 
            LIMIT 1
        ];
        if(acrs.size()>0){
        List<Contact> acrs1 = [SELECT Salutation, FirstName, Contact.LastName 
                FROM Contact 
                WHERE ID =: acrs[0].Contact__c
                ORDER BY CreatedDate DESC 
                LIMIT 1];
                
        if(acrs1.size() > 0) {
            return acrs1.get(0);
        }
        else{
          List<Contact_Role__c> conRList = [
            SELECT Contact__c FROM Contact_Role__c  
            WHERE Provider__c = :inv.Provider_No__c AND Role__c like 'Main Contact%' 
            ORDER BY CreatedDate DESC 
            LIMIT 1];
            
             List<Contact> contactList = [SELECT Salutation, FirstName, Contact.LastName 
                FROM Contact 
                WHERE ID =: conRList[0].Contact__c
                ORDER BY CreatedDate DESC 
                LIMIT 1];
                
                if(contactList.size() > 0) {
                  return contactList.get(0);
                }
            }
        }
    }
        
        return null;
    }
    
 
    public Datetime getOldestCaseDate(){
        Datetime d = null;
         
        for(Case c : inv.Cases__r){  
            if(d == null){
                d = c.CreatedDate;
            }
        
            if(d > c.CreatedDate){
                d = c.CreatedDate;
            }
        
        } 
        
        return d;
    }
 
    public String getCaseNumbers(){
        String ret = '';
         
        for(Case c : inv.Cases__r){
            System.debug(c);
        
            if(ret != ''){
                ret += ', ';
            }
            
            ret += c.CaseNumber;
        } 
        
        return ret;
    }
    
       public string getProviderName(){
        String ret = '';
        
        if(inv.Provider_No__r.Name.indexOf(',') > -1){
        	String[] rets = inv.Provider_No__r.Name.split(',');
            ret = rets[1] + ' ' + rets[0];
        }
        else 
            ret = inv.Provider_No__r.Name;
        
        return ret;
    }
    
    public String getInvestigationNumber(){
        String ret = '';
        
        String[] rets = inv.Name.split('#');
        if(rets.size() > 0)
        	ret = rets[1];
        
        return ret;
    }
    
    
    public List<InvestigationVisitChecklistItemWrapper> getOustandingComplianceIssues(){
        List<InvestigationVisitChecklistItemWrapper> items = new List<InvestigationVisitChecklistItemWrapper>();
        
        items.addAll(getInspecitonItems());
        items.addAll(getNonCompliantItems());
        
        return items;
    }
    
    public List<InvestigationVisitChecklistItemWrapper> getInspecitonItems(){ 
        List<InvestigationVisitChecklistItemWrapper> items = new List<InvestigationVisitChecklistItemWrapper>();
        Set<ID> inspIds = new Set<ID>(); 
        
        for(Inspection__c i : inv.Inspections__r){
            inspIds.add(i.Id);
        }
        
        List<Inspection__c> is = [
            SELECT (SELECT 
                Standard_Inspection_Item__c, 
                Associated_regulation__r.Name, 
                Associated_regulation__r.Regulation_Number__c, 
                Inspection_Item_Name__c, Date_Implemented__c, 
                Additional_Inspection_Item_Name__c, ID,
                Observations__c, Correction_Plan__c 
                FROM Inspection_Items__r
                WHERE Inspection_Result__c = 'Non-Compliant')
            FROM Inspection__c
            WHERE ID IN :inspIds
        ];
         
        
        for(Inspection__c i : is) {
            for(Inspection_Item__c row : i.Inspection_Items__r ){ 
                String regs = '';
                
                if(row.Standard_Inspection_Item__c != null){
                    Standard_Inspection_Item__c sii = standardInspectionItems.get(row.Standard_Inspection_Item__c); 
                        
                    for(Junction_InspReg__c jir : sii.Junction_InspRegs__r){
                        if(regs != ''){
                            regs += ', ';
                        }
                    
                        regs += jir.Regulation__r.Regulation_Number__c;
                    }
                }
                
                items.add(new InvestigationVisitChecklistItemWrapper(row, null, regs));
            } 
        }
        
        return items;
    }
    
    public List<InvestigationVisitChecklistItemWrapper> getNonCompliantItems(){ 
        List<InvestigationVisitChecklistItemWrapper> items = new List<InvestigationVisitChecklistItemWrapper>();
        Set<ID> ncIds = new Set<ID>();
        
        for(Non_Compliant__c nc : inv.Non_Compliant_Item__r){
            ncIds.add(nc.Id);
        }
        
        List<Non_Compliant__c> ncItems = [
            SELECT Observations__c, Date_Implemented__c, Correction_Plan__c,
            (SELECT Id, Regulation__r.Name, Regulation__r.Regulation_Number__c  FROM Non_Compliant_Item_Regulations__r)
            FROM Non_Compliant__c
            WHERE ID in :ncIds
        ];
         
        for(Non_Compliant__c item : ncItems) {
            String ret = '';
            
            for(Non_Compliant_Item_Regulation__c itemRegs : item.Non_Compliant_Item_Regulations__r){
                if(ret != ''){
                    ret += ', ';
                }
                
                ret += itemRegs.Regulation__r.Regulation_Number__c;
            }
            items.add(new InvestigationVisitChecklistItemWrapper(null, item, ret));
        }
        
        return items;
    }
}