phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <valueField>$Source.State__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_city_text__c</fullName>
        <formula>Provider_City__r.Name</formula>
        <label>Provider_city_text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Provider State</description>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Umbrella</fullName>
        <active>true</active>
        <description>Umbrella</description>
        <label>Umbrella</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>NewUmbrella_Alternate_Phone__c</fullName>
        <description>Alternate Phone of the new umbrella that provider can request for new license transaction.</description>
        <label>Alternate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_City__c</fullName>
        <description>City of the new umbrella that provider can request for new license transaction.</description>
        <label>City</label>
        <length>28</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Date_of_Incorporation__c</fullName>
        <description>Date of Incorporation of the new umbrella that provider can request for new license transaction.</description>
        <label>Date of Incorporation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Director_Email__c</fullName>
        <description>Director Email of the new umbrella that provider can request for new license transaction.</description>
        <label>Director Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Director_First_Name__c</fullName>
        <description>Director First Name of the new umbrella that provider can request for new license transaction.</description>
        <label>Director First Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Director_Last_Name__c</fullName>
        <description>Director Last Name of the new umbrella that provider can request for new license transaction.</description>
        <label>Director Last Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Director_Phone__c</fullName>
        <description>Director Phone of the new umbrella that provider can request for new license transaction.</description>
        <label>Director Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Director_Title__c</fullName>
        <description>Director Title of the new umbrella that provider can request for new license transaction.</description>
        <label>Director Title</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Email__c</fullName>
        <description>Email of the new umbrella that provider can request for new license transaction.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Fax__c</fullName>
        <description>Fax of the new umbrella that provider can request for new license transaction.</description>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Phone__c</fullName>
        <description>Phone of the new umbrella that provider can request for new license transaction.</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Place_of_Incorporation__c</fullName>
        <label>Place of Incorporation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_State__c</fullName>
        <description>State of the new umbrella that provider can request for new license transaction.</description>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Street_Address_1__c</fullName>
        <description>Street Address 1 of the new umbrella that provider can request for new license transaction.</description>
        <label>Street Address 1</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Street_Address_2__c</fullName>
        <description>Street Address 1 of the new umbrella that provider can request for new license transaction.</description>
        <label>Street Address 2</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewUmbrella_Zip_Code__c</fullName>
        <description>Zip Code of the new umbrella that provider can request for new license transaction.</description>
        <label>Zip Code</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>New_Umbrella_Business_Name__c</fullName>
        <description>Business Name of the new umbrella that provider can request for new license transaction.</description>
        <label>New Umbrella Business Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Umbrella_Name__c</fullName>
        <description>Name of the new umbrella that provider can request for new license transaction.</description>
        <label>New Umbrella Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_UmbrellaLookupController.cls
public without sharing class EEC_UmbrellaLookupController {
    
  public String umbrellaName { get; set; }
  public String cityName{get;set;}
  public String errorMessage { get; set; }
  public String umbrellaId {get; set;}
  public List<Account> queryResults { get; set; }
  public  String licenseTransationId {get;set;} 
  public Licensing_Transaction__c licensingTransaction{get;set;}
  public boolean isNewUmbrella{get;set;}
  
  public EEC_UmbrellaLookupController() {
  	isNewUmbrella = false;
    licenseTransationId  = ApexPages.currentPage().getParameters().get('licenseTransationId');
    queryResults = new List<Account>();
    licensingTransaction = [select Id, Name,
    New_Umbrella_Name__c,
New_Umbrella_Business_Name__c,
NewUmbrella_Place_of_Incorporation__c,
NewUmbrella_Date_of_Incorporation__c,
NewUmbrella_Street_Address_1__c,
NewUmbrella_Street_Address_2__c,
NewUmbrella_State__c,
NewUmbrella_City__c,
NewUmbrella_Zip_Code__c,
NewUmbrella_Phone__c,
NewUmbrella_Alternate_Phone__c,
NewUmbrella_Fax__c,
NewUmbrella_Email__c,
NewUmbrella_Director_First_Name__c,
NewUmbrella_Director_Last_Name__c,
NewUmbrella_Director_Title__c,
NewUmbrella_Director_Phone__c,
NewUmbrella_Director_Email__c from Licensing_Transaction__c where Id=: licenseTransationId];
 }
    
  public PageReference query() {
  	try{
		queryResults = new List<Account>();
      	errorMessage = '';
        
        if (String.isBlank(umbrellaName) && String.isBlank(cityName)) {
        	errorMessage = 'Enter at least one criteria before you start your search';
            return null;
		}
        if (!String.isBlank(umbrellaName)) {
	       umbrellaName = '%'+umbrellaName+'%';
        }
        if (!String.isBlank(cityName)) {
           cityName = '%'+cityName+'%';
        }
        queryResults = [select Id, Name, Provider_Address_1__c, Provider_city_text__c, Provider_Zip_Code__c , State__c
              				from Account where RecordType.Name = 'Umbrella' and (Name like : umbrellaName or Provider_City__r.Name like : cityName)];
        if (queryResults.size() == 0) {
            errorMessage = 'Based on these criteria, no Umbrella were found. Please review your search criteria.';
        }
	} catch(Exception e) {
    	System.debug('Error: ' + e.getMessage());
        errorMessage = 'An error has occured attempting to get your results. Please try again.';
    }
    return null;
  }
  
  public PageReference addUmbrella(){
  	try{  		
        licensingTransaction = EEC_ContactRoleUtil.updateLicensingTransaction(licensingTransaction);
  	}
  	 catch(Exception e) {
    	System.debug('Error: ' + e.getMessage());
        errorMessage = 'An error has occured attempting to save new umbrella. Please try again later.';
    }
    return null;
  }
}