phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Electronic_Communication__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, emails and documents will be sent electronically. Also, electronic signature will be required. If unchecked, all communication will be paper and the email address is not mandatory.</description>
        <inlineHelpText>If checked, emails and documents will be sent electronically. Also, electronic signature will be required.</inlineHelpText>
        <label>Electronic Communication</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region_Address__c</fullName>
        <description>Region Address to be used in Email Templates.</description>
        <formula>Region__r.Street__c &amp; &quot;, &quot; &amp;   Region__r.City__c  &amp; &quot;, &quot; &amp;   Region__r.State__c  &amp; &quot; &quot; &amp;  Region__r.Zip__c</formula>
        <label>Region Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_Email__c</fullName>
        <description>Region Email address to be used in Email Templates.</description>
        <formula>Region__r.Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_Fax__c</fullName>
        <description>Fax number associated with the Region, to be used in Email Templates.</description>
        <formula>Region__r.Fax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region Fax</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_Phone__c</fullName>
        <description>This field is the region phone number and is used in email templates.</description>
        <formula>Region__r.Phone__c</formula>
        <label>Region Phone</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Electronic_Communication__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this provider will be using the portal and receive electronic communication from EEC.</inlineHelpText>
        <label>Electronic Communication</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Assigned_To_Phone__c</fullName>
        <formula>Assigned_To__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned To Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Licensing_Transactions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_User_Email__c</fullName>
        <description>Email address for the record&apos;s assigned user. Will be updated via a field update every time the record is updated and/or created</description>
        <inlineHelpText>Email address for the record&apos;s assigned user</inlineHelpText>
        <label>Assigned User Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Associated_Fee__c</fullName>
        <label>Associated Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Provider Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Confirmation_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set this value to TRUE when Change of Address - Automatically Send Submission Confirmation to the Provider
Other_Transactions_Automatically_Send_Submission_Confirmation_to_the_Provid
New_License_Renewal_Upgrade_Automatically_Send_Submission_Confirmation</description>
        <label>Submission Confirmation Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitter_Email_Address__c</fullName>
        <description>Submitter email address used in email templates.</description>
        <formula>Submitter__r.Email</formula>
        <label>Submitter Email Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Licensing_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_SendEmailProvider.cls
public  class EEC_SendEmailProvider {
    @InvocableMethod 
    public static void sendEmail(list<string> templateAndRecordID){
    	string recordid;
    	string tempid;
    	for(string tempRec : templateAndRecordID){
    	   Recordid = tempRec.substringAfter('|');
    	   tempid = tempRec.substringbefore('|');
    	   system.debug('MMMM'+Recordid+tempid);
    	}
     EmailTemplate template47a = [SELECT Body,brandtemplateid,Subject,HtmlValue FROM EmailTemplate WHERE DeveloperName = 'X47a_Transaction_Electronic_Submission_Confirmation_New_App_Renewal_Upgrade'];
     EmailTemplate template92a = [SELECT Body,brandtemplateid,Subject,HtmlValue FROM EmailTemplate WHERE DeveloperName = 'X92a_FCC_Assistant_Transaction_submission_confirmation_NewLicense_Renewal_Upgra'];
     BrandTemplate bt = [SELECT Id,Value FROM BrandTemplate WHERE Id =: template47a.brandtemplateid LIMIT 1];	
     
     set<id> ltset = new set<id>();
     
     list<Licensing_Transaction__c> lList = [select id,name,Status__c,Source__c,RecordType.Name,Assigned_User_Email__c,Submission_Confirmation_Sent__c,
                                             Provider__c,Assigned_To__c,Associated_Fee__c,Provider__r.Region_Address__c,Provider__r.recordtype.name,
                                             Assigned_To_Phone__c,Provider__r.Region_Fax__c,Provider__r.Region_Phone__c,Provider__r.Electronic_Communication__c,
                                             Provider__r.Region_Email__c,Submitter__c,Submitter__r.ContactId,Submitter__r.id,Submitter_Email_Address__c from Licensing_Transaction__c where id =: recordid];
      list<OrgWideEmailAddress> orgList = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = 'EEC LEAD Alert'];
      for(Licensing_Transaction__c ltran: lList){
       ltset.add(ltran.Submitter__r.ContactId);
      }
      List<Contact> c = [select id, Email from Contact where Id IN: ltset];	
      if(c.size() >0){
         system.debug('MMMM'+c[0].id);
      
	      for(Licensing_Transaction__c lt: lList){
	      EEC_EmailUtil email = new EEC_EmailUtil();
	      email.saveAsActivity = false;
	      string fee = string.valueof(lt.Associated_Fee__c);
	     
	          
		  PageReference pdf = Page.EEC_EmailRegionPDF;
	      pdf.getParameters().put('id',(String)lt.id);
		  pdf.setRedirect(true);
		  Blob b = pdf.getcontent();
	          
		  Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
		  efa.setFileName('RegionInfo.pdf');
		  efa.setBody(b);
		  system.debug('MMMMM'+efa);
		  email.FileAttachments = new list<Messaging.EmailFileAttachment>();
	      email.FileAttachments.add(efa);
		  email.targetObjectId = c[0].Id;
		   email.orgWideEmailId = orglist[0].id;
	      email.toAddresses = new List<String>();
	      //email.toAddresses.add(lt.Submitter_Email_Address__c);
	      email.whatid=lt.id;
	      if(tempid == '47a'){
	      email.templateid= template47a.id;   
		  string htmlBody = template47a.HtmlValue;
	      htmlBody = htmlBody.replace('{!Licensing_Transaction__c.Provider__c}', lt.Provider__c)
	                    .replace('{!Licensing_Transaction__c.RecordType}', lt.recordtype.name)
	                    .replace('{!Licensing_Transaction__c.Associated_Fee__c}',fee)
	                    .replace('{!Account.Region_Address__c}', lt.Provider__r.Region_Address__c)
	                    .replace('{!Licensing_Transaction__c.Assigned_To__c}', lt.Assigned_To__c)
	                    .replace('{!Licensing_Transaction__c.Assigned_To_Phone__c}', lt.Assigned_To_Phone__c)
	                    .replace('{!Licensing_Transaction__c.Assigned_User_Email__c}', lt.Assigned_User_Email__c)
	                    .replace('{!Account.Region_Phone__c}', lt.Provider__r.Region_Phone__c);
	            //system.debug('MMMM'+email.htmlBody);
	            //email.targetObjectId= c.id; 
	            
	      //email.htmlBody = htmlBody;
	      email.subject = template47a.Subject;
	      }else if(tempid == '92a'){
	      email.templateid= template92a.id;
	      email.subject = template92a.Subject;
	      string htmlBody = template92a.HtmlValue;
	      htmlBody = htmlBody.replace('{!Licensing_Transaction__c.Provider__c}', lt.Provider__c)
	                    .replace('{!Licensing_Transaction__c.RecordType}', lt.recordtype.name)
	                    .replace('{!Licensing_Transaction__c.Associated_Fee__c}',fee)
	                    .replace('{!Account.Region_Address__c}', lt.Provider__r.Region_Address__c)
	                    .replace('{!Licensing_Transaction__c.Assigned_To__c}', lt.Assigned_To__c)
	                    .replace('{!Licensing_Transaction__c.Assigned_To_Phone__c}', lt.Assigned_To_Phone__c)
	                    .replace('{!Licensing_Transaction__c.Assigned_User_Email__c}', lt.Assigned_User_Email__c)
	                    .replace('{!Account.Region_Phone__c}', lt.Provider__r.Region_Phone__c);
	      }
	      System.debug('MMMMM'+email.toAddresses);
	      email.sendEmail();
	     }
    }
    
   }
}