phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Large_Group</fullName>
        <active>true</active>
        <description>Large Group and school age</description>
        <label>Large Group</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact_Role__c.object
<CustomObject>
    <description>This is a junction object between a provider and contact. A single contact may play multiple roles for a provider like Owner, Administrator etc.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Account to which the contact is associated with.</description>
        <label>Provider / Umbrella</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document__c.object
<CustomObject>
    <description>A custom object to be used for non-Salesforce reference documents.</description>
    <fields>
        <fullName>Approved_for_Future_Usage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Future Usage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>The file&apos;s content meta type.</description>
        <label>Content Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Type</label>
        <referenceTo>Document_Type__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes relating to the document.</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>DateTime</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC- {0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document_Type__c.object
<CustomObject>
    <description>An object for storing all document types. This is not to be confused with document prototypes (i.e. image/jpeg, document/pdf, etc)</description>
    <fields>
        <fullName>Allow_use_of_Umbrella_Level_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Use of Umbrella Level Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>A description for the document type.</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Individual_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Individual Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEAD_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Provider Type</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Document Types</relationshipLabel>
        <relationshipName>Document_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Need_to_be_Updated_at_each_new_Transacti__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Update Each New Transaction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Transactio_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Optional for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Related_Role__c</fullName>
        <label>Related Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Director / Administrative Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Contact</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Required_for_Transaction_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Required for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Document Type</label>
    <nameField>
        <label>Document Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Main Contact / Licensee</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Director / Administrative Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <recordTypes>
        <fullName>Per_Transaction_Type</fullName>
        <active>true</active>
        <description>Give Configuration options based on Transaction type</description>
        <label>Per Transaction Type</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>GSA_New_License</fullName>
        <active>true</active>
        <description>Request for a new license as GSA provider</description>
        <label>GSA New License</label>
    </recordTypes>
    <recordTypes>
        <fullName>Large_Group</fullName>
        <active>true</active>
        <description>This record type supports the License record for Large Group</description>
        <label>Large Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/S3_File__c.object
<CustomObject>
    <description>This is an object for storing S3 file representations.</description>
    <fields>
        <fullName>Acl__c</fullName>
        <description>The access control level of the file.</description>
        <label>Acl</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>The name of the bucket the file is contained in.</description>
        <label>Bucket</label>
        <length>125</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>The content type of the file.</description>
        <label>Content_Type</label>
        <length>125</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection between the S3 File reference and the Document__c object.</description>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>S3 Files</relationshipLabel>
        <relationshipName>S3_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <description>The name of the file.</description>
        <label>Filename</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prefix__c</fullName>
        <description>The prefix for the file.</description>
        <inlineHelpText>The originating object&apos;s ID typically.</inlineHelpText>
        <label>Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_AttachmentSelectionControllertest.cls
@istest
public class EEC_AttachmentSelectionControllertest {
    @isTest
    static void testAttachmentSelectionController() {        
        //insert Account
        Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('GSA New License', null);
        RecordType r = [SELECT Id FROM RecordType WHERE DeveloperName='Per_Transaction_Type' AND sObjectType='Lead_Configuration__c'];
        config2.RecordTypeId = r.Id;
        update config2;
        
        Lead_Configuration__c config = EEC_TestUtil.mockLeadConfig('Large Group', null);
        
        Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'Large_Group');
        accnt.Config_Record__c = config2.Id;
        update accnt;
        
        //insert Contact
        Contact contact = EEC_TestUtil.mockContact(accnt, 'Test', 'LastName', '');
        //insert Contactrole   
        Contact_Role__c contactRole = EEC_TestUtil.mockContactRole('Partner', contact.Id, accnt.Id);
        contactRole = EEC_TestUtil.mockContactRole('Administrative Designee', contact.Id, accnt.Id);
        contactRole = EEC_TestUtil.mockContactRole('Program Director / Administrative Head', contact.Id, accnt.Id);
        contactRole = EEC_TestUtil.mockContactRole('Board Chair', contact.Id, accnt.Id); 
        contactRole = EEC_TestUtil.mockContactRole('Owner', contact.Id, accnt.Id);
        //creating user
        User portaluser = EEC_TestUtil.mockPortalUser(contact);
        
        Licensing_Transaction__c  lic = EEC_TestUtil.mockAssistantLicenseTransaction(accnt, 'GSA_New_License');

        //insert Document Type
        List<Document_Type__c> listDocumentType = new List<Document_Type__c>();
        Document_Type__c docType = new Document_Type__c();
        docType.Allow_use_of_Umbrella_Level_Document__c = true;
        docType.Name = 'Doc Type 1';
        docType.Description__c ='Test Description';
        docType.Individual_Document__c = false;
        docType.Need_to_be_Updated_at_each_new_Transacti__c = true;
        docType.Optional_for_Transactio_Type__c = 'GSA New License';
        docType.Related_Role__c = '';
        docType.LEAD_Configuration__c = config2.Id;
        docType.Required_For_Transaction_Type__c = 'GSA New License';
        listDocumentType.add(docType);
        
        docType = new Document_Type__c();
        docType.Allow_use_of_Umbrella_Level_Document__c = true;
        docType.Name = 'Doc Type 2';
        docType.Description__c ='Test Description';
        docType.Individual_Document__c = true;
        docType.Need_to_be_Updated_at_each_new_Transacti__c = true;
        docType.Optional_for_Transactio_Type__c = 'GSA New License';
        docType.Related_Role__c = 'Administrative Designee';
        docType.LEAD_Configuration__c = config2.Id;        
        docType.Required_For_Transaction_Type__c = 'GSA New License'; 
        listDocumentType.add(docType);
        
        insert listDocumentType;
         
        //Insert Document
        List<Document__c> listDocument = new List<Document__c>();
        Document__c document = new Document__c();        
        document.Provider__c = accnt.Id;
        //document.Notes__c = 'Test Notes';
        document.Document_Type__c = listDocumentType[0].Id;
        document.Content_Type__c = 'jpg';
        document.Approved_for_Future_Usage__c = False;
        document.Valid_To__c = DateTime.now();
        document.Valid_From__c = null;
        document.Document_Name__c = 'testdocs1';
        
        listDocument.add(document);
        
        document = new Document__c();
        document.Provider__c = accnt.Id;
        document.Notes__c = 'Test Notes';
        document.Document_Type__c = listDocumentType[1].Id;
        document.Content_Type__c = 'jpg';
        document.Approved_for_Future_Usage__c = True;
        document.Valid_To__c = DateTime.now();
        document.Valid_From__c = DateTime.now();
        document.Document_Name__c = 'testdocs2';
        listDocument.add(document);
        
        document = new Document__c();
        document.Provider__c = accnt.Id;
        document.Notes__c = 'Test Notes';
        document.Document_Type__c = listDocumentType[0].Id;
        document.Content_Type__c = 'jpg';
        document.Approved_for_Future_Usage__c = True;
        document.Valid_To__c = DateTime.now();
        document.Valid_From__c =  DateTime.now();
        document.Document_Name__c = 'testdocs3';
        listDocument.add(document);
        
        insert listDocument;
        
        //Insert S3File
        List<S3_File__c> listFiles = new List<S3_File__c>();
        S3_File__c files = new S3_File__c();
        files.Filename__c = 'testFile';
        files.Content_Type__c = 'image/png';
        files.Bucket__c = 'test';
        files.Acl__c = 'authenticated-read';
        files.Prefix__c = listDocument[0].Id;   
        files.Document__c = listDocument[0].Id;
        
        listFiles.add(files);
        
        S3_File__c  dltfiles = new S3_File__c();
        dltfiles.Filename__c = 'testFile2';
        dltfiles.Content_Type__c = 'image/png';
        dltfiles.Bucket__c = 'test';
        dltfiles.Acl__c = 'authenticated-read';
        dltfiles.Prefix__c = listDocument[0].Id;   
        dltfiles.Document__c = listDocument[0].Id;        
        listFiles.add(dltfiles); 
        
        insert listFiles;
        
        EEC_BaseAttachmentsExtensionTest.loadMock();
        EEC_TestUtil.mockAWSKeys();
        
        AWS_Config__c aws_config = new AWS_Config__c(S3_Bucket_Name__c = 'eec-lead'); 
        insert aws_config; 
        
        ApexPages.currentPage().getParameters().put('id', listDocument[0].Id);
        ApexPages.currentPage().getParameters().put('transactionId',lic.Id);
        ApexPages.currentPage().getParameters().put('type','A');
        
        System.runAs(portaluser){
            test.startTest();         
            EEC_AttachmentSelectionController mp = new EEC_AttachmentSelectionController();  
            mp.doCreateDocument();
            
            mp.doBack();
            
            string filebody = '[{"Filename__c":"file1.csv","Prefix__c":"'+listDocument[0].Id+'","Content_Type__c":"application/vnd.ms-excel","Acl__c":"authenticated-read","Bucket__c":"eec-lead-integration"}]';
            ApexPages.currentPage().getParameters().put('attachmentbody', filebody);
            ApexPages.currentPage().getParameters().put('attachmentdeletebody', filebody);
            mp.doSave();
            
            ApexPages.currentPage().getParameters().put('id', listDocument[1].Id);
            mp.doSave();
            
            ApexPages.currentPage().getParameters().put('id', '');
            mp = new EEC_AttachmentSelectionController();  
            mp.doCreateDocument();
            
            String exampleJson = '[{"filename": "testName", "type": "image/png"}]'; 
            
            List<Map<String,String>> result = EEC_AttachmentSelectionController.generateMultiplePolicySignature('eec', 'authenticated-read', exampleJson);
            test.stopTest();
        }
    }
}