phase2_Dev/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_LicenseCertificatePDF.cls
public class EEC_LicenseCertificatePDF {

     public Licensing_Transaction__c ld;
    
     public EEC_LicenseCertificatePDF(ApexPages.StandardController std){
        Id id = std.getId();
        ld = [SELECT Id,Name, Provider__c FROM Licensing_Transaction__c WHERE Id = :id]; 
   	 }
     
     public PageReference savePDF(){
     	
     	Account acc = [Select Id,name, RecordTypeId From Account Where Id=:ld.Provider__c];
     	Map<Id,RecordType> accountRTMap = new Map<Id,RecordType>([Select id,Name from RecordType where sObjectType = 'Account' and isActive = true]);
        string rtName = null;
        PageReference pagePdf;
        
        if (acc != null){
            rtName = accountRTMap.get(acc.RecordTypeId).Name;
        }
        
        if(rtName == 'Family Child Care'){
            pagePdf = pdfPageReference();
        }
        else if (rtName == 'FCC Assistant'){
        	pagePdf = pdfFCCAssistant();
        }
        else {
            pagePdf = pdfGSACertificatePDF();
        } 
        pagePdf.getParameters().put('id', ld.id); 
        
        
        Attachment a = new Attachment();
        a.Body = Test.isRunningTest() ? Blob.valueOf('UNIT.TEST') : pagePdf.getContentAsPdf();
        a.ParentID = ld.ID;
        a.Name = 'License Certificate-' + ld.Name + '.pdf';
        
        insert a;
                 
        return new PageReference('/' + ld.Id);
    }
    
    public PageReference pdfPageReference(){
        return Page.EEC_LicenseCertificatePDF;
    } 
    
    public PageReference pdfFCCAssistant(){
        return Page.EEC_FCCAssistantLicenseCertPDF;
    }
    
    public PageReference pdfGSACertificatePDF(){
        return Page.EEC_GSARPLicenseCertificatePDF;
    } 
}