phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Umbrella_Members__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field implements a Look Up relationship to create a self relationship in order for the Umbrella record type to display an Umbrella Members related list to display all Providers within the Umbrella</description>
        <label>Umbrella</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected umbrella must be an umbrella record type</errorMessage>
            <filterItems>
                <field>Account.Record_Type_Name__c</field>
                <operation>contains</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Umbrella Members</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Umbrella</fullName>
        <active>true</active>
        <description>Umbrella</description>
        <label>Umbrella</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document__c.object
<CustomObject>
    <description>A custom object to be used for non-Salesforce reference documents.</description>
    <fields>
        <fullName>Approved_for_Future_Usage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Future Usage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Type</label>
        <referenceTo>Document_Type__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes relating to the document.</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC- {0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document_Type__c.object
<CustomObject>
    <description>An object for storing all document types. This is not to be confused with document prototypes (i.e. image/jpeg, document/pdf, etc)</description>
    <fields>
        <fullName>LEAD_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Provider Type</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Document Types</relationshipLabel>
        <relationshipName>Document_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Type</label>
    <nameField>
        <label>Document Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_DocumentLookupController.cls
public class EEC_DocumentLookupController {

  public String queryStr { get; set; }
  public String docType;
  public String errorMessage { get; set; }
  public String documentId {get; set;}
  public String documentName {get; set;}
  public List<Document__c> queryResults { get; set; }
  public List<DocumentWrapper> listDocumentWrapper { get; set; }
  public String providerId  {get;set;}
  public  String licenseTransationId {get;set;} 
  public Account accDocs{get;set;}
  public Map<Id,Document__c> documentMap;
  public String level{get; set;}  
  public string documentType{get;set;}
  public List<SelectOption> documentTypes{get;set;}
  public string providerType{get;set;}
  
  public class DocumentWrapper{
  	public Document__c document{get;set;}
  	public string levelName{get;set;}
  }  
  
  public EEC_DocumentLookupController() {
    providerId  = ApexPages.currentPage().getParameters().get('providerId');
    licenseTransationId  = ApexPages.currentPage().getParameters().get('licenseTransationId');
    providerType = ApexPages.currentPage().getParameters().get('providerType');
    level = '--None--';
    documentType = '--None--';
    query();
  }
    
  public PageReference query() {
        try {
            accDocs = new Account();
            
            documentTypes = new List<SelectOption>();
        	
        	List<Document_Type__c> listDocumentType = [select Id, Name from Document_Type__c where  LEAD_Configuration__r.Name =: providerType];
        	
        	documentTypes.add(new SelectOption('--None--','--None--'));
        	for(Document_Type__c documentType : listDocumentType){
        		documentTypes.add(new SelectOption(documentType.Id,documentType.Name));	
        	}
        	 listDocumentWrapper = new List<DocumentWrapper>();
            queryResults = new List<Document__c>();
          errorMessage = '';
              if (!String.isBlank(queryStr)) {
               queryStr = '%'+queryStr+'%';
              }
              
        if(level == 'Provider'){
            if(queryStr == null || queryStr == ''){
            	if(documentType != '--None--')
            		accDocs = [select id,Name,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where Document_Type__c =: documentType and Approved_for_Future_Usage__c=true ) from Account where id =:providerId];
            	else
                accDocs = [select id,Name,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where Approved_for_Future_Usage__c=true ) from Account where id =:providerId];           
            }else{  
            	if(documentType != '--None--')
            		accDocs = [select id,Name,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where Document_Type__c =: documentType and (Name Like : queryStr) AND Approved_for_Future_Usage__c=true) From Account where id =:providerId];
            	else
                	accDocs = [select id,Name,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where (Name Like : queryStr) AND Approved_for_Future_Usage__c=true) From Account where id =:providerId];    
   }
                queryResults = accDocs.Documents__r;
                
                for(Document__c document : accDocs.Documents__r){
            	DocumentWrapper DocumentWrapper = new DocumentWrapper();
            	DocumentWrapper.document = document;
            	DocumentWrapper.levelName = 'Provider';
            	listDocumentWrapper.add(DocumentWrapper);
            }
        }else if(level == 'Umbrella') {
            Id umbrellaRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Umbrella').getRecordTypeId();

            Account umbrellaAcc = [select id,Name,Umbrella_Members__c,RecordTypeId from Account where Id =: providerId  Limit 1];
                if(queryStr == ''|| queryStr == null){
                	if(documentType != '--None--')
                    accDocs = [select id,Name,Umbrella_Members__c,RecordTypeId,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.createdDate,Document_Type__r.Name,Approved_for_Future_Usage__c,Provider__c from Documents__r where Document_Type__c =: documentType and Approved_for_Future_Usage__c=true)  From Account where Id =: umbrellaAcc.Umbrella_Members__c And RecordTypeId =: umbrellaRecId Limit 1 ];
                    else
                    accDocs = [select id,Name,Umbrella_Members__c,RecordTypeId,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.createdDate,Document_Type__r.Name,Approved_for_Future_Usage__c,Provider__c from Documents__r where Approved_for_Future_Usage__c=true)  From Account where Id =: umbrellaAcc.Umbrella_Members__c And RecordTypeId =: umbrellaRecId Limit 1 ];
                }else{
                	if(documentType != '--None--')
                	accDocs = [select id,Name,Umbrella_Members__c,RecordTypeId,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.createdDate,Document_Type__r.Name,Approved_for_Future_Usage__c,Provider__c from Documents__r where Document_Type__c =: documentType and (Name Like : queryStr) AND Approved_for_Future_Usage__c=true)  From Account where Id =: umbrellaAcc.Umbrella_Members__c And RecordTypeId =: umbrellaRecId Limit 1 ];
                	else
                    accDocs = [select id,Name,Umbrella_Members__c,RecordTypeId,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.createdDate,Document_Type__r.Name,Approved_for_Future_Usage__c,Provider__c from Documents__r where Document_Type__c =: documentType and (Name Like : queryStr) AND Approved_for_Future_Usage__c=true)  From Account where Id =: umbrellaAcc.Umbrella_Members__c And RecordTypeId =: umbrellaRecId Limit 1 ];
    }
                    queryResults = accDocs.Documents__r;
                    
                     for(Document__c document : accDocs.Documents__r){
            	DocumentWrapper DocumentWrapper = new DocumentWrapper();
            	DocumentWrapper.document = document;
            	DocumentWrapper.levelName = 'Umbrella';
            	listDocumentWrapper.add(DocumentWrapper);
            }
        }else {
               Id umbrellaRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Umbrella').getRecordTypeId();

               Account umbrellaAcc = [select id,Name,Umbrella_Members__c,RecordTypeId from Account where Id =: providerId  Limit 1];
   Account accDocs1 = new Account();
      Account accDocs2 = new Account();
    if(queryStr == null || queryStr == ''){
    	if(documentType != '--None--'){
    		accDocs1 = [select id,Name,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where Document_Type__c =: documentType and Approved_for_Future_Usage__c=true) from Account where id =:providerId];           
     accDocs2 = [select id,Name,Umbrella_Members__c,RecordTypeId,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where Document_Type__c =: documentType and Approved_for_Future_Usage__c=true)  From Account where Id =: umbrellaAcc.Umbrella_Members__c And RecordTypeId =: umbrellaRecId Limit 1 ];
    	}
    	else{
     accDocs1 = [select id,Name,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where Approved_for_Future_Usage__c=true) from Account where id =:providerId];           
     accDocs2 = [select id,Name,Umbrella_Members__c,RecordTypeId,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where Approved_for_Future_Usage__c=true)  From Account where Id =: umbrellaAcc.Umbrella_Members__c And RecordTypeId =: umbrellaRecId Limit 1 ];
    	}
                }else{
                	if(documentType != '--None--'){
                		accDocs1 = [select id,Name,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where Document_Type__c =: documentType and (Name Like : queryStr) AND Approved_for_Future_Usage__c=true) from Account where id =:providerId];           
     accDocs2 = [select id,Name,Umbrella_Members__c,RecordTypeId,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where Document_Type__c =: documentType and (Name Like : queryStr) AND Approved_for_Future_Usage__c=true)  From Account where Id =: umbrellaAcc.Umbrella_Members__c And RecordTypeId =: umbrellaRecId Limit 1 ];
                	}
                	else{
     accDocs1 = [select id,Name,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where (Name Like : queryStr) AND Approved_for_Future_Usage__c=true) from Account where id =:providerId];           
     accDocs2 = [select id,Name,Umbrella_Members__c,RecordTypeId,(select id,Name,Notes__c,Document_Type__c,Document_Type__r.Name,Document_Type__r.createdDate,Approved_for_Future_Usage__c,Provider__c from Documents__r where (Name Like : queryStr) AND Approved_for_Future_Usage__c=true)  From Account where Id =: umbrellaAcc.Umbrella_Members__c And RecordTypeId =: umbrellaRecId Limit 1 ];
                	}     
    }
    queryResults = accDocs1.Documents__r;
                for(Document__c doc: accDocs2.Documents__r){
                    queryResults.add(doc);
                }
        
        
	            for(Document__c document : accDocs1.Documents__r){
	            	DocumentWrapper DocumentWrapper = new DocumentWrapper();
	            	DocumentWrapper.document = document;
	            	DocumentWrapper.levelName = 'Provider';
	            	listDocumentWrapper.add(DocumentWrapper);
	            }
	            
	            for(Document__c document : accDocs2.Documents__r){
	            	DocumentWrapper DocumentWrapper = new DocumentWrapper();
	            	DocumentWrapper.document = document;
	            	DocumentWrapper.levelName = 'Umbrella';
	            	listDocumentWrapper.add(DocumentWrapper);
	            }
            system.debug('value in query results'+queryResults);
                
        }  
        documentMap = new Map<Id,Document__c>();
        for(Document__c doc : queryResults){
            documentMap.put(doc.id,doc);
        }
        
          if (queryResults.size() == 0) {
            errorMessage = 'No results found.';
          }
        } catch(Exception e) {
          System.debug('Error: ' + e.getMessage());
          errorMessage = 'An error has occured attempting to get your results. Please try again later.';
        }
        system.debug('value in query results22222'+queryResults);
    return null;
  }
 
}