phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Can_be_Edited__c</fullName>
        <formula>!AND(OR(ISPICKVAL(Status__c,&apos;Cancelled&apos;), ISPICKVAL(Status__c,&apos;Closed&apos;)),!ISBLANK($UserRole.Name),$UserRole.Name !=&apos;Executive_and_Directors&apos;,$UserRole.Name!=&apos;Regional_Director&apos;,OR(NOT(OR(CONTAINS($UserRole.DeveloperName,&apos;Director&apos;),CONTAINS($UserRole.DeveloperName,&apos;Supervisor&apos;))),AND($UserRole.DeveloperName==&apos;FCC_Supervisor&apos;, Provider_No__r.RecordType.Name != &apos;Family Child Care&apos;), AND($UserRole.DeveloperName==&apos;SLGSA_Supervisor&apos;,Provider_No__r.RecordType.Name != &apos;Large Group&apos;,Provider_No__r.RecordType.Name != &apos;Small Group&apos;), AND($UserRole.DeveloperName==&apos;R_P_Supervisor&apos;, Provider_No__r.RecordType.Name != &apos;Group Care&apos;,Provider_No__r.RecordType.Name != &apos;Temporary Shelter&apos;,Provider_No__r.RecordType.Name != &apos;Adoption Agency&apos;,Provider_No__r.RecordType.Name != &apos;Foster Care Agency&apos;)))</formula>
        <label>Can be Edited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Additional_Inspection_Item_Name__c</fullName>
        <description>Allow user to name this additional inspection item</description>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessed_Date__c</fullName>
        <inlineHelpText>Date the visit item was assessed (= mark compliant / non compliant / not applicable) by the licensor. This date is automatically filled by the system when a result is added for the first time.</inlineHelpText>
        <label>Assessed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Associated_regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For non standard items, this lookup allows the user to select the regulation associated with this inspection item.</description>
        <label>Associated regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_list__c</fullName>
        <description>Domain(Category) used for list.</description>
        <formula>TEXT( Category_additional__c ) &amp; IF(ISPICKVAL(Category_additional__c,&quot;&quot;) , Category_standard__c , &quot;&quot;)</formula>
        <label>Domain (list)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <description>Will be filled by the corrective actions taken by the provider in case of non-compliance</description>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <description>Date the corrective actions were or will be implemented. This information should be provided by the provider when filling the answer of statement of non-compliance.</description>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description_of_inspection_list__c</fullName>
        <description>This is used in related list to display the description no matter the record type</description>
        <formula>Description_of_inspection__c &amp;  Description_of_additional_inspection__c</formula>
        <label>Description (list)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discussed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Discussed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Key_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this visit item is identified as a key indicator = associated to a regulation flagged as high risk</inlineHelpText>
        <label>Key Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Assessed_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, it means that this visit item is only for information and does not need to be assessed during the visit</description>
        <inlineHelpText>If checked, this visit item is only for information and does not need to be assessed during the visit</inlineHelpText>
        <label>Non-Assessed Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Technical_Assistance__c</fullName>
        <label>Technical Assistance</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Regulation_Number__c</fullName>
        <formula>IF(CONTAINS(Name,&quot;_&quot;),LEFT(Name,LEN(Name)-9),Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Regulation Number</label>
        <type>Text</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Best_Practices__c.object
<CustomObject>
    <fields>
        <fullName>Best_Practice_Guidance__c</fullName>
        <label>Best Practice Guidance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Standard Best Practices</label>
    <nameField>
        <label>Best Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Best Practices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Visit_Best_Practices__c.object
<CustomObject>
    <fields>
        <fullName>Best_Practice_Guidance__c</fullName>
        <formula>Best_Practice__r.Best_Practice_Guidance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Best Practice Guidance</label>
        <type>Text</type>
    </fields>
    <label>Visit Best Practices</label>
    <nameField>
        <displayFormat>VBP-{0000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Best Practices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/TestInspectVisitModeController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestInspectVisitModeController {

    @isTest  static void testVisitModeController() {
        // Setup test defaults.
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        test.startTest();
        Inspection_Item__c inspItem = EEC_TestUtil.mockInspectionItem(insp, EEC_TestUtil.mockStdInspectionItem(), '', true, '');
        
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        pageRef.getParameters().put('correctionPlan','EEC Accepted');
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        
        // Test the sort direction default when no expression is present.
        ivm.sortExpression = null;
        System.assertEquals(ivm.getSortDirection(), 'ASC');
       
        ivm.selectedCategoryFilter = 'NS';
        ivm.selectedResultFilter = 'NoneSelected';
        ivm.setSortDirection('ASC');
        ivm.sortExpression = 'name';
        // Call a 2nd time to hit alternate flow.
        ivm.sortExpression = 'name';
        ivm.getSortDirection();
        ivm.getCatFilterOptions();
        ivm.getFilterOptions();
        ivm.getInspectionItemData();
        ivm.lockVisitMode();
        ivm.Save();
        ivm.SaveAndCloseVisitMode();
        ivm.NewVisitItemTabletView();
        ivm.SaveItems(); 
        ivm.MarkSelectionCompliant();
        Test.stopTest();
        
        //System.assertNotEquals(null, ivm.SaveAndAddNewVisitItem());
        //System.assertEquals(null, ivm.MarkCompliant());
        
        
    }

    static testMethod void testStandardVistiModeSelectOption(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        insp = [SELECT Id,Start_Time__c,End_Time__c, Status__c, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c from Inspection__c where Id = :insp.Id];
        Inspection_Item__c inspItem = EEC_TestUtil.mockInspectionItem(insp, EEC_TestUtil.mockStdInspectionItem(), '', true, '');
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        
        Test.startTest();
        System.assertNotEquals(ivm.getStdBestPractices(), null);
        pageRef.getParameters().put('reason','sbpDomain');
        pageRef.getParameters().put('mode','1');
        System.assertEquals(ivm.retrieveBestPracticeListForDomain(), null);
        ivm.SaveReason();
    }
    @isTest  static void testAddVisitModeController() {
        // Setup test defaults.
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        test.startTest();
        Inspection_Item__c inspItem = EEC_TestUtil.mockInspectionItem(insp, EEC_TestUtil.mockStdInspectionItem(), '', true, '');
        
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        pageRef.getParameters().put('correctionPlan','EEC Accepted');
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        
        // Test the sort direction default when no expression is present.
        ivm.sortExpression = null;
        System.assertEquals(ivm.getSortDirection(), 'ASC');
       
        ivm.selectedCategoryFilter = 'NS';
        ivm.selectedResultFilter = 'NoneSelected';
        ivm.setSortDirection('ASC');
        ivm.sortExpression = 'name';
        // Call a 2nd time to hit alternate flow.
        
        ivm.getInspectionItemData();
        ivm.visitModeLocked = true;
        ivm.lockVisitMode();
        ivm.visitModeLocked = false;
        ivm.CancelAndCloseVisitMode();
        ivm.SaveItems();
        ivm.autoSave();
        ivm.MarkCompliantTabletView();
        Test.stopTest();
        
        
    }
    static testMethod void testDeleteVisitMode(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        insp = [select Id,Start_Time__c,End_Time__c, Status__c, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c from Inspection__c where Id = :insp.Id];
        Inspection_Item__c inspItem = EEC_TestUtil.mockInspectionItem(insp, EEC_TestUtil.mockStdInspectionItem(), '', true, '');
        Inspection_Item__c inspItemDeleted = EEC_TestUtil.mockInspectionItem(insp, EEC_TestUtil.mockStdInspectionItem(), '', true, '');
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();

        Test.startTest();
        // Add a simple list to the controller.
	ivm.lockVisitMode();
        iiWrapperList.add(new InspectVisitModeController.InspectionListWrapper(0, new Inspection_Item__c(), null));
        ivm.iiWrapperList = iiWrapperList;
        // Test the marking of a compliant. 
        ivm.MarkCompliant();
        // Assert that the wrapper list has at least one element.
        System.assert(ivm.iiWrapperList.size() > 0 ? true : false);
        for(InspectVisitModeController.InspectionListWrapper iiw : ivm.iiWrapperList) {
            System.assertEquals('Compliant', iiw.result);
            break;
        }
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        // Create and add a new InspectionListWrapper.
        InspectVisitModeController.InspectionListWrapper ilw = new InspectVisitModeController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        // Create and add a new InspectionListWrapper that is expected to be deleted.
        InspectVisitModeController.InspectionListWrapper ilwDeleted = new InspectVisitModeController.InspectionListWrapper(0, inspItemDeleted, null);
        ilwDeleted.isDeleted = true;
        iiWrapperList.add(ilwDeleted);
        // Set the wrapper list in the controller.
        ivm.iiWrapperList = iiWrapperList;
        // Attempt to update and save the items.
        ivm.Save();
        ivm.filterCriteria = 'all'; 
        ivm.markBulkAssessForDomain();
        ivm.retrieveBestPracticeListForDomain();
        ivm.getStdBestPractices();
       
       // ivm.markBulkAssessForDomain(); 
        
        // Set a null deleteIndex for false path.
        ApexPages.currentPage().getParameters().put('deleteIndex','');
        System.assertEquals(null, ivm.DeleteInspectionItem());
        
        // Setup the positive path for DeleteInspectionItem().
        Test.stopTest();
    }


    static testMethod void testDeleteVisitMode1(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
         
        Test.startTest();  
        insp = [select Id, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c,Status__c,Start_Time__c from Inspection__c where Id = :insp.Id];
       
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.selectedResultFilter = 'NoneSelected'; 
        ivm.selectedCategoryFilter ='NS';
         List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();

        // Add a simple list to the controller. 
        
        iiWrapperList.add(new InspectVisitModeController.InspectionListWrapper(0, new Inspection_Item__c(), null));
        ivm.iiWrapperList = iiWrapperList;
        // Test the marking of a compliant.
       ivm.MarkCompliant(); 
        ivm.lockVisitMode(); 
        // Assert that the wrapper list has at least one element.
       System.assert(ivm.iiWrapperList.size() > 0 ? true : false);
        for(InspectVisitModeController.InspectionListWrapper iiw : ivm.iiWrapperList) {
            System.assertEquals('Compliant', iiw.result);
            break;
        }  
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        // Create and add a new InspectionListWrapper.
        InspectVisitModeController.InspectionListWrapper ilw = new InspectVisitModeController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        // Create and add a new InspectionListWrapper that is expected to be deleted.
        //InspectVisitModeController.InspectionListWrapper ilwDeleted = new InspectVisitModeController.InspectionListWrapper(0, inspItemDeleted, null);
        //ilwDeleted.isDeleted = true;
       // iiWrapperList.add(ilwDeleted); 
        // Set the wrapper list in the controller.
        ivm.iiWrapperList = iiWrapperList;
        // Attempt to update and save the items.
        
        
        ivm.SaveAndAddNewVisitItem();
        ivm.SaveAndAddNewBP();
        ivm.MarkBulkAssess();
        ivm.StartTimer();
        ivm.endTimer();
        ivm.showDesc();
        ivm.uploadAttachment();
        ivm.SaveBP();
        ivm.DeleteBP();
        Test.stopTest();
    }

    static testMethod void testVistiModeController(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        insp = [SELECT Id,Start_Time__c,End_Time__c, Status__c, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c from Inspection__c where Id = :insp.Id];
        Inspection_Item__c inspItem = EEC_TestUtil.mockInspectionItem(insp, EEC_TestUtil.mockStdInspectionItem(), '', true, '');
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        
        Test.startTest();
        ivm.SaveAndAddNewBP();
        pageRef.getParameters().put('inspId',insp.Id);
        ivm.StartTimer();
        ivm.EndTimer();
        ivm.MarkCompliantTabletView();
    }
    static testMethod void testVistiModeControllerWithHelperClasses(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        insp = [SELECT Id,Start_Time__c,End_Time__c, Status__c, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c from Inspection__c where Id = :insp.Id];
        Inspection_Item__c inspItem = EEC_TestUtil.mockInspectionItem(insp, EEC_TestUtil.mockStdInspectionItem(), '', true, '');
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        
        Test.startTest();
        ivm.SaveAndAddNewBP();
        pageRef.getParameters().put('ids',inspItem.Id);
        ivm.MarkSelectionCompliant();
        System.assertEquals(ivm.uploadAttachment(),null);
        Standard_Best_Practices__c stBP = new Standard_Best_Practices__c(
            Name  = 'test',
            Best_Practice_Guidance__c = 'test',
        	Domain__c = 'Administration');
        insert stBp;
        List<Standard_Best_Practices__c> lstbp = new List<Standard_Best_Practices__c>();
        lstbp.add(stBp);
        pageRef.getParameters().put('bpID',stBp.Id);
        pageRef.getParameters().put('optObservation',inspItem.Id);
        ivm.SaveBP();
        ivm.DeleteBP();
        ivm.processStdBestPractices(lstbp);
    }

    
    static testMethod void testVisitBestPractices(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
        Standard_Best_Practices__c stdbest = EEC_TestUtil.mockStdBestPractice();
        Visit_Best_Practices__c visitpratice = EEC_TestUtil.mockVisitBestPractice(insp,stdbest);
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        pageRef.getParameters().put('bpID',visitpratice.Id);
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.DeleteBP();
        
        
        
    }
    
    
    static testMethod void testMarkSelectionCompliant(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
        test.startTest();
        Standard_Best_Practices__c stdbest = EEC_TestUtil.mockStdBestPractice();
        Visit_Best_Practices__c visitpratice = EEC_TestUtil.mockVisitBestPractice(insp,stdbest);
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        pageRef.getParameters().put('ids',inspItem.id);
        
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.MarkSelectionCompliant();
        test.stopTest();
        
        
    }
    
    static testMethod void testDeleteNoneAssessed(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
         
        Test.startTest();  
        insp = [select Id, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c,Status__c,Start_Time__c from Inspection__c where Id = :insp.Id];
       
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.selectedResultFilter = 'NonAssessed'; 
        ivm.selectedCategoryFilter ='NS';
         List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();

        // Add a simple list to the controller. 
        
        iiWrapperList.add(new InspectVisitModeController.InspectionListWrapper(0, new Inspection_Item__c(), null));
        ivm.iiWrapperList = iiWrapperList;
        // Test the marking of a compliant.
       ivm.MarkCompliant(); 
        ivm.lockVisitMode(); 
        // Assert that the wrapper list has at least one element.
       System.assert(ivm.iiWrapperList.size() > 0 ? true : false);
        for(InspectVisitModeController.InspectionListWrapper iiw : ivm.iiWrapperList) {
            System.assertEquals('Compliant', iiw.result);
            break;
        }  
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        // Create and add a new InspectionListWrapper.
        InspectVisitModeController.InspectionListWrapper ilw = new InspectVisitModeController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        // Create and add a new InspectionListWrapper that is expected to be deleted.
        //InspectVisitModeController.InspectionListWrapper ilwDeleted = new InspectVisitModeController.InspectionListWrapper(0, inspItemDeleted, null);
        //ilwDeleted.isDeleted = true;
       // iiWrapperList.add(ilwDeleted); 
        // Set the wrapper list in the controller.
        ivm.iiWrapperList = iiWrapperList;
        // Attempt to update and save the items.
        
        
        ivm.SaveAndAddNewVisitItem();
        ivm.SaveAndAddNewBP();
        ivm.MarkBulkAssess();
        ivm.StartTimer();
        ivm.endTimer();
        ivm.showDesc();
        ivm.uploadAttachment();
        ivm.SaveBP();
        ivm.DeleteBP();
        Test.stopTest();
    }
    
     static testMethod void testKeyIndicators(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
         
        Test.startTest();  
        insp = [select Id, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c,Status__c,Start_Time__c from Inspection__c where Id = :insp.Id];
       
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.selectedResultFilter = 'KeyIndicators'; 
        ivm.selectedCategoryFilter ='NS';
         List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();

        // Add a simple list to the controller. 
        
        iiWrapperList.add(new InspectVisitModeController.InspectionListWrapper(0, new Inspection_Item__c(), null));
        ivm.iiWrapperList = iiWrapperList;
        // Test the marking of a compliant.
       ivm.MarkCompliant(); 
        ivm.lockVisitMode(); 
        // Assert that the wrapper list has at least one element.
       System.assert(ivm.iiWrapperList.size() > 0 ? true : false);
        for(InspectVisitModeController.InspectionListWrapper iiw : ivm.iiWrapperList) {
            System.assertEquals('Compliant', iiw.result);
            break;
        }  
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        // Create and add a new InspectionListWrapper.
        InspectVisitModeController.InspectionListWrapper ilw = new InspectVisitModeController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        // Create and add a new InspectionListWrapper that is expected to be deleted.
        //InspectVisitModeController.InspectionListWrapper ilwDeleted = new InspectVisitModeController.InspectionListWrapper(0, inspItemDeleted, null);
        //ilwDeleted.isDeleted = true;
       // iiWrapperList.add(ilwDeleted); 
        // Set the wrapper list in the controller.
        ivm.iiWrapperList = iiWrapperList;
        // Attempt to update and save the items.
        
        
        ivm.SaveAndAddNewVisitItem();
        ivm.SaveAndAddNewBP();
        ivm.MarkBulkAssess();
        ivm.StartTimer();
        ivm.endTimer();
        ivm.showDesc();
        ivm.uploadAttachment();
        ivm.SaveBP();
        ivm.DeleteBP();
        Test.stopTest();
    }
    
     static testMethod void testCompliant(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
         
        Test.startTest();  
        insp = [select Id, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c,Status__c,Start_Time__c from Inspection__c where Id = :insp.Id];
       
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.selectedResultFilter = 'Non-Compliant'; 
        ivm.selectedCategoryFilter ='NS';
         List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();

        // Add a simple list to the controller. 
        
        iiWrapperList.add(new InspectVisitModeController.InspectionListWrapper(0, new Inspection_Item__c(), null));
        ivm.iiWrapperList = iiWrapperList;
        // Test the marking of a compliant.
       ivm.MarkCompliant();  
        ivm.lockVisitMode(); 
        // Assert that the wrapper list has at least one element.
       System.assert(ivm.iiWrapperList.size() > 0 ? true : false);
        for(InspectVisitModeController.InspectionListWrapper iiw : ivm.iiWrapperList) {
            System.assertEquals('Compliant', iiw.result);
            break;
        }  
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        // Create and add a new InspectionListWrapper.
        InspectVisitModeController.InspectionListWrapper ilw = new InspectVisitModeController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        // Create and add a new InspectionListWrapper that is expected to be deleted.
        //InspectVisitModeController.InspectionListWrapper ilwDeleted = new InspectVisitModeController.InspectionListWrapper(0, inspItemDeleted, null);
        //ilwDeleted.isDeleted = true;
       // iiWrapperList.add(ilwDeleted); 
        // Set the wrapper list in the controller.
        ivm.iiWrapperList = iiWrapperList;
        // Attempt to update and save the items.
        
        
        ivm.SaveAndAddNewVisitItem();
        ivm.SaveAndAddNewBP();
        ivm.MarkBulkAssess();
        ivm.StartTimer();
        ivm.endTimer();
        ivm.showDesc();
        ivm.uploadAttachment();
        ivm.SaveBP();
        ivm.DeleteBP();
        Test.stopTest();
    }
    
    static testMethod void testNotAssessed(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
         
        Test.startTest();  
        insp = [select Id, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c,Status__c,Start_Time__c from Inspection__c where Id = :insp.Id];
       
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.selectedResultFilter = 'NotAssessed'; 
        ivm.selectedCategoryFilter ='NS';
         List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();

        // Add a simple list to the controller. 
        
        iiWrapperList.add(new InspectVisitModeController.InspectionListWrapper(0, new Inspection_Item__c(), null));
        ivm.iiWrapperList = iiWrapperList;
        // Test the marking of a compliant.
       ivm.MarkCompliant();  
        ivm.lockVisitMode(); 
        // Assert that the wrapper list has at least one element.
       System.assert(ivm.iiWrapperList.size() > 0 ? true : false);
        for(InspectVisitModeController.InspectionListWrapper iiw : ivm.iiWrapperList) {
            System.assertEquals('Compliant', iiw.result);
            break;
        }  
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        // Create and add a new InspectionListWrapper.
        InspectVisitModeController.InspectionListWrapper ilw = new InspectVisitModeController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        // Create and add a new InspectionListWrapper that is expected to be deleted.
        //InspectVisitModeController.InspectionListWrapper ilwDeleted = new InspectVisitModeController.InspectionListWrapper(0, inspItemDeleted, null);
        //ilwDeleted.isDeleted = true;
       // iiWrapperList.add(ilwDeleted); 
        // Set the wrapper list in the controller.
        ivm.iiWrapperList = iiWrapperList;
        // Attempt to update and save the items.
        
        
        ivm.SaveAndAddNewVisitItem();
        ivm.SaveAndAddNewBP();
        ivm.MarkBulkAssess();
        ivm.StartTimer();
        ivm.endTimer();
        ivm.showDesc();
        ivm.uploadAttachment();
        ivm.SaveBP();
        ivm.DeleteBP();
        Test.stopTest();
    }
    static testMethod void testNonCompliant(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
         
        Test.startTest();  
        insp = [select Id, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c,Status__c,Start_Time__c from Inspection__c where Id = :insp.Id];
       
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.selectedResultFilter = 'Compliant';   
        ivm.selectedCategoryFilter ='NS';
         List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();

        // Add a simple list to the controller. 
        
        iiWrapperList.add(new InspectVisitModeController.InspectionListWrapper(0, new Inspection_Item__c(), null));
        ivm.iiWrapperList = iiWrapperList;
        // Test the marking of a compliant.
       ivm.MarkCompliant();  
        ivm.lockVisitMode(); 
        // Assert that the wrapper list has at least one element.
       System.assert(ivm.iiWrapperList.size() > 0 ? true : false);
        for(InspectVisitModeController.InspectionListWrapper iiw : ivm.iiWrapperList) {
            System.assertEquals('Compliant', iiw.result);
            break;
        }  
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        // Create and add a new InspectionListWrapper.
        InspectVisitModeController.InspectionListWrapper ilw = new InspectVisitModeController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        // Create and add a new InspectionListWrapper that is expected to be deleted.
        //InspectVisitModeController.InspectionListWrapper ilwDeleted = new InspectVisitModeController.InspectionListWrapper(0, inspItemDeleted, null);
        //ilwDeleted.isDeleted = true;
       // iiWrapperList.add(ilwDeleted); 
        // Set the wrapper list in the controller.
        ivm.iiWrapperList = iiWrapperList;
        // Attempt to update and save the items.
        
        
        ivm.SaveAndAddNewVisitItem();
        ivm.SaveAndAddNewBP();
        ivm.MarkBulkAssess();
        ivm.StartTimer();
        ivm.endTimer();
        ivm.showDesc(); 
        ivm.uploadAttachment();
        ivm.SaveBP();
        ivm.DeleteBP(); 
        Test.stopTest();
    }
    
    
    static testMethod void testNotApplicable(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
         
        Test.startTest();  
        insp = [select Id, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c,Status__c,Start_Time__c from Inspection__c where Id = :insp.Id];
       
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.selectedResultFilter = 'NotApplicable';   
        ivm.selectedCategoryFilter ='NS';
         List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();

        // Add a simple list to the controller. 
        
        iiWrapperList.add(new InspectVisitModeController.InspectionListWrapper(0, new Inspection_Item__c(), null));
        ivm.iiWrapperList = iiWrapperList;
        // Test the marking of a compliant.
       ivm.MarkCompliant();  
        ivm.lockVisitMode(); 
        // Assert that the wrapper list has at least one element.
       System.assert(ivm.iiWrapperList.size() > 0 ? true : false);
        for(InspectVisitModeController.InspectionListWrapper iiw : ivm.iiWrapperList) {
            System.assertEquals('Compliant', iiw.result);
            break;
        }  
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();
        // Create and add a new InspectionListWrapper.
        InspectVisitModeController.InspectionListWrapper ilw = new InspectVisitModeController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        // Create and add a new InspectionListWrapper that is expected to be deleted.
        //InspectVisitModeController.InspectionListWrapper ilwDeleted = new InspectVisitModeController.InspectionListWrapper(0, inspItemDeleted, null);
        //ilwDeleted.isDeleted = true;
       // iiWrapperList.add(ilwDeleted); 
        // Set the wrapper list in the controller.
        ivm.iiWrapperList = iiWrapperList;
        // Attempt to update and save the items.
        
        
        ivm.SaveAndAddNewVisitItem();
        ivm.SaveAndAddNewBP();
        ivm.MarkBulkAssess();
        ivm.StartTimer();
        ivm.endTimer();
        ivm.showDesc();
        ivm.uploadAttachment();
        ivm.SaveBP();
        ivm.DeleteBP();
        Test.stopTest();
    }
    
    static testMethod void testsaveReason(){
         Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
        test.startTest();
        Inspection_Item__c inspItem =[Select id ,name,RecordTypeId,RecordType.Name ,Date_Implemented__c,Observations__c,Non_Assessed_Item__c,Key_Indicator__c,Technical_Assistance__c,Correction_Plan__c,Inspection_Result__c,Discussed__c,Assessed_Date__c,Additional_Inspection_Item_Name__c,Description_of_inspection_list__c,Associated_regulation__c,Category_list__c,Associated_regulation__r.Regulation_Number__c from Inspection_Item__c limit 1];
        PageReference pageRef = Page.InspectVisitMode;
        pageRef.getParameters().put('itemId',inspItem.Id);
        
        Test.setCurrentPage(pageRef); 
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        ivm.SaveReason();
        test.stopTest();
    }

    static testMethod void testprocessStdBestPractices(){   
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();  
       
        Standard_Best_Practices__c stdinsp = EEC_TestUtil.mockStdBestPractice();          
         test.startTest();  
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc); 
        List<Standard_Best_Practices__c> stdBestPractList; 
        stdBestPractList = [Select id ,Best_Practice_Guidance__c From Standard_Best_Practices__c Limit 1];
        ivm.processStdBestPractices(stdBestPractList);
        List<SelectOption> bestPRac = ivm.processStdBestPractices(stdBestPractList);
        test.stopTest();
    }    

    static testMethod void testVisitMode() {
		List<InspectVisitModeController.InspectionListWrapper> iiWrapperList = new List<InspectVisitModeController.InspectionListWrapper>();

		Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        insp = [select Id,Start_Time__c,End_Time__c, Status__c, Provider_No__c,Provider_No__r.RecordType.Name, Name,Can_be_edited__c from Inspection__c where Id = :insp.Id];
		ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        InspectVisitModeController ivm = new InspectVisitModeController(sc);
        
		List<Inspection_Item__c> iiList = [SELECT Id from Inspection_Item__c where Inspection_no__c = :insp.Id];
        ApexPages.currentPage().getParameters().put('deleteIndex','0');
        ApexPages.currentPage().getParameters().put('deleteId',iiList.get(0).Id);
        //ivm.iiWrapperList = iiWrapperList;
        ivm.DeleteInspectionItem();

    }
}