phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <description>Provider.Status</description>
        <label>Provider Status</label>
        <picklist>
            <controllingField>License_Status__c</controllingField>
            <picklistValues>
                <fullName>Application To Be Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended to PPM Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New application in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Enrollment Freeze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-open in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Status under review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Provider_Closed_Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag to make sure the user has been reminded that he/she has created a case on a closed provider.</description>
        <label>Provider Closed Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <formula>TEXT(Account.Provider_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_CaseOnClosedProviderController.cls
public class EEC_CaseOnClosedProviderController {
    
    protected final Case c;

    public EEC_CaseOnClosedProviderController(ApexPages.StandardController ctr){
        this.c = (Case) ctr.getRecord();
    }
    
    public void updateReminder(){
        if((c.Account.Provider_Status__c == 'Voluntary Closure' || 
            c.Account.Provider_Status__c == 'Application Withdrawn / Closed') && 
           c.Account.RecordType.Name != 'Unlicensed Provider' && 
           !c.Provider_Closed_Reminder__c){
           		Case c = [SELECT Id, Provider_Closed_Reminder__c FROM Case WHERE Id =: c.Id];
                c.Provider_Closed_Reminder__c = true;
                update c;
        	}
    }
  }