phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probationary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Prov. for Public Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Prov. for Public Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exempt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delegated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular Public Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <valueField>$Source.State__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <description>Provider.Status</description>
        <label>Provider Status</label>
        <picklist>
            <controllingField>License_Status__c</controllingField>
            <picklistValues>
                <fullName>Application To Be Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended to PPM Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New application in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Enrollment Freeze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-open in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Status under review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region this provider is assigned to</description>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_ConvertContactToContactRoleTest.cls
@isTest
public with sharing class EEC_ConvertContactToContactRoleTest {

    static testMethod void testBatch_ConvertContactToContactRole()	{
        EEC_Batch_ConvertContactToContactRole batchCreateContactRole = new EEC_Batch_ConvertContactToContactRole();   
        
        Test.startTest();
           Database.executeBatch(batchCreateContactRole, 1);
        Test.stopTest();
    }
    
    static testMethod void testConvertContactToContactRole(){
        Account a = new Account();
        a.name ='Test Acccount';
        a.RecordTypeId = [Select Id from RecordType where SobjectType='Account' and Name like 'Small Group'].Id;
        a.License_Type__c = 'Regular';
        a.License_Status__c = 'Not Licensed';
        a.Provider_Status__c ='New application in progress';
        a.Provider_Address_1__c = 'Adres 123';
        a.Provider_Zip_Code__c = '12345';
        a.Provider_City__c = EEC_TestUtil.mockCity('Craigville').Id;
        a.Region__c = EEC_TestUtil.mockRegion().Id;
        insert a;
        
        Contact c = new Contact();
        c.firstname = 'firstname';
        c.LastName = 'lname';
        c.AccountId = a.id;
        insert c;
        
        EEC_Batch_ConvertContactToContactRole batchCreateContactRole = new EEC_Batch_ConvertContactToContactRole();   
        test.startTest();
           Database.executeBatch(batchCreateContactRole, 1);
        test.stopTest();
        
    }
}