phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Foster_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Foster Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_GSA__c</fullName>
        <description>Will be true if this provider is a Large Group or Small Group</description>
        <formula>OR ( Record_Type_Name__c  = &apos;Large Group&apos;, Record_Type_Name__c   = &apos;Small Group&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is GSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <description>Provider.Status</description>
        <label>Provider Status</label>
        <picklist>
            <controllingField>License_Status__c</controllingField>
            <picklistValues>
                <fullName>Application To Be Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attended to PPM Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New application in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Enrollment Freeze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-open in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Status under review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Foster_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Foster Parent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <formula>Account.Provider_Email__c</formula>
        <label>Provider Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <formula>TEXT(Account.Provider_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Extension__c</fullName>
        <label>Extension</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Program Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact_Role__c.object
<CustomObject>
    <description>This is a junction object between a provider and contact. A single contact may play multiple roles for a provider like Owner, Administrator etc.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact to which contact role is associated with.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Account to which the contact is associated with.</description>
        <label>Provider / Umbrella</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Role that the contact plays for the provider associated.</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Director / Administrative Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date when a certain contact role became effective.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>New_First_Name__c</fullName>
        <inlineHelpText>New first name submitted by provider</inlineHelpText>
        <label>New First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Last_Name__c</fullName>
        <inlineHelpText>New last name submitted by provider</inlineHelpText>
        <label>New Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prior_First_Name__c</fullName>
        <inlineHelpText>First Name of the applicant prior to change</inlineHelpText>
        <label>Prior First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prior_Last_Name__c</fullName>
        <inlineHelpText>Last Name of the Provider prior submitted change</inlineHelpText>
        <label>Prior Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_New_Provider_Name__c</fullName>
        <inlineHelpText>Once this transaction is processed, the provider name will be changed to this value</inlineHelpText>
        <label>Proposed New Provider Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Provider Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Provider Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Licensing_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>FCC_Change_of_Name</fullName>
        <active>true</active>
        <label>FCC Change of Name</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>Mr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof.</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_ContactTriggerHandler.cls
public  class EEC_ContactTriggerHandler {
    
    public List<Contact> ct {get; set;}
    public List<Contact> newC {get; set;}
    public Map<Id,Contact> oldC {get; set;}
    public Map<Id,Id> CCMap {get; set;}
    public Set<id> contactIdSet {get; set;}
    private static list<case> caselist = new list<case> ();
    //private string contactid;
        
    public EEC_ContactTriggerHandler(List<Contact> newListC, Map<Id,Contact> oldMapC){
        this.newC = newListC;
        this.oldC = oldMapC;
    }
    
   
    public static void updateUser(List<Contact> newListC,List<Contact> oldListC, Map<Id,Contact> oldMapC,  Map<Id,Contact> newMapC){

        Map<Id,Contact> accounttoupdate = new  Map<Id,Contact>();
        
           // for contact
        set<ID> contactidset = new  set<ID>();        
        Map<Id,User> usermap= new  Map<Id,User>();
        list<User> userstoUpdate = new list<User>(); 
        
        //forloop for contact
        for(Contact newContact : newListC){
            
            Contact oldContact = oldMapC.get(newContact.id);
            system.debug('====>'+UserInfo.getUserType());
            system.debug('====>'+newContact);
            if( (oldContact.FirstName != newContact.FirstName || 
                         oldContact.LastName != newContact.LastName || 
                         oldContact.Title != newContact.Title ||  
                         oldContact.MobilePhone != newContact.MobilePhone || 
                         oldContact.Email != newContact.Email ||                          
                         oldContact.Phone != newContact.Phone ||
                         oldContact.Extension__c!= newContact.Extension__c||
                         oldContact.Salutation != newContact.Salutation))
                          {
                             contactidset.add(newContact.id);    
                          }          
                          
                          if( newContact.Role__c == 'Main Contact / Licensee'
                             && (oldContact.Email != newContact.Email ||                          
                                 oldContact.Phone != newContact.Phone))
                          {
                             accounttoupdate.put(newContact.AccountId, newContact);    
                          } 
                          
                      }
                      
          if(contactidset.size()>0){            
        for(User userrecord: [SELECT Id,FirstName,LastName,Title,MobilePhone,Email,Phone,Contact.Salutation,Contact.Extension__c,ContactId   FROM User WHERE ContactId =: contactidset ]){
            usermap.put(userrecord.ContactId ,userrecord);
         }   
       // system.debug('accounttoupdate: ' + accounttoupdate);
        if(accounttoupdate.keySet().size()>0){   
        
        List<Account> listAccounts = new List<Account>();
                 
        for(Account accountrecord: [SELECT Id,Provider_Email__c,Phone,RecordTypeID  FROM Account WHERE Id in : accounttoupdate.keySet()]){
           if((Schema.SObjectType.Account.getRecordTypeInfosByName().get('FCC Assistant').getRecordTypeId() == accountrecord.recordTypeID || Schema.SObjectType.Account.getRecordTypeInfosByName().get('Family Child Care').getRecordTypeId() == accountrecord.recordTypeID)){
           Account accrecord= new Account(id = accountrecord.id);
           accrecord.Provider_Email__c = accounttoupdate.get(accountrecord.Id).Email;
            accrecord.Phone   = accounttoupdate.get(accountrecord.Id).Phone;
            listAccounts.add(accrecord);
         } 
           
        // system.debug('listAccounts: ' + listAccounts);
         update listAccounts;
         }
         }
         //Savepoint sp = Database.setSavepoint();
        map<id,String> userIDUsernameMap = new map<id,String>();
        for(ID contactID : contactidset){
        
            if(usermap.get(contactID) != null && ((UserInfo.getUserType() == 'CspLitePortal' && UserInfo.getUserID() == usermap.get(contactID).id) || UserInfo.getUserType() == 'Standard')){
                User userrecord = new User(id = usermap.get(contactID).id);
                userrecord.FirstName = newMapC.get(contactID).FirstName;
                userrecord.LastName = newMapC.get(contactID).LastName ;
                userrecord.Title = newMapC.get(contactID).Title ;
                userrecord.MobilePhone= newMapC.get(contactID).MobilePhone;
                userrecord.Email = newMapC.get(contactID).Email ;
                //userrecord.UserName = newMapC.get(contactID).Email;
                userrecord.Phone = newMapC.get(contactID).Phone ;
                
                userrecord.Salutation__c = newMapC.get(contactID).Salutation;
                userrecord.Extension = newMapC.get(contactID).Extension__c ;
                if(userrecord.Email != userrecord.UserName){
                    userIDUsernameMap.put(userrecord.id,userrecord.email);
                }
                userstoUpdate.add(userrecord);
            }
        }
        if(userstoUpdate.size()>0){
       
        update userstoUpdate;
        userupdate(userIDUsernameMap);
        
      }
       } 
         
    }
    
    @future
    public static void userupdate(map<id,string> useridUsernameMap){
        list<User> userlist = new list<User>();
        for(ID userID : useridUsernameMap.keyset()){
            userlist.add(new User(id = userID,UserName = useridUsernameMap.get(userID))); 
        }
       // system.debug('======'+userlist);
        update userlist;
    //update userstoUpdate;
    
    }
    
    public void createTransaction(){
    
        User portalUser = [SELECT Id, IsPortalEnabled, UserType  FROM USER WHERE Id =: Userinfo.getUserId() LIMIT 1];
        if(portalUser.UserType == 'PowerCustomerSuccess' || portalUser.UserType == 'CustomerSuccess'){
        Id fccRecordTypeId = EEC_RecordTypeUtil.findByName('ACCOUNT.FCC').Id;
        
        for(Contact newContact : newC){
            Contact oldContact = oldC.get(newContact.id);
            
            Account provider = [SELECT Id, Recordtype.Name, RecordTypeId FROM Account 
                                WHERE ID IN (SELECT AccountId FROM user WHERE id = :Userinfo.getUserId()) LIMIT 1];
            
            
            if((oldContact.FirstName != newContact.FirstName || 
               oldContact.LastName != newContact.LastName) && fccRecordTypeId == provider.RecordTypeId &&
              (portalUser.IsPortalEnabled == true || portalUser.UserType == 'PowerCustomerSuccess')){
                  
                Licensing_Transaction__c lt = new Licensing_Transaction__c();
                
                lt.RecordTypeId = EEC_RecordTypeUtil.findByName('Licensing_Transaction__c.FCC_Change_of_Name').Id;
                lt.Prior_First_Name__c = oldContact.FirstName;
                lt.Prior_Last_Name__c = oldContact.LastName;
                lt.New_First_Name__c = newContact.FirstName;
                lt.New_Last_Name__c = newContact.LastName;
                lt.Proposed_New_Provider_Name__c = newContact.FirstName + ' ' + newContact.LastName;
                lt.Provider__c = oldContact.AccountId;
                lt.Status__c = 'Submitted';
                lt.Submission_Date__c = Date.today();
                lt.Submitter__c = Userinfo.getUserId();
                lt.Source__c = 'Provider Portal';
                
                insert lt;
                }
            }
        }
    }
   public void AccountMandatory(){
       contactidset = new Set<id>();
       CCMap = new Map<Id,Id>();
       for(contact c : newC){
         contactidset.add(c.id);
       }
       caselist =[SELECT id,Contactid,Foster_Parent__c FROM Case WHERE contactid IN: contactidset];
       for(Case Cs : caselist){
          CCMap.put(Cs.contactid,Cs.id);
       }
       for(Contact Ct: newC){
        	if(ct.accountid == null && CCMap.get(Ct.id)==null)
         		ct.adderror('All Contacts must have either an Associated Case or Provider Name');
       }
    }    
     public void createContactRole(){        
        set<ID> contactid = new  set<ID>();
        list<contact> updatelist = new list<contact>();
        for(Contact newContact : newC){
           contactid.add(newContact.id);
        }
        list<Contact> Con = new list<contact>([Select id,name,accountid,account.Provider_Status__c,account.Is_GSA__c,account.CreatedDate,Role__c from contact where id IN: contactid]);
        for(Contact C : Con){
            Date myDate = date.newinstance(C.account.createddate.year(), C.account.createddate.month(), C.account.createddate.day());
            if(C.account.Provider_Status__c == 'Attended to PPM Meeting' && mydate == date.today() && C.account.Is_GSA__c == true && string.isnotBlank(C.Role__c)){
	            Contact_Role__c CR = new Contact_Role__c();
	            CR.Start_Date__c = date.today();
	            CR.Role__c = C.Role__c;
	            CR.Contact__c = C.id;
	            CR.Provider__c = C.Accountid;
	             
	            insert CR;
	            
	            C.Role__c = '';
	            
	            Updatelist.add(C);
        	}
        }
        update Updatelist;
     }
}