phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Small_Group</fullName>
        <active>true</active>
        <description>Small group and school age</description>
        <label>Small Group</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_LicenseCertificatePDFTest.cls
@IsTest
public class EEC_LicenseCertificatePDFTest {
	 static testMethod void testEEC_LicenseCertificatePDFController() {
        // Setup basic defaults.
        Licensing_Transaction__c insp = EEC_TestUtil.loadLicenseSetup();
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        // Call constructor.
        EEC_LicenseCertificatePDF tPdf = new EEC_LicenseCertificatePDF(sc);
        tPdf.savePDF(); 
    }
	 static testmethod void licensepdf(){
         		Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('Small Group', null);
       		  Account acc = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'Small_Group');
          	  acc.Config_Record__c = config2.Id;
        	  update acc;
       		 Licensing_Transaction__c ld = EEC_TestUtil.mockLiscence(acc);
         		
         		//insert ld;
         
   			PageReference pageref = Page.EEC_LicenseCertificatePDF;  
         	Test.setCurrentPage(pageref);   
         	ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(ld);
         	ApexPages.currentPage().getParameters().put('Id',ld.id);
          
         
         EEC_LicenseCertificatePDF pdf = new EEC_LicenseCertificatePDF(sc);
         
         pdf.savePDF();
         pdf.pdfPageReference();
         	
         
         	
        	     
	}
}