phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Small_Group</fullName>
        <active>true</active>
        <description>Small group and school age</description>
        <label>Small Group</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact_Role__c.object
<CustomObject>
    <description>This is a junction object between a provider and contact. A single contact may play multiple roles for a provider like Owner, Administrator etc.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Account to which the contact is associated with.</description>
        <label>Provider / Umbrella</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document__c.object
<CustomObject>
    <description>A custom object to be used for non-Salesforce reference documents.</description>
    <fields>
        <fullName>Approved_for_Future_Usage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Future Usage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>The file&apos;s content meta type.</description>
        <label>Content Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Type</label>
        <referenceTo>Document_Type__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes relating to the document.</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>DateTime</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC- {0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document_Type__c.object
<CustomObject>
    <description>An object for storing all document types. This is not to be confused with document prototypes (i.e. image/jpeg, document/pdf, etc)</description>
    <fields>
        <fullName>Allow_use_of_Umbrella_Level_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Use of Umbrella Level Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>A description for the document type.</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Individual_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Individual Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEAD_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Provider Type</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Document Types</relationshipLabel>
        <relationshipName>Document_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Library_Level__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If check, this document type will appear in the library of all providers this document type is defined on - per type of provider</inlineHelpText>
        <label>Library Level</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Need_to_be_Updated_at_each_new_Transacti__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Update Each New Transaction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Transactio_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Optional for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Related_Role__c</fullName>
        <label>Related Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Director / Administrative Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Contact</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Required_for_Transaction_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Required for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Document Type</label>
    <nameField>
        <label>Document Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Provider_Meeting__c.object
<CustomObject>
    <label>Provider Meeting</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Provider Meeting No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_DocumentLibraryControllertest.cls
@istest
public class EEC_DocumentLibraryControllertest {
    
    @isTest
    static void testDocumentLibraryController() {
        Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('Small Group', null);
        
        Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'Small_Group');
        accnt.Config_Record__c = config2.Id;     
        update accnt;
        
        Contact contact = EEC_TestUtil.mockContact(accnt, 'Test', 'LastName', '');
        
        Contact_Role__c contactRole = EEC_TestUtil.mockContactRole('Partner', contact.Id, accnt.Id);
        contactRole = EEC_TestUtil.mockContactRole('Administrative Designee', contact.Id, accnt.Id);
        contactRole = EEC_TestUtil.mockContactRole('Program Director / Administrative Head', contact.Id, accnt.Id);
        contactRole = EEC_TestUtil.mockContactRole('Board Chair', contact.Id, accnt.Id); 
        contactRole = EEC_TestUtil.mockContactRole('Owner', contact.Id, accnt.Id);
        
        User portaluser = EEC_TestUtil.mockPortalUser (contact);
        
        Provider_Meeting__c  providermeeting  = EEC_TestUtil.mockGsaProviderMeeting();
        
        List<Document_Type__c> listDocumentType = new List<Document_Type__c>();
        Document_Type__c docType = new Document_Type__c();
        docType.Allow_use_of_Umbrella_Level_Document__c = true;
        docType.Name = 'Doc Type 1';
        docType.Description__c ='Test Description';
        docType.Individual_Document__c = false;
        docType.Need_to_be_Updated_at_each_new_Transacti__c = true;
        docType.Optional_for_Transactio_Type__c = 'GSA New License';
        docType.Related_Role__c = '';
        docType.LEAD_Configuration__c = config2.Id;
        docType.Required_For_Transaction_Type__c = 'GSA New License'; 
        listDocumentType.add(docType);
        
        docType = new Document_Type__c();
        docType.Allow_use_of_Umbrella_Level_Document__c = true;
        docType.Name = 'Doc Type 2';
        docType.Description__c ='Test Description';
        docType.Individual_Document__c = true;
        docType.Need_to_be_Updated_at_each_new_Transacti__c = true;
        docType.Optional_for_Transactio_Type__c = 'GSA New License';
        docType.Related_Role__c = 'Administrative Designee';
        docType.LEAD_Configuration__c = config2.Id;
        docType.Required_For_Transaction_Type__c = 'GSA New License'; 
        docType.Library_Level__c = true;
        listDocumentType.add(docType);
        
        insert listDocumentType;
        
        List<Document__c> listDocument = new List<Document__c>();
        Document__c document = new Document__c();
        document.Provider__c = accnt.Id;
        document.Notes__c = 'Test Notes';
        document.Document_Type__c = listDocumentType[0].Id;
        document.Content_Type__c = 'jpg';
        document.Approved_for_Future_Usage__c = false;
        document.Valid_To__c = DateTime.now();
        document.Valid_From__c = DateTime.now();
        listDocument.add(document);
        
        document = new Document__c();
        document.Provider__c = accnt.Id;
        document.Notes__c = 'Test Notes';
        document.Document_Type__c = listDocumentType[1].Id;
        document.Content_Type__c = 'jpg';
        document.Approved_for_Future_Usage__c = true;
        document.Valid_To__c = DateTime.now();
        document.Valid_From__c = DateTime.now();
        listDocument.add(document);
        insert listDocument;
        
        System.runAs(portaluser){
            test.startTest();
            EEC_DocumentLibraryController mp = new EEC_DocumentLibraryController();  
            mp.doCreateDocs();
            mp.doBack();
            mp.doMarkAsOutOfDate();
            test.stopTest();
            
        }
        
    }
}