phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region this provider is assigned to</description>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <description>Address 1</description>
        <inlineHelpText>At creation and if left blank, Address 1 will be populated with Provider address after saving.</inlineHelpText>
        <label>Street Address 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspector_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Licensor or investigator who performs the inspection</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inspections_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Visit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Provider of the associated visit must be the provider of the visit</errorMessage>
            <filterItems>
                <field>$Source.Provider_No__c</field>
                <operation>equals</operation>
                <valueField>Inspection__c.Provider_No__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Associated Visits (Follow-Ups)</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Provider_No__r.Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>At creation and if left blank, Zip Code will be populated with Provider zip code after saving</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>visitLatitude__c</fullName>
        <description>Latitude part of geo-coordinates of the visit address</description>
        <label>visitLatitude</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>visitLongitude__c</fullName>
        <description>Longitude part of geo-coordinates of the visit address</description>
        <label>visitLongitude</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Investigation_Visits</fullName>
        <active>true</active>
        <description>Visits done in the scope of an investigation, these visits will not generate a specific report as the visit report will be included in the investigation report</description>
        <label>Investigation Visits</label>
    </recordTypes>
    <recordTypes>
        <fullName>Licensing_Visits</fullName>
        <active>true</active>
        <description>Visits done in the scope of licensing activities (initial license, renewal, additional control, follow-up visit). These visits will trigger a specific report.</description>
        <label>Licensing Visits</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Fill this field if the corrective action submitted by the provider is not appropriate. By updating this field, Providers using electronic communication will be informed by email and will be able to update the correction plan on the portal.</inlineHelpText>
        <label>Corrective Action EEC Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Feedback_Requested__c</fullName>
        <formula>AND(
ISPICKVAL(Inspection_Result__c, &quot;Non-Compliant&quot;),
ISBLANK( Date_Implemented__c )
)</formula>
        <label>Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation can be assigned to a Licensor, Supervisor or Inspector</description>
        <inlineHelpText>User who will take the lead on the investigation.</inlineHelpText>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <inlineHelpText>This text will be used as default on Investigation Non-Compliance narrative text in case there is no non-compliance identified on this investigation.</inlineHelpText>
        <label>Investig. Non-comp. Default if None</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Visit_Narrative_Summary_Default__c</fullName>
        <inlineHelpText>Text that will be used as default for the visit narrative summary text. Note that the tags #Visit_Date# and #Visit_Reason# will be replaced by the values from the visit object when the text is used.</inlineHelpText>
        <label>Visit Narrative Summary Default</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <fields>
        <fullName>Deputy_Commissioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This information is used by the system during the approval process of escalated Investigation. This user is the 1st reviewer / approver.</inlineHelpText>
        <label>Associate Commissioner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This information is used by the system during the approval process of escalated Investigation. For FCC / GSA, this user is the 2nd reviewer / approver.</inlineHelpText>
        <label>Regional Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Out_of_Office__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Out of Office</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the user is attached to</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast and Cape</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_VisitTriggerHandler.cls
public with sharing class EEC_VisitTriggerHandler {
    
    List<Inspection__c> newInspectionList;
    Map<Id,Inspection__c> oldInspectionMap;
    Map<Id,User> userMap;
    Set<Id> cancelledVisits;
    Map<Id,Account> providerMap;
    Map<Id,ProcessInstance> inspectionApprovals;
    Map<Id,Investigation__c> investigationMap;
    Map<Id, Inspection_Item__c> inspectionItemMap;
    Set<Id> inspectionIds;
    public static boolean flag =false;

    public EEC_VisitTriggerHandler(List<Inspection__c> newList){
        this.newInspectionList = newList;
        setup();
    }
    
    public void sendInvestigationApprovalEmailOutOfOffice(){
        User escalationUser = userMap.get(UserInfo.getUserId());
        Account prov;
        if(escalationUser != null){
            for(Inspection__c insp : newInspectionList){
                Inspection__c old = oldInspectionMap.get(insp.Id);
                User escalationManager = userMap.get(escalationUser.ManagerId);
                if(providerMap != null)
                    prov = providerMap.get(insp.Provider_No__c);
                else
                    prov = [SELECT Id,Name,Region__c, Region__r.Deputy_Commissioner__c,
                            Region__r.Regional_Director__r.Email,RecordType.Name 
                            FROM Account WHERE Id =: insp.Provider_No__c];
                if(insp.Status__c == 'Pending Approval' && old.Status__c != 'Pending Approval' && escalationManager.Out_of_Office__c){
                    List<OrgWideEmailAddress> orgList = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = 'EEC LEAD Alert'];
                    EEC_EmailUtil email = new EEC_EmailUtil(); 
                    String fullRecordURL = URL.getSalesforceBaseUrl().toExternalForm() + '/' + insp.Id;
                    
                    EmailTemplate template9 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'X9_New_Licensing_Visit_to_Review_and_Approve'];
                    
                    email.plainTextBody = template9.Body
                        .replace('{!Inspection__c.Provider_No__c}', prov.Name)
                        .replace('{!Inspection__c.Id}', insp.Id)
                        .replace('{!Inspection__c.Link}', fullRecordURL);
                    email.Subject = 'New Licensing Visit to Review and Approve';
                    email.toAddresses = new List<String>();
                    
                    if(escalationManager.DelegatedApproverId != null){
                        email.toAddresses.add(userMap.get(escalationManager.DelegatedApproverId).Email); 
                    }
                    else if(escalationManager.ManagerId != null && escalationManager.Out_of_office__c){
                        User managersManager = userMap.get(escalationManager.ManagerId);
                        email.toAddresses.add(managersManager.Email); 
                    }
                                        
                    email.whatId = insp.Id;
                    email.saveAsActivity = false;
                    if(orgList.size() > 0)
                        email.orgWideEmailId = orgList.get(0).Id;
                    
                    email.sendEmail();
                }
            }
        }
    }
    
    public EEC_VisitTriggerHandler(List<Inspection__c> newList, Map<Id,Inspection__c> oldMap){
        this.newInspectionList = newList;
        this.oldInspectionMap = oldMap;
        setup();
    }
    
    public void setup(){
        userMap = new map<Id,User>();
        inspectionIds = new Set<Id>();
        Set<Id> providerSet = new Set<Id>();  
        
        for(Inspection__c insp : newInspectionList){ 
            inspectionIds.add(insp.Id);
            if(insp.Provider_No__c != null){
                providerSet.add(insp.Provider_No__c);
            } 
        }

        inspectionItemMap = new Map<Id, Inspection_Item__c>([SELECT Id, Name, Feedback_Requested__c,Inspection_No__c, Corrective_Action_EEC_Feedback__c 
                                                             FROM Inspection_Item__c 
                                                             WHERE Feedback_Requested__c = TRUE 
                                                             AND Inspection_No__c IN : inspectionIds]);

        providerMap = new Map<Id, Account>([SELECT Id,OwnerId,Name, Config_Record__r.Visit_Narrative_Summary_Default__c 
                                            FROM Account 
                                            WHERE Id in :providerSet]);
        
        userMap = new Map<Id, User>([
            SELECT ManagerId, UserRoleId, Email, Name, DelegatedApproverId, Out_of_Office__c
            FROM User
            WHERE UserType = 'Standard'
        ]); 
        
    }
    
    public void bulkBefore(){
        
        userMap = new map<Id,User>(); 
        Set<Id> investigationSet = new Set<Id>();
        
        for(Inspection__c insp : newInspectionList){
             
            if(insp.Investigation__c != null){
                investigationSet.add(insp.Investigation__c);
            }
        }
         
        investigationMap = new Map<Id, Investigation__c>([select Id,Assigned_To__c from Investigation__c where Id in :investigationSet]);
    }

    public void updateVisitCoordinatesBefore(){
      //Get list of inspections where address field is populated
      Set<String> addressLinesSet = new Set<String>();
      Set<String> zipCodesSet = new Set<String>();
      Boolean addressUpdated = false;
      
      for(Inspection__c insp : newInspectionList){
        if(Trigger.isUpdate){
          Inspection__c oldInsp = oldInspectionMap.get(insp.id);
          System.debug('------->OldInspection: ' + oldInsp);
          if(insp.Address_1__c != oldInsp.Address_1__c || insp.Zip_Code__c != oldInsp.Zip_Code__c){
            addressUpdated = true;
          }
        }
        
        if(String.isNotBlank(insp.Address_1__c) && String.isNotBlank(insp.Zip_Code__c)){
          addressLinesSet.add(insp.Address_1__c);
          zipCodesSet.add(insp.Zip_Code__c);
        }
      }
      //Check if visit coordinates need to be updated/populated
      if( (Trigger.isInsert && addressLinesSet.size() < 1) || (Trigger.isUpdate && addressUpdated == false)){
        System.debug('------> No updates required');
        return;
      }
      //Get the coordinates from exisiting visits
      AggregateResult[] inspWithCoordinates = [SELECT Address_1__c, Zip_Code__c, visitLatitude__c, visitLongitude__c 
                              FROM Inspection__c
                              WHERE Address_1__c IN :addressLinesSet AND Zip_Code__c IN :zipCodesSet
                                AND visitLatitude__c != null AND visitLatitude__c != ''
                              GROUP BY Address_1__c, Zip_Code__c, visitLatitude__c, visitLongitude__c];
      Map<String, String> visitCoordinatesMap = new Map<String, String>();
      if(inspWithCoordinates != null && inspWithCoordinates.size() > 0){
        for(AggregateResult ar : inspWithCoordinates){
          visitCoordinatesMap.put(ar.get('Address_1__c') + ' ' + ar.get('Zip_Code__c'), ar.get('visitLatitude__c') + '|' + ar.get('visitLongitude__c'));
        }
      }
      //Map<Id, Inspection__c> inspCoordinatesNotFound = new Map<Id, Inspection__c>(newInspectionList);
      for(Inspection__c insp : newInspectionList){
        if(String.isNotBlank(insp.Address_1__c) && String.isNotBlank(insp.Zip_Code__c)){
          String keyToGetCoordinates = insp.Address_1__c + ' ' + insp.Zip_Code__c;
          String visitCoordinates = visitCoordinatesMap.get(keyToGetCoordinates);
          if(String.isNotBlank(visitCoordinates)){
            insp.visitLatitude__c = visitCoordinates.substring(0, visitCoordinates.indexOf('|'));
            insp.visitLongitude__c = visitCoordinates.substring(visitCoordinates.indexOf('|')+1, visitCoordinates.length());
            //Inspection__c inspFound = inspCoordinatesNotFound.remove(insp.ID);
          } else{
            if(Trigger.isUpdate){
              Inspection__c oldInsp = oldInspectionMap.get(insp.id);
              System.debug('------->OldInspection: ' + oldInsp);
              if(insp.Address_1__c != oldInsp.Address_1__c || insp.Zip_Code__c != oldInsp.Zip_Code__c){
                insp.visitLongitude__c = null;
                insp.visitLatitude__c = null;
              }
            }
          }
        }
      }
    }
    
    public void bulkAfter(){
        
        cancelledVisits = new Set<Id>();
        Inspection__c oldInsp;
        for(Inspection__c insp : newInspectionList){
            oldInsp = oldInspectionMap.get(insp.Id);
            if(insp.Status__c != null && (insp.Status__c == 'Cancelled' || insp.Status__c == 'Closed') && insp.Status__c != oldInsp.Status__c){
                cancelledVisits.add(insp.Id);
            }
        }
        
    }
    
    public void updateVisit(){ 
        
        Id assignedTo;
        for(Inspection__c insp : newInspectionList){
            if(insp.Original_Visit__c == null && String.isNotBlank(insp.Inspector_del__c)){
                /*if(EEC_RecordTypeUtil.findById(insp.recordTypeId).DeveloperName == 'Licensing_Visits'){
                    if(providerMap != null && providerMap.containsKey(insp.Provider_No__c) != null){
                        insp.Inspector_del__c = providerMap.get(insp.Provider_No__c).ownerid;
                    }
                }
                else */if(EEC_RecordTypeUtil.findById(insp.recordTypeId).DeveloperName == 'Investigation_Visits' && insp.Investigation__c != null){
                    if(investigationMap != null && investigationMap.containsKey(insp.Investigation__c) != null){
                        assignedTo = investigationMap.get(insp.Investigation__c).Assigned_To__c;
                        insp.Inspector_del__c = assignedTo;
                    }
                }
            }
            if(insp.Inspector_del__c == null){
                insp.Inspector_del__c = Userinfo.getUserId();
            }
        }
    }
    
    public void createVisitTasks(){
        List<Task> taskList = new List<Task>();
        Task vTask;
        for(Inspection__c insp : newInspectionList){
            System.debug('Inspection*******' + insp);
            vTask = new Task();
            vTask.Status = 'Not Started';
            vTask.Priority = 'Normal';
            vTask.WhatId = insp.Id;
            vTask.OwnerId = String.isNotBlank(insp.Inspector_del__c)?insp.Inspector_del__c:UserInfo.getUserId();
            String city = insp.City__c;
            String address = insp.Address_1__c;
            if((city==null || address==null)&&(insp.Provider_Address_City__c !=null)){
                city = insp.Provider_Address_City__c.split(',')[1];
                address = insp.Provider_Address_City__c.split(',')[0]; 
            }
            vTask.Subject = 'Schedule visit - ' + insp.Provider_Name__c + ' - ' + address + ' - ' + city ;//+ '-' + insp.Date_of_Visit__c + '-' + insp.Provider_No__r.Name
            system.debug('Address value: '+insp);
            system.debug('Subject Value: '+vTask.Subject);
            if(insp.Announced__c){
                //vTask.Subject = 'Schedule visit - Announced';
                vTask.Subject = 'Schedule visit - Announced';
                vTask.ActivityDate = (insp.Estimated_Deadline__c != null) ? insp.Estimated_Deadline__c.addDays(-10):null;
            }
            else{
                //vTask.Subject = 'Schedule visit - UnAnnounced';
                vTask.ActivityDate = (insp.Date_of_Visit__c != null) ? insp.Date_of_Visit__c.addDays(-10):null;
            }
            taskList.add(vTask);
        }
        if(taskList.size() > 0){
            insert taskList;
        }
    }

    public void updateTaskSubjectForAnnouncementType(){
      List<Task> taskList = new List<Task>();
      Set<Id> visitIdSet = new Set<Id>();
      for(Inspection__c insp : newInspectionList){
        Inspection__c old = oldInspectionMap.get(insp.Id);
        if(insp.Status__c == 'To be Scheduled' && insp.Announcement_Type__c <> old.Announcement_Type__c){
          visitIdSet.add(insp.Id);
        }
      }
      if(visitIdSet <> null && visitIdSet.size() > 0){
        taskList = [SELECT Status, Subject, WhatId 
                    FROM Task 
                    WHERE WhatId IN: visitIdSet
                      AND Status = 'Not Started'];
        Map<Id, Inspection__c> newInspectionMap = new Map<Id, Inspection__c>(newInspectionList);
        if(taskList <> null && taskList.size() > 0){
          for(Task vTask : taskList){
            Inspection__c i = newInspectionMap.get(vTask.WhatId);
            String city = i.City__c;
            String address = i.Address_1__c;
            if((city==null || address==null)&&(i.Provider_Address_City__c !=null)){
                city = i.Provider_Address_City__c.split(',')[1];
                address = i.Provider_Address_City__c.split(',')[0]; 
            }
            vTask.Subject = 'Schedule visit - ' + i.Announcement_Type__c + ' - ' + i.Provider_Name__c + ' - ' + address + ' - ' + city ;
          }
          update taskList;
        }
        
      }
      
    }
    
    public void updateClosedActivitySummary(){
        for(Inspection__c i : newInspectionList){
            Inspection__c oldRecord = oldInspectionMap.get(i.Id);
            
            Lead_Configuration__c conf = providerMap.get(i.Provider_No__c).Config_Record__r;
           
            if((i.Status__c == 'Visit Completed' && (i.Activity_Summary__c == NULL || i.Activity_Summary__c.trim() == '')) &&
                (oldRecord.Status__c == 'Scheduled' || oldRecord.Status__c == 'To be scheduled') &&
                (conf != NULL && conf.Visit_Narrative_Summary_Default__c != NULL)){
                
                String defaultActivitySummary = conf.Visit_Narrative_Summary_Default__c;
                                           
                // Set visit reason and visit date only if they are set.
                defaultActivitySummary = defaultActivitySummary .replace('#Visit_Reason#', 
                    i.Type_of_Visit__c == NULL ? 'unknown' : i.Type_of_Visit__c);
                    
                defaultActivitySummary = defaultActivitySummary .replace('#Visit_Date#', 
                    i.Date_of_Visit__c == NULL ? 'unknown' : EEC_DateUtil.formatDate('MM/dd/yyyy',i.Date_of_Visit__c));
                
                i.Activity_Summary__c = defaultActivitySummary;
            }
        }
    }
    
    public void closeCancelledTasks(){
        
        List<Task> closeTaskList = new List<Task>();
        List<Task> deleteTaskList = new List<Task>();
        
        for(Task tsk : [select Id,status,activitydate from Task where WhatId = :cancelledVisits and isClosed != true]){
            if(tsk.activitydate != null && tsk.activitydate > Date.Today()){
                deleteTaskList.add(tsk);
            }
            else{
                tsk.status = 'Completed';
                closeTaskList.add(tsk);
            }
        }
        
        if(closeTaskList != null && closeTaskList.size() > 0){
            update closeTaskList;
        }
        if(deleteTaskList != null && deleteTaskList.size() > 0){
            delete deleteTaskList;
        }
    }
    
    /**
     * checkItemsForPublishedToWeb
     * 
     * This function will check the newly updated Visits to ensure that if their published to web is enabled
     *   that their Visit Items will be set accordingly.
     * @author Darkis 
     */
    public void updateVisitStatusBefore(){
      for (Inspection__c i : newInspectionList){
        Inspection__c oldRecord = oldInspectionMap.get(i.Id);
        if (i.Created_on_the_Web__c && !oldRecord.Created_on_the_Web__c) {
          if(i.RecordType.Developername == 'Licensing_Visits'){
            i.Status__c = 'Report Sent to Provider, Awaiting feedback';
          } 
        }
      }
    }
    public void checkItemsForPublishedToWeb() {
      //List<Inspection__c> nInsp = [SELECT Id, Created_on_the_Web__c, RecordType.Developername FROM Inspection__c WHERE Id IN: inspIds];  
      List<Inspection_Item__c> feedbackRequestedItemList = new List<Inspection_Item__c>();
      for(Inspection__c i : newInspectionList){
        //Inspection__c modifiedVisit = [Select Id, Status__c, RecordType.Developername From Inspection__c Where Id = :i.Id];
        Inspection__c oldRecord = oldInspectionMap.get(i.Id);
        // If the new record has been switched to true and the old record was false.  
        if (i.Created_on_the_Web__c && !oldRecord.Created_on_the_Web__c) {
          // Search for at least one item from this visit that has Feedback_Requested__c = true. 
          for(Inspection_Item__c insp_Item : inspectionItemMap.values()){
                if(insp_Item.Inspection_No__c == i.Id )
                    feedbackRequestedItemList.add(insp_Item);
          }
          // If the item is not null then we know there is one set to true.   
          if (feedbackRequestedItemList != null && feedbackRequestedItemList.size() > 0) {
            // Loop through all the items and change their 'To_Review_on_Portal__c' status to true.
            for (Inspection_Item__c item : feedbackRequestedItemList) {
              item.To_Review_on_Portal__c = true;
            }  
          }  
        }
      }
      if(feedbackRequestedItemList.size() > 0){
          update feedbackRequestedItemList;
      }
    }
    
    /**
     * checkForNewMasterVisit
     * 
     * This function will check for new master visits and close all tasks related to the changed visit. 
     * @author Darkis
     */
    public void checkForNewMasterVisit() {
      // Get the visit id list fro the new inspection list.
      Set<Id> visitIdSet = (new Map<Id, Inspection__c>(newInspectionList)).keySet();
      // Fetch all the modified visit items.
      Map<Id, Inspection__c> modifiedVisits = new Map<Id, Inspection__c>([Select Id From Inspection__c Where Id IN :visitIdSet]);
      // Create a new instacne of child visit ids. 
      Set<Id> newChildVisits = new Set<Id>();
      // Verify all the modified visits and check if the new version has a NEW master visit.  
      for (Inspection__c i : newInspectionList) {
        Inspection__c modifiedVisit = modifiedVisits.get(i.Id);           
        Inspection__c oldRecord = oldInspectionMap.get(i.Id);
        // If a master visit has been added then add the id to the child visit id list.  
        if (i.Mater_Visit_for_Res_Cluster_of_Visits__c != null && oldRecord.Mater_Visit_for_Res_Cluster_of_Visits__c == null) {
          newChildVisits.add(i.Id);
        }
      }  
      
      if (newChildVisits != null && newChildVisits.size() > 0) {
        // Collect all the tasks for the new child visits for closure.   
        List<Task> allTasksToClose = [select Id,status,activitydate from Task where WhatId = :newChildVisits and isClosed != true];  
        for(Task tsk : allTasksToClose) {
          tsk.status = 'Completed';       
        }
        // Update the tasks.
        update allTasksToClose;
      }
    }
    
    public void checkMasterVisitForChanges() {
      // Get the visit id list fro the new inspection list.
      Set<Id> visitIdSet = (new Map<Id, Inspection__c>(newInspectionList)).keySet();
      // Fetch all the modified visit items.
      Map<Id, Inspection__c> modifiedVisits = new Map<Id, Inspection__c>([
        Select 
          Id, 
          Status__c, 
          Estimated_Deadline__c, 
          Closed_Cancellation_Date__c,  
          Cancellation__c,
          Announced__c,
          Date_of_Visit__c,
          Time_of_visit__c,
          Activity_Summary__c,
          Corrective_Action_Required__c,
          Tech_Assist_Recommendations_Comments__c,
          Comments__c,
          Cover_Letter_Narrative__c,
          Updates_Changes__c,
          Announcement_Type__c
        From Inspection__c Where Id IN :visitIdSet
      ]);    
      // Get all the children visits for the master records. 
      List<Inspection__c> childVisits = [SELECT Id, Status__c, 
                                         Mater_Visit_for_Res_Cluster_of_Visits__c 
                                         FROM Inspection__c 
                                         WHERE Mater_Visit_for_Res_Cluster_of_Visits__c 
                                         IN : visitIdSet];
      Map<Id, List<Inspection__c>> childVisitsMapToMaster = new Map<Id, List<Inspection__c>>();
      if (childVisits != null && childVisits.size() > 0) {
        // Loop through the children and add them to a list in a mapping for their master.  
        for (Inspection__c child : childVisits) {
          // If the master already has a record then get the list and add the child to it. 
          if (childVisitsMapToMaster.containsKey(child.Mater_Visit_for_Res_Cluster_of_Visits__c)) {
            childVisitsMapToMaster.get(child.Mater_Visit_for_Res_Cluster_of_Visits__c).add(child);       
          } else {
            // If there is no record of this master then create one and add it's firse child.
            childVisitsMapToMaster.put(child.Mater_Visit_for_Res_Cluster_of_Visits__c, new List<Inspection__c>{child});    
          }
        }  
      }
      // Verify all the modified visits and check if the new version has a NEW master visit.  
      for (Inspection__c i : newInspectionList) {  
        Inspection__c masterVisit = modifiedVisits.get(i.Id);           
        Inspection__c oldMasterVisit = oldInspectionMap.get(i.Id);
        if (i.Mater_Visit_for_Res_Cluster_of_Visits__c == null) {
          // When Status of Master visit is changed, update the Status of all child visits associated
          if (masterVisit.Status__c != oldMasterVisit.Status__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Status__c');
          }
          //Keep visit status in sync
          if(childVisitsMapToMaster != null && childVisitsMapToMaster.size() > 0){
            for(Inspection__c childVisit : childVisitsMapToMaster.get(i.Id)){
              if(childVisit.Status__c != masterVisit.Status__c){
                updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Status__c');
              }
            }
          }
          
          // When Estimated Deadline is changed, update the Estimated Deadline of all child visits associated
          if (masterVisit.Estimated_Deadline__c != oldMasterVisit.Estimated_Deadline__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Estimated_Deadline__c');
          }
          // When Closed / Cancellation Date is changed, update the Closed / Cancellation Date of all child visits associated
          if (masterVisit.Closed_Cancellation_Date__c != oldMasterVisit.Closed_Cancellation_Date__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Closed_Cancellation_Date__c');
          }
          // When Cancellation Reason is changed, update the Cancellation Reason of all child visits associated
          if (masterVisit.Cancellation__c != oldMasterVisit.Cancellation__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Cancellation__c');
          } 
          /*
          // When Announced flag is changed, update the Announced flag of all child visits associated
          if (masterVisit.Announced__c != oldMasterVisit.Announced__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Announced__c');
          }*/
          // When Announced flag is changed, update the Announced flag of all child visits associated
          if (masterVisit.Announcement_Type__c != oldMasterVisit.Announcement_Type__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Announcement_Type__c');
          }
          // When Date of Visit is changed, update the Date of Visit of all child visits associated
          if (masterVisit.Date_of_Visit__c != oldMasterVisit.Date_of_Visit__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Date_of_Visit__c');
          }
          // When Time of Visit is changed, update the Time of Visit of all child visits associated
          if (masterVisit.Time_of_visit__c != oldMasterVisit.Time_of_visit__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Time_of_visit__c');
          }
          // When Activity Summary is changed, update the Activity Summary of all child visits associated
          if (masterVisit.Activity_Summary__c != oldMasterVisit.Activity_Summary__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Activity_Summary__c');
          }
          // When Corrective Action Required is changed, update the Corrective Action Required of all child visits associated
          if (masterVisit.Corrective_Action_Required__c != oldMasterVisit.Corrective_Action_Required__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Corrective_Action_Required__c');
          }
          // When Technical Assistance is changed, update the Technical Assistance of all child visits associated
          if (masterVisit.Tech_Assist_Recommendations_Comments__c != oldMasterVisit.Tech_Assist_Recommendations_Comments__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Tech_Assist_Recommendations_Comments__c');
          }
          // When Comments is changed, update the Comments of all child visits associated
          if (masterVisit.Comments__c != oldMasterVisit.Comments__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Comments__c');
          }
          // When Cover Letter Narrative is changed, update the Cover Letter Narrative of all child visits associated     
          if (masterVisit.Cover_Letter_Narrative__c != oldMasterVisit.Cover_Letter_Narrative__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Cover_Letter_Narrative__c');
          }
          // When Updates_Changes__c is changed, update the Updates_Changes__c of all child visits associated     
          if (masterVisit.Updates_Changes__c != oldMasterVisit.Updates_Changes__c) {
            updateChildVisitsData(masterVisit, childVisitsMapToMaster, 'Updates_Changes__c');
          }  
        }       
      }
      
      List<Inspection__c> fullChildrenList = new List<Inspection__c>();  
      for (Id key : childVisitsMapToMaster.keySet()) {
        fullChildrenList.addAll(childVisitsMapToMaster.get(key));        
      }

      flag = true;
      update fullChildrenList;
    }
    
    /**
     * updateChildVisitsData
     * 
     * This function will take in the master visit, its children and the fieldname that the children need to learn.
     * @author Darkis
     */
    private void updateChildVisitsData(Inspection__c masterVisit, Map<Id, List<Inspection__c>> childVisitsMapToMaster, String fieldname) {
      List<Inspection__c> childVisitsToMold = new List<Inspection__c>();
      childVisitsToMold = childVisitsMapToMaster.get(masterVisit.Id);
      // Loop through the children and mold their status to the masters. 
      if (childVisitsToMold != null && childVisitsToMold.size() > 0) {
        for (Inspection__c child : childVisitsToMold) {
          child.put(fieldname, masterVisit.get(fieldname));    
        }  
      }
    }
    
}