phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Umbrella_Members__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field implements a Look Up relationship to create a self relationship in order for the Umbrella record type to display an Umbrella Members related list to display all Providers within the Umbrella</description>
        <label>Umbrella</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected umbrella must be an umbrella record type</errorMessage>
            <filterItems>
                <field>Account.Record_Type_Name__c</field>
                <operation>contains</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Umbrella Members</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document__c.object
<CustomObject>
    <description>A custom object to be used for non-Salesforce reference documents.</description>
    <fields>
        <fullName>Approved_for_Future_Usage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Future Usage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attachment_Status__c</fullName>
        <label>Attachment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attachment(s) Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Attachment</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>The file&apos;s content meta type.</description>
        <label>Content Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Type</label>
        <referenceTo>Document_Type__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes relating to the document.</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>DateTime</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC- {0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document_Type__c.object
<CustomObject>
    <description>An object for storing all document types. This is not to be confused with document prototypes (i.e. image/jpeg, document/pdf, etc)</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>A description for the document type.</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LEAD_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Provider Type</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Document Types</relationshipLabel>
        <relationshipName>Document_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Type</label>
    <nameField>
        <label>Document Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Attachment_Selection_Page_Intro__c</fullName>
        <inlineHelpText>Introduction text that will be displayed on the Attachment Selection Page that is opened when a provider updates document on his/her library or during a transaction. This is only for GSA and R&amp;P provider</inlineHelpText>
        <label>Attachment Selection Page Intro</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Configuration</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>LEAD_Configuration__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Per Transaction Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/S3_File__c.object
<CustomObject>
    <description>This is an object for storing S3 file representations.</description>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>The name of the bucket the file is contained in.</description>
        <label>Bucket</label>
        <length>125</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection between the S3 File reference and the Document__c object.</description>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>S3 Files</relationshipLabel>
        <relationshipName>S3_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <description>The name of the file.</description>
        <label>Filename</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prefix__c</fullName>
        <description>The prefix for the file.</description>
        <inlineHelpText>The originating object&apos;s ID typically.</inlineHelpText>
        <label>Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Transaction_Document__c.object
<CustomObject>
    <description>A junction between the Document and a transaction.</description>
    <fields>
        <fullName>Document_Level__c</fullName>
        <formula>If(Document__r.Provider__r.Record_Type_Name__c == &apos;Umbrella&apos;, &apos;Umbrella&apos; , &apos;Provider&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Type</label>
        <referenceTo>Document_Type__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Transaction Documents (Document)</relationshipLabel>
        <relationshipName>Transaction_Documents1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Licensing_Transaction__c</fullName>
        <label>Licensing Transaction</label>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <formula>Document__r.Provider__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>S3 File</label>
        <referenceTo>S3_File__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Upload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - EEC to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Attachment</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction Document</label>
    <nameField>
        <displayFormat>TD- {0000000}</displayFormat>
        <label>Transaction Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Variance_on_Regulation__c.object
<CustomObject>
    <description>Variance on regulation can be requested by a provider when it can not be in compliance with a specific regulation. Every variance should be associated to 1 reg.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Variance on Regulations</relationshipLabel>
        <relationshipName>Variance_on_Regulations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Variance on Regulation</label>
    <nameField>
        <displayFormat>VAR- {000000}</displayFormat>
        <label>Variance No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Variance on Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_AttachmentSelectionController.cls
public with sharing class EEC_AttachmentSelectionController{
    public LEAD_Configuration__c leadConfiguration {get;set;}
    public Document__c document{get;set;}
	public List<s3Wrapper> listS3File{get;set;}
    public String generateFileId {get; set;}
    public string accessKey{get;set;}
    public string attachmentJSON{get;set;}
	public string documentName{get;set;}
	public string documentNotes{get;set;}
	public Transaction_Document__c transactionDocument {get; set;}
	public Licensing_Transaction__c licenseTransaction {get; set;}
	public Contact contact {get; set;}

    private string accountId{get;set;}
    private string transactionId{get;set;}
    private string varianceId{get;set;}
    private string transactiondocId{get;set;}
    private string attachmentType{get;set;}
    
    private AWS_Config__c aws{get;set;}
    private AWSKeys credentials{get;set;}
    private string bucket{get;set;}
	
	public class s3Wrapper{
		public S3_File__c s3File{get;set;}
		public string fileUrl{get;set;}	
	}
	
    public EEC_AttachmentSelectionController(){
    	string documentId = ApexPages.currentPage().getParameters().get('id');
    	transactionId = ApexPages.currentPage().getParameters().get('transactionId');
    	varianceId = ApexPages.currentPage().getParameters().get('varianceid');
    	transactiondocId = ApexPages.currentPage().getParameters().get('transactiondocId');
    	attachmentType = ApexPages.currentPage().getParameters().get('type');
    	
	    User loggedUser = [select Id, Name, contactId from User where Id = :UserInfo.getUserId()];
	    
	    string providerRecordType = '';
	    
	    if(loggedUser.contactId != null){
	    	contact = [select Id, Account.Id, Account.RecordType.Name from Contact where Id =: loggedUser.contactId];    	
	    	providerRecordType = contact.Account.RecordType.Name;
	    	accountId = contact.Account.Id;

			//System.Debug('TransctionDocID=' + transactiondocId);
			
			//Changed for Lead 5169
			if(string.isNotBlank(transactiondocId))
			{
				transactionDocument = [SELECT Status__c,Document_Level__c FROM Transaction_Document__c WHERE ID= :transactiondocId];
			}
			
			//System.debug('transactionDocument' + transactionDocument);
			if(string.isNotBlank(transactionId))
			{
				licenseTransaction = [Select Id, Provider__c, 
	    			RecordType.Name, RecordType.DeveloperName,
	    			RecordTypeId,
	    			Provider__r.RecordType.Name,
	    			Provider__r.RecordType.DeveloperName,
	    			Transaction_Configuration__c,
			    	Provider__r.Umbrella_Members__c, Status__c
	             	From Licensing_Transaction__c where Id = :transactionId];
			}
			
	    }
	    else{
	    	if(string.isNotBlank(transactionId)){
				//Changed for Lead 5169
		    	licenseTransaction = [Select Id, Provider__c, 
	    			RecordType.Name, RecordType.DeveloperName,
	    			RecordTypeId,
	    			Provider__r.RecordType.Name,
	    			Provider__r.RecordType.DeveloperName,
	    			Transaction_Configuration__c,
			    	Provider__r.Umbrella_Members__c, Status__c
	             	From Licensing_Transaction__c where Id = :transactionId];
	             	
	            accountId = licenseTransaction.Provider__c;
	            
	            Account account = [select Id, RecordType.Name from Account where Id =: accountId];
	            
	            providerRecordType = account.RecordType.Name;

				
	    	}
	    }
	    
    	leadConfiguration = [Select Id, Attachment_Selection_Page_Intro__c from LEAD_Configuration__c where 
    												Name = :providerRecordType];

		aws = AWS_Config__c.getInstance();
        bucket = aws.S3_Bucket_Name__c;
        string signedUrl = aws.S3_Endpoint_Url__c;
        
        credentials = new AWSKeys('eec');
                
        accessKey = credentials.key;

		listS3File = new List<s3Wrapper>();
    	if(string.isNotBlank(documentId)){
			document = [select Id, Document_Name__c, Document_Type__c, Document_Type__r.Name,
				Approved_for_Future_Usage__c,Provider__c,
				Document_Type__r.Description__c, Attachment_Status__c, Notes__c,Valid_From__c,Valid_To__c from 
				Document__c where Id =: documentId limit 1];
			
			if(string.isBlank(document.Document_Name__c))	
				documentName = document.Document_Type__r.Name;
			else
				documentName = document.Document_Name__c;
			
			documentNotes = document.Notes__c;
			
			List<S3_File__c> listFiles = [select Id, Filename__c, Bucket__c, CreatedDate, Prefix__c,Content_Type__c,
							Acl__c from S3_File__c 
						where Document__c =: documentId];
			
			string fileName = '';
	        for(S3_File__c s3File : listFiles){
	        	s3Wrapper s3Wrapper = new s3Wrapper();
	        	fileName = '';
	        	if (!String.isBlank(s3File.Prefix__c)) {
			    	filename += s3File.Prefix__c + '/';
			    }
			    filename += s3File.Filename__c;
			    
	        	s3Wrapper.fileUrl = EEC_S3ComponentCtrl.generateTempS3Url(s3File.Bucket__c,EncodingUtil.urlEncode(filename, 'UTF-8'));
	        	s3Wrapper.s3File = s3File;
	        	listS3File.add(s3Wrapper);
	        }
	        
	        attachmentJSON = JSON.serialize(listS3File);
    	}
    	else{
    		document = new Document__c();
    		documentName = '';
    		documentNotes = '';
    		attachmentJSON = '[]';
    	}
    }
	
	public void doCreateDocument(){
		if(document.Id == null){
			document.Provider__c = accountId;
			insert document;
		}	
	}
	
    public PageReference doBack(){
    	PageReference pageReference = Page.EEC_PortalLandingPage_2;
    	pageReference.setRedirect(true);
    	return pageReference;
    }
    
    /**
	* generateMultiplePolicySignature
	* 
	* This function will call the S3ComponentCtrl to generate multiple or single policy and signature combos for specified files to upload to S3.
	* @author Darkis
	* @param String bucket The name of the bucket to save to.
	* @param String acl The permission level of the file. Typically this would be 'authenticated-read' for our purposes. 
	* @param String fileJson A JSON string of all the files to be uploaded from the Angular Controller.
	*/
    @RemoteAction
    public static List<Map<String, String>> generateMultiplePolicySignature(String bucket, String acl, String fileJson) {
        List<Map<String, String>> returnJson = new List<Map<String, String>> ();
        List<EEC_S3ComponentCtrl.FileTypeJsonWrapper> fileTypeWrapperList = (List<EEC_S3ComponentCtrl.FileTypeJsonWrapper>) JSON.deserialize(fileJson, List<EEC_S3ComponentCtrl.FileTypeJsonWrapper>.class);
        // Loop through the files given and get all the necessary policy/sig combos.
        for (EEC_S3ComponentCtrl.FileTypeJsonWrapper wrapper : fileTypeWrapperList) {
            returnJson.add(EEC_S3ComponentCtrl.generatePolicySignature(bucket, acl, wrapper.filename, wrapper.type, null));
        }
        return returnJson;
    }
    
    public void doSave(){    	
    	String attachmentbody = ApexPages.currentPage().getParameters().get('attachmentbody');
    	String attachmentdeletebody = ApexPages.currentPage().getParameters().get('attachmentdeletebody');

    	List<S3_File__c> s3FilesList;
    	List<S3_File__c> s3FilesDeleteList;
    	if (!String.isBlank(attachmentbody)) {
    		s3FilesList = (List<S3_File__c>) JSON.deserialize(attachmentbody, List<S3_File__c>.class);
    	}
    	else{
    		s3FilesList = new List<S3_File__c>();
    	}
    	if(!string.isBlank(attachmentdeletebody)){
    		s3FilesDeleteList = (List<S3_File__c>) JSON.deserialize(attachmentdeletebody, List<S3_File__c>.class);
    	}
    	else{
    		s3FilesDeleteList = new List<S3_File__c>();
    	}
    	
    	if(document.Valid_From__c == null){
    		document.Valid_From__c = datetime.now();
    		if(string.isNotBlank(varianceId) && attachmentType == 'V'){
    			Variance_on_Regulation__c variance = [select Id, Associated_Regulation__r.Regulation_Number__c from
    			Variance_on_Regulation__c where Id =: varianceId];
    			
    			documentName = 'Variance  -  ' + variance.Associated_Regulation__r.Regulation_Number__c + ' - ' + documentName;
    		}
    		else if(attachmentType == 'A'){
    			documentName = 'Attach  -  ' + documentName;
    		}
    		if(documentName.length() > 100)
    			documentName.subString(0,100);
    			
    		document.Document_Name__c = documentName;
    		document.Notes__c = documentNotes;
    		
    		upsert document;
    		
			//Changed for Lead 5169
    		transactionDocument = new Transaction_Document__c();
    		 	
    		if(string.isNotBlank(transactionId)){
				transactionDocument.Licensing_Transaction__c = transactionId;
			}
    		
    		transactionDocument.Document__c = document.Id;
    		
    		if(string.isNotBlank(transactiondocId)){
    			transactionDocument.Id = transactiondocId;
    		}
    		else{
    			if(string.isNotBlank(transactionId)){
    				transactionDocument.Licensing_Transaction__c = transactionId;
    			}
    		}
    		if(attachmentType == 'A'){
    			transactionDocument.Mode__c = 'Additional';
    		}
    		else if(string.isNotBlank(varianceId) && attachmentType == 'V'){
    			transactionDocument.Variance_on_Regulation__c = varianceId;
    			transactionDocument.Mode__c = 'Variance';
    		}
    		else if(attachmentType == 'I'){
    			transactionDocument.Mode__c = 'Individual';
    		}
    		else if(attachmentType == 'R'){
    			transactionDocument.Mode__c = 'Required';
    		}
    		else if(attachmentType == 'O'){
    			transactionDocument.Mode__c = 'Optional';
    		}
    		if(string.isNotBlank(transactionId)){
	    		transactionDocument.Status__c = 'To Submit';
	    		transactionDocument.Last_Status_Date__c = date.today();
	    		upsert transactionDocument;
    		}
    		if(s3FilesList != null && s3FilesList.size() > 0){
	    		for(S3_File__c s3File : s3FilesList){
	    			s3File.Document__c = document.Id;
	    		}
	    		if(s3FilesList.size() > 0)
	    			upsert s3FilesList;
	    	}
    		
    		if(s3FilesDeleteList != null && s3FilesDeleteList.size() > 0){
    			List<S3_File__c> listDeleteS3 = new List<S3_File__c>();
    			for(S3_File__c s3File : s3FilesDeleteList){
    				if(s3File.Id != null)
    					listDeleteS3.add(s3File);
    			}
    			if(listDeleteS3.size() > 0)
    				delete listDeleteS3;
    		}    		
		}
    	else{
    		if(documentName != document.Document_Name__c || documentNotes != document.Notes__c 
    		 || s3FilesList.size() != listS3File.size() || s3FilesDeleteList.size() > 0){
    		 	document.Valid_To__c = datetime.now();
	    		document.Approved_for_Future_Usage__c = false;
	    		upsert document;
	    		
	    		Document__c newDocument = new Document__c();
	    		if(string.isNotBlank(varianceId)){
	    			Variance_on_Regulation__c variance = [select Id, Associated_Regulation__r.Regulation_Number__c from
	    			Variance_on_Regulation__c where Id =: varianceId];
	    			
	    			documentName = 'Variance  -  ' + variance.Associated_Regulation__r.Regulation_Number__c + ' - ' + documentName;
	    		}
	    		else if(string.isNotBlank(transactionId)){
	    			documentName = 'Attach  -  ' + documentName;
	    		}
	    		if(documentName.length() > 100)
    				documentName.subString(0,100);
    				
    			document.Document_Name__c = documentName;
	    		newDocument.Notes__c = documentNotes;
	    		newDocument.Valid_From__c = datetime.now();
	    		newDocument.Document_Type__c = document.Document_Type__c;
	    		newDocument.Provider__c = document.Provider__c;
	    		
	    		insert newDocument;
	    		
	    		if(s3FilesList != null){
	    			List<S3_File__c> listNewS3 = new List<S3_File__c>();
		    		for(S3_File__c s3File : s3FilesList){
		    			if(s3File.Id == null){
		    				s3File.Document__c = newDocument.Id;
			    			listNewS3.add(s3File);
		    			}
		    			else{
			    			S3_File__c newS3 = s3File.clone(false, false, false, false);
			    			newS3.Document__c = newDocument.Id;
			    			listNewS3.add(newS3);
		    			}
		    		}
		    		if(listNewS3.size() > 0)
		    			insert listNewS3;
		    	}
	    		else{
	    			List<S3_File__c> listNewS3 = new List<S3_File__c>();
	    			for(s3Wrapper s3File : listS3File){
		    			S3_File__c newS3 = s3File.s3File.clone(false, false, false, false);
		    			newS3.Document__c = newDocument.Id;
		    			listNewS3.add(newS3);
		    		}
		    		if(listNewS3.size() > 0)
		    			insert listNewS3;
		    	}
		    	
		    	if(string.isNotBlank(transactionId)){
			    	Transaction_Document__c transactionDocument = new Transaction_Document__c();
		    		transactionDocument.Document__c = newDocument.Id;
		    		if(string.isNotBlank(transactiondocId)){
		    			transactionDocument.Id = transactiondocId;
		    		}
		    		else{
	    				transactionDocument.Licensing_Transaction__c = transactionId;
		    		}
		    		if(string.isNotBlank(varianceId)){
		    			transactionDocument.Variance_on_Regulation__c = varianceId;
		    		}
		    		if(attachmentType == 'A'){
		    			transactionDocument.Mode__c = 'Additional';
		    		}
		    		else if(string.isNotBlank(varianceId) && attachmentType == 'V'){
		    			transactionDocument.Variance_on_Regulation__c = varianceId;
		    			transactionDocument.Mode__c = 'Variance';
		    		}
		    		else if(attachmentType == 'I'){
		    			transactionDocument.Mode__c = 'Individual';
		    		}
		    		else if(attachmentType == 'R'){
		    			transactionDocument.Mode__c = 'Required';
		    		}
		    		else if(attachmentType == 'O'){
		    			transactionDocument.Mode__c = 'Optional';
		    		}
		    		transactionDocument.Last_Status_Date__c = date.today();
		    		transactionDocument.Status__c = 'To Submit';
		    		upsert transactionDocument;
		    	}
    		}
    	}
    }
}