phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact_Role__c.object
<CustomObject>
    <description>This is a junction object between a provider and contact. A single contact may play multiple roles for a provider like Owner, Administrator etc.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact to which contact role is associated with.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Formula__c</fullName>
        <formula>AND (
OR ( ISBLANK(Start_Role_Licensing_Transaction__c),  ISPICKVAL(Start_Role_Licensing_Transaction__r.Status__c, &quot;Closed (License Issued / Updated)&quot;), ISPICKVAL(Start_Role_Licensing_Transaction__r.Status__c, &quot;Closed (Processed)&quot;))
,
OR(
AND(ISBLANK( Start_Date__c ), ISBLANK( End_Date__c )),
AND(ISBLANK( End_Date__c), Start_Date__c &lt;= TODAY()),
AND(Start_Date__c &lt;= TODAY(), End_Date__c &gt;= TODAY())
))</formula>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Registration_Page_Instruction__c</fullName>
        <inlineHelpText>For GSA Only. Instruction / Introduction that will be displayed at the top of the Meeting Registration Page</inlineHelpText>
        <label>Registration Page Instruction</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Provider_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Expected_No_of_participants__c</fullName>
        <description>Number of participants that are scheduled or were scheduled to attend</description>
        <label>Expected - No. of participants</label>
        <summaryFilterItems>
            <field>Provider_Meeting_Participant__c.Participation_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>Provider_Meeting_Participant__c.Provider_Meeting__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Language the speaker of the meeting will be using</description>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other_Non_English</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Meeting_Address__c</fullName>
        <description>This field will be populated by default with the Region address but can be updated by the user</description>
        <label>Meeting Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Location_Description__c</fullName>
        <description>This field will be populated by default with the Region associated field but can be updated by the user</description>
        <label>Meeting Location Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region the meeting will be hold</description>
        <label>Meeting Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Provider Meetings</relationshipLabel>
        <relationshipName>Provider_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Status__c</fullName>
        <description>Status of the meeting</description>
        <label>Meeting Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open for registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed for registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <description>Type of meeting that will be conducted</description>
        <label>Meeting Type</label>
        <picklist>
            <picklistValues>
                <fullName>PPM (FCC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPM (GSA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal (GSA)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Remaining_Spots__c</fullName>
        <formula>IF( (No_of_seats_available__c  -  Expected_No_of_participants__c)  &gt;= 0, 
     No_of_seats_available__c  -  Expected_No_of_participants__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Remaining Spots</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheduled_End__c</fullName>
        <description>End Time of the meeting</description>
        <label>Scheduled End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start__c</fullName>
        <description>Start Time of the meeting</description>
        <label>Scheduled Start</label>
        <type>DateTime</type>
    </fields>
    <label>Provider Meeting</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Provider Meeting No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Provider_Meeting_Participant__c.object
<CustomObject>
    <fields>
        <fullName>GSA_Renewal_Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If checked, it means that it&apos;s the latest information available for this provider</description>
        <label>GSA Renewal Participant</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>Contact.Account.License_Status__c</field>
                <operation>equals</operation>
                <value>Licensed</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.Is_GSA__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provider Meeting Participants</relationshipLabel>
        <relationshipName>Provider_Meeting_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GSA_Renewal_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For Renewal meeting, provider the participant belongs to. This field will be filled automatically.</description>
        <label>GSA Renewal Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Meeting Participants</relationshipLabel>
        <relationshipName>Provider_Meeting_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Region__c</fullName>
        <formula>Provider_Meeting__r.Meeting_Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <formula>TEXT( Provider_Meeting__r.Meeting_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participation_Status__c</fullName>
        <description>Status of the registration / participation</description>
        <label>Participation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Meeting__c</fullName>
        <description>Meeting the participant is registered / attended to</description>
        <label>Provider Meeting</label>
        <referenceTo>Provider_Meeting__c</referenceTo>
        <relationshipLabel>Provider Meeting Participants</relationshipLabel>
        <relationshipName>Provider_Meeting_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Time__c</fullName>
        <formula>Provider_Meeting__r.Scheduled_Start__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scheduled Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Provider Meeting Participant</label>
    <nameField>
        <displayFormat>PMA-{0000000}</displayFormat>
        <label>Provider Meeting Participant No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the region office address</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FCC_Meeting_Default_Allowed_no_of_part__c</fullName>
        <inlineHelpText>Give default description on how to find the building / meeting room for Providers attending an EEC meeting that will be displayed on portal. If this information is set, then when user is creating a new meeting for this region, then this text will be used.</inlineHelpText>
        <label>FCC Meeting Default Allowed no.of part</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Nb_of_Participants_For_GSA_Renewal__c</fullName>
        <inlineHelpText>For GSA Only. Define the maximum number of participants a provider can register from the portal to a given renewal meeting. If you don&apos;t have a limit, let this field empty</inlineHelpText>
        <label>Max Nb of Participants For GSA Renewal</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone number of the region office</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_MeetingRegistrationController.cls
public without sharing class EEC_MeetingRegistrationController {
	public LEAD_Configuration__c leadConfiguration {get;set;}
	public string errorParticipantMessage{get;set;}
	public string errorMeetingMessage{get;set;}
	private string accountId{get;set;}
	public string participantId{get;set;}
	public string selectedMeetingId{get;set;}
	public string viewOnly{get;set;}
	public string selectedParticipantId{get;set;}
	public string selectedContact{get;set;}
	public boolean isViewOnly{get;set;}
	public Provider_Meeting__c providerMeeting{get;set;}
	public List<Provider_Meeting_Participant__c> listMeetingParticipant{get;set;}
	public List<Provider_Meeting__c> listMeeting{get;set;}
	public List<selectOption> listContacts{get;set;}
	public string errorMessage{get;set;}
	
    public EEC_MeetingRegistrationController() {
    	isViewOnly = true;
    	errorMessage = '';
    	User loggedUser = [select Id, Name, contactId from User where Id = :UserInfo.getUserId()];    	
    	Contact contact = [select Id, Account.Id, Account.RecordType.Name from Contact where Id =: loggedUser.contactId];    	
    	accountId = contact.Account.Id;    	
    	string providerRecordType = contact.Account.RecordType.Name;    	
    	leadConfiguration = [Select Registration_Page_Instruction__c from LEAD_Configuration__c where 
    												Name = :providerRecordType];	
		providerMeeting = new Provider_Meeting__c();		
		doGetParticipantDetails();
    }
    
    private void doGetParticipantDetails(){    	
    	listMeetingParticipant = [select Id, GSA_Renewal_Participant__r.Name, Scheduled_Start_Time__c, 
    							Provider_Meeting__c, GSA_Renewal_Participant__c,
    							Provider_Meeting__r.Meeting_Address__c from Provider_Meeting_Participant__c
    							where GSA_Renewal_Provider__c =: accountId
    							and Scheduled_Start_Time__c > TODAY
    							and Participation_Status__c= 'Registered'    							
    							and Meeting_Type__c = 'Renewal (GSA)'];
    	
    	if(listMeetingParticipant.size() == 0){
    		errorParticipantMessage = 'None of your team member is currently registered for an upcoming renewal meeting.';
    	}	
    	
    	listMeeting = [select Id, Scheduled_Start__c, Meeting_Address__c, Language__c, Number_of_Remaining_Spots__c,
    				Meeting_Region__r.FCC_Meeting_Default_Allowed_no_of_part__c,
    				Meeting_Region__r.Max_Nb_of_Participants_For_GSA_Renewal__c,
    				Expected_No_of_participants__c
    				from Provider_Meeting__c where Meeting_Status__c = 'Open for registration'
    				and Scheduled_Start__c > TODAY
    				and Meeting_Type__c = 'Renewal (GSA)' order by Scheduled_Start__c asc];		
    				
        if(listMeeting.size() == 0){
        	errorMeetingMessage = 'Currently, there is no meeting scheduled. Contact your licensor for more information.';
        }
    }
    
    public void doRegistration(){
    	Provider_Meeting_Participant__c providerParticipant = new Provider_Meeting_Participant__c();
    	providerParticipant.GSA_Renewal_Participant__c = selectedContact;
    	providerParticipant.GSA_Renewal_Provider__c = accountId;
    	providerParticipant.Participation_Status__c = 'Registered';
    	providerParticipant.Provider_Meeting__c = selectedMeetingId;
    	
    	insert providerParticipant;
    	
    	doGetParticipantDetails();	
    }
    
    public pageReference doBack(){
    	PageReference pageReference = Page.EEC_PortalLandingPage_2;
    	pageReference.setRedirect(true);
    	return pageReference;
    }
    
    public void doCancelRegistration(){
    	Provider_Meeting_Participant__c participant = [select Id, Participation_Status__c from 
        Provider_Meeting_Participant__c where Id =: selectedParticipantId];
        
        participant.Participation_Status__c = 'Cancelled';        
        update participant;
        
        doGetParticipantDetails();
    }
    
    public PageReference doViewMeetingDetail(){
    	if(viewOnly == 'yes'){
    		isViewOnly = true;
    	}
    	else{
    		isViewOnly = false;
    	}
    	errorMessage = '';
    	providerMeeting = [select Id, Scheduled_Start__c, Scheduled_End__c, 
    						Number_of_Remaining_Spots__c,
							Meeting_Address__c, Language__c, Meeting_Location_Description__c,
							Meeting_Region__r.Phone__c, Meeting_Region__r.Email__c,
							Meeting_Region__r.FCC_Meeting_Default_Allowed_no_of_part__c,
    						Meeting_Region__r.Max_Nb_of_Participants_For_GSA_Renewal__c,
    						Expected_No_of_participants__c
							from Provider_Meeting__c where Id=: selectedMeetingId];
		
		if(providerMeeting.Number_of_Remaining_Spots__c == 0){
			errorMessage = 'You have reached the limit of allowed number of participants for this meeting. Please contact your regional office if you need to register more participants.'; 	
		}
		List<Provider_Meeting_Participant__c> listParticipant = [select Id, GSA_Renewal_Participant__r.Name, Scheduled_Start_Time__c, 
    							Provider_Meeting__c, GSA_Renewal_Participant__c,
    							Provider_Meeting__r.Meeting_Address__c from Provider_Meeting_Participant__c
    							where Provider_Meeting__c =: selectedMeetingId
    							and Participation_Status__c= 'Registered'];
    	
        Set<Id> setContactId = new Set<Id>();
        
        for(Provider_Meeting_Participant__c participant : listParticipant){
        	if(!setContactId.contains(participant.GSA_Renewal_Participant__c)){
        		setContactId.add(participant.GSA_Renewal_Participant__c);
        	}
        }
        
        List<Contact_Role__c> listContactRoles = [select Id, Contact__c, Contact__r.Name from Contact_Role__c where
        									Contact__r.AccountId =: accountId and Current_Formula__c = true];
        
        listContacts = new List<SelectOption>();        
        listContacts.add(new SelectOption('--Select--', '--Select--'));
        
        for(Contact_Role__c contactRole : listContactRoles){
        	if(!setContactId.contains(contactRole.Contact__c)){
        		listContacts.add(new SelectOption(contactRole.Contact__c, contactRole.Contact__r.Name));
        		setContactId.add(contactRole.Contact__c);
        	}
        }
		return null;
	}
}