phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_GSA__c</fullName>
        <description>Will be true if this provider is a Large Group or Small Group</description>
        <formula>OR ( Record_Type_Name__c  = &apos;Large Group&apos;, Record_Type_Name__c   = &apos;Small Group&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is GSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_R_P__c</fullName>
        <description>Return True if this is an R&amp;P provider</description>
        <formula>OR(Is_Residential__c,  Is_Placement__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is R&amp;P</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Umbrella</fullName>
        <active>true</active>
        <description>Umbrella</description>
        <label>Umbrella</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in the data conversion batch to convert GSA, R&amp;P Contacts to ContactRoles</description>
        <label>Contact Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Program Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_Batch_ConvertContactToContactRole.cls
//Author - Latha Davuluri
//Batch job to convert Contacts to Contact Roles on ONLY GSA and R&P Providers  - LEAD-4721

global class EEC_Batch_ConvertContactToContactRole implements Database.Batchable<sObject>{

    global List<Contact> dataListSize = null;
      
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT c.Id, c.Role__c, c.Name,  c.Contact_Processed__c, c.AccountId FROM Contact c WHERE c.AccountId != null AND c.AccountId in
                     (SELECT id FROM account WHERE is_GSA__c = true OR is_R_P__c = true OR RecordType.Name like '%umbrella%') AND c.Contact_Processed__c = false]);
    }

    global void execute(Database.BatchableContext BC,List<Contact> scope){
    	
        dataListSize = scope;
        
        for(Contact c : scope){
        	   EEC_ConvertContactToContactRole.convertContactToContactRole(c);
               c.Contact_Processed__c = true;  
       	}       
        
        update scope; 
        
    }

    global void finish(Database.BatchableContext BC){
    	
    	try{
	    	if(dataListSize != null){
		    	AsyncApexJob batchJob = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
	       
		        Integer jobs = [Select count() From AsyncApexJob Where JobType = 'BatchApex' and ( Status = 'Queued' or Status = 'Processing' or Status = 'Preparing' )];   
		        
		        if(jobs <= 1){
		            EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ConvertContactToContactRole'); 
		        }
		
		        //If NumberOfErrors is "0" - if the execute method processed all records without errors - then call next contact batch.
			    if (batchJob.NumberOfErrors == 0)
			    {     
			        EEC_Batch_ConvertContactToContactRole batchCreateContactRole = new EEC_Batch_ConvertContactToContactRole();   
			        Id batchProcessId = Database.executeBatch(batchCreateContactRole,1);    //finish method logic here
			    }
			    else
			    {
			        //process other code
			        if ((batchJob.NumberOfErrors == 0) && (jobs < 5)){
		
		        		 EEC_Batch_ConvertContactToContactRole batchCreateContactRole = new EEC_Batch_ConvertContactToContactRole();   
			             Id batchProcessId = Database.executeBatch(batchCreateContactRole,1);    //finish method logic here
		         		}
		        	else{
		         		//wait for 1 hour
		          	}
			    }
	         }
	         else{
	         	EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ConvertContactToContactRole'); 
	         }
    	}
    	catch(exception ex){
    		System.debug('----> Error Processing the EEC_Batch_ConvertContactToContactRole job: ' + ex.getMessage());
    	}
    	
    }

}