phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <description>Will be filled by the corrective actions taken by the provider in case of non-compliance</description>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <description>Date the corrective actions were or will be implemented. This information should be provided by the provider when filling the answer of statement of non-compliance.</description>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Assistance__c</fullName>
        <label>Technical Assistance</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Require_Portal_Feedback__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows for Licensor/Investigator to specify if a feedback is to be sent to the Provider via email to request a review of non-compliance items</description>
        <inlineHelpText>Check this field if an email is required to be sent to the Provider to request a review of non-compliant items</inlineHelpText>
        <label>Require Portal Feedback</label>
        <type>Checkbox</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TestNonComplaintItemTrigger.cls
@isTest
public with sharing class EEC_TestNonComplaintItemTrigger{
    @isTest static void testupdateRequireFeedback() {
        test.startTest();
        
        User u = EEC_TestUtil.mockUser();        
        System.runAs(u) { 
            ID accountid;      
            Integer int1 =0;

            Investigation__c  invest = EEC_TestUtil.loadInvestigationSetup();  
             
            Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
            test.startTest();
            insp.Investigation__c = invest.Id;
            update insp;

            invest.Require_Portal_Feedback__c = true;
            update invest;
            test.stoptest();
        }
    } 
    @isTest static void testRequireFeedback() {
        Account acc = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
        
        Inspection__c insp = EEC_TestUtil.mockInspection(acc);
        
        Standard_Inspection_Item__c sii = EEC_TestUtil.mockStdInspectionItem();
        
        Inspection_Item__c item1 = EEC_TestUtil.mockInspectionItem(insp, sii, 'Non-Compliant', false, 'Test');
        Inspection_Item__c item2 = EEC_TestUtil.mockInspectionItem(insp, sii, 'Compliant', false, 'Test');
        
        test.startTest();
        Inspection_Item__c ii = [SELECT Id, Inspection_No__r.Provider_No__c,Inspection_No__c,Observations__c,
                                 Technical_Assistance__c, Date_Implemented__c,Correction_Plan__c
                                 FROM Inspection_Item__c 
                                 WHERE Inspection_Result__c = 'Compliant' LIMIT 1];
        
        //Inspection__c i = [SELECT Id FROM Inspection__c WHERE ID =: ii.Inspection_No__c LIMIT 1];
        
        ii.Observations__c = 'technicalAssistance';
        ii.Technical_Assistance__c = 'technicalAssistance';
        ii.Inspection_Result__c = 'Non-Compliant';
        ii.Date_Implemented__c  = Date.Today();
        ii.Correction_Plan__c = 'Testing222';
        update ii;

        test.stopTest();
    }
}