phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/HistoryOfNonCompliance__c.object
<CustomObject>
    <fields>
        <fullName>Citation__c</fullName>
        <label>Citation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InteractionDate__c</fullName>
        <label>InteractionDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <label>Interaction</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>HistoryOfNonCompliance</label>
    <nameField>
        <label>ProgramID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HistoryOfNonCompliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Date_of_Visit__c</fullName>
        <description>Date of site inspection visit</description>
        <label>Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Legacy_System_Interaction__c</fullName>
        <label>Legacy System Interaction #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Provider_Type__c</fullName>
        <formula>Provider_No__r.RecordType.Name</formula>
        <label>Provider Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Visit__c</fullName>
        <description>Reason of Visit</description>
        <label>Reason of Visit</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Licensing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License 90-day Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Full Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Activate Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy System Import</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Change</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Additional_Inspection_Item_Name__c</fullName>
        <description>Allow user to name this additional inspection item</description>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessed_Date__c</fullName>
        <inlineHelpText>Date the visit item was assessed (= mark compliant / non compliant / not applicable) by the licensor. This date is automatically filled by the system when a result is added for the first time.</inlineHelpText>
        <label>Assessed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Category_additional__c</fullName>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care of Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Child Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Home Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General records/logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health/Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy System Non Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personnel Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Indoors</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this regulation applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/HistoryOfNonComplianceTriggerHelper.cls
public with sharing class HistoryOfNonComplianceTriggerHelper {
	//Created by LD - LEAD-2226
    public static void bulkVisitInsert(List<HistoryOfNonCompliance__c> triggerNew){
    	
    	Set<string> ProgramIds = new Set<string>();
    	Set<string> ProgramIdInteraction = new Set<string>();
    	Set<string> CitationIds = new Set<string>();
    	List<string> citationList = new List<string>();
    	integer prevPId = 0;
    	integer currPId = 0;
    	
    	for (HistoryOfNonCompliance__c nc : triggerNew) {
    		
    		currPId = integer.valueof(nc.name.trim());
    		
    		if(currPId != prevPId){
    		   ProgramIds.add(nc.name.trim()); 
    		   ProgramIdInteraction.add(nc.name.trim() + '|' + nc.Interaction__c.trim()); 
    		   prevPId = currPId;
    		   currPId = 0;
    		} 
    		
    		if (nc.citation__c != null){
	    		citationList = nc.citation__c.split(';');
	    		for(string cs: citationList){
	    			CitationIds.add(cs);
	    		}
    		}
    				
    	}
    	
    	List<Inspection__c> VisitsToInsert = new List<Inspection__c>();
    	List<Inspection_Item__c> VisitItemsToInsert = new List<Inspection_Item__c>();
    	
    	List<Regulation__c> RegulationList = [Select Id, Name, Applicable_To__c From Regulation__c Where Name in :CitationIds];
    	Map<string,Regulation__c> RegulationMap = new Map<string,Regulation__c>();
    	for(Regulation__c rg: RegulationList){
    		RegulationMap.put(rg.Name,rg);
    	}
    	
    	system.debug('****Regulation Map:'+RegulationMap);
    	
    	Map<Id,Account> AccountMap = new Map<Id,Account>([Select Id,Name, Provider_No__c,RecordTypeId From Account Where Provider_No__c in :ProgramIds]);
    	Map<string,Account> ProgramIdMap = new Map<string,Account>();
    	for(Account a: AccountMap.values()){
    		ProgramIdMap.put(a.Provider_No__c,a);
    	}
    	
        string prevVisit = null;
        string newVisit = null;
        integer interactionYear = 0;
        string ncStr = null;
        Id LegacySystemImport = [Select id,Name from RecordType where sObjectType = 'Inspection__c' and Name like 'Legacy System Import%'].Id;
        Id NonStandardItm = [Select id,Name from RecordType where sObjectType = 'Inspection_Item__c' and Name like 'Non Standard%'].Id;
        
    	for (HistoryOfNonCompliance__c nc : triggerNew) {
    		
    		newVisit = nc.Name.trim() + '|' + nc.Interaction__c.trim();
    		
    		if (nc.InteractionDate__c != null){
	    	    interactionYear = nc.InteractionDate__c.Year();
	    	 }
	    		       		
    		if(newVisit != prevVisit){
    		
	    		Account acc = ProgramIdMap.get(nc.Name);	
	    		
	    		if(acc != null){
			
	    		   prevVisit = null;	
	    			
	    		   Inspection__c visiTT = new Inspection__c();
	    		  
	    		   visiTT.RecordTypeId = LegacySystemImport;
	    		   visiTT.Provider_No__c = acc.Id;
	    		   visiTT.Legacy_System_Interaction__c = nc.Interaction__c;
	    		   visiTT.Date_of_Visit__c = nc.InteractionDate__c;
	    		   visiTT.Type_of_Visit__c = 'Legacy System Import';
	    		   visiTT.Status__c = 'Closed';
	    		   
	    		   system.debug('YEAR*********:'+nc.InteractionDate__c.Year());
	    		   
	    		   if (interactionYear == 2015 || interactionYear == 2014){
		              ProgramIds.add(acc.Id);
			        }
	    		   
	    		   VisitsToInsert.add(visiTT);
	    		   
	    		   prevVisit = nc.Name.trim() + '|' + nc.Interaction__c.trim();
	    		   interactionYear = 0;    		   
    		
	    	      } 
    		  }
    		  newVisit = null; 	      
    	      
          }
          
          if(VisitsToInsert.size() > 0){
          	insert VisitsToInsert;
          	
          }
         
          if(VisitsToInsert.size() > 0){
          	string prgId = null;
          	DateTime dtGMT = null;
          	DateTime current = system.now();
          	Date currDate = system.today();
			Time currTime = current.time();
			DateTime local;
            List<string> regList = new List<string>();
          	Map<Id,Inspection__c> VisitMap = new Map<Id,Inspection__c>([Select Id,Name,Provider_No__c,Provider_Type__c,Legacy_System_Interaction__c From Inspection__c Where Id in :VisitsToInsert]);
          
          	system.debug('****VistMap****:'+ VisitMap);
          	List<HistoryOfNonCompliance__c> nonComplianceList = [Select Id,Name, Interaction__c,Observations__c,InteractionDate__c,Citation__c  From HistoryOfNonCompliance__c];
          	if (VisitMap != null){
          	for(Inspection__c v : VisitMap.values()){
          		
          		Account programIdVal = AccountMap.get(v.Provider_No__c);
       
          		if (programIdVal != null){
              	    if (nonComplianceList.size() > 0){
	          	     	for (HistoryOfNonCompliance__c ncl : nonComplianceList){
	          	     		prgId = string.valueOf(programIdVal.Provider_No__c);
	          	     	     if(ncl.Name.trim() == prgId && (ncl.InteractionDate__c.Year() == 2014 || ncl.InteractionDate__c.Year() == 2015) && ncl.Interaction__c.trim() == v.Legacy_System_Interaction__c.trim()){
			          	     	 Inspection_Item__c visitItm = new Inspection_Item__c();
				    		     
				    		     visitItm.Inspection_No__c = v.Id;
				    		     visitItm.RecordTypeId = NonStandardItm;
					    	     visitItm.Category_additional__c = 'Legacy System Non Compliance';
					    	     visitItm.Additional_Inspection_Item_Name__c = ncl.Observations__c.substring(0,37) + '...';
					    	     visitItm.Observations__c = ncl.Observations__c;
					    	     visitItm.Inspection_Result__c ='Non-Compliant';
					    	     
					    	     if(ncl.InteractionDate__c != null){
					    	     	dtGMT = ncl.InteractionDate__c;
					    	     	currDate = dtGMT.dateGmt();
                                    local = datetime.newinstance(currDate,currTime); 
				    	            visitItm.Assessed_Date__c = local;
					    	     }
					    	     
					    	     system.debug('****Citation ****:'+ncl.Citation__c);
					    	     
					    	     regList = ncl.citation__c.split(';');
					    		 if(regList.size() > 1){
						    		 for (string cs: regList){
						    		 	 Regulation__c rgFound = regulationMap.get(cs);
						    	         
						    	          if (rgFound != null){
						    	     	
						    	             system.debug('****rgFound***:'+rgFound);
						    	             system.debug('****Provider_Type__c***:'+v.Provider_Type__c);
						    	     	
						    	     	     if (rgFound.Applicable_To__c.contains(v.Provider_Type__c)){
						    	     	     	 Inspection_Item__c visitItmClone = visitItm.clone();	
						    	     		     system.debug('****Applicable_To***:'+rgFound.Applicable_To__c.contains(v.Provider_Type__c));				  
						    		             visitItmClone.Associated_regulation__c = rgFound.Id;
						    		             VisitItemsToInsert.add(visitItmClone); 
						    	     	      }
						    		      } 
						    		   }//end for citation
					    		   }
					    		   else if(regList.size() <= 1){
						     	       Regulation__c rgFound2 = regulationMap.get(ncl.Citation__c);
							    	   if(rgFound2 != null){
							    	     	
							              system.debug('****rgFound***:'+rgFound2);
							    	      system.debug('****Provider_Type__c***:'+v.Provider_Type__c);
							    	     	
							    	   	  if (rgFound2.Applicable_To__c.contains(v.Provider_Type__c)){	
							    	    	 system.debug('****Applicable_To***:'+rgFound2.Applicable_To__c.contains(v.Provider_Type__c));				  
							    		     visitItm.Associated_regulation__c = rgFound2.Id;
							    	       }
							            }
							            VisitItemsToInsert.add(visitItm); 
					    		   }
	          	     	     }
	          	     	     prgId = null; 
	          	     	  } //end for
	          	        }// end if  
	       		     }	 
	    	     }//end for
          	  }//end if
          }
          if(VisitItemsToInsert.size() > 0){
          	system.debug('VisitItems to Insert****:'+VisitItemsToInsert);
          	insert VisitItemsToInsert;
          }
    
    string SOQL = 'Select Id from HistoryOfNonCompliance__c';
    Database.executeBatch(new Batch_CleanHistoryofNonCompliance(SOQL),200);       
          
    }

}