phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Electronic_Communication__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, emails and documents will be sent electronically. Also, electronic signature will be required. If unchecked, all communication will be paper and the email address is not mandatory.</description>
        <inlineHelpText>If checked, emails and documents will be sent electronically. Also, electronic signature will be required.</inlineHelpText>
        <label>Electronic Communication</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Umbrella_Members__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field implements a Look Up relationship to create a self relationship in order for the Umbrella record type to display an Umbrella Members related list to display all Providers within the Umbrella</description>
        <label>Umbrella</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected umbrella must be an umbrella record type</errorMessage>
            <filterItems>
                <field>Account.Record_Type_Name__c</field>
                <operation>contains</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Umbrella Members</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <recordTypes>
        <fullName>Small_Group</fullName>
        <active>true</active>
        <description>Small group and school age</description>
        <label>Small Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>Umbrella</fullName>
        <active>true</active>
        <description>Umbrella</description>
        <label>Umbrella</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Checklist_Summary_issue_date__c</fullName>
        <inlineHelpText>Date the checklist summary was issued last.</inlineHelpText>
        <label>Tool Summary issue date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_Deadline__c</fullName>
        <description>This field contains the deadline given to the provider to answer to a visit report with corrective actions</description>
        <formula>IF( OR(ISPICKVAL(Status__c, &quot;Closed&quot;),  ISPICKVAL(Status__c, &quot;Cancelled&quot;), ISPICKVAL(Status__c, &quot;Feedback received, to review&quot;), Number_of_non_compliant_items__c=0,  RecordType.Name = &quot;Investigation Visits&quot;),NULL, TODAY() +  Number_of_days_to_receive_response__c)</formula>
        <inlineHelpText>Deadline given to the provider to answer to a visit report with corrective actions</inlineHelpText>
        <label>Corrective Action Reception Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Issue_Date__c</fullName>
        <inlineHelpText>Date the cover letter was issued last.</inlineHelpText>
        <label>Cover Letter Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Note that all licensing visits with the following statuses will be available on portal:  &quot;Scheduled&quot; (if Announced flag is checked)  / &quot;Closed&quot; / &quot;Report Sent to Provider, Awaiting Feedback&quot; / &quot;Feedback received, to review&quot;</description>
        <inlineHelpText>If checked, non compliant items associated to this visit have been published on portal and are ready to be reviewed.</inlineHelpText>
        <label>Published on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inspector_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Licensor or investigator who performs the inspection</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inspections_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_days_to_receive_response__c</fullName>
        <description>Number of days to receive response</description>
        <inlineHelpText>Number of days given to the provider to receive corrective actions plan.</inlineHelpText>
        <label>Number of Days to Receive Corr. Actions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Narrative_Issue_Date__c</fullName>
        <inlineHelpText>Date the Visit Narrative was last issued</inlineHelpText>
        <label>Visit Narrative Issue Date</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_ReportGeneration_OneExtensionTest.cls
@isTest
public class EEC_ReportGeneration_OneExtensionTest {   
    public static testmethod void testProcessNaraitiveDefault() {
        
          Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('Small Group', null);
        
        Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'Small_Group');
        accnt.Config_Record__c = config2.Id;
        update accnt;
        
          Contact contact = EEC_TestUtil.mockDirectorContact(accnt);
        
         Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();	
        
        /*Account provider = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
        
        Inspection__c i = EEC_TestUtil.mockInspection(provider);

        i.Number_of_days_to_receive_response__c= 5;
        update i;
        
        //Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
        System.debug('Test Provider Id' + i.Provider_No__c);*/
        
        Inspection__c i = EEC_TestUtil.loadInspectionSetup();
       // i.Corrective_Action_Deadline__c = TODAY();
        
        Test.startTest();
        
        EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
        //ext.processNaraitiveDefault();
        //System.assertEquals('This functionality is only available if the visit is in status "Visit Completed" or "Report to be sent to Provider"', ext.toastMsg);
        
        i.Number_of_days_to_receive_response__c= 5;
        i.Status__c = 'Visit Completed';
        i.Inspector_del__c = UserInfo.getUserId();  
        update i;
        
        ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
        ext.processNaraitiveDefault();
        
        Test.stopTest();
    } 
    public static testmethod void testProcessNaraitiveDefaultWithUmbrella() {
       
        /*Account provider = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
        Account umbrella = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
        
        Contact director = EEC_TestUtil.mockContact(provider, 'firstName', 'lastName', 'Director');
        //Contact mainContact = EEC_TestUtil.mockContact(provider, 'firstName', 'lastName', 'Main Contact / Licensee');  
        
        umbrella.Umbrella_Members__c = provider.Id;
        update provider;  
        
        Inspection__c i = EEC_TestUtil.mockInspection(umbrella);
        
        i.Number_of_days_to_receive_response__c = 5;
        update i;
        
        //Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
        System.debug('Test Provider Id' + i.Provider_No__c);*/
        
        Inspection__c i = EEC_TestUtil.loadInspectionSetup();
        
        Test.startTest();
        
        EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
        ext.processNaraitiveDefault();
        //System.assertEquals('This functionality is only available if the visit is in status "Visit Completed" or "Report to be sent to Provider"', ext.toastMsg);
        
        i.Number_of_days_to_receive_response__c= 5;
        i.Status__c = 'Visit Completed';
        i.Inspector_del__c = UserInfo.getUserId();  
        update i;
        
        ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
        //ext.processNaraitiveDefault();
        
        Test.stopTest();
    }   
    
    public static testmethod void testGenerateAllReports() {
        
        
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
        
        Test.setCurrentPageReference(new PageReference('EEC_ReportGeneration_One')); 
        System.currentPageReference().getParameters().put('reportType', 'nc');
        
        Test.startTest();
        
        EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
        ext.generateAllReports();
        System.assertEquals('Report Narrative can only be generated if the Visit is Completed, and not Closed', ext.toastMsg);
        
        i.Status__c = 'Visit Completed';
        update i;
        
        ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
        ext.generateAllReports();
        System.assertEquals('This functionality is not available for a Closed or Cancelled Visit, Visit must first be re-opened by a Supervisor or Director', ext.toastMsg);
        
        Test.stopTest();  
    } 
    public static testmethod void testGenerateChecklistReports() {
        
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
        
        i.Status__c = 'Visit Completed';
        update i;
        Test.startTest();
        
        EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));  
        
        Test.setCurrentPageReference(new PageReference('EEC_ReportGeneration_One')); 
        System.currentPageReference().getParameters().put('reportType', 'checklist');
        ext.generateAllReports();
        System.assertEquals('Visit Summary generated. See Notes and Attachments to view the report.', ext.toastMsg);
        
        
        Test.stopTest();    
    }
    
    public static testmethod void testGenerateNarrativeReports() {
        
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
        
        i.Status__c = 'Visit Completed';
        update i;
        Test.startTest();
        
        EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));  
        
        Test.setCurrentPageReference(new PageReference('EEC_ReportGeneration_One')); 
        System.currentPageReference().getParameters().put('reportType', 'narrative');
        ext.generateAllReports();
        System.assertEquals('Visit Narrative generated. See Notes and Attachments to view the report.', ext.toastMsg);
        
        
        Test.stopTest(); 
    }
    
    public static testmethod void testGenerateCoverLetterReports() {
        
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
        
        i.Status__c = 'Visit Completed';
        update i;
 
        Test.startTest();
               
        EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));  
        
        Test.setCurrentPageReference(new PageReference('EEC_ReportGeneration_One')); 
        System.currentPageReference().getParameters().put('reportType', 'coverletter');
        ext.generateAllReports();
        System.assertEquals('Cover Letter generated. See Notes and Attachments to view the report.', ext.toastMsg);
        
        
        Test.stopTest();  
        
    }  
    
    public static testmethod void testPublishReportOnPortal() {
    
     
    
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
         update i;
        
        EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
        
        Test.startTest();
         Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('Small Group', null);
      
      Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'Small_Group');
        accnt.Config_Record__c = config2.Id;
       accnt.Electronic_Communication__c = true;
        update accnt;
      
        update i;
        ext.publishReportOnPortal();
        
        i.Checklist_Summary_issue_date__c = null;
        i.Visit_Narrative_Issue_Date__c = null; 
         update i;
        ext.publishReportOnPortal();
        
        i.Cover_Letter_Issue_Date__c = null;
        update i;
        ext.publishReportOnPortal();
        
         i.Created_on_the_Web__c = true;
         update i;
        ext.publishReportOnPortal();
        
        
        Test.stopTest();
        System.assertEquals('This provider does not use electronic communication', ext.toastMsg);
    } 
}