phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Adoption_Agency</fullName>
        <active>true</active>
        <description>Placement - Adoption Agency</description>
        <label>Adoption Agency</label>
    </recordTypes>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <recordTypes>
        <fullName>Small_Group</fullName>
        <active>true</active>
        <description>Small group and school age</description>
        <label>Small Group</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Additional_Information__c.object
<CustomObject>
    <description>This object is to capture additional information like licenses held, other applications, admin/criminal actions, investigations etc for a provider during a licensing transactions.</description>
    <fields>
        <fullName>License_Number__c</fullName>
        <description>License number of out of State child caring related licenses held by the applicant.</description>
        <label>License Number</label>
        <length>56</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licensing_Transaction__c</fullName>
        <description>Look up relation to the licensing transaction during which the additional information is added.</description>
        <label>Licensing Transaction</label>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Additional Information</relationshipLabel>
        <relationshipName>Additional_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name_of_Licensee__c</fullName>
        <description>Name of licensee on out of State child caring related licenses held by the applicant.</description>
        <label>Name of Licensee</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Provider record to which the additional information is related.</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Information</relationshipLabel>
        <relationshipName>Additional_Information</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State_Country_Issuing_the_License__c</fullName>
        <description>State/country issuing the out of State child caring related licenses held by the applicant.</description>
        <label>State/Country Issuing the License</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_License__c</fullName>
        <description>Type of license of the out of State child caring related licenses held by the applicant.</description>
        <label>Type of License</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Additional Information</label>
    <nameField>
        <displayFormat>AdditionalInfo-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact_Role__c.object
<CustomObject>
    <description>This is a junction object between a provider and contact. A single contact may play multiple roles for a provider like Owner, Administrator etc.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Account to which the contact is associated with.</description>
        <label>Provider / Umbrella</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document__c.object
<CustomObject>
    <description>A custom object to be used for non-Salesforce reference documents.</description>
    <fields>
        <fullName>Approved_for_Future_Usage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Future Usage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>The file&apos;s content meta type.</description>
        <label>Content Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Type</label>
        <referenceTo>Document_Type__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes relating to the document.</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Original_File_Name__c</fullName>
        <label>Original File Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Out_of_Date__c</fullName>
        <label>Out of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC- {0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document_Type__c.object
<CustomObject>
    <description>An object for storing all document types. This is not to be confused with document prototypes (i.e. image/jpeg, document/pdf, etc)</description>
    <fields>
        <fullName>Allow_use_of_Umbrella_Level_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Use of Umbrella Level Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>A description for the document type.</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Individual_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Individual Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEAD_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Provider Type</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Document Types</relationshipLabel>
        <relationshipName>Document_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Need_to_be_Updated_at_each_new_Transacti__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Update Each New Transaction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Transactio_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Optional for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Related_Role__c</fullName>
        <label>Related Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Director / Administrative Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Contact</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Required_for_Transaction_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Required for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Document Type</label>
    <nameField>
        <label>Document Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Last_Reached_Step__c</fullName>
        <inlineHelpText>Last steps reached by Portal User.</inlineHelpText>
        <label>Last Reached Step</label>
        <picklist>
            <picklistValues>
                <fullName>Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction / Provider Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Members</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Status and Capacity / Assistant Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEC Involvement Experience &amp; Professional Exp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Background Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indoor / Outdoor space information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Routing Activities / Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attachments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Summary and Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensing Status and Capacity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Umbrella__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>In case of Corporation / LLC type of ownership, this is the umbrella the provider is owned by.</inlineHelpText>
        <label>Umbrella</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions (Umbrella)</relationshipLabel>
        <relationshipName>Licensing_Transactions_Umbrella</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>FCC_New_License</fullName>
        <active>true</active>
        <label>FCC New License</label>
    </recordTypes>
    <recordTypes>
        <fullName>GSA_New_License</fullName>
        <active>true</active>
        <description>Request for a new license as GSA provider</description>
        <label>GSA New License</label>
    </recordTypes>
    <recordTypes>
        <fullName>Placement_Renewal</fullName>
        <active>true</active>
        <description>Request for a renewal of license as a Placement Provider</description>
        <label>Placement Renewal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Variance_On_Regulation_Request</fullName>
        <active>true</active>
        <description>Request a new variance on regulations (to be used by FCC, GSA, R&amp;P providers)</description>
        <label>Variance On Regulation Request</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_ViewLicenseTransactionControllerTest.cls
@isTest
public class EEC_ViewLicenseTransactionControllerTest {
     static testmethod void testViewGSA() {
      Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('Small Group', null);
	  
	  Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'Small_Group');
	  accnt.Config_Record__c = config2.Id;
	  update accnt;
	  
      Contact contact = EEC_TestUtil.mockContact(accnt, 'Test', 'LastName', '');
      Contact_Role__c contactRole = EEC_TestUtil.mockContactRole('Partner', contact.Id, accnt.Id);
      contactRole = EEC_TestUtil.mockContactRole('Administrative Designee', contact.Id, accnt.Id);
      contactRole = EEC_TestUtil.mockContactRole('Program Director / Administrative Head', contact.Id, accnt.Id);
      contactRole = EEC_TestUtil.mockContactRole('Board Chair', contact.Id, accnt.Id);
      contactRole = EEC_TestUtil.mockContactRole('Owner', contact.Id, accnt.Id);
      
      List<Document_Type__c> listDocumentType = new List<Document_Type__c>();
      Document_Type__c docType = new Document_Type__c();
      docType.Allow_use_of_Umbrella_Level_Document__c = true;
      docType.Name = 'Doc Type 1';
      docType.Description__c ='Test Description';
      docType.Individual_Document__c = false;
      docType.Need_to_be_Updated_at_each_new_Transacti__c = true;
      docType.Optional_for_Transactio_Type__c = 'GSA New License';
      docType.Related_Role__c = '';
      docType.LEAD_Configuration__c = config2.Id;
      docType.Required_For_Transaction_Type__c = 'GSA New License'; 
      listDocumentType.add(docType);
      
      docType = new Document_Type__c();
      docType.Allow_use_of_Umbrella_Level_Document__c = true;
      docType.Name = 'Doc Type 2';
      docType.Description__c ='Test Description';
      docType.Individual_Document__c = true;
      docType.Need_to_be_Updated_at_each_new_Transacti__c = true;
      docType.Optional_for_Transactio_Type__c = 'GSA New License';
      docType.Related_Role__c = 'Administrative Designee';
      docType.LEAD_Configuration__c = config2.Id;
      docType.Required_For_Transaction_Type__c = 'GSA New License'; 
      listDocumentType.add(docType);
      
      insert listDocumentType;
      
      List<Document__c> listDocument = new List<Document__c>();
      Document__c document = new Document__c();
      document.Provider__c = accnt.Id;
      //document.Out_of_Date__c = date.today() + 100;
      //document.Original_File_Name__c = 'TestFile.jpg';
      document.Notes__c = 'Test Notes';
      document.Document_Type__c = listDocumentType[0].Id;
      document.Content_Type__c = 'jpg';
      document.Approved_for_Future_Usage__c = true;
      listDocument.add(document);
      
      document = new Document__c();
      document.Provider__c = accnt.Id;
      //document.Out_of_Date__c = date.today() + 100;
      //document.Original_File_Name__c = 'TestFile2.jpg';
      document.Notes__c = 'Test Notes';
      document.Document_Type__c = listDocumentType[1].Id;
      document.Content_Type__c = 'jpg';
      document.Approved_for_Future_Usage__c = true;
      listDocument.add(document);
      
      insert listDocument;
      
      Licensing_Transaction__c lic = EEC_TestUtil.mockAssistantLicenseTransaction(accnt,'GSA_New_License');
      //lic.Umbrella__c = accnt.Id;
	  lic.Last_Reached_Step__c = 'Attachments';
	  update lic;
	  
      EEC_TestUtil.mockHouseHold(lic, accnt);
      EEC_TestUtil.mockFCCAssistant(lic, accnt);
      EEC_TestUtil.mockRoom(lic);
      EEC_TestUtil.mockTrainingExperience(lic);
      EEC_TestUtil.mockAWSKeys();
      
      Id addInfoId   = Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('Other Licenses Held').getRecordTypeId();
      Id addRelatedId =  Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('Other License Applications').getRecordTypeId();
      Id addCriminId = Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('Admin/civil/criminal action detail').getRecordTypeId();
      Id addFedId =  Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('State/federal investigation detail').getRecordTypeId();
       
      List<Additional_Information__c> listAdditionalInfo = new List<Additional_Information__c>();
      Additional_Information__c additionalInfo = new Additional_Information__c(recordTypeId = addInfoId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      additionalInfo = new Additional_Information__c(recordTypeId = addRelatedId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      additionalInfo = new Additional_Information__c(recordTypeId = addCriminId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      additionalInfo = new Additional_Information__c(recordTypeId = addFedId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      insert listAdditionalInfo;

      Test.startTest();
      
      PageReference pg1 = Page.EEC_ViewLicenseTransaction;
      test.setCurrentPage(pg1);      
      ApexPages.currentPage().getParameters().put('ltId', lic.Id);
      ApexPages.currentPage().getParameters().put('member',accnt.Id);
      
      EEC_ViewGSALicenseTransactionController gsaController = new EEC_ViewGSALicenseTransactionController();
      gsaController.getLicenseTrans();
      gsaController.getItems();
      gsaController.getPickItems();
      gsaController.backInstruction();
      gsaController.getCtrlInstance();
      gsaController.getBaseLicenseTransaction();
      gsaController.getBaseLicenseRecordTypeName();
      gsaController.CancelTransaction();
      gsaController.editInstruction();
      test.stopTest();
    }
    
    static testmethod void testViewRP() {
      Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('Adoption Agency', null);
	  
	  Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'Adoption_Agency');
	  accnt.Config_Record__c = config2.Id;
	  update accnt;
	  
      Contact contact = EEC_TestUtil.mockContact(accnt, 'Test', 'LastName', '');
      Contact_Role__c contactRole = EEC_TestUtil.mockContactRole('Partner', contact.Id, accnt.Id);
      contactRole = EEC_TestUtil.mockContactRole('Administrative Designee', contact.Id, accnt.Id);
      contactRole = EEC_TestUtil.mockContactRole('Program Director / Administrative Head', contact.Id, accnt.Id);
      contactRole = EEC_TestUtil.mockContactRole('Board Chair', contact.Id, accnt.Id);
      contactRole = EEC_TestUtil.mockContactRole('Owner', contact.Id, accnt.Id);
      
      Licensing_Transaction__c lic = EEC_TestUtil.mockAssistantLicenseTransaction(accnt,'Placement_Renewal');
      //lic.Umbrella__c = accnt.Id;
	  lic.Last_Reached_Step__c = 'Attachments';
	  update lic;
	  
      EEC_TestUtil.mockHouseHold(lic, accnt);
      EEC_TestUtil.mockFCCAssistant(lic, accnt);
      EEC_TestUtil.mockRoom(lic);
      EEC_TestUtil.mockTrainingExperience(lic);
      EEC_TestUtil.mockAWSKeys();
      
      Id addInfoId   = Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('Other Licenses Held').getRecordTypeId();
      Id addRelatedId =  Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('Other License Applications').getRecordTypeId();
      Id addCriminId = Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('Admin/civil/criminal action detail').getRecordTypeId();
      Id addFedId =  Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('State/federal investigation detail').getRecordTypeId();
       
      List<Additional_Information__c> listAdditionalInfo = new List<Additional_Information__c>();
      Additional_Information__c additionalInfo = new Additional_Information__c(recordTypeId = addInfoId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      additionalInfo = new Additional_Information__c(recordTypeId = addRelatedId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      additionalInfo = new Additional_Information__c(recordTypeId = addCriminId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      additionalInfo = new Additional_Information__c(recordTypeId = addFedId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      insert listAdditionalInfo;

      Test.startTest();
      
      PageReference pg1 = Page.EEC_ViewLicenseTransaction;
      test.setCurrentPage(pg1);      
      ApexPages.currentPage().getParameters().put('ltId', lic.Id);
      ApexPages.currentPage().getParameters().put('member',accnt.Id);
      
      EEC_ViewLicenseTransactionController viewController = new EEC_ViewLicenseTransactionController();
      viewController.getLicenseTrans();
      viewController.getItems();
      viewController.getPickItems();
      viewController.backInstruction();
      viewController.getCtrlInstance();
      viewController.getBaseLicenseTransaction();
      viewController.getBaseLicenseRecordTypeName();
      viewController.gettypeOfOwnership();
      viewController.CancelTransaction();
      viewController.editInstruction();
      
      test.stopTest();
    }
    
    static testmethod void testViewVariance() {
      Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('Adoption Agency', null);
	  
	  Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'Adoption_Agency');
	  accnt.Config_Record__c = config2.Id;
	  update accnt;
	  
      Licensing_Transaction__c lic = EEC_TestUtil.mockAssistantLicenseTransaction(accnt,'Variance_On_Regulation_Request');
      //lic.Umbrella__c = accnt.Id;
	  lic.Last_Reached_Step__c = 'Attachments';
	  update lic;
	  
      Test.startTest();
      
      PageReference pg1 = Page.EEC_ViewLicenseTransaction;
      test.setCurrentPage(pg1);      
      ApexPages.currentPage().getParameters().put('ltId', lic.Id);
      ApexPages.currentPage().getParameters().put('member',accnt.Id);
      
      EEC_ViewVarianceTransactionController viewController = new EEC_ViewVarianceTransactionController();
      viewController.getLicenseTrans();
      viewController.getItems();
      viewController.getPickItems();
      viewController.backInstruction();
      viewController.getCtrlInstance();
      viewController.getBaseLicenseTransaction();
      viewController.getBaseLicenseRecordTypeName();
      viewController.CancelTransaction();
      viewController.editInstruction();
      
      test.stopTest();
    }
    
    static testmethod void testViewFCC() {
      Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('Family Child Care', null);
	  
	  Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'FCC');
	  accnt.Config_Record__c = config2.Id;
	  update accnt;
	  
      Licensing_Transaction__c lic = EEC_TestUtil.mockAssistantLicenseTransaction(accnt,'FCC_New_License');
      //lic.Umbrella__c = accnt.Id;
	  lic.Last_Reached_Step__c = 'Attachments';
	  update lic;
	  
      EEC_TestUtil.mockHouseHold(lic, accnt);
      EEC_TestUtil.mockFCCAssistant(lic, accnt);
      EEC_TestUtil.mockRoom(lic);
      EEC_TestUtil.mockTrainingExperience(lic);
      EEC_TestUtil.mockAWSKeys();
      
      Id addInfoId   = Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('Other Licenses Held').getRecordTypeId();
      Id addRelatedId =  Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('Other License Applications').getRecordTypeId();
      Id addCriminId = Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('Admin/civil/criminal action detail').getRecordTypeId();
      Id addFedId =  Schema.SObjectType.Additional_Information__c.getRecordTypeInfosByName().get('State/federal investigation detail').getRecordTypeId();
       
      List<Additional_Information__c> listAdditionalInfo = new List<Additional_Information__c>();
      Additional_Information__c additionalInfo = new Additional_Information__c(recordTypeId = addInfoId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      additionalInfo = new Additional_Information__c(recordTypeId = addRelatedId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      additionalInfo = new Additional_Information__c(recordTypeId = addCriminId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      additionalInfo = new Additional_Information__c(recordTypeId = addFedId,Name_of_Licensee__c = 'Test', Licensing_Transaction__c = lic.Id, Provider__c = accnt.id, Type_of_License__c = 'Test',State_Country_Issuing_the_License__c = 'US',License_Number__c = '123');
      listAdditionalInfo.add(additionalInfo);
      
      insert listAdditionalInfo;

      Test.startTest();
      
      PageReference pg1 = Page.EEC_ViewLicenseTransaction;
      test.setCurrentPage(pg1);      
      ApexPages.currentPage().getParameters().put('ltId', lic.Id);
      ApexPages.currentPage().getParameters().put('member',accnt.Id);
      
      EEC_ViewTransactionController viewController = new EEC_ViewTransactionController();
      viewController.getLicenseTrans();
      viewController.getItems();
      viewController.getHeatingElements();
      viewController.backInstruction();
      viewController.getCtrlInstance();
      viewController.getBaseLicenseTransaction();
      viewController.getBaseLicenseRecordTypeName();
      viewController.refreshAttachmentsList();
      viewController.CancelTransaction();
      viewController.editInstruction();
      
      test.stopTest();
    }
}