phase2_Dev/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Additional_Information__c.object
<CustomObject>
    <description>This object is to capture additional information like licenses held, other applications, admin/criminal actions, investigations etc for a provider during a licensing transactions.</description>
    <fields>
        <fullName>Licensing_Transaction__c</fullName>
        <description>Look up relation to the licensing transaction during which the additional information is added.</description>
        <label>Licensing Transaction</label>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Additional Information</relationshipLabel>
        <relationshipName>Additional_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name_of_Licensee__c</fullName>
        <description>Name of licensee on out of State child caring related licenses held by the applicant.</description>
        <label>Name of Licensee</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Provider record to which the additional information is related.</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Additional Information</relationshipLabel>
        <relationshipName>Additional_Information</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Information</label>
    <nameField>
        <displayFormat>AdditionalInfo-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_AdditionalInfoControllerTest.cls
@isTest
public class EEC_AdditionalInfoControllerTest {
    public static testMethod void EEC_AdditionalInfoCtrlTestMain() {
        Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'FCC');
    Licensing_Transaction__c lic = EEC_TestUtil.mockLiscence(accnt);
    
    List<RecordType> aiRtList = [select Id, DeveloperName from RecordType Where SobjectType = 'Additional_Information__c'];
    List<Additional_Information__c> aiList = new List<Additional_Information__c>();
    
    for(RecordType aiRt : aiRtList){
      Additional_Information__c ai = new Additional_Information__c(RecordTypeId = aiRt.id
                                          , Name_of_Licensee__c = 'Test Name'
                                          , Licensing_Transaction__c = lic.id
                                          , Provider__c = accnt.id);
      aiList.add(ai);
    }
    
    Insert aiList;
    ApexPages.StandardController sc = new ApexPages.StandardController(lic);
    EEC_AdditionalInfoController controller = new EEC_AdditionalInfoController(sc);

    System.assertEquals(true, controller.renderOtherLicenses);
    }
}