phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Intervention__c.object
<CustomObject>
    <description>List the intervention needed for a given investigation</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Interventions</relationshipLabel>
        <relationshipName>Interventions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Do</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit via Portal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Intervention</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Intervention ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interventions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation can be assigned to a Licensor, Supervisor or Inspector</description>
        <inlineHelpText>User who will take the lead on the investigation.</inlineHelpText>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <formula>Provider_No__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Out_of_Office__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Out of Office</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_InterventionTriggerHandler.cls
public class EEC_InterventionTriggerHandler {
    
    List<Intervention__c> newIntList;
    Map<Id, Intervention__c> oldCaseMap;
    Map<Id, User> userList;

    public EEC_InterventionTriggerHandler(List<Intervention__c> newList, Map<Id, Intervention__c> oldList){
        this.newIntList = newList;
        this.oldCaseMap = oldList;
        
        userList = new Map<Id, User>([
            SELECT ManagerId, UserRoleId, Email, Name, DelegatedApproverId, Out_of_Office__c 
            FROM User
            WHERE UserType = 'Standard'
        ]);
    }
    
    public void sendInterventionSubmittedOutOfOffice(){
        for(Intervention__c inv : newIntList){
            Intervention__c oldI = oldCaseMap.get(inv.Id);
            Investigation__c invest = [SELECT Id,Name,Assigned_To__r.Out_of_Office__c,Provider_No__r.Name,Assigned_To__r.ManagerId,Provider_Name__c
                                       FROM Investigation__c WHERE Id =: inv.Investigation__c];
            User leader = userList.get(invest.Assigned_To__c);

            String invRtName = [SELECT recordType.Name FROM Intervention__c WHERE id =: inv.Id].RecordType.Name;
            if(inv.Status__c == 'Submitted' && oldI.Status__c != 'Submitted' 
               && invRtName == 'Internal Investigation'
               && leader != null && leader.Out_of_Office__c){
                   
                List<OrgWideEmailAddress> orgList = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = 'EEC LEAD Alert'];
                EmailTemplate template41 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'X41_An_Internal_Investigation_Has_Been_Submitted'];
                   
                EEC_EmailUtil email = new EEC_EmailUtil(); 
                email.plainTextBody = template41.Body
                    .replace('{!Investigation__c.Name}', invest.Name)
                    .replace('{!Account.Name}', invest.Provider_Name__c);
                email.subject = 'Alert to Investigation Leader that internal investigation has been submitted';
                email.toAddresses = new List<String>();
                
                if(leader.ManagerId != null){
                    User manager = userList.get(leader.ManagerId);
                    email.toAddresses.add(manager.Email);
                    
                    if(manager.ManagerId != null && manager.Out_of_office__c){
                        User managersManager = userList.get(manager.ManagerId);
                        email.toAddresses.add(managersManager.Email); 
                    }
                }
                                    
                email.whatId = inv.Id;
            	email.saveAsActivity = false; 

                if(orgList.size() > 0)
                	email.orgWideEmailId = orgList.get(0).Id;
                
                email.sendEmail();
            }
        }
    }
}