phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <valueField>$Source.State__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region this provider is assigned to</description>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>Created for ease of access on triggers</description>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Cases</description>
        <label>Investigation</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This investigation is associated with another provider.</errorMessage>
            <filterItems>
                <field>Investigation__c.Provider_No__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Associated Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Out_Of_Office_Email_Template_To_Send__c</fullName>
        <label>Out Of Office Email Template To Send</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Out_Of_Office_Initial_Recipient_ID__c</fullName>
        <description>In case we need to forward email to the supervisor in case of out of office, this field will contain the ID of the initial recipient.</description>
        <label>Out Of Office Initial Recipient ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <formula>Account.Provider_Email__c</formula>
        <label>Provider Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendCaseTriageEmail__c</fullName>
        <description>Flag to indicate that a case triage email should be sent.</description>
        <label>SendCaseTriageEmail</label>
        <picklist>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TriageEscalationApproverEmailList__c</fullName>
        <description>The list of the most recent approvers of  a case triage escalation.</description>
        <label>TriageEscalationApproverEmailList</label>
        <length>1300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Triage_Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User that will be / is / was in charge of the triage.</inlineHelpText>
        <label>Triage Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TriggerTriageEscalationApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag that will trigger an escalation in approvals for In Triage to Escalated for the Case object.</description>
        <label>TriggerTriageEscalationApproval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unlicensed_Provider_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Region</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a valid Licensing Region (currently a subsidy region is selected)</errorMessage>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1st_Escalation_Case_Approver_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>1st Escalation Case Approver Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X1st_Escalation_Case_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Denotes the user that will be the 1st Level escalation approver on cases</description>
        <inlineHelpText>Denotes the user that will be the 1st Level escalation approver on cases</inlineHelpText>
        <label>1st Escalation Case Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Lvl1_Escalation_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X2nd_Escalation_Case_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Denotes the user that will be the 2nd Level escalation approver on cases</description>
        <inlineHelpText>Denotes the user that will be the 2nd Level escalation approver on cases</inlineHelpText>
        <label>2nd Escalation Case Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Lvl2_Escalation_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Incident</fullName>
        <active>true</active>
        <businessProcess>Incident</businessProcess>
        <description>Incident - select this record type when capturing an Incident from a Provider</description>
        <label>Incident</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Announced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Announced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Provider_No__r.Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <description>Copies the email id from the Provider record so it can be used as a Recipient in workflows on the Investigation object</description>
        <label>Provider Email</label>
        <type>Email</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Provider Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <fields>
        <fullName>Deputy_Commissioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This information is used by the system during the approval process of escalated Investigation. This user is the 1st reviewer / approver.</inlineHelpText>
        <label>Associate Commissioner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>DB_Region__c</fullName>
        <description>This is a field that is installed by and used with the Adoption Dashboard AppExchange package. If your org already has a similar field, you can change the reports that are part of the Adoption Dashboard package to use your custom field and then delete this field.</description>
        <label>DB Region</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
                <color>#3333FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
                <color>#CC6600</color>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
                <color>#990000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Out_of_Office__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Out of Office</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the user is attached to</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast and Cape</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TestCaseTrigger.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod   
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
*
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
@isTest
private class EEC_TestCaseTrigger {
    
    static testMethod void myUnitTest() {
      Account mockProvider = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
            Investigation__c i = EEC_TestUtil.mockInvestigation(mockProvider);
            Case c = EEC_TestUtil.mockCase(mockProvider, EEC_TestUtil.mockContact(), i);
            c.SendCaseTriageEmail__c = 'Recalled';
            c.TriggerTriageEscalationApproval__C = true;
            update c;
            c.SendCaseTriageEmail__c = 'Approved';
            update c;
            c.SendCaseTriageEmail__c = 'Rejected';   
            update c;
}
    
    static testMethod void testCaseTriggerHandlerEmail() {
        Test.startTest();
        EEC_CaseTriggerHandler.sendIEmail('test@test.com', 'Test', UserInfo.getUserId(), 'TestCaseEmail', 'investId', 'TestSubject', 'AccountName');
        Test.stopTest();
    }
   
    @isTest
    public static void testIncidentSubmissionForOutOfOffice() {
        Test.startTest();
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
      
        
        Account accnt = [SELECT ID,OwnerId FROM Account WHERE RecordType.DeveloperName = 'FCC' AND Provider_Address_1__c != null LIMIT 1];
        
        
        Contact con = EEC_TestUtil.mockDirectorContact(accnt);  
        Case c = EEC_TestUtil.mockWebCase(accnt, con);
        Test.stopTest();  
    }
    
    @isTest
    public static void testcheckProviderEditAccess() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        Contact con = EEC_TestUtil.mockDirectorContact(acc);  
       
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        EEC_CaseTriggerHandler.FirstRun = null;
        c.Status ='In Triage';
       // c.Out_Of_Office_Initial_Recipient_ID__c = 'test';
        update c; 
        
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c,Investigation__c FROM Case WHERE Status = 'In Triage' AND X1st_Escalation_Case_Approver__c != null AND X2nd_Escalation_Case_Approver__c != null LIMIT 1];
        update c;
        Test.startTest();
        c.Status = 'Escalated';
        c.SendCaseTriageEmail__c = 'Recalled';
        
        EEC_CaseTriggerHandler.FirstRun = null;
        c.X1st_Escalation_Case_Approver_Completed__c = false;      
        update c;
        c.Status = 'In Triage';
        EEC_CaseTriggerHandler.FirstRun = null;
        if(c.Triage_Responsible__c == null)
            c.Triage_Responsible__c = EEC_TestUtil.mockUser().Id;  
        update c;
        c.Status = 'Escalated';
       
        EEC_CaseTriggerHandler.FirstRun = null;
        c.SendCaseTriageEmail__c ='Approved';
        
        c.X1st_Escalation_Case_Approver__c = null;
        c.X1st_Escalation_Case_Approver_Completed__c = true;
        update c;    
        Test.stopTest();  
    }
    
    @isTest
    public static void testAssignCaseOwnerByStatus() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        Contact con = EEC_TestUtil.mockDirectorContact(acc);  
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        c.Status ='In Triage';
        EEC_CaseTriggerHandler.FirstRun = null;
        update c;
        
        
        c = [SELECT ID, Status,AccountId,X1st_Escalation_Case_Approver_Completed__c FROM Case WHERE Status = 'In Triage' AND X1st_Escalation_Case_Approver__c != null LIMIT 1];
        Account a = [SELECT ID, Name FROM Account WHERE Id =: c.AccountId];
       
        update a;
        update c;    
        Investigation__c i = EEC_TestUtil.mockInvestigation(a);
        User us = EEC_TestUtil.mockUser();
        us.Out_of_Office__c = false ;
        us.DB_Region__c = 'NA';
        
        Test.startTest();

        c.Investigation__c = i.Id;  
        c.Status = 'Investigation in Progress';
        EEC_CaseTriggerHandler.FirstRun = null;
        c.Out_Of_Office_Initial_Recipient_ID__c = null; 
        c.X1st_Escalation_Case_Approver_Completed__c = false;      
        update c;
        c.Status = 'In Triage';
        EEC_CaseTriggerHandler.FirstRun = null;        
        c.X1st_Escalation_Case_Approver_Completed__c = false;   
        update c;
        c.Status ='No Non-Compliance Closure Pending';     
        c.Triage_Responsible__c = us.Id;
        EEC_CaseTriggerHandler.FirstRun = null;  
        update us;
        update c;
        Test.stopTest();  
    }
    
    @isTest
    public static void testNewCaseOwner() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        Contact con = EEC_TestUtil.mockDirectorContact(acc);  
        User us =  EEC_TestUtil.mockUser();
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        Investigation__c invest = EEC_TestUtil.mockInvestigation(acc);
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c,Investigation__c FROM Case WHERE Status = 'New' LIMIT 1];
       Account accnt = [SELECT ID,OwnerId FROM Account WHERE RecordType.DeveloperName = 'FCC' AND Provider_Address_1__c != null LIMIT 1];
        update accnt;
        c.Out_Of_Office_Initial_Recipient_ID__c = 'test';
        update c;
        Test.startTest();
     
        c.Unlicensed_Provider_Region__c = null;
        c.SendCaseTriageEmail__c = null;  
        EEC_CaseTriggerHandler.FirstRun = null;
        update c;
        c.Status = 'In Triage';
        c.SendCaseTriageEmail__c = 'Approved'; 
        EEC_CaseTriggerHandler.FirstRun = null;
        c.TriageEscalationApproverEmailList__c = 'test@test.com,abc@test.com';  
        update c;  
        //c.Status = 'No Non-Compliance Closure Pending';
        //update c;  
        Test.stopTest();  
    }
    
    @isTest
    public static void testInTriageEmail() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        Region__c reg = EEC_TestUtil.mockRegion();
        Account accnt = [SELECT ID,OwnerId FROM Account WHERE RecordType.DeveloperName = 'FCC' AND Provider_Address_1__c != null LIMIT 1];
        update acc;
          
        Investigation__c invest = EEC_TestUtil.mockInvestigation(acc); 
        Contact con = EEC_TestUtil.mockDirectorContact(acc);  
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c,Case_Type__c FROM Case WHERE  Status = 'New' and Origin = 'Web'   LIMIT 1];
        update c;
        
        User u = EEC_TestUtil.mockUser(); 
        User manager = EEC_TestUtil.mockUser();  
        u.Out_Of_Office__c = true;
        u.ManagerId = manager.Id;  
        update u;    
           
        Test.startTest();
       // c.RecordTypeId  = Schema.SObjectType.Inspection_Item__c.getRecordTypeInfosByName().get('Incident').getRecordTypeId();
        c.Status = 'In Triage';  
        c.Unlicensed_Provider_Region__c = null;
        c.SendCaseTriageEmail__c = null;  
        c.Triage_Responsible__c = u.Id;        
        EEC_CaseTriggerHandler.FirstRun = null;
        update c;     
        c.SendCaseTriageEmail__c = 'Recalled';
        // c.RecordTypeId  = Schema.SObjectType.Inspection_Item__c.getRecordTypeInfosByName().get('SLGSA Injury').getRecordTypeId();
        c.TriageEscalationApproverEmailList__c = 'test@test.com';    
        EEC_CaseTriggerHandler.FirstRun = null;
        update c;
        Test.stopTest();  
    }
    
   
    
    @isTest
    public static void testEscalatedEmailToManagerOutofOffice() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        Contact con = EEC_TestUtil.mockDirectorContact(acc);  
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c FROM Case WHERE Status = 'New' LIMIT 1];
        User u = EEC_TestUtil.mockUser();
        User manager = EEC_TestUtil.mockUser();  
        u.Out_Of_Office__c = true;
        u.ManagerId = manager.Id;  
        update u;  
        Test.startTest();
        c.Out_Of_Office_Initial_Recipient_ID__c = u.Id; 
        c.Out_Of_Office_Email_Template_To_Send__c = 'X19_Case_Escalated_Case_sent_for_review_and_approval';  
        c.Unlicensed_Provider_Region__c = null;
        EEC_CaseTriggerHandler.FirstRun = null;
        update c;
        Test.stopTest();  
    }
    
    @isTest
    public static void testInjuryCaseClosureOutofOffice() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        Contact con = EEC_TestUtil.mockDirectorContact(acc);  
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c FROM Case WHERE Status = 'New' LIMIT 1];
        Test.startTest();
        User u = EEC_TestUtil.mockUser();
        User manager = EEC_TestUtil.mockUser();  
        u.Out_Of_Office__c = true;
        u.ManagerId = manager.Id;  
        update u;    
        c.Triage_Responsible__c = u.Id; 
        c.Status = 'No Non-Compliance Closure Pending';
        c.X1st_Escalation_Case_Approver_Completed__c = false;      
        update c;
        c.Status = 'In Triage';
        c.X1st_Escalation_Case_Approver_Completed__c = false;   
        Test.stopTest();  
    }
    
    
    static testMethod void testEventTrigger() {
        RecordType r = [select Id from RecordType where DeveloperName='FCC' and sobjecttype='Account'];
        Account pAccount = new Account(
            name='TestProvider1',
            RecordTypeId=r.Id,
            Provider_Email__c='test@test.com',
            Provider_Address_1__c='123 Test St.',
            Provider_City__c=EEC_TestUtil.mockCity().Id,
            Provider_Zip_Code__c='B3H0A2');
        insert pAccount;
        // Use a visit obj.
        
       // Inspection_Item__c item1 = EEC_TestUtil.mockInspectionItem(EEC_TestUtil.mockInspection(pAccount), EEC_TestUtil.mockStdInspectionItem(), 'Test', true, 'Test');
        Inspection__c item = EEC_TestUtil.mockInspection(pAccount);
        System.debug('*****Item Id: ' + item.Id);
        
        Event event = new Event(
            DurationInMinutes = 14400,
            ActivityDateTime = DateTime.now(),
            WhatId = item.Id,
            EndDateTime = DateTime.now().addDays(10)
        );
        insert event;
        event.Description = 'Testing!';
        update event;
    }
    static testMethod void testUpdateEventTrigger() {
        Inspection__c[] item = [SELECT ID, Name,Announced__c FROM Inspection__c LIMIT 1];
        if (item.size() > 0)
            item[0].Announced__c = true;
        update item;
    }
    
    @isTest
    public static void testassignCaseOwner() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        
        Contact con = EEC_TestUtil.mockDirectorContact(acc);
        
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        
        Region__c regionrecord = [Select id,Deputy_Commissioner__c FROM Region__c limit 1];
        regionrecord.Deputy_Commissioner__c = EEC_TestUtil.mockUser().id;
        update regionrecord;
        Investigation__c invest = EEC_TestUtil.mockInvestigation(acc);
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c,Investigation__c FROM Case WHERE Status = 'New' LIMIT 1];
       Account accnt = [SELECT ID,OwnerId FROM Account WHERE RecordType.DeveloperName = 'FCC' AND Provider_Address_1__c != null LIMIT 1];
        User LEADSystem_Batch_User = EEC_TestUtil.mockUser();
        LEADSystem_Batch_User.firstName = 'LEAD';
        LEADSystem_Batch_User.LastName = 'System_Batch_User';
        update LEADSystem_Batch_User;
        accnt.OwnerID = LEADSystem_Batch_User.id;
        update accnt;
        c.Out_Of_Office_Initial_Recipient_ID__c = 'test';
        update c;
        Test.startTest();
     
        c.Unlicensed_Provider_Region__c = null;
        c.SendCaseTriageEmail__c = null;  
        EEC_CaseTriggerHandler.FirstRun = null;
        update c;
        c.Status = 'In Triage';
        c.SendCaseTriageEmail__c = 'Approved'; 
        EEC_CaseTriggerHandler.FirstRun = null;
        c.TriageEscalationApproverEmailList__c = 'test@test.com,abc@test.com';  
        update c;  
        //c.Status = 'No Non-Compliance Closure Pending';
        //update c;  
        Test.stopTest();  
    }
    
    @isTest
    public static void testassignCaseOwnerwithOutLeadSystemBatchUser() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        
        Contact con = EEC_TestUtil.mockDirectorContact(acc);
        
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        
        Region__c regionrecord = [Select id,Deputy_Commissioner__c FROM Region__c limit 1];
        regionrecord.Deputy_Commissioner__c = EEC_TestUtil.mockUser().id;
        update regionrecord;
        Investigation__c invest = EEC_TestUtil.mockInvestigation(acc);
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c,Investigation__c FROM Case WHERE Status = 'New' LIMIT 1];
       c.Out_Of_Office_Initial_Recipient_ID__c = 'test';
        update c;
        Test.startTest();
       c.Unlicensed_Provider_Region__c = null;
        c.SendCaseTriageEmail__c = null;  
        EEC_CaseTriggerHandler.FirstRun = null;
        update c;
        c.Status = 'In Triage';
        c.SendCaseTriageEmail__c = 'Approved'; 
        EEC_CaseTriggerHandler.FirstRun = null;
        c.TriageEscalationApproverEmailList__c = 'test@test.com,abc@test.com';  
        update c;  
        //c.Status = 'No Non-Compliance Closure Pending';
        //update c;  
        Test.stopTest();  
    }
    
    @isTest
    public static void testassignCaseOwnerwithUnlicensedProviderRegion() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        
        Contact con = EEC_TestUtil.mockDirectorContact(acc);
        
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        
        Region__c regionrecord = [Select id,Deputy_Commissioner__c FROM Region__c limit 1];
        regionrecord.Deputy_Commissioner__c = EEC_TestUtil.mockUser().id;
        update regionrecord;
        Investigation__c invest = EEC_TestUtil.mockInvestigation(acc);
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c,Investigation__c FROM Case WHERE Status = 'New' LIMIT 1];
       c.Out_Of_Office_Initial_Recipient_ID__c = 'test';
        c.Unlicensed_Provider_Region__c = regionrecord.id;
        update c;
        Test.startTest();
       c.SendCaseTriageEmail__c = null;  
        EEC_CaseTriggerHandler.FirstRun = null;
        update c;
        c.Status = 'In Triage';
        c.SendCaseTriageEmail__c = 'Approved'; 
        EEC_CaseTriggerHandler.FirstRun = null;
        c.TriageEscalationApproverEmailList__c = 'test@test.com,abc@test.com';  
        update c;  
        //c.Status = 'No Non-Compliance Closure Pending';
        //update c;  
        Test.stopTest();  
    }
    @isTest
    public static void testsendNonComplianceInjuryCaseClosureOutofOffice() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        
        Contact con = EEC_TestUtil.mockDirectorContact(acc);
        
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        
        Region__c regionrecord = [Select id,Deputy_Commissioner__c FROM Region__c limit 1];
        regionrecord.Deputy_Commissioner__c = EEC_TestUtil.mockUser().id;
        update regionrecord;
        User u = EEC_TestUtil.mockUser();
        u.Out_of_Office__c = true;
        u.ManagerId = Userinfo.getUserID();
        update u;
        
        User exeManager = EEC_TestUtil.mockUser();
        
        User currentUser = new User(id= UserInfo.getUserId(), ManagerID = exeManager.id);
        update currentUser;
        
        Investigation__c invest = EEC_TestUtil.mockInvestigation(acc);
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c,Investigation__c FROM Case WHERE Status = 'New' LIMIT 1];
       c.Out_Of_Office_Initial_Recipient_ID__c = 'test';
        c.Unlicensed_Provider_Region__c = regionrecord.id;
        c.Triage_Responsible__c = u.id;
        update c;
        Test.startTest();
       c.SendCaseTriageEmail__c = null;
        c.Status = 'No Non-Compliance Closure Pending';
        EEC_CaseTriggerHandler.FirstRun = null;
        update c;
        c.Status = 'In Triage';
        c.SendCaseTriageEmail__c = 'Approved'; 
        EEC_CaseTriggerHandler.FirstRun = null;
        c.TriageEscalationApproverEmailList__c = 'test@test.com,abc@test.com';  
        update c;  
        //c.Status = 'No Non-Compliance Closure Pending';
        //update c;  
        Test.stopTest();  
    }
    
    @isTest
    public static void testsendcloseTasksOnStatusChange() {
        Account acc = EEC_TestUtil.mockUnlicensedProvider(EEC_TestUtil.mockCity(),null,null);
        Contact con = EEC_TestUtil.mockDirectorContact(acc);
        Case c = EEC_TestUtil.mockWebCase(acc, con);
        Investigation__c invest = EEC_TestUtil.mockInvestigation(acc);
        Task taskrecord  = EEC_TestUtil.mockTask(c);
        c = [SELECT ID, Status,X1st_Escalation_Case_Approver_Completed__c,Investigation__c FROM Case WHERE Status = 'New' LIMIT 1];
       c.Out_Of_Office_Initial_Recipient_ID__c = 'test';
        c.SendCaseTriageEmail__c = null;
        c.Status = 'In Triage';
        update c;
        Test.startTest();
       
        c.status = 'New';
        EEC_CaseTriggerHandler.FirstRun = null;
        update c ;
         
        Test.stopTest();  
    }
}