phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Date_of_Visit__c</fullName>
        <description>Date of site inspection visit</description>
        <label>Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Tool_Used__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Visit tool that is used for this visit</inlineHelpText>
        <label>Current Visit Tool Used</label>
        <referenceTo>Standard_Checklist_Reference__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Associated_regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For non standard items, this lookup allows the user to select the regulation associated with this inspection item.</description>
        <label>Associated regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <description>Will be filled by the corrective actions taken by the provider in case of non-compliance</description>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Fill this field if the corrective action submitted by the provider is not appropriate. By updating this field, Providers using electronic communication will be informed by email and will be able to update the correction plan on the portal.</inlineHelpText>
        <label>Corrective Action EEC Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <description>Date the corrective actions were or will be implemented. This information should be provided by the provider when filling the answer of statement of non-compliance.</description>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description_of_inspection__c</fullName>
        <formula>Standard_Inspection_Item__r.Description__c</formula>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <recordTypes>
        <fullName>Additional_Inspection_Item</fullName>
        <active>true</active>
        <description>Visit item that is not defined in LEAD Configuration, and most likely will reference a regulation article that needs to be or has been reviewed during the visit</description>
        <label>Non Standard Visit Item</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <description>Investigation.Closed Date</description>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation_Status__c</fullName>
        <description>Investigation Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved - Report to send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Publish/Send to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Legacy Investigation)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <inlineHelpText>Describe here the corrective actives that have been taken or will be taken to resolve this non-compliance</inlineHelpText>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Fill this field if the corrective action submitted by the provider is not appropriate. By updating this field, Providers using electronic communication will be informed by email and will be able to update the correction plan on the portal</inlineHelpText>
        <label>Corrective Action EEC Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <inlineHelpText>Mention here the date the corrective actions were implemented or the expected date of completion</inlineHelpText>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <inlineHelpText>Describe here the non-compliance</inlineHelpText>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Non_Compliant_Item_Regulation__c.object
<CustomObject>
    <description>Junction between non compliant items and regulations so multiple regulations can be added to one non-compliant item.</description>
    <fields>
        <fullName>Regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Non Compliant Item Regulations</relationshipLabel>
        <relationshipName>Non_Compliant_Item_Regulations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non Compliant Item Regulation</label>
    <nameField>
        <displayFormat>NC-R-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Regulation_Number__c</fullName>
        <formula>IF(CONTAINS(Name,&quot;_&quot;),LEFT(Name,LEN(Name)-9),Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Regulation Number</label>
        <type>Text</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Checklist_Reference__c.object
<CustomObject>
    <description>Standard Checklist Reference object manages standard inspection checklists for all Provider Types</description>
    <label>Visit Tool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_PortalNonCompliancePageTest.cls
@isTest
public class EEC_PortalNonCompliancePageTest {
    
    public static testMethod void testEEC_PortalNonCompliancePageController() {
        PageReference pr = Page.EEC_PortalNonCompliancePage;
        Test.setCurrentPage(pr);
        ID accountid;  
        
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup(); 
        
        test.startTest();
        RecordType rType = [select Id from RecordType where SobjectType = 'Inspection_Item__c' and DeveloperName = 'Additional_Inspection_Item'];
        List<Inspection_Item__c> iItemList = [select Id,Inspection_No__r.Provider_No__c from Inspection_Item__c where Inspection_no__c = :insp.Id and RecordTypeId = :rType.Id];
        Inspection_Item__c iItem = iItemList.get(0);     
        accountid=insp.Provider_No__c;
        ApexPages.currentPage().getParameters().put('member',accountid);    
        EEC_PortalNonCompliancePageController ncomp = new EEC_PortalNonCompliancePageController();    
        ncomp = new EEC_PortalNonCompliancePageController();    
        Investigation__c inv = EEC_TestUtil.loadInvestigationSetup(); 
        Regulation__c reg =  EEC_TestUtil.mockRegulation();
        Non_Compliant__c nc = EEC_TestUtil.mockNonCompliant(inv);
        Non_Compliant_Item_Regulation__c ncr = EEC_TestUtil.mockNonCompliantItemRegulation(nc,reg);
        accountid=inv.Provider_No__c;
        ApexPages.currentPage().getParameters().put('member',accountid);    
        ApexPages.currentPage().getParameters().put('view','all');      
        EEC_PortalNonCompliancePageController ncomp2 = new EEC_PortalNonCompliancePageController();    
        ncomp2 = new EEC_PortalNonCompliancePageController();
        ncomp2.valcount = 10;
        test.stopTest();
    }           
    
    static testMethod void testSaveInspectionItems() {
        EEC_PortalNonCompliancePageController ncomp = new EEC_PortalNonCompliancePageController();
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        test.startTest();
        RecordType rType = [select Id from RecordType where SobjectType = 'Inspection_Item__c' and DeveloperName = 'Additional_Inspection_Item'];
        List<Inspection_Item__c> iItemList = [select Id,Inspection_No__r.Provider_No__c,Associated_regulation__c,Associated_regulation__r.Regulation_Number__c,
                                              Inspection_No__r.Name,Inspection_No__r.Investigation__r.Name,Inspection_No__r.Investigation__c,Date_Implemented__c,
                                              Inspection_No__r.Date_Of_Visit__c,Inspection_No__r.Investigation__r.Closed_Date__c,observations__c,correction_plan__c,
                                              Corrective_Action_EEC_Feedback__c,Description_of_inspection__c,Inspection_No__r.Status__c,Inspection_No__r.Visit_Tool_Used__r.Name,
                                              Inspection_No__r.RecordType.Name,Inspection_No__r.Investigation__r.Investigation_Status__c,
                                              RecordTypeId, RecordType.Name from Inspection_Item__c where Inspection_no__c = :insp.Id and RecordTypeId = :rType.Id];
        
        Inspection_Item__c inspItem = iItemList[0];       
        Investigation__c inv = EEC_TestUtil.loadInvestigationSetup(); 
        Regulation__c reg =  EEC_TestUtil.mockRegulation();
        Non_Compliant__c nc = EEC_TestUtil.mockNonCompliant(inv);
        Non_Compliant_Item_Regulation__c ncr = EEC_TestUtil.mockNonCompliantItemRegulation(nc,reg);
        
        
        List<EEC_PortalNonCompliancePageController.InspectionListWrapper> iiWrapperList = new List<EEC_PortalNonCompliancePageController.InspectionListWrapper>();
        List<EEC_PortalNonCompliancePageController.ComplainceListWrapper> ncWrapperList = new List<EEC_PortalNonCompliancePageController.ComplainceListWrapper>();       
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<EEC_PortalNonCompliancePageController.InspectionListWrapper>();
        ncWrapperList = new List<EEC_PortalNonCompliancePageController.ComplainceListWrapper>();
        
        // Create and add a new InspectionListWrapper.
        EEC_PortalNonCompliancePageController.InspectionListWrapper ilw = new EEC_PortalNonCompliancePageController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        EEC_PortalNonCompliancePageController.ComplainceListWrapper clw = new EEC_PortalNonCompliancePageController.ComplainceListWrapper(0, nc, null);
        ncWrapperList.add(clw);
        
        ncomp.iiWrapperList =iiWrapperList;
        ncomp.ncWrapperList =ncWrapperList;
        ncomp.getitems();
        ncomp.Cancel();
        ncomp.Save();   
        test.stopTest();
        
    }
    @isTest static void testGeneratePDF() {
        Account prov = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
        Investigation__c inv = EEC_TestUtil.loadInvestigationSetup(); 
        Regulation__c reg =  EEC_TestUtil.mockRegulation();
        Non_Compliant__c nc = EEC_TestUtil.mockNonCompliant(inv);
        Non_Compliant_Item_Regulation__c ncr = EEC_TestUtil.mockNonCompliantItemRegulation(nc,reg);
        
        nc = [SELECT Id, Investigation__r.Provider_No__c FROM Non_Compliant__c LIMIT 1];
        ApexPages.currentPage().getParameters().put('member', nc.Investigation__r.Provider_No__c);
        ApexPages.currentPage().getParameters().put('mode','accountid');   
        EEC_PortalNonCompliancePageController ncomp = new EEC_PortalNonCompliancePageController();
        ncomp.generatePDF();
        ncomp.returnProvider();
    }
    @isTest static void testGetNonComplaintItems() {
        Account prov = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
        Investigation__c inv = EEC_TestUtil.loadInvestigationSetup(); 
        Regulation__c reg =  EEC_TestUtil.mockRegulation();
        Non_Compliant__c nc = EEC_TestUtil.mockNonCompliant(inv);
        Non_Compliant_Item_Regulation__c ncr = EEC_TestUtil.mockNonCompliantItemRegulation(nc,reg);
        
        nc = [SELECT Id, Investigation__r.Provider_No__c FROM Non_Compliant__c LIMIT 1];
        ApexPages.currentPage().getParameters().put('member', nc.Investigation__r.Provider_No__c);    
        EEC_PortalNonCompliancePageController ncomp = new EEC_PortalNonCompliancePageController();
        ncomp.generatePDF();
        ncomp.returnProvider();
    } 
    @isTest static void testSaveForLater() {
        Account prov = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
        Investigation__c inv = EEC_TestUtil.loadInvestigationSetup(); 
        Regulation__c reg =  EEC_TestUtil.mockRegulation();
        Non_Compliant__c nc = EEC_TestUtil.mockNonCompliant(inv);
        Non_Compliant_Item_Regulation__c ncr = EEC_TestUtil.mockNonCompliantItemRegulation(nc,reg);
        
        nc = [SELECT Id, Investigation__r.Provider_No__c FROM Non_Compliant__c LIMIT 1];
        ApexPages.currentPage().getParameters().put('member', nc.Investigation__r.Provider_No__c);    
        EEC_PortalNonCompliancePageController ncomp = new EEC_PortalNonCompliancePageController();
        ncomp.generatePDF();
        ncomp.ReturnToProvider();  
    }   
    
    static testMethod void testInspectionListWrapper() {
        new EEC_PortalNonCompliancePageController.InspectionListWrapper(0, new Inspection_Item__c(), null);
    } 
}