phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region this provider is assigned to</description>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Intervention__c.object
<CustomObject>
    <description>List the intervention needed for a given investigation</description>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <inlineHelpText>Reason this intervention was not done and cancelled</inlineHelpText>
        <label>Cancel Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <label>Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Interventions</relationshipLabel>
        <relationshipName>Interventions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Do</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit via Portal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Intervention</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Intervention ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interventions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>All_Interventions_Done__c</fullName>
        <formula>Number_of_Interventions__c = Number_of_Interventions_Done__c</formula>
        <inlineHelpText>Checked if all interventions associated with this investigation are done</inlineHelpText>
        <label>All Interventions Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Task_Creation__c</fullName>
        <label>Approval Task Creation</label>
        <picklist>
            <picklistValues>
                <fullName>NonEscalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NonEscalated Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation can be assigned to a Licensor, Supervisor or Inspector</description>
        <inlineHelpText>User who will take the lead on the investigation.</inlineHelpText>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <description>Investigation.Closed Date</description>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Issue_Date__c</fullName>
        <inlineHelpText>Date the cover letter was created in the system</inlineHelpText>
        <label>Cover Letter Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine if a report has been deployed/shown to the portal community.</description>
        <inlineHelpText>Check this box if you wish to deploy this Investigation to the Web Portal.</inlineHelpText>
        <label>Publish Report on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation_Status__c</fullName>
        <description>Investigation Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved - Report to send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Publish/Send to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Legacy Investigation)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Interventions__c</fullName>
        <label>Number of Interventions</label>
        <summaryForeignKey>Intervention__c.Investigation__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Out_Of_Office_Email_Template_To_Send_del__c</fullName>
        <label>Out Of Office Email Template To Send</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Out_Of_Office_Initial_Recipient__c</fullName>
        <description>In case we need to forward email to the supervisor in case of out of office, this field will contain the ID of the initial recipient.</description>
        <label>Out Of Office Initial Recipient ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Narrative_Issue_Date__c</fullName>
        <inlineHelpText>Date the report narrative was issued last</inlineHelpText>
        <label>Report Narrative Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sent_Date__c</fullName>
        <label>Sent Date</label>
        <type>Date</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>For_Portal_Email__c</fullName>
        <formula>Email</formula>
        <label>For_Portal Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Out_of_Office__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Out of Office</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the user is attached to</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast and Cape</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TestInvestigationTrigger.cls
@isTest
public with sharing class EEC_TestInvestigationTrigger {

    @isTest static void testUpdateClosedInvestigationsBefore() {
        test.startTest();
        
        User u = EEC_TestUtil.mockUser();
        
        System.runAs(u) {
            Investigation__c i = EEC_TestUtil.mockInvestigation(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
            i.Investigation_Status__c = 'Approved - Report to send';
            i.Assigned_To__c = u.id;
            i.Approval_Task_Creation__c = 'NonEscalated Approved';
            EEC_InvestigationTriggerHandler.FirstRun = true;
           // update i;
            i.Investigation_Status__c = 'Report Sent to Provider';    
            update i;    
            //i.Investigation_Status__c = 'Closed'; 
            //i.Cover_Letter_Issue_Date__c = System.Today();
            //Intervention__c inv = EEC_TestUtil.mockIntervention(i);
            //inv.Status__c = 'Cancelled';
            //inv.Cancel_Reason__c = 'Testing';
            
            //update inv;
            //update i;
            
            //i = [SELECT Closed_date__c FROM Investigation__c WHERE ID = :i.Id];
             
            //System.assertEquals(System.today(), i.Closed_Date__c); 
        }
        
        test.stopTest();
    }
    
    @isTest static void testUpdateClosedInvestigationsAfter() {   
        User u = EEC_TestUtil.mockUser();
        
        System.runAs(u) {
            Investigation__c i = EEC_TestUtil.mockInvestigation(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
            i.Investigation_Status__c = 'Approved - Report to send';
            i.Assigned_To__c = u.id;
            i.Approval_Task_Creation__c = 'NonEscalated Rejected';
            update i;
            i.Investigation_Status__c = 'Ready to Publish/Send to Provider';
            i.Report_Narrative_Issue_Date__c = Date.today();
            i.Sent_Date__c = Date.today();
            i.Cover_Letter_Issue_Date__c = Date.today();
			i.Created_on_the_Web__c = true;   
            test.startTest();
            update i; 
            i.Investigation_Status__c = 'Closed';
            update i;
        }
    }

    static testMethod void testCheckVisitForPublishedToWeb(){
        User u = EEC_TestUtil.mockUser();
        System.runAs(u){
            Account a = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
            Investigation__c i = EEC_TestUtil.mockInvestigation(a);
            i.Created_on_the_Web__c = false;
            update i;
            
            i.Created_on_the_Web__c = true;
            update i;

        }
    }
    @isTest static void testInvestigationAssignedEmailOutOfOffice() {  
        Investigation__c  invest = EEC_TestUtil.loadInvestigationSetup();  
        Intervention__c inter = EEC_TestUtil.mockIntervention(invest); 
        Investigation__c inv = [SELECT Id,Assigned_To__c FROM Investigation__c WHERE Investigation_Status__c != 'Closed' 
                                AND Number_of_Interventions__c > 0 LIMIT 1];

        User leader = [SELECT Id,Out_Of_Office__c,Name,ManagerId,For_Portal_Email__c FROM User WHERE IsActive = True AND UserType = 'Standard' AND 
                       Region__c != null AND ManagerId != null LIMIT 1];
        leader.Out_Of_Office__c = true;
        leader.Email = 'test@test.com';
        update leader;
        
        inv.Assigned_To__c = leader.Id;
        update inv;
        
    }
    
    @isTest static void testInvestigationApprovalEmailOutOfOffice() {
        Investigation__c  invest = EEC_TestUtil.loadInvestigationSetup();  
        Intervention__c inter = EEC_TestUtil.mockIntervention(invest); 
        Investigation__c inv = [SELECT Id,Assigned_To__c,Out_Of_Office_Initial_Recipient__c,Out_Of_Office_Email_Template_To_Send_del__c
                                FROM Investigation__c WHERE Investigation_Status__c != 'Closed' 
                                AND Number_of_Interventions__c > 0 LIMIT 1];
        User leader = [SELECT Id,Out_Of_Office__c,Name,ManagerId,For_Portal_Email__c FROM User WHERE IsActive = True AND UserType = 'Standard' AND 
                       Region__c != null AND ManagerId != null LIMIT 1];
        leader.Email = 'test@test.com';
        leader.Out_Of_Office__c = true;
        update leader;
        
        inv.Assigned_To__c = leader.Id;
        inv.Out_Of_Office_Initial_Recipient__c = leader.Id;
        inv.Out_Of_Office_Email_Template_To_Send_del__c = 'X25_Investigation_Approval_Investigation_sent_for_review_and_approval';
        update inv;
        
    }
    
    @isTest static void testCaseOwnerByInvestigationLeader() {
        Investigation__c  invest = EEC_TestUtil.loadInvestigationSetup();  
        Intervention__c inter = EEC_TestUtil.mockIntervention(invest); 
        Investigation__c inv = [SELECT Id,Assigned_To__c,Investigation_Status__c
                                FROM Investigation__c WHERE Investigation_Status__c = 'New' AND 
                                Number_of_Interventions__c > 0 LIMIT 1];
        
        User leader = [SELECT Id,Out_Of_Office__c,Name,ManagerId,For_Portal_Email__c FROM User WHERE IsActive = True AND UserType = 'Standard' AND 
                       Region__c != null AND ManagerId != null LIMIT 1];
        
        leader.Out_Of_Office__c = true;
        leader.Email = 'test@test.com';
        update leader;
        
        inv.Assigned_To__c = leader.Id;
        inv.Investigation_Status__c = 'Assigned - In Progress';
        update inv;
        
    }
    @isTest static void testReportDatesForApproved() {
        Investigation__c  invest = EEC_TestUtil.loadInvestigationSetup();  
        Intervention__c inter = EEC_TestUtil.mockIntervention(invest); 
        invest.Investigation_Status__c = 'Assigned - In Progress';
        update invest;
        Investigation__c inv = [SELECT Id,Assigned_To__c,Investigation_Status__c
                                FROM Investigation__c WHERE Investigation_Status__c = 'Assigned - In Progress' AND 
                                Number_of_Interventions__c > 0 LIMIT 1];
                        
        inv.Investigation_Status__c = 'Approved - Report to send';
        update inv;
        
    }
    
    @isTest static void testClosedInvestigationsAfter() {
        Investigation__c  invest = EEC_TestUtil.loadInvestigationSetup();  
        Intervention__c inter = EEC_TestUtil.mockIntervention(invest); 
		inter.Status__c = 'Done';
        inter.Date_Completed__c = system.today();
        update inter;
        test.startTest();
        Investigation__c inv = [SELECT Id,Assigned_To__c,Investigation_Status__c,Cover_Letter_Issue_Date__c
                                FROM Investigation__c WHERE Investigation_Status__c != 'Closed' AND
                                All_Interventions_Done__c = True LIMIT 1];
        
        inv.Investigation_Status__c = 'Ready to Publish/Send to Provider';
        inv.Cover_Letter_Issue_Date__c = System.today();
        update inv;
        
        inv.Investigation_Status__c = 'Closed';
        update inv;
        test.stopTest();
    }

}