phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Cases</description>
        <label>Investigation</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This investigation is associated with another provider.</errorMessage>
            <filterItems>
                <field>Investigation__c.Provider_No__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Associated Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_Case_Id__c</fullName>
        <description>Only displayed on the Legacy Case RecordType Page layout</description>
        <label>Legacy Case Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/HistoricalDocumentStaging__c.object
<CustomObject>
    <description>This object will be used as staging for converting metadata for historical documents into S3_file records related to appropriate cases, visits or investigations.</description>
    <fields>
        <fullName>DocumentDate__c</fullName>
        <label>DocumentDate</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>ErrorMessage</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FileName__c</fullName>
        <label>FileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntakeId__c</fullName>
        <label>IntakeId</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InteractionId__c</fullName>
        <label>InteractionId</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetaDataFileName__c</fullName>
        <label>MetaDataFileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramId__c</fullName>
        <label>ProgramId</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isProcessed</label>
        <type>Checkbox</type>
    </fields>
    <label>HistoricalDocumentStaging</label>
    <nameField>
        <label>HistoricalDocumentStaging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HistoricalDocumentStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legacy_System_Interaction__c</fullName>
        <label>Legacy System Interaction #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Legacy_IntakeID__c</fullName>
        <label>Legacy IntakeID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_System_Interaction__c</fullName>
        <description>Interaction Id from EECCRS for legacy data imported</description>
        <label>Legacy_System_Interaction</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isLegacyInvestigation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is to indicate that this is a legacy investigation.</description>
        <inlineHelpText>This is to indicate that this is a legacy investigation.</inlineHelpText>
        <label>isLegacyInvestigation</label>
        <type>Checkbox</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/S3_File__c.object
<CustomObject>
    <description>This is an object for storing S3 file representations.</description>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>The name of the bucket the file is contained in.</description>
        <label>Bucket</label>
        <length>125</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <description>The name of the file.</description>
        <label>Filename</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegacyRecordId__c</fullName>
        <label>LegacyRecordId</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_BatchProcessLegacyDocumentMetaData.cls
global class EEC_BatchProcessLegacyDocumentMetaData implements Database.Batchable<sObject> {

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([SELECT Id, ProgramId__c, IntakeId__c, InteractionId__c, FileName__c
																			, MetaDataFileName__c, DocumentDate__c
																		FROM HistoricalDocumentStaging__c
																		WHERE isProcessed__c = false]);
	}

	global void execute(Database.BatchableContext BC, List<HistoricalDocumentStaging__c> scope) {
		for(HistoricalDocumentStaging__c hds : scope){
			processHistoricalDocument(hds);
		}
		update scope;
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}

	private void processHistoricalDocument(HistoricalDocumentStaging__c hds){
		S3_File__c s3File = new S3_File__c();
		String provId = '';
		String caseId = '';
		String visitId = '';
		String invId = '';
		try{
			provId = (String)[SELECT ID FROM Account WHERE Provider_No__c = :hds.ProgramId__c limit 1].Id;
			caseId = (String)[SELECT Id FROM Case WHERE Legacy_Case_Id__c = :hds.IntakeId__c limit 1].id;
			visitId = (String)[SELECT Id FROM Inspection__c WHERE Legacy_System_Interaction__c = :hds.InteractionId__c limit 1].id;
			invId = (String)[SELECT Id FROM Investigation__c 
											WHERE isLegacyInvestigation__c = true 
												AND Legacy_IntakeID__c = :hds.IntakeId__c limit 1].id;
		} catch(Exception e){
			System.debug('-------> Id Error: ' + e.getMessage());
		}
		if(provId == ''){
			hds.ErrorMessage__c = 'Provider not found.';
			return;
		} 
		try{
			//Start processing documents other than visit/inv reports
			if(!hds.Filename__c.contains('ReportImage')){
				if(caseId == ''){
					hds.ErrorMessage__c = 'No legacy case found with Intake Id provided.';
					return;
				} else {
					s3File.LegacyRecordId__c = caseId;
				}
			}
			//End processing documents other than visit/inv reports

			//Start processing Visit coverLetters
			if(hds.Filename__c.contains('coverletter')){
				if(visitId == ''){
					hds.ErrorMessage__c = 'No legacy visit found with Interaction Id provided.';
					return;
				} else {
					s3File.LegacyRecordId__c = visitId;
				}
			}
			//End processing Visit coverLetters

			//Start processing investigation reports
			if(hds.Filename__c.contains('invreport')){
				if(String.isBlank(hds.InteractionId__c) && invId == ''){
					hds.ErrorMessage__c = 'No legacy investigation found with Intake Id provided.';
					return;
				} else if(String.isNotBlank(hds.InteractionId__c) && visitId == ''){
					hds.ErrorMessage__c = 'No legacy visit found with Interaction Id provided.';
					return;
				} else {
					s3File.LegacyRecordId__c = String.isBlank(hds.InteractionId__c) && invId != '' ? invId : visitId;
				}

			}
			//End processing investigation reports

			s3File.Bucket__c = 'eec-lead-legacydocs';
			s3File.Filename__c = hds.FileName__c;
			hds.isProcessed__c = true;
			if(String.isNotBlank(s3File.LegacyRecordId__c)){
				insert s3File;
			}

		} catch(Exception e){
			System.debug('--------> Error Message: ' + e.getMessage());
			hds.ErrorMessage__c = e.getMessage();
		}
		
	}
	
}