phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_GSA__c</fullName>
        <description>Will be true if this provider is a Large Group or Small Group</description>
        <formula>OR ( Record_Type_Name__c  = &apos;Large Group&apos;, Record_Type_Name__c   = &apos;Small Group&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is GSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_R_P__c</fullName>
        <description>Return True if this is an R&amp;P provider</description>
        <formula>OR(Is_Residential__c,  Is_Placement__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is R&amp;P</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region this provider is assigned to</description>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Cases</description>
        <label>Investigation</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This investigation is associated with another provider.</errorMessage>
            <filterItems>
                <field>Investigation__c.Provider_No__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Associated Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X2nd_Escalation_Case_Approver_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Escalation Case Approver Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X2nd_Escalation_Case_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Denotes the user that will be the 2nd Level escalation approver on cases</description>
        <inlineHelpText>Denotes the user that will be the 2nd Level escalation approver on cases</inlineHelpText>
        <label>2nd Escalation Case Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Lvl2_Escalation_Approver</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Assigned_To_Id__c</fullName>
        <formula>Inspector_del__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned To Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_days_to_receive_response__c</fullName>
        <description>Number of days to receive response</description>
        <inlineHelpText>Number of days given to the provider to receive corrective actions plan.</inlineHelpText>
        <label>Number of Days to Receive Corr. Actions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Provider_No__r.Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Assigned_To_Id__c</fullName>
        <formula>Assigned_To__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned To Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation can be assigned to a Licensor, Supervisor or Inspector</description>
        <inlineHelpText>User who will take the lead on the investigation.</inlineHelpText>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Investigation Type, Due Date and Intervention Type must be filled out when an Investigation is assigned</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_to_Receive_Response__c</fullName>
        <inlineHelpText>Number of days given to the provider to receive corrective actions plan.</inlineHelpText>
        <label>Number of Days to Receive Response</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Out_Of_Office_Email_Template_To_Send_del__c</fullName>
        <label>Out Of Office Email Template To Send</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Out_Of_Office_Initial_Recipient__c</fullName>
        <description>In case we need to forward email to the supervisor in case of out of office, this field will contain the ID of the initial recipient.</description>
        <label>Out Of Office Initial Recipient ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X1st_Escalation_Approver_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>1st Escalation Approver Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <inlineHelpText>This text will be used as default on Investigation Non-Compliance narrative text in case there is no non-compliance identified on this investigation.</inlineHelpText>
        <label>Investig. Non-comp. Default if None</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_days_to_receive_response_inv__c</fullName>
        <inlineHelpText>Default number of days given to the provider to fill corrective action plan on an investigation. This deadline will appear in the cover letter narrative and be used for the task created for the user to collect corrective action. Note that email reminder i</inlineHelpText>
        <label>Number of days to receive response (inv)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <fields>
        <fullName>Deputy_Commissioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This information is used by the system during the approval process of escalated Investigation. This user is the 1st reviewer / approver.</inlineHelpText>
        <label>Associate Commissioner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This information is used by the system during the approval process of escalated Investigation. For FCC / GSA, this user is the 2nd reviewer / approver.</inlineHelpText>
        <label>Regional Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>For_Portal_Email__c</fullName>
        <formula>Email</formula>
        <label>For_Portal Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Out_of_Office__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Out of Office</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the user is attached to</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast and Cape</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_InvestigationTriggerHandler.cls
public with sharing class EEC_InvestigationTriggerHandler {

    private Map<Id, Investigation__c> newMap;
    private Map<Id, Investigation__c> oldMap;
    private Map<Id,User> userMap;
    private Map<Id,Account> providerMap;
    private List<Case> cases;
    private List<Inspection__c> inspections;
    private List<Task> tasks;
    private Boolean gotRelatedObjects = false;
    private Set<Id> leaderSet;
    private Set<Id> providerSet;
    public static boolean FirstRun = true;
    Map<String, EmailTemplate> emailTemplateMap;
    List<OrgWideEmailAddress> orgList;
    private Map<String, Lead_Configuration__c> leadConfigMap;
    Map<Id, User> userList;
    
    EmailTemplate template24,template25,template34,template125; 

    public EEC_InvestigationTriggerHandler(Map<Id, Investigation__c> newMap, Map<Id, Investigation__c> oldMap){
        this.newMap = newMap;
        this.oldMap = oldMap; 
    }
    public void sendEscalationNotificationToInvestigator(){
        for(Investigation__c inv : newMap.values()){
            Investigation__c old = oldMap.get(inv.Id);
            if(inv.X1st_Escalation_Approver_Completed__c  && !old.X1st_Escalation_Approver_Completed__c 
               && inv.X1st_Escalation_Approver_Completed__c){
                EEC_EmailUtil email = new EEC_EmailUtil();
                EEC_EmailUtil invEmail = new EEC_EmailUtil();   
                if(!this.gotRelatedObjects){
                    getRelatedObjects();
                }
                   
                User invLeader = userList.get(inv.Assigned_To__c);
                Account prov = [SELECT Id,Name,Region__c, Region__r.Deputy_Commissioner__c,
                                Is_R_P__c,Is_GSA__c,OwnerId,Region__r.Regional_Director__r.Email,RecordType.Name 
                                FROM Account WHERE Id =: inv.Provider_No__c];
                
                 
                String fullRecordURL = URL.getSalesforceBaseUrl().toExternalForm() + '/' + inv.Id;
                email.subject = 'Investigation sent for review and approval';
                invEmail.subject = 'Investigation sent for review and approval: First Level Approval Complete';   
                template125 = emailTemplateMap.get('X125_Investigation_approved_by_Associate_Commissioner_of_Investigations');
                email.plainTextBody = template125.Body
                    .replace('{!Investigation__c.Name}', inv.Name)
                    .replace('{!Investigation__c.Assigned_To__c}', invLeader.Name)
                    .replace('{!Investigation__c.Provider_No__c}', prov.Name)
                    .replace('{!Investigation__c.Link}', fullRecordURL);
               
                invEmail.plainTextBody = template125.Body
                    .replace('{!Investigation__c.Name}', inv.Name)
                    .replace('{!Investigation__c.Assigned_To__c}', invLeader.Name)
                    .replace('{!Investigation__c.Provider_No__c}', prov.Name)
                    .replace('{!Investigation__c.Link}', fullRecordURL);   
                
                email.toAddresses = new List<String>();
                invEmail.toAddresses = new List<String>();   
                
                invEmail.toAddresses.add(invLeader.Email);
                if(invLeader.Out_of_Office__c){
                    User manager = userList.get(invLeader.ManagerId);
                    if(!manager.Out_of_office__c)
                        email.toAddresses.add(manager.Email);
                }
                if(prov.Is_GSA__c)
                    email.toAddresses.add(prov.Region__r.Regional_Director__r.Email);
                else if(prov.Is_R_P__c){
                    User licensor = userList.get(prov.OwnerId);
                    if(licensor.ManagerId != null)
                        email.toAddresses.add(userList.get(licensor.ManagerId).Email);
                }
                email.whatId = inv.Id;
                email.saveAsActivity = false; 
                invEmail.whatId = inv.Id;
                invEmail.saveAsActivity = false;
                   
                if(orgList.size() > 0){
                    System.debug('email.orgWideEmailId-->' + email.orgWideEmailId);
                    email.orgWideEmailId = orgList.get(0).Id;
                    invEmail.orgWideEmailId = orgList.get(0).Id;
                }
                if(email.toAddresses.size() > 0)    
                    email.sendEmail();
                if(invEmail.toAddresses.size() > 0)    
                    invEmail.sendEmail();   
            }
        }
    }

    public void sendInvestigationAssignedEmailOutOfOffice(){
        for(Investigation__c inv : newMap.values()){
            Investigation__c old = oldMap.get(inv.Id);

            if ( (old.Assigned_To__c == null && inv.Assigned_To__c != null) || 
                    (old.Assigned_To__c != null && inv.Assigned_To__c != null && old.Assigned_To__c != inv.Assigned_To__c)){
                if(!this.gotRelatedObjects){
                    getRelatedObjects();
                }
                User invLeader = userList.get(inv.Assigned_To__c);
                if(invLeader.out_of_Office__c){
                    EEC_EmailUtil email = new EEC_EmailUtil();
                    Account prov = [SELECT Id,Name,Region__c, Region__r.Deputy_Commissioner__c,
                                   Region__r.Regional_Director__c,RecordType.Name 
                                   FROM Account WHERE Id =: inv.Provider_No__c];
                    String fullRecordURL = URL.getSalesforceBaseUrl().toExternalForm() + '/' + inv.Id;
                    User leaderAssignedBy = userList.get(inv.LastModifiedById);
                    if(old.Assigned_To__c != null){
                        template24 = emailTemplateMap.get('X24_Investigation_ReAssigned_Notification_docx');
                        email.subject = template24.Subject;
                    }
                    else{
                        template24 = emailTemplateMap.get('X23a_Investigation_Assigned_Leader_Notification');
                        email.subject = template24.Subject.replace('{!Investigation__c.Provider_No__c}', prov.Name);
                        email.plainTextBody = template24.Body.replace('{!Investigation__c.Due_Date__c}', String.valueOf(inv.Due_Date__c));
                    }
                    email.plainTextBody = template24.Body
                        .replace('{!Investigation__c.Name}', inv.Name)
                        .replace('{!Investigation__c.LastModifiedBy}', leaderAssignedBy.Name)
                        .replace('{!Investigation__c.Provider_No__c}', prov.Name)
                        .replace('{!Investigation__c.Link}', fullRecordURL);
                    email.toAddresses = new List<String>();

                    if(invLeader.ManagerId != null){
                        User manager = userList.get(invLeader.ManagerId);
                        if(!manager.Out_of_office__c){
                            email.toAddresses.add(manager.Email); 
                        }
                        else if(manager.ManagerId != null){
                            User managersManager = userList.get(manager.ManagerId);
                            email.toAddresses.add(managersManager.Email); 
                        }
                    }
                    email.whatId = inv.Id;
                    email.saveAsActivity = false; 
    
                    if(orgList.size() > 0)
                        email.orgWideEmailId = orgList.get(0).Id;
                    
                    email.sendEmail();
                }
            }
        }
    }

    public void sendInvestigationApprovalEmailOutOfOffice(){
        for(Investigation__c inv : newMap.values()){
            Investigation__c old = oldMap.get(inv.Id);
            
            if(inv.Out_Of_Office_Initial_Recipient__c != null 
               && old.Out_Of_Office_Initial_Recipient__c == null){
                if(!this.gotRelatedObjects){
                    getRelatedObjects();
                }
                User approver = userList.get(inv.Out_Of_Office_Initial_Recipient__c);
                if(approver.Out_of_Office__c){
                    //template25 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName =: inv.Out_Of_Office_Email_Template_To_Send_del__c];   
                    template25 = emailTemplateMap.get(inv.Out_Of_Office_Email_Template_To_Send_del__c);
                    EEC_EmailUtil email = new EEC_EmailUtil();
                    Account prov = [SELECT Id,Name,Region__c, Region__r.Deputy_Commissioner__c,
                                   Region__r.Regional_Director__c,RecordType.Name 
                                   FROM Account WHERE Id =: inv.Provider_No__c];
                    User invLeader = userList.get(inv.Assigned_To__c);
                        
                    String fullRecordURL = URL.getSalesforceBaseUrl().toExternalForm() + '/' + inv.Id;
                    email.subject = template25.Subject;
                    email.plainTextBody = template25.Body
                        .replace('{!Investigation__c.Name}', inv.Name)
                        .replace('{!Investigation__c.Assigned_To__c}', invLeader.Name)
                        .replace('{!Investigation__c.Provider_No__c}', prov.Name)
                        .replace('{!Investigation__c.Link}', fullRecordURL);
                    
                    email.toAddresses = new List<String>();
                    
                    if(approver.ManagerId != null){
                        User manager = userList.get(approver.ManagerId);
                        if(!manager.Out_of_office__c)
                            email.toAddresses.add(manager.For_Portal_Email__c); 
                        else if(manager.ManagerId != null){
                            User managersManager = userList.get(manager.ManagerId);
                            email.toAddresses.add(managersManager.For_Portal_Email__c); 
                        }
                    }
                                        
                    email.whatId = inv.Id;
                    email.saveAsActivity = false; 
    
                    if(orgList.size() > 0)
                        email.orgWideEmailId = orgList.get(0).Id;
                    
                    email.sendEmail();
                }
                inv.Out_Of_Office_Email_Template_To_Send_del__c = '';
                inv.Out_Of_Office_Initial_Recipient__c = '';
            }
        }
    }
        
    private Boolean isInvestigator(Id userId) {
        //Do a check to see if this is an investigator and if so do not add task - per LEAD-4112
        Boolean ret = false;
        
        User[] user = [SELECT Id FROM User WHERE User.UserRole.Name ='Investigator' AND Id =: userId LIMIT 1];
        if(user.size() > 0){
            ret = true;
        }
        
        return ret;
    }
    
    public void assignNumberOfDaysToRecieveRespose(){
        Account provider;
        for(Investigation__c inv : newMap.values()){
            provider = providerMap.get(inv.Provider_no__c);
            if(inv.Number_of_Days_to_Receive_Response__c == null){
                if(!this.gotRelatedObjects){
                    getRelatedObjects();
                }
                Lead_Configuration__c lc = leadConfigMap.get(provider.RecordType.Name);
                inv.Number_of_Days_to_Receive_Response__c = lc.Number_of_days_to_receive_response_inv__c;
            }
        }
    }
    
    public void checkBeforeAssigningInvLeader(){
        Account provider;
        Boolean valid = true;
        for(Investigation__c inv : newMap.values()){
            Investigation__c old = oldMap.get(inv.Id);
            if(inv.Assigned_To_Id__c != old.Assigned_To_Id__c){
                provider = providerMap.get(inv.Provider_no__c);
                if(!this.gotRelatedObjects){ 
                    getRelatedObjects();
                }
                List<Case> cases = casesForInvestigation(inv); 
                for(Case c : cases){
                    if(c.Status == 'Escalated' && ((!c.X2nd_Escalation_Case_Approver_Completed__c && c.X2nd_Escalation_Case_Approver__c != null) || 
                       (!c.X1st_Escalation_Case_Approver_Completed__c && c.X2nd_Escalation_Case_Approver__c == null)))
                        valid = false;
                }
            }
            if(!valid)
                inv.addError('The associated case needs to be approved before assigning an investigation leader.');
        }
    }
   
    public void updateClosedInvestigationsBefore(){
        
        leaderSet = new Set<Id>();
        providerSet = new Set<Id>();
        for(Investigation__c inv : newMap.values()){
            
            Investigation__c old = oldMap.get(inv.Id);
            System.debug('New Investigation Status --- >' + inv.Investigation_Status__c);
            System.debug(old);
            
            providerSet.add(inv.Provider_no__c);
            if(String.isNotBlank(inv.Assigned_to__c)){
                leaderSet.add(inv.Assigned_to__c);
            }    
            if((old == NULL || old.Investigation_Status__c != 'Closed') && inv.Investigation_Status__c == 'Closed'){
                inv.Closed_date__c = System.Today();
                inv.Created_on_the_Web__c = true;
                inv.Require_Portal_Feedback__c = true;
            }
            
        }
    }
    
    private void getRelatedObjects(){ 
        
        this.cases = [
            SELECT ID, Investigation__c, X2nd_Escalation_Case_Approver_Completed__c, 
            Status,X2nd_Escalation_Case_Approver__c,X1st_Escalation_Case_Approver_Completed__c
            FROM Case 
            WHERE Investigation__c IN :newMap.keySet()
        ];
        
        this.inspections = [
            SELECT ID, Investigation__c, Status__c, Closed_Cancellation_Date__c, Cancellation__c
            From Inspection__c 
            WHERE Investigation__c IN :newMap.keySet()
            AND Status__c IN ('Visit Completed', 'Report to be sent to Provider')
        ];
        
        this.tasks = [
            SELECT ID, WhatId
            FROM Task 
            WHERE WhatId IN :newMap.keySet() 
            AND IsRecurrence = false AND Status != 'Completed'
        ];
        
        this.userList = new Map<Id, User>([
            SELECT ManagerId, UserRoleId, Email, Name, DelegatedApproverId,Out_of_Office__c,For_Portal_Email__c
            FROM User
            WHERE UserType = 'Standard'
        ]);
        
        this.leadConfigMap = new Map<String, Lead_Configuration__c>();
        for(Lead_Configuration__c lc : [SELECT Id, Name,Number_of_days_to_receive_response_inv__c FROM Lead_Configuration__c]){
            if(lc.Number_of_days_to_receive_response_inv__c != null && !leadConfigMap.keySet().Contains(lc.Name)){
                leadConfigMap.put(lc.Name, lc);
            }
        }
        
        orgList = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = 'EEC LEAD Alert'];
        
        Set<String> emailTemplateName = new Set<String>();
        emailTemplateName.add('X24_Investigation_ReAssigned_Notification_docx');
        emailTemplateName.add('X25_Investigation_Approval_Investigation_sent_for_review_and_approval');
        emailTemplateName.add('X34_Alert_to_licensor_that_corrective_actions_have_been_submitted');
        emailTemplateName.add('X23a_Investigation_Assigned_Leader_Notification');
        emailTemplateName.add('X125_Investigation_approved_by_Associate_Commissioner_of_Investigations');

        
        List<EmailTemplate> emailTempateList = new List<EmailTemplate>([SELECT Body, Subject,DeveloperName FROM EmailTemplate WHERE DeveloperName IN: emailTemplateName]);
        emailTemplateMap = new Map<String, EmailTemplate>();
        for(EmailTemplate temp : emailTempateList){
            emailTemplateMap.put(temp.DeveloperName, temp);
        }
        
        /*template24 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'X24_Investigation_ReAssigned_Notification_docx'];
        template25 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'X25_Investigation_Approval_Investigation_sent_for_review_and_approval'];
        template34 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'X34_Alert_to_licensor_that_corrective_actions_have_been_submitted'];
        template125 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'X125_Investigation_approved_by_Associate_Commissioner_of_Investigations'];*/

        this.gotRelatedObjects = true;
    }
    public void updateCaseOwnerByInvestigationLeader(){
        for(Investigation__c inv : newMap.values()){
            Investigation__c old = oldMap.get(inv.Id);
            if((old.Investigation_Status__c == 'New' 
                || inv.Investigation_Status__c == 'Assigned - In Progress') 
                && old.Assigned_To__c != inv.Assigned_To__c && inv.Assigned_To__c != null){
                if(!this.gotRelatedObjects){
                    getRelatedObjects();
                }
                List<Case> cases = casesForInvestigation(inv); 
                for(Case c : cases){
                    c.Status = 'Investigation in Progress';
                    c.OwnerId = inv.Assigned_To__c;
                }
                if(cases.size() != 0){
                    update cases;
                }
            }
        }
    }
    
    public void updateReportDatesForApproved(){
        for(Investigation__c inv : newMap.values()){
            Investigation__c old = oldMap.get(inv.Id);
            if(old.Investigation_Status__c != 'Approved - Report to send' &&
               inv.Investigation_Status__c == 'Approved - Report to send') {
                Attachment[] att = [SELECT Id, CreatedDate FROM Attachment WHERE Name Like '%NonCompliance-%' AND ParentId =: inv.Id ORDER BY CreatedDate DESC];   
                Attachment[] attNarr = [SELECT Id, CreatedDate FROM Attachment WHERE Name Like '%Narrative-%' AND ParentId =: inv.Id ORDER BY CreatedDate DESC];      
                if(att.size() > 0)
                    inv.Statement_of_non_compliance_Issue_Date__c = att[0].CreatedDate.date();
                if(attNarr.size() > 0)   
                    inv.Report_Narrative_Issue_Date__c = attNarr[0].CreatedDate.date();
            }
        }
    }
    
    public void updateClosedInvestigationsAfter() {
        for(Investigation__c inv : newMap.values()){
            Investigation__c old = oldMap.get(inv.Id);
            if((old == NULL || old.Investigation_Status__c != 'Closed') && inv.Investigation_Status__c == 'Closed'){
                if(!this.gotRelatedObjects){
                    getRelatedObjects();
                }
                List<Case> cases = casesForInvestigation(inv); 
                for(Case c : cases){ 
                    c.Status = 'Closed';
                    c.Closing_reasons__c = 'Investigation Closed';
                } 
                if(cases.size() != 0){
                    update cases;
                }
                List<Inspection__c> inspections = inspectionsForInvestigation(inv);
                
                for(Inspection__c insp : inspectionsForInvestigation(inv)){
                    insp.Status__c = 'Closed';
                    insp.Closed_Cancellation_Date__c = System.Today();
                    insp.Cancellation__c = 'Investigation Closed';
                }
                if(inspections.size() != 0){
                    update inspections;
                }
                
               /* List<Task> tasks = tasksForInvestigation(inv);
                
                for(Task t : tasks){
                    t.Status = 'Completed'; 
                }
                
                if(tasks.size() != 0){
                    update tasks;
                }*/
                
            }
        }
    }
    
    public void updateLeaderHeirarchy(){
        
        List<Task> approvalTaskList = new List<Task>();
        Account provider;
        providerMap = new Map<Id,Account>([select Id,Name,Region__c, Region__r.Deputy_Commissioner__c,Region__r.Regional_Director__c,RecordType.Name from Account where Id in :providerSet]);
        if(leaderSet != null && leaderSet.size()>0){
            this.userMap  = new Map<Id,User>([select Id, ManagerId from User where Id in :leaderSet and ManagerId != null]);
        }
        
        for(Investigation__c inv : newMap.values()){
            provider = providerMap.get(inv.Provider_no__c);
            if(String.isNotBlank(provider.Region__c) && String.isNotBlank(provider.Region__r.Deputy_Commissioner__c)){
             /* REPLACED BY WORKFLOW   inv.Leader_Deputy_Commisioner__c = provider.Region__r.Deputy_Commissioner__c;  */
            }
            if(userMap != null && String.isNotBlank(inv.Assigned_To__c) && userMap.containsKey(inv.Assigned_To__c)){
              inv.Leader_Manager__c = userMap.get(inv.Assigned_To__c).ManagerId;
            }
            if(provider.RecordType.Name == 'Family Child Care' || provider.RecordType.Name == 'Small Group' || provider.RecordType.Name == 'Large Group'){
              /* REPLACED BY WORKFLOW     inv.Leader_Director_Supervisor__c = provider.Region__r.Regional_Director__c;*/
            }
            else{
              /* REPLACED BY WORKFLOW     inv.Leader_Director_Supervisor__c = inv.Leader_Manager__c;*/
            }
                        
            String newATC = inv.Approval_Task_Creation__c;
            String oldATC;
            Task approvalTask;
            if(String.isNotBlank(newATC)){
                if(oldMap != null){
                    Investigation__c old = oldMap.get(inv.Id);
                    oldATC = (old != null && String.isNotBlank(old.Approval_Task_Creation__c))?old.Approval_Task_Creation__c:'';
                    if(newATC != oldATC){
                        if(newATC == 'NonEscalated Approved' || newATC == 'Escalated Approved'){
                            //if (!isInvestigator(inv.Assigned_To__c)) {
                                approvalTask = new Task();
                                approvalTask.Subject = 'Review, send investigation report to Provider and close investigation - For ' + provider.Name;
                                approvalTask.Status = 'Not Started';
                                approvalTask.Priority = 'High';
                                approvalTask.WhatId = inv.Id;
                                if(newATC == 'NonEscalated Approved') 
                                    approvalTask.OwnerId = String.isNotBlank(inv.Assigned_To__c) ? inv.Assigned_To__c : UserInfo.getUserId();
                                else {
                                    if(!provider.Is_R_P__c)
                                        approvalTask.OwnerId = String.isNotBlank(inv.Leader_Director_Supervisor__c) ? inv.Leader_Director_Supervisor__c : UserInfo.getUserId();
                                    else
                                        approvalTask.OwnerId = String.isNotBlank(inv.Licensor_Manager__c) ? inv.Licensor_Manager__c : UserInfo.getUserId();
                                }
                                    approvalTask.ActivityDate = Date.today().addDays(3);
                                    approvalTaskList.add(approvalTask);
                                
                            //} 
                        }
                        else if(newATC == 'NonEscalated Rejected' || newATC == 'Escalated Rejected'){
                            approvalTask = new Task();
                            approvalTask.Subject = 'Re-work required on investigation following review and rejection';
                            approvalTask.Status = 'Not Started';
                            approvalTask.Priority = 'High';
                            approvalTask.WhatId = inv.Id;
                            approvalTask.OwnerId = String.isNotBlank(inv.Assigned_To__c)?inv.Assigned_To__c:UserInfo.getUserId();
                            approvalTask.ActivityDate = Date.today().addDays(3);
                            approvalTaskList.add(approvalTask);
                        }
                        
                    }
                }
            }
        }
        if(approvalTaskList != null && approvalTaskList.size()>0){
            insert approvalTaskList;
        }
        
    }
    
    
    
    public List<Case> casesForInvestigation(Investigation__c i){ 
        List<Case> l = new List<Case>();
        
        for(Case c : cases){
            if(c.Investigation__c == i.Id){
                l.add(c);
            }
        }
        
        return l;
    }
    
    public List<Task> tasksForInvestigation(Investigation__c i){ 
        List<Task> l = new List<Task>();
        
        for(Task t : tasks){
            if(t.WhatId == i.Id){
                l.add(t);
            }
        }
        
        return l;
    }
    
    public List<Inspection__c> inspectionsForInvestigation(Investigation__c i){ 
        List<Inspection__c> l = new List<Inspection__c>();
        
        for(Inspection__c insp : inspections){
            if(insp.Investigation__c == i.Id){
                l.add(insp);
            }
        }
        
        return l;
    }
    
    /**
     * checkVisitsForPublishedToWeb
     * 
     * This function will verify all visits and non compliants for published to web. 
     * @author Darkis
     */
    public void checkVisitsForPublishedToWeb() {
      for(Investigation__c inv : newMap.values()){
        Investigation__c old = oldMap.get(inv.Id); System.debug('-----> Investigation: ' + inv.Id);
        // If the old record was not published to web and the new one is then continue.  
        if (!old.Created_on_the_Web__c && inv.Created_on_the_Web__c) {
          // Get all the related visits who are not closed or cancelled.
          List<Id> visitIds = new List<Id>();
          List<Inspection__c> visits = [SELECT Id, Name, Status__c, Created_on_the_Web__c 
                                        FROM Inspection__c 
                                        WHERE Investigation__c = :inv.Id 
                                        AND Status__c NOT IN('Cancelled', 'Closed')];  
            System.debug('-----> Visits: ' + visits);
          // If there are any visits meeting the criteria.
          if (visits != null && visits.size() > 0) {
            // Loop through the results.
            for (Inspection__c visit : visits) {
              visitIds.add(visit.Id);
              visit.Created_on_the_Web__c = true;
            }    
            // Update the visits. The visits will be modified by the Visits trigger to set Visit Items to Review on Portal = true and the Visit to "Report Sent to Provider, Awaiting Feedback".
            update visits;
          }
          //Get all non-compliant items.
          List<Non_Compliant__c> nonCompliantItems = [Select Id, Name, Feedback_Requested__c,Correction_Plan_Status__c, To_Review_on_Portal__c From Non_Compliant__c Where Investigation__c = :inv.Id AND Feedback_Requested__c = true]; System.debug('-----> NonCompliants: ' + nonCompliantItems);
          // If there are non compliant items with feedback requested. 
          List<Non_Compliant__c> updateNonComp = new List<Non_Compliant__c>();
          if (nonCompliantItems != null && nonCompliantItems.size() > 0) {
            // Loop through non compliant items and update To_Review_on_Portal__c to True.
            for (Non_Compliant__c ncItem : nonCompliantItems) {
                Non_Compliant__c ncItem2 = ncItem;
                ncItem2.To_Review_on_Portal__c = true;
                ncItem2.Correction_Plan_Status__c ='Provider To Submit';
                updateNonComp.add(ncItem2);
            } 
            update updateNonComp;
          }
          // Get a count of the Visit Items that have Feedback_Requested__c = true.
          Integer visitItemsCount = [Select Count() From Inspection_Item__c Where Feedback_Requested__c = true AND Inspection_No__c IN :visitIds]; System.debug('-----> visitItemsCount: ' + visitItemsCount);
          // If there are any NonCompliant Items OR Visit Items with Feedback_Requested__c = true then update the Investigation.   
          if ((nonCompliantItems != null && nonCompliantItems.size() > 0) || (visitItemsCount != null && visitItemsCount > 0)) {
            // Update Investigation fields.
            Investigation__c newInvest = [Select Id, Name, Require_Portal_Feedback__c,lock_investigation__c From Investigation__c Where Id = :inv.Id];
            newInvest.Require_Portal_Feedback__c = true;
            update newInvest;      
          }
        }
      }
    }
}