phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document__c.object
<CustomObject>
    <description>A custom object to be used for non-Salesforce reference documents.</description>
    <fields>
        <fullName>Document_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Type</label>
        <referenceTo>Document_Type__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC- {0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document_Type__c.object
<CustomObject>
    <description>An object for storing all document types. This is not to be confused with document prototypes (i.e. image/jpeg, document/pdf, etc)</description>
    <fields>
        <fullName>Allow_use_of_Umbrella_Level_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Use of Umbrella Level Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>A description for the document type.</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Individual_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Individual Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEAD_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Provider Type</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Document Types</relationshipLabel>
        <relationshipName>Document_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Library_Level__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If check, this document type will appear in the library of all providers this document type is defined on - per type of provider</inlineHelpText>
        <label>Library Level</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Need_to_be_Updated_at_each_new_Transacti__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Update Each New Transaction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Transactio_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Optional for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Related_Role__c</fullName>
        <label>Related Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Director / Administrative Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Contact</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Required_for_Transaction_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Required for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Document Type</label>
    <nameField>
        <label>Document Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>List_of_Missing_Mandatory_Document__c</fullName>
        <inlineHelpText>List of all mandatory documents not yet attached to the transaction.</inlineHelpText>
        <label>List of Missing Mandatory Document</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_of_Rejected_Document_Not_Submitted__c</fullName>
        <inlineHelpText>List of all documents rejected by EEC that have not been yet reviewed and submitted again by provider.</inlineHelpText>
        <label>List of Rejected Document Not Submitted</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Transaction_Document__c.object
<CustomObject>
    <description>A junction between the Document and a transaction.</description>
    <fields>
        <fullName>Document_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Type</label>
        <referenceTo>Document_Type__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Transaction Documents (Document)</relationshipLabel>
        <relationshipName>Transaction_Documents1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Licensing_Transaction__c</fullName>
        <label>Licensing Transaction</label>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Optional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Variance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <formula>Document__r.Provider__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provider</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Upload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - EEC to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Attachment</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction Document</label>
    <nameField>
        <displayFormat>TD- {0000000}</displayFormat>
        <label>Transaction Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TransactionDocumentTriggerHandler.cls
public class EEC_TransactionDocumentTriggerHandler {
    public static void doAfterInsert(List<Transaction_Document__c> listTransactionDocument){
        updateMissingDocuments(listTransactionDocument);	
    }
    
    public static void doAfterUpdate(List<Transaction_Document__c> listTransactionDocument){
        system.debug('start updateMissingDocuments');
        updateMissingDocuments(listTransactionDocument);
        system.debug('start updateMissingDocuments');
    }
    
    public static void doAfterUnDelete(List<Transaction_Document__c> listTransactionDocument){
        updateMissingDocuments(listTransactionDocument);
    }
    
    public static void doAfterDelete(List<Transaction_Document__c> listTransactionDocument){
        updateMissingDocuments(listTransactionDocument);
    }
    
    private static void updateMissingDocuments(List<Transaction_Document__c> listTransactionDocument){        
        Set<Id> setTransactionId = new Set<Id>();
        
        for(Transaction_Document__c transactionDocument : listTransactionDocument){
            if(transactionDocument.Document_Type__c != null && transactionDocument.Document__c != null){
                setTransactionId.add(transactionDocument.Licensing_Transaction__c);
            }
        }
        List<Licensing_Transaction__c> listTransactions = [select Id, List_of_Missing_Mandatory_Document__c, List_of_Rejected_Document_Not_Submitted__c,
                                                           Provider__r.Config_Record__c,
                                                           RecordType.Name,
                                                           (select Id, Document_Type__c,Document__c,Document_Type__r.Name, Status__c,Mode__c from Transaction_Documents__r)
                                                           from Licensing_Transaction__c where Id in : setTransactionId  and
                                                           Status__c <> 'To Submit' and
                                                           (not Status__c like '%Closed%') and
                                                           (not Status__c like '%Cancelled%')];
        
        
        Set<Id> setLeadConfiguration = new Set<Id>();
        for(Licensing_Transaction__c licesingTransaction : listTransactions){
            setLeadConfiguration.add(licesingTransaction.Provider__r.Config_Record__c);
        }
        
        List<Document_Type__c> listDocumentType = [select Id, LEAD_Configuration__c, Allow_use_of_Umbrella_Level_Document__c, Description__c,Name,Individual_Document__c,Library_Level__c,Need_to_be_Updated_at_each_new_Transacti__c,
                                                   Optional_for_Transactio_Type__c,Related_Role__c,Required_For_Transaction_Type__c from Document_Type__c 
                                                   where LEAD_Configuration__c in : setLeadConfiguration];
        
        Map<Id, List<Document_Type__c>> mapLeadDocumentType = new Map<Id, List<Document_Type__c>>();
        for(Document_Type__c documentType : listDocumentType){
            List<Document_Type__c> listDocumentTypes;
            if(mapLeadDocumentType.get(documentType.LEAD_Configuration__c) == null){
                listDocumentTypes = new List<Document_Type__c>();
            }
            else{
                listDocumentTypes = mapLeadDocumentType.get(documentType.LEAD_Configuration__c);
            }
            listDocumentTypes.add(documentType);
            mapLeadDocumentType.put(documentType.LEAD_Configuration__c, listDocumentTypes);
        }
        
        for(Licensing_Transaction__c licensingTransaction : listTransactions){
            
            List<Document_Type__c> listDocumentTypes = mapLeadDocumentType.get(licensingTransaction.Provider__r.Config_Record__c);
            
            string missingDocuments = '';
            for(Document_Type__c documentType : listDocumentTypes){
                if(string.isNotEmpty(documentType.Required_For_Transaction_Type__c) && documentType.Individual_Document__c == false && documentType.Required_For_Transaction_Type__c.contains(licensingTransaction.RecordType.Name)){
                    for(Transaction_Document__c transactionDocument : licensingTransaction.Transaction_Documents__r){
                        if(transactionDocument.Document_Type__c == documentType.Id && transactionDocument.Mode__c == 'Required' && transactionDocument.Status__c == 'To Upload' && transactionDocument.Document_Type__c != null && transactionDocument.Document__c != null){
                            missingDocuments = missingDocuments + ', ' + documentType.Name;
                        }
                    }
                }
                else if(string.isNotEmpty(documentType.Required_For_Transaction_Type__c) && documentType.Individual_Document__c == true && documentType.Required_For_Transaction_Type__c.contains(licensingTransaction.RecordType.Name)){
                    for(Transaction_Document__c transactionDocument : licensingTransaction.Transaction_Documents__r){
                        if(transactionDocument.Document_Type__c == documentType.Id && transactionDocument.Mode__c == 'Individual' && transactionDocument.Status__c == 'To Upload' && transactionDocument.Document_Type__c != null && transactionDocument.Document__c != null){                                
                            missingDocuments = missingDocuments + ', ' + documentType.Name;
                        }
                    }
                }
            }
            if(missingDocuments.length() > 0)
                licensingTransaction.List_of_Missing_Mandatory_Document__c = missingDocuments.removeStart(', ');
            else
                licensingTransaction.List_of_Missing_Mandatory_Document__c = '';
            
            string rejectedDocuments = '';
            for(Transaction_Document__c transactionDocument : licensingTransaction.Transaction_Documents__r){
                if(transactionDocument.Status__c == 'Returned for Revision' && transactionDocument.Document_Type__c != null && transactionDocument.Document__c != null){
                    rejectedDocuments = rejectedDocuments + ', ' + transactionDocument.Document_Type__r.Name;
                }
            }
            if(rejectedDocuments.length() > 0)
                licensingTransaction.List_of_Rejected_Document_Not_Submitted__c = rejectedDocuments.removeStart(', ');
            else
                licensingTransaction.List_of_Rejected_Document_Not_Submitted__c = '';
        }
        update listTransactions;
    }
}