phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Cases</description>
        <label>Investigation</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This investigation is associated with another provider.</errorMessage>
            <filterItems>
                <field>Investigation__c.Provider_No__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Associated Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>At creation and if left blank, City will be populated with Provider address after saving</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Note that all licensing visits with the following statuses will be available on portal:  &quot;Scheduled&quot; (if Announced flag is checked)  / &quot;Closed&quot; / &quot;Report Sent to Provider, Awaiting Feedback&quot; / &quot;Feedback received, to review&quot;</description>
        <inlineHelpText>If checked, non compliant items associated to this visit have been published on portal and are ready to be reviewed.</inlineHelpText>
        <label>Published on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Approval_Task_Creation__c</fullName>
        <label>Approval Task Creation</label>
        <picklist>
            <picklistValues>
                <fullName>NonEscalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NonEscalated Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation can be assigned to a Licensor, Supervisor or Inspector</description>
        <inlineHelpText>User who will take the lead on the investigation.</inlineHelpText>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine if a report has been deployed/shown to the portal community.</description>
        <inlineHelpText>Check this box if you wish to deploy this Investigation to the Web Portal.</inlineHelpText>
        <label>Publish Report on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Out_Of_Office_Email_Template_To_Send_del__c</fullName>
        <label>Out Of Office Email Template To Send</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Out_Of_Office_Initial_Recipient__c</fullName>
        <description>In case we need to forward email to the supervisor in case of out of office, this field will contain the ID of the initial recipient.</description>
        <label>Out Of Office Initial Recipient ID</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>X1st_Escalation_Approver_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>1st Escalation Approver Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Out_of_Office__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Out of Office</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TestInvestigationTriggerHandler.cls
@isTest
public class EEC_TestInvestigationTriggerHandler {
    static testMethod void investigationtrigger(){
        City__c  c = EEC_TestUtil.mockCity();
        Account a = EEC_TestUtil.mockProvider(c);
        Contact con  = EEC_TestUtil.mockContact();
        User u = EEC_TestUtil.mockUser();
        Investigation__c inve = new Investigation__c(Provider_No__c = a.Id, Assigned_To__c=u.Id);
        inve.X1st_Escalation_Approver_Completed__c = false;
        insert inve;
        
        Task task = EEC_TestUtil.mockTask(inve);
        Case cas = EEC_TestUtil.mockCase(a, con, inve);
        //Inspection__c insp = EEC_TestUtil.mockInspection(a);
        
        test.startTest(); 
        
        inve.Approval_Task_Creation__c = 'NonEscalated Approved';
        inve.Assigned_To__c = null;  
        inve.X1st_Escalation_Approver_Completed__c = true;
        inve.Assigned_To__c=u.Id;
        EEC_InvestigationTriggerHandler.FirstRun = true;
        update inve;  
        
        system.debug('inv.X1st_Escalation_Approver_Completed__c: ' + inve.X1st_Escalation_Approver_Completed__c);
        
        test.stopTest();        
    }
    
    static testMethod void investemailoutofoffice(){
        City__c  c = EEC_TestUtil.mockCity();
        Account a = EEC_TestUtil.mockProvider(c);
        
        User tempUser = new User(id = UserInfo.getUserId() , Out_of_Office__c = true,ManagerID = (EEC_TestUtil.mockUser()).id);
        update tempUser;
        
        Investigation__c inv = new Investigation__c(Provider_No__c = a.Id, Assigned_To__c=Userinfo.getUserId());
        inv.X1st_Escalation_Approver_Completed__c = false;
        insert inv;
        
        test.startTest();
        
        inv.Created_on_the_Web__c = false;
        inv.Out_Of_Office_Initial_Recipient__c = UserInfo.getUserId();
        inv.Out_Of_Office_Email_Template_To_Send_del__c = 'X25_Investigation_Approval_Investigation_sent_for_review_and_approval';
        inv.X1st_Escalation_Approver_Completed__c = true;
        
        update inv;
        
        system.debug('inv.X1st_Escalation_Approver_Completed__c: ' + inv.X1st_Escalation_Approver_Completed__c);
        test.stopTest();        
    }
}