phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <valueField>$Source.State__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Umbrella_Members__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field implements a Look Up relationship to create a self relationship in order for the Umbrella record type to display an Umbrella Members related list to display all Providers within the Umbrella</description>
        <label>Umbrella</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected umbrella must be an umbrella record type</errorMessage>
            <filterItems>
                <field>Account.Record_Type_Name__c</field>
                <operation>contains</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Umbrella Members</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Umbrella</fullName>
        <active>true</active>
        <description>Umbrella</description>
        <label>Umbrella</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Mater_Visit_for_Res_Cluster_of_Visits__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select here the visit that will serve as Primary Visit. Being defined as a &apos;dependent associated&apos; visit, this visit will follow the same process than the Primary for the following steps: visit scheduling, selection of visit checklist, and report creation.</inlineHelpText>
        <label>Primary Visit (for Cluster of Visit)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Inspector_del__c</field>
                <operation>equals</operation>
                <valueField>Inspection__c.Inspector_del__c</valueField>
            </filterItems>
            <filterItems>
                <field>Inspection__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Is_Residential__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Mater_Visit_for_Res_Cluster_of_Visits__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Umbrella_Members__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Dependent Associated Visits (for Res. Cluster of Visits)</relationshipLabel>
        <relationshipName>Slave_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TestGenerateVisitNarrativeExtension.cls
@isTest
public with sharing class EEC_TestGenerateVisitNarrativeExtension {

    @isTest static void testGetCompliantWithObservations(){
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        Standard_Inspection_Item__c sii1 = EEC_TestUtil.mockStdInspectionItem();
        
        Regulation__c reg1 = EEC_TestUtil.mockRegulation();
        Regulation__c reg2 = EEC_TestUtil.mockRegulation();
        EEC_TestUtil.mockRegStdInsp(reg1, sii1);
        EEC_TestUtil.mockRegStdInsp(reg2, sii1);
        
         Inspection_Item__c ii1 = EEC_TestUtil.mockInspectionItem(i, sii1 , 'Compliant', false, null);
        Inspection_Item__c ii2 = EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation() , 'Non-Compliant', false, null);
        
        Inspection_Item__c ii = [SELECT Id, Inspection_No__r.Provider_No__c,Inspection_No__c FROM Inspection_Item__c 
                                WHERE Inspection_Result__c = 'Compliant' LIMIT 1];
        
        i = [SELECT Id,Mater_Visit_for_Res_Cluster_of_Visits__c,Provider_No__r.Umbrella_Members__c
                           FROM Inspection__c WHERE ID =: ii.Inspection_No__c LIMIT 1];
        
        //Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        //EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
        //EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null, null); 
        //EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Not Applicable', false, null, 'test'); 
        //EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null, 'test 2'); 
        test.startTest();
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
        
        List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = ext.getCompliantWithObservations();
        test.stopTest();
        //System.assertEquals(2, l.size());
    }

    @isTest static void testGetProgramDirectorContactValid(){ 
        Account pa = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()); 
         
        Inspection__c i = EEC_TestUtil.mockInspection(pa);
        
        i = [SELECT Provider_No__r.Umbrella_Members__c FROM Inspection__c WHERE Id = :i.Id];
        
        Contact c = EEC_TestUtil.mockDirectorContact(pa);
        //AccountContactRole acr = EEC_TestUtil.mockAccountContactRole('Director', c, pa);
        test.startTest();
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
        Contact result = ext.getDirectorContact();
        test.stopTest();
        System.assertEquals(c.FirstName, result.FirstName);
        System.assertEquals(c.Id, result.Id);
    }

    @isTest static void testGetProgramDirectorContactInvalid(){ 
        Account pa = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());  
         
        Inspection__c i = EEC_TestUtil.mockInspection(pa);
        
        i = [SELECT Provider_No__r.Umbrella_Members__c,Mater_Visit_for_Res_Cluster_of_Visits__c FROM Inspection__c WHERE Id = :i.Id];
        
        test.startTest();
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
        Contact result = ext.getDirectorContact();
        
        List<Inspection__c> insp = ext.getChildVisits();
        test.stopTest();
        System.assertEquals(null, result ); 
    }


    @isTest static void testGetExecutiveDirectorContactValid(){ 
       
        Account a1 = new Account();
          RecordType r = [SELECT Id, Name FROM RecordType WHERE DeveloperName='Umbrella' and sobjecttype='Account'];
        a1.Name = 'Test Umbrella';
        a1.RecordTypeId = r.Id;
        a1.Provider_Address_1__c = 'Test';
        a1.Provider_City__c = EEC_TestUtil.mockCity().Id;
        a1.Provider_Zip_Code__c = '43433';
        insert a1;
        
         Account ca = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), a1);
        ca.Umbrella_Members__c = a1.Id;
        update ca;
        Inspection__c i = EEC_TestUtil.mockInspection(ca);
        
        i = [SELECT Provider_No__r.Umbrella_Members__c FROM Inspection__c WHERE Id = :i.Id];
        
        System.debug('-----Inspection__c: ' + i);
        
        Contact c = EEC_TestUtil.mockDirectorContact(ca);
        AccountContactRole acr = EEC_TestUtil.mockAccountContactRole('Director', c, ca);
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
      //  ext.getExecutiveDirectorContact();
        System.debug('Ext: ' + ext);   
        Contact result = ext.getExecutiveDirectorContact();   
       
        
        //System.assertEquals(c.FirstName, result.FirstName);
        //System.assertEquals(c.Id, result.Id);
    }

    @isTest static void testGetExecutiveDirectorContactInvalid(){ 
        Account pa = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()); 
         
        Inspection__c i = EEC_TestUtil.mockInspection(pa);
        
        i = [SELECT Provider_No__r.Umbrella_Members__c FROM Inspection__c WHERE Id = :i.Id];
        
        Contact c = EEC_TestUtil.mockDirectorContact(pa);
        //AccountContactRole acr = EEC_TestUtil.mockAccountContactRole('Director', c, pa);
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
        Contact result = ext.getExecutiveDirectorContact();
        
        System.assertEquals(null, result);
    }
   
}