phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_Investigation_Conclusion_Notificati__c</fullName>
        <label>Last Investi. Concl. Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notify_for_Investigation_Conclusion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify for Investigation Conclusion</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Incident_Reported_Date__c</fullName>
        <label>Incident Reported Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation_Conclusion_Submitted_Date__c</fullName>
        <label>Investigation Conclusion Submitted Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Incident</fullName>
        <active>true</active>
        <businessProcess>Incident</businessProcess>
        <description>Incident - select this record type when capturing an Incident from a Provider</description>
        <label>Incident</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_Batch_InvestigationConclusion.cls
global class EEC_Batch_InvestigationConclusion implements Database.Batchable<sObject> {
	
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
    	
		return Database.getQueryLocator([Select Id, AccountID 
                                         from CASE 
                                         WHERE RecordType.Name = 'Foster Home 51A or Incident' 
                                         AND Investigation_Conclusion_Submitted_Date__c = NULL
                                         AND	Status != 'Closed' AND Status != 'Not Submitted'
                                         AND Incident_Reported_Date__c < LAST_N_DAYS:28
                                         AND ( Account.Last_Investigation_Conclusion_Notificati__c = NULL OR Account.Last_Investigation_Conclusion_Notificati__c < LAST_N_DAYS:28 )
                                         ]);
    }

    global void execute(Database.BatchableContext bc, List<Case> scope) {
    	
    	if(scope.Size()>0)
    	{
    		
    		Set<Id> setAccount = new Set<Id>();
        
	        for(Case c : scope)
	        {
	            setAccount.add(c.AccountId);
	        }
	       
	        List<Account> accountList = [SELECT ID,Notify_for_Investigation_Conclusion__c FROM Account WHERE ID in :setAccount];
	        
	        if(accountList.Size()>0)
	        {
	        	
	        	for(Account acc : accountList)
		        {
		            acc.Notify_for_Investigation_Conclusion__c = true;
		        }
		        
		        Database.update(accountList);
	        }
    	}
		
    }

    global void finish(Database.BatchableContext bc) {
		

    }



}