phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <recordTypes>
        <fullName>Small_Group</fullName>
        <active>true</active>
        <description>Small group and school age</description>
        <label>Small Group</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact_Role__c.object
<CustomObject>
    <description>This is a junction object between a provider and contact. A single contact may play multiple roles for a provider like Owner, Administrator etc.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Account to which the contact is associated with.</description>
        <label>Provider / Umbrella</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Roles</relationshipLabel>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Transaction_Attachments_New__c</fullName>
        <label>Transaction Attachments New</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Transaction_Attachments_Renewal__c</fullName>
        <label>Transaction Attachments Renewal</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Transaction_Attachments_Upgrade__c</fullName>
        <label>Transaction Attachments Upgrade</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>FCC_New_License</fullName>
        <active>true</active>
        <label>FCC New License</label>
    </recordTypes>
    <recordTypes>
        <fullName>R_P_Change_of_Admin_Authority</fullName>
        <active>true</active>
        <description>Request change in ownership or administrative designee for R&amp;P provider.</description>
        <label>R&amp;P Change of Admin Authority</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Provider_Meeting__c.object
<CustomObject>
    <label>Provider Meeting</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Provider Meeting No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_LicensingAttachmentControllertest.cls
@isTest
public class EEC_LicensingAttachmentControllertest {
    
    static testMethod void testEEC_LicensingAttachmentController() {
       
        Lead_Configuration__c config2 = EEC_TestUtil.mockLeadConfig('Small Group', null);
        config2.Transaction_Attachments_New__c = 'largetest';
        config2.Transaction_Attachments_Renewal__c = 'rentest';  
        config2.Transaction_Attachments_Upgrade__c = 'tatest';     
        config2.Name = 'Change of Address';
        update config2;
        
        Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), 'Test User', 'Fake Adres 123', 'Small_Group');
        accnt.Config_Record__c = config2.Id;     
        update accnt;   
     
      
        
      //	Licensing_Transaction__c lic = EEC_TestUtil.mockLicenseTransaction(accnt,'FCC_New_License');
       //	 lic.Status__c = 'Submitted';
          //update lic; 
         
        
        Contact contact = EEC_TestUtil.mockContact(accnt, 'Test', 'LastName', '');
        
        Contact_Role__c contactRole = EEC_TestUtil.mockContactRole('Partner', contact.Id, accnt.Id);
        contactRole = EEC_TestUtil.mockContactRole('Administrative Designee', contact.Id, accnt.Id);
        contactRole = EEC_TestUtil.mockContactRole('Program Director / Administrative Head', contact.Id, accnt.Id);
        contactRole = EEC_TestUtil.mockContactRole('Board Chair', contact.Id, accnt.Id); 
        contactRole = EEC_TestUtil.mockContactRole('Owner', contact.Id, accnt.Id);
        
        User portaluser = EEC_TestUtil.mockPortalUser (contact);
        
        
        EEC_BaseAttachmentsExtensionTest.loadMock();
        
        EEC_TestUtil.mockAWSKeys(); 
        
        Regulation__c reg = EEC_TestUtil.mockRegulation();  
        
        
        AWS_Config__c aws_config = new AWS_Config__c(S3_Bucket_Name__c = 'eec'); 
        insert aws_config; 
        
        Provider_Meeting__c  providermeeting  = EEC_TestUtil.mockGsaProviderMeeting();
      
        System.runAs(portaluser){
            test.startTest();
            EEC_LicensingAttachmentController mp = new EEC_LicensingAttachmentController();  
           // mp.doGetDocuments(); 
         //   mp.SaveAndNextAttachment();
          //	mp.UpdateDocument();
          //  mp.delAttachment();
           // mp.CancelTransaction() ;
           // mp.doUpdateComments();
           // mp.doUpdateComments();  
            //Licensing_Transaction__c lic = EEC_TestUtil.mockLicenseTransaction(accnt,'R_P_Change_of_Admin_Authority');
         	//lic.RecordTypeId = [Select Id,Name From RecordType Where sObjectType='Licensing_Transaction__c' and name='R_P_Change_of_Admin_Authority'].id;
              
          test.stopTest();
            
        }
    }/*
    static Account loadTestData(PageReference lPageRef,String buttonLabel, String index){
        Account accnt = EEC_TestUtil.loadLicenseTransaction();
        PageReference pageRef = lPageRef;
        pageRef.getParameters().put('accountId',accnt.Id);
        pageRef.getParameters().put('buttonLabel',buttonLabel);
        pageRef.getParameters().put('index',index);
        Test.setCurrentPage(pageRef);
        EEC_TestUtil.mockAWSKeys();
        return accnt;
    }
	 static testMethod void testGetAttachmentSpotlightText() {
      Test.startTest();
      Account accnt = loadTestData(Page.EEC_ReviewSummarySubmission,'Apply for License Renewal','1');
      EEC_LicensingAttachmentController controller = new EEC_LicensingAttachmentController();
         
     // Account accnts = [SELECT ID,OwnerId FROM Account WHERE RecordType.DeveloperName = 'FCC' AND Provider_Address_1__c != null LIMIT 1]; 
      
     // Licensing_Transaction__c lic = [select Id from Licensing_Transaction__c where Provider__c = :accnts.Id limit 1]; 
        
      
    }
   
*/
     
   
}