phase2_Dev/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_License_Number__c</fullName>
        <label>Current License Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Probationary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Prov. for Public Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Prov. for Public Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exempt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delegated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular Public Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <valueField>$Source.State__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/EEC_Lookup_Params__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to store custom query modifiers for the lookup controller when processing a Licensing Transaction. They are stored in Object value pairs with the new params.</description>
    <fields>
        <fullName>Like_Conditional_Operator__c</fullName>
        <defaultValue>&quot;OR&quot;</defaultValue>
        <description>This will be the static operator for the LIKE clause.</description>
        <inlineHelpText>This can only be OR or AND.</inlineHelpText>
        <label>Like Conditional Operator</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Like_Conditions__c</fullName>
        <defaultValue>&quot;Id&quot;</defaultValue>
        <description>This field will contain fields that need to be compared for the like conditional against the query string.</description>
        <inlineHelpText>This is a comma separated list of strings. Please ensure no spaces are present.</inlineHelpText>
        <label>Like Conditions</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order_Conditions__c</fullName>
        <defaultValue>&quot;Id DESC&quot;</defaultValue>
        <description>This field will contain the order by conditions for the query.</description>
        <label>Order Conditions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Query_Fields__c</fullName>
        <defaultValue>&quot;Id&quot;</defaultValue>
        <description>This field is to store all additional fields for the object to query.</description>
        <inlineHelpText>This can be any field on the object in question. Please ensure there are no spaces in this definition.</inlineHelpText>
        <label>Query Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Where_Conditions__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <description>This field is for all Where conditions required.</description>
        <label>Where Conditions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>sObject_Name__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <description>The sObject&apos;s name for the field coming into the lookup.</description>
        <label>sObject Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Lookup Query Definitions</label>
</CustomObject>

phase2_Dev/src/classes/EEC_LookupControllerTest.cls
@isTest
public class EEC_LookupControllerTest {
  @testSetup static void setup() {

  }

  public static testMethod void testConstructor() {
    EEC_LookupControllerTest.pageSetup();
    // Call the constructor.
    EEC_LookupController ctrl = new EEC_LookupController();
    System.assertEquals(ctrl.sObjectName, 'Account');  
  }

  public static testMethod void testQuery() {
    EEC_LookupControllerTest.pageSetup();
    EEC_LookupController ctrl = new EEC_LookupController();
    ctrl.sObjectName = null;
    System.assertEquals(null, ctrl.query());
  }

  private static void pageSetup() {
    // Setup an instance of the page. 
    PageReference page = new PageReference('Page.EEC_Lookup');
    Test.setCurrentPageReference(page);
    // Set the get params for the page.
    System.currentPageReference().getParameters().put('sobject', 'Account');
    System.currentPageReference().getParameters().put('sortfield', 'Name');
      
    EEC_Lookup_Params__c config = new EEC_Lookup_Params__c();
    config.Name = 'Account';
    config.Where_Conditions__c = 'RecordType.Name = \'FCC Assistant\'';
    config.sObject_Name__c = 'Account';
    config.Query_Fields__c = 'Name,CreatedDate,License_Status__c,Current_License_Number__c,Renewal_date__c,License_Type__c,Provider_City__r.Name';
    config.Order_Conditions__c = 'Created Date DESC';
    config.Like_Conditional_Operator__c = 'OR';
    config.Like_Conditions__c = 'Name,Current_License_Number__c,Provider_City__r.Name';
    insert config;
      
    
  }
}