phase2_Dev/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <valueField>$Source.State__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PPM_Language__c</fullName>
        <label>PPM Language</label>
        <picklist>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PPM_Participation_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PPM Participation Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Prospect PPM Participation Region</relationshipLabel>
        <relationshipName>PPM_Region_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>Must be &quot;MA&quot; (system will default to MA)</inlineHelpText>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Provider_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Meeting_Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region the meeting will be hold</description>
        <label>Meeting Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Provider Meetings</relationshipLabel>
        <relationshipName>Provider_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Status__c</fullName>
        <description>Status of the meeting</description>
        <label>Meeting Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open for registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed for registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <description>Type of meeting that will be conducted</description>
        <label>Meeting Type</label>
        <picklist>
            <picklistValues>
                <fullName>PPM (FCC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPM (GSA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal (GSA)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_of_seats_available__c</fullName>
        <description>Number of seats available. Will be set by default after creation of the record to the value from the Region</description>
        <label>No. of seats available</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheduled_End__c</fullName>
        <description>End Time of the meeting</description>
        <label>Scheduled End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start__c</fullName>
        <description>Start Time of the meeting</description>
        <label>Scheduled Start</label>
        <type>DateTime</type>
    </fields>
    <label>Provider Meeting</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Provider Meeting No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Provider_Meeting_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Meeting_Region__c</fullName>
        <formula>Provider_Meeting__r.Meeting_Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <formula>TEXT( Provider_Meeting__r.Meeting_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Meeting__c</fullName>
        <description>Meeting the participant is registered / attended to</description>
        <label>Provider Meeting</label>
        <referenceTo>Provider_Meeting__c</referenceTo>
        <relationshipLabel>Provider Meeting Participants</relationshipLabel>
        <relationshipName>Provider_Meeting_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Provider Meeting Participant</label>
    <nameField>
        <displayFormat>PMA-{0000000}</displayFormat>
        <label>Provider Meeting Participant No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City of the region office address</description>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <defaultValue>&quot;MA&quot;</defaultValue>
        <description>State of the region office address</description>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_PotentialProviderControllerTest.cls
@IsTest
public class EEC_PotentialProviderControllerTest {
    static testMethod void testEEC_PotentialProvider() {    	
    	Lead mLead = new Lead(FirstName = 'TestF', LastName = 'TestL', Status = 'Registered',
                       Company = 'Test Provider', Street_Address_1__c = '1st Street',
                       City__c = EEC_TestUtil.mockCity().Id, State__c = 'MA', Zip_code__c = '01803', 
                       Region__c = EEC_TestUtil.mockRegion().Id, 
                       PPM_Participation_Region__c = EEC_TestUtil.mockRegion().Id,
                       PPM_Language__c = 'test');
                       
        RecordType rt = [select Id from RecordType where Name = 'Potential Provider GSA' and SobjectType = 'Lead' limit 1];
    	
        mLead.RecordTypeId = rt.Id;
        insert mLead;
        
        Provider_Meeting__c providerMeeting = new Provider_Meeting__c(
                       Meeting_Region__c = EEC_TestUtil.mockRegion().Id, 
                       Meeting_Status__c ='Open for registration',
                       Meeting_Type__c = 'PPM (GSA)',
                       No_of_seats_available__c = 3,
                       Scheduled_Start__c = system.now() + 5,
                       Scheduled_End__c = system.now() + 7);
                       
    	insert providerMeeting;
    	
    	Provider_Meeting_Participant__c meetingParticipant = new Provider_Meeting_Participant__c(
    	Provider_Meeting__c = providerMeeting.Id,
    	Potential_Provider__c = mLead.Id,
    	Participation_Status__c = 'Registered'    	
    	);
    	
    	insert meetingParticipant;
    	
    	ApexPages.StandardController sc = new ApexPages.StandardController(mLead);
    	
    	test.startTest();
    	EEC_PotentialProviderController potentialProvider = new EEC_PotentialProviderController(sc);
    	potentialProvider.doCancel();
    	potentialProvider.contactFirstName = 'Test';
    	potentialProvider.contactLastName = 'Contact';
    	potentialProvider.doSave();
    	test.stopTest();
    }
    
    static testMethod void testEEC_PotentialProviderConvert() {    	
    	Lead mLead = new Lead(FirstName = 'TestF', LastName = 'TestL', Status = 'Registered',
                       Company = 'Test Provider', Street_Address_1__c = '1st Street',
                       City__c = EEC_TestUtil.mockCity().Id, State__c = 'MA', Zip_code__c = '01803', 
                       Region__c = EEC_TestUtil.mockRegion().Id, 
                       PPM_Participation_Region__c = EEC_TestUtil.mockRegion().Id,
                       PPM_Language__c = 'test');
                       
        RecordType rt = [select Id from RecordType where Name = 'Potential Provider GSA' and SobjectType = 'Lead' limit 1];
    	
        mLead.RecordTypeId = rt.Id;
        insert mLead;
        
        Provider_Meeting__c providerMeeting = new Provider_Meeting__c(
                       Meeting_Region__c = EEC_TestUtil.mockRegion().Id, 
                       Meeting_Status__c ='Open for registration',
                       Meeting_Type__c = 'PPM (GSA)',
                       No_of_seats_available__c = 3,
                       Scheduled_Start__c = system.now() + 5,
                       Scheduled_End__c = system.now() + 7);
                       
    	insert providerMeeting;
    	
    	Provider_Meeting_Participant__c meetingParticipant = new Provider_Meeting_Participant__c(
    	Provider_Meeting__c = providerMeeting.Id,
    	Potential_Provider__c = mLead.Id,
    	Participation_Status__c = 'Registered'    	
    	);
    	
    	insert meetingParticipant;
    	
    	ApexPages.StandardController sc = new ApexPages.StandardController(mLead);
    	
    	test.startTest();
    	EEC_PotentialProviderController potentialProvider = new EEC_PotentialProviderController(sc);
    	potentialProvider.doCancel();
    	potentialProvider.contactFirstName = 'Test';
    	potentialProvider.contactLastName = 'Contact';
    	potentialProvider.doSave();
    	
    	Database.LeadConvert lc = new database.LeadConvert();
		lc.setLeadId(mLead.id);
		
		LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
		lc.setConvertedStatus(convertStatus.MasterLabel);
		
		Database.LeadConvertResult lcr = Database.convertLead(lc);
		
    	test.stopTest();
    }
}