phase2_Dev/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Restraint_Report__c.object
<CustomObject>
    <description>For R&amp;P, this object is used to capture DYS and Other types of Restraints. There will be a look up relationship from Restraint Report Object to Provider Object.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Look up relationship from Restraint Report to Provider</description>
        <inlineHelpText>Look up relationship from Restraint Report to Provider</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Restraint Reports</relationshipLabel>
        <relationshipName>Restraint_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Restraint Report</label>
    <nameField>
        <displayFormat>RR-{00000}</displayFormat>
        <label>Report ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restraint Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_RestraintReportTest.cls
@IsTest public class EEC_RestraintReportTest {
    @isTest static void testEEC_RestraintReportTest () {
        City__c c = EEC_TestUtil.mockCity();
        Account a = EEC_TestUtil.mockProvider(c);
        Contact con = EEC_TestUtil.mockDirectorContact(a);
        
        ApexPages.currentPage().getParameters().put('accountId',a.Id);
        
        Restraint_Report__c restraintReport = new Restraint_Report__c();
        restraintReport.Provider__c = a.Id;
        insert restraintReport;
        
         test.startTest();
         EEC_RestraintReport p1 = new EEC_RestraintReport();
         p1.contact = con;
         p1.getRestraintReport(string.valueOf(a.id));
         p1.getRestraintReportByID(restraintReport.id);
         test.stopTest();
    }
    
    @isTest  static  void save() {
        City__c c = EEC_TestUtil.mockCity();
        Account a = EEC_TestUtil.mockProvider(c);
        ApexPages.currentPage().getParameters().put('accountId',a.Id);
        ApexPages.currentPage().getParameters().put('member',a.Id);
        test.startTest();
        EEC_RestraintReport p1 = new EEC_RestraintReport();
        User user = [SELECT ContactId FROM User WHERE Id =: userinfo.getuserid()];
        p1.restraintAccountID = a.Id;
        p1.Contact_Submitted_By = userInfo.getUserName();
        p1.CreatedById = userInfo.getUserId();
        p1.Provider = a.Name;
        p1.Submitted_Date = date.today();
        p1.Total_Injured = 10;        
        p1.getRestraintReport(string.valueOf('0011100000vwa1WAAQ'));
        p1.getRestraintReportByID(string.valueOf('0011100000vwa1WAAQ'));
        p1.save();
        p1.returnProvider();
        test.stopTest();
    }
}