phase2_Dev/src/objects/Component__c.object
<CustomObject>
    <fields>
        <fullName>DeveloperName__c</fullName>
        <label>Developer Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Grouping</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Form__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>UUID</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/FormComponent__c.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Form Components</relationshipLabel>
        <relationshipName>FormComponents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FormVersion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Form Version</label>
        <referenceTo>FormVersion__c</referenceTo>
        <relationshipLabel>Form Components</relationshipLabel>
        <relationshipName>FormComponents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order that this component should be rendered as related to its siblings.</description>
        <label>Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT( Component__r.Type__c )</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>A UUID for the Form Component. It should not be changed once set.</description>
        <label>UUID</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Form Component</label>
    <nameField>
        <displayFormat>FC-{0}</displayFormat>
        <label>Form Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/FormVersion__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Form that this Form Version belongs to.</description>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Versions</relationshipLabel>
        <relationshipName>FormVersions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>UUID</label>
        <length>36</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Form Version</label>
    <nameField>
        <label>Form Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/ProcessingStep__c.object
<CustomObject>
    <fields>
        <fullName>Config__c</fullName>
        <description>Configuration for the Processing Step.</description>
        <label>Config</label>
        <length>8192</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FormVersion__c</fullName>
        <label>Form Version</label>
        <referenceTo>FormVersion__c</referenceTo>
        <relationshipLabel>Processing Steps</relationshipLabel>
        <relationshipName>Processing_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Type</label>
        <referenceTo>ProcessingStepType__c</referenceTo>
        <relationshipLabel>Processing Steps</relationshipLabel>
        <relationshipName>ProcessingSteps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Processing Step</label>
    <nameField>
        <label>Processing Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processing Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/ProcessingStepType__c.object
<CustomObject>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>ClassName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Post</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Processing Step Type</label>
    <nameField>
        <label>Processing Step Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processing Step Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/BatchTestUtil.cls
public with sharing class BatchTestUtil {
  public BatchTestUtil() {
    
  }

  public static FormVersion__c loadData() {
    Form__c testForm = new Form__c(Name = 'Test Form',UUID__c = '123');
    insert testForm;

    FormVersion__c testFormVersion = new FormVersion__c(Form__c = testForm.Id, Status__c='Draft', UUID__c = '1234');
    insert testFormVersion;

    Component__c c1 = new Component__c(Name = 'TestComponent', DeveloperName__c = 'test');
    insert c1;

    FormComponent__c fc1 = new FormComponent__c(Component__c = c1.Id, FormVersion__c = testFormVersion.Id, Order__c = 0, UUID__c = '123456');
    FormComponent__c fc2 = new FormComponent__c(Component__c = c1.Id, FormVersion__c = testFormVersion.Id, Order__c = 1, UUID__c = '1234567');
    List<FormComponent__c> fcList = new List<FormComponent__c>{fc1, fc2};
    insert fcList;

    ProcessingStepType__c pst1 = new ProcessingStepType__c(Type__c = 'Pre', ClassName__c = 'ProcessingStepValue');
    insert pst1;

    ProcessingStepType__c pst2 = new ProcessingStepType__c(Type__c = 'Post', ClassName__c = 'ProcessingStepObjMapping');
    insert pst2;

    ProcessingStep__c psPre1 = new ProcessingStep__c(Type__c = pst1.Id, Order__c = 0, FormVersion__c = testFormVersion.Id, Config__c = '{"' + fc1.Id + '":{"type":"value","value":"New"}, "' + fc2.Id + '":{"type":"value","value":"Web"}}');
    insert psPre1;

    ProcessingStep__c psPost1 = new ProcessingStep__c(Type__c = pst2.Id, Order__c = 0, FormVersion__c = testFormVersion.Id, Config__c = '{"case1": {"type": "Case","mappings": [{"destination":"Status","formComponentId": "' + fc1.Id + '"},{"destination": "Origin", "formComponentId": "' + fc2.Id + '" }]}}');
    insert psPost1;

    return testFormVersion;
  }
}