phase2_Dev/src/objects/Component__c.object
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/ComponentProperty__c.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Component Properties</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Component Property</label>
    <nameField>
        <displayFormat>CP-{0}</displayFormat>
        <label>Component Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/IFFPackageInformation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ObjectsVersion__c</fullName>
        <label>Objects Version</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IFF Package Information</label>
</CustomObject>

phase2_Dev/src/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/Test_IFFInstallHandler.cls
@isTest
public class Test_IFFInstallHandler {
    
    @isTest
    static void testV0() {
        IFFInstallHandler.v0(IFFPackageInformation__c.getOrgDefaults());
        
        IFFPackageInformation__c info = IFFPackageInformation__c.getOrgDefaults();
        
        System.assertEquals(info.ObjectsVersion__c, 0);
    }
     
     
    @isTest
    static void testUpgrade() {
        IFFPackageInformation__c info = IFFPackageInformation__c.getOrgDefaults();
        info.ObjectsVersion__c = 0;
        insert info;
        
        IFFInstallHandler.upgrade(info);
        
        info = IFFPackageInformation__c.getOrgDefaults();
        
        System.assertEquals(info.ObjectsVersion__c, 1);
        System.assertEquals([SELECT ID From Component__c].size(), 20);
        System.assertEquals([SELECT ID From Property__c].size(), 6);
        System.assertEquals([SELECT ID From ComponentProperty__c].size(), 41);
    }
}