phase2_Dev/src/objects/Conditions_and_Limitations__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Additional_Information__c</fullName>
        <inlineHelpText>To be filled if the standard condition selected needs some additional information (ex: Other). The content of this field will replace #Add_Info# tag in the standard condition</inlineHelpText>
        <label>Condition Additional Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Condition_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Name</label>
        <referenceTo>Condition__c</referenceTo>
        <relationshipLabel>Conditions and Limitations</relationshipLabel>
        <relationshipName>Conditions_and_Limitations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Condition_On_License__c</fullName>
        <formula>IF ( FIND(&quot;#Effective_Date#&quot;,  Condition_Name__r.Full_Description__c ) &lt;&gt; 0,  

SUBSTITUTE(IF (FIND(&quot;#Add_Info#&quot;, Condition_Name__r.Full_Description__c ) &lt;&gt; 0, SUBSTITUTE(Condition_Name__r.Full_Description__c, &quot;#Add_Info#&quot;,  Condition_Additional_Information__c ), Condition_Name__r.Full_Description__c), &quot;#Effective_Date#&quot;,  TEXT(MONTH( Start_Date__c ))+&quot;/&quot; +TEXT(DAY( Start_Date__c ))+&quot;/&quot; +TEXT(YEAR( Start_Date__c ))),  

IF (FIND(&quot;#Add_Info#&quot;, Condition_Name__r.Full_Description__c ) &lt;&gt; 0, SUBSTITUTE(Condition_Name__r.Full_Description__c, &quot;#Add_Info#&quot;,  Condition_Additional_Information__c ), Condition_Name__r.Full_Description__c))</formula>
        <inlineHelpText>Condition as it will be displayed on the license</inlineHelpText>
        <label>Condition Full Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conditions__c</fullName>
        <label>Conditions</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <formula>AND( Start_Date__c &lt;=  TODAY(),
OR(
ISBLANK(Expiration_Date__c), 
 Expiration_Date__c  &gt;= TODAY())
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Conditions and Limitations</relationshipLabel>
        <relationshipName>Conditions_and_Limitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Transaction</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Transaction selected must be associated to the provider this condition applies.</errorMessage>
            <filterItems>
                <field>Licensing_Transaction__c.Provider__c</field>
                <operation>equals</operation>
                <valueField>$Source.Provider__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Conditions and Limitations</relationshipLabel>
        <relationshipName>Conditions_and_Limitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Conditions and Limitations</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions and Limitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Transaction Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Variance_on_Regulation__c.object
<CustomObject>
    <description>Variance on regulation can be requested by a provider when it can not be in compliance with a specific regulation. Every variance should be associated to 1 reg.</description>
    <fields>
        <fullName>Associated_Regulation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Regulation</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Regulation__c.Date_Active__c</field>
                <operation>lessOrEqual</operation>
                <valueField>$Source.Date_today__c</valueField>
            </filterItems>
            <filterItems>
                <field>Regulation__c.Date_Removed__c</field>
                <operation>greaterOrEqual</operation>
                <valueField>$Source.Date_today__c</valueField>
            </filterItems>
            <filterItems>
                <field>Regulation__c.Date_Removed__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Variance on Regulations</relationshipLabel>
        <relationshipName>Variance_on_Regulations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brief_explanation_for_license__c</fullName>
        <label>Brief explanation for license</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <formula>IF( ISBLANK(Expiration_Date__c ) || TODAY() &gt; Expiration_Date__c || TODAY() &lt; Date_Granted__c , False, IF(ISPICKVAL(Source_Transaction__r.Status__c, &quot;Closed (License Issued / Updated)&quot;) || ISPICKVAL(Source_Transaction__r.Status__c, &quot;Closed (Processed)&quot;), True, False))</formula>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Decision</label>
        <picklist>
            <picklistValues>
                <fullName>Granted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <formula>IF( AND(ISPICKVAL( Decision__c , &quot;Granted&quot;), ISPICKVAL(Source_Transaction__r.Status__c, &quot;Closed (License Issued / Updated)&quot;) || ISPICKVAL(Source_Transaction__r.Status__c, &quot;Closed (Processed)&quot;)) ,  Source_Transaction__r.License_Expiration_Date__c  ,null )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Variance on Regulations</relationshipLabel>
        <relationshipName>Variance_on_Regulations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_Transaction__c</fullName>
        <label>Source Transaction</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Licensing_Transaction__c.Provider__r.Id</field>
                <operation>equals</operation>
                <value>Variance on Regulation: Provider</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Variance on Regulations</relationshipLabel>
        <relationshipName>Variance_on_Regulations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Variance on Regulation</label>
    <nameField>
        <displayFormat>VAR- {000000}</displayFormat>
        <label>Variance No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Variance on Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_LicensingCertificatePDFExtension.cls
public class EEC_LicensingCertificatePDFExtension {
    
    protected final Licensing_Transaction__c trans;
    public Licensing_Transaction__c lt {get;set;}
    public List<Conditions_and_Limitations__c> lstConditions {get;set;}
    public Boolean HasConditions {get;set;}
        public Boolean HasVariance {get;set;}

    public List<Variance_on_Regulation__c> lstVariance {get;set;}

    public EEC_LicensingCertificatePDFExtension(ApexPages.StandardController ctr){
        this.trans = (Licensing_Transaction__c) ctr.getRecord();
        getProviderConditions();
        getVarianceOnReg();
    }
    
    public List<Conditions_and_Limitations__c> getProviderConditions()
    {
        Licensing_Transaction__c lt = [SELECT Id,Capacity__c, Date_Closed__c FROM Licensing_Transaction__c
                                      WHERE Id =: trans.Id];
        lstConditions = [SELECT Conditions__c,Condition_Additional_Information__c,
                         Condition_Name__c,Condition_On_License__c,CreatedById,
                         CreatedDate,Current__c,Expiration_Date__c,Id,
                         Name,Provider__c,Source_Transaction__c,
                         Start_Date__c FROM Conditions_and_Limitations__c 
                         WHERE Provider__c =: trans.Provider__c 
                         AND 
                         (
                             (Start_Date__c <=: lt.Date_Closed__c AND Expiration_Date__c >=: lt.Date_Closed__c) 
                          OR 
                             (Expiration_Date__c = null AND Start_Date__c <=: lt.Date_Closed__c)
                         )];
        HasConditions=!lstConditions.isEmpty();
        
        return lstConditions;
    }
    
    public list<Variance_on_Regulation__c> getVarianceOnReg()
    {
        Licensing_Transaction__c lt = [SELECT Id,Capacity__c, Date_Closed__c FROM Licensing_Transaction__c
                                      WHERE Id =: trans.Id];
        
        lstVariance = [SELECT Decision__c, Brief_explanation_for_license__c, Source_Transaction__c, Provider__c, Id, 
                       Associated_Regulation__r.Name
                       FROM Variance_on_Regulation__c 
                       WHERE Provider__c =: trans.Provider__c
                       AND (Decision__c = 'Granted')
                      ];
        
        HasVariance=  !lstVariance.isEmpty();
              
        return lstVariance;
        
    }
}