phase2_Dev/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Program Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Historical_Staff_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Assigned__c</fullName>
        <label>Date Assigned</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duplicate_Rule__c</fullName>
        <formula>Intake_Id__c + &apos;|&apos; + Program_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Rule</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Text__c</fullName>
        <label>Error Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Intake_Id__c</fullName>
        <label>Intake Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licensor_Name__c</fullName>
        <label>Licensor Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licensor_Number__c</fullName>
        <label>Licensor Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Id__c</fullName>
        <label>Program Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Staff Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Number__c</fullName>
        <label>Total Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Historical Staff Staging</label>
    <nameField>
        <displayFormat>HS-{0000000}</displayFormat>
        <label>Historical Staff Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Staff Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_Batch_ProcessLegacyStaff.cls
global class EEC_Batch_ProcessLegacyStaff implements Database.Batchable<sObject> {
	
	
    
    global List<Historical_Staff_Staging__c> dataListSize = null;
      
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([Select Id,name,Active__c,Date_Assigned__c,Duplicate_Rule__c,Error_Text__c,Intake_Id__c,Licensor_Name__c,Licensor_Number__c,Program_Id__c,Role__c,Staff_Processed__c,Total_Number__c
                                         From Historical_Staff_Staging__c WHERE Staff_Processed__c = false]);
        
    }

    global void execute(Database.BatchableContext BC,List<Historical_Staff_Staging__c> scope){
    	
        dataListSize = scope;
        
        for(Historical_Staff_Staging__c v : scope){
        	 EEC_ProcessLegacyInvestigationData.processLegacyStaff(v);
        }
        update scope; 
        
    }

    global void finish(Database.BatchableContext BC){
    	
    	try{ 
	    	if(dataListSize != null){
		    	AsyncApexJob batchJob = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
	       
		        Integer jobs = [Select count() From AsyncApexJob Where JobType = 'BatchApex' and ( Status = 'Queued' or Status = 'Processing' or Status = 'Preparing' )];   
		        
		        if(jobs <= 1){
		            EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyStaff'); 
		        }
		
		        //If NumberOfErrors is "0" - if the execute method processed all records without errors - then call next contact batch.
			    if (batchJob.NumberOfErrors == 0)
			    {     
			        EEC_Batch_ProcessLegacyStaff batchLegacyStaff = new EEC_Batch_ProcessLegacyStaff();   
			        Id batchProcessId = Database.executeBatch(batchLegacyStaff,1);    //finish method logic here
			    }
			    else
			    {
			        //process other code
			        if ((batchJob.NumberOfErrors == 0) && (jobs < 5)){
		
		        		 EEC_Batch_ProcessLegacyStaff batchLegacyStaff = new EEC_Batch_ProcessLegacyStaff();   
			             Id batchProcessId = Database.executeBatch(batchLegacyStaff,1);    //finish method logic here
		         		}
		        	else{
		         		//wait for 1 hour
		          	}
			    }
	         }
	         else{
	         	EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyStaff'); 
	         }
    	}
    	catch(exception ex){
    		System.debug('----> Error Processing the EEC_Batch_ProcessLegacyStaff job: ' + ex.getMessage());
    	}
    }

	
    
}