phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Historical_Investigation_Staging__c.object
<CustomObject>
    <fields>
        <fullName>AG1__c</fullName>
        <label>AG1</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AG2__c</fullName>
        <label>AG2</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AG3__c</fullName>
        <label>AG3</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agencies_Involved__c</fullName>
        <formula>IF(OR(AG1__c = &quot;None&quot;,ISBLANK(AG1__c)),&quot;&quot;,AG1__c)  + &quot;;&quot; +   IF(OR(AG2__c = &quot;None&quot;,ISBLANK(AG2__c)),&quot;&quot;,AG2__c) + &quot;;&quot; +   IF(OR(AG3__c = &quot;None&quot;,ISBLANK(AG3__c)),&quot;&quot;,AG3__c)</formula>
        <label>Agencies Involved</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assign_Date__c</fullName>
        <label>Assign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_Due_Days__c</fullName>
        <label>Corrective Action Due Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_CC_List__c</fullName>
        <label>Cover Letter Custom CC List</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_From_Name__c</fullName>
        <label>Cover Letter Custom From Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_From_Title__c</fullName>
        <label>Cover Letter Custom From Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_Text__c</fullName>
        <label>Cover Letter Custom Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_To_Name__c</fullName>
        <label>Cover Letter Custom To Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duplicate_Rule__c</fullName>
        <formula>Intake_Id__c + &apos;|&apos; + Program_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Rule</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Text__c</fullName>
        <label>Error Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Filed_with_51A__c</fullName>
        <label>Filed with 51A</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intake_Id__c</fullName>
        <label>Intake Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation_Number__c</fullName>
        <label>Investigation Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Investigation Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Leader__c</fullName>
        <label>Leader</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Id__c</fullName>
        <label>Program Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_to_51A__c</fullName>
        <label>Related to 51A</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Historical Investigation Staging</label>
    <nameField>
        <displayFormat>HI-{0000000}</displayFormat>
        <label>Historical Investigation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Investigation Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_Batch_ProcessLegacyInvestigations.cls
global class EEC_Batch_ProcessLegacyInvestigations implements Database.Batchable<sObject>{
    
    global List<Historical_Investigation_Staging__c> dataListSize = null;
      
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([Select Id,name,Investigation_Processed__c,Error_Text__c,AG1__c,AG2__c,AG3__c,Assign_Date__c,Corrective_Action_Due_Days__c,Cover_Letter_Custom_CC_List__c,
                                         Cover_Letter_Custom_From_Name__c,Cover_Letter_Custom_From_Title__c,Cover_Letter_Custom_Text__c,Cover_Letter_Custom_To_Name__c,Due_Date__c,
                                         Duplicate_Rule__c,Filed_with_51A__c,Intake_Id__c,Investigation_Number__c,Agencies_Involved__c,Leader__c,Program_Id__c,Related_to_51A__c
                                         From Historical_Investigation_Staging__c WHERE Investigation_Processed__c = false]);
        
    }

    global void execute(Database.BatchableContext BC,List<Historical_Investigation_Staging__c> scope){
    	
        dataListSize = scope;
        
        for(Historical_Investigation_Staging__c v : scope){
        	 EEC_ProcessLegacyInvestigationData.processLegacyInvestigations(v);
        }
        update scope; 
        
    }

    global void finish(Database.BatchableContext BC){
    	
    	try{
	    	if(dataListSize != null){
		    	AsyncApexJob batchJob = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
	       
		        Integer jobs = [Select count() From AsyncApexJob Where JobType = 'BatchApex' and ( Status = 'Queued' or Status = 'Processing' or Status = 'Preparing' )];   
		        
		        if(jobs <= 1){
		            EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyInvestigations'); 
		        }
		
		        //If NumberOfErrors is "0" - if the execute method processed all records without errors - then call next contact batch.
			    if (batchJob.NumberOfErrors == 0)
			    {     
			        EEC_Batch_ProcessLegacyInvestigations batchLegacyInv = new EEC_Batch_ProcessLegacyInvestigations();   
			        Id batchProcessId = Database.executeBatch(batchLegacyInv,1);    //finish method logic here
			    }
			    else
			    {
			        //process other code
			        if ((batchJob.NumberOfErrors == 0) && (jobs < 5)){
		
		        		 EEC_Batch_ProcessLegacyInvestigations batchLegacyInv = new EEC_Batch_ProcessLegacyInvestigations();   
			             Id batchProcessId = Database.executeBatch(batchLegacyInv,1);    //finish method logic here
		         		}
		        	else{
		         		//wait for 1 hour
		          	}
			    }
	         }
	         else{
	         	EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyInvestigations'); 
	         }
    	}
    	catch(exception ex){
    		System.debug('----> Error Processing the EEC_Batch_ProcessLegacyInvestigations job: ' + ex.getMessage());
    	}
    }

}