phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Historical_Follow_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duplicate_Rule__c</fullName>
        <formula>Intake_Id__c + &apos;|&apos; + Program_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Rule</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Text__c</fullName>
        <label>Error Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FollowUp_Code__c</fullName>
        <label>FollowUp Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUp_Id__c</fullName>
        <label>FollowUp Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Follow_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Follow Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intake_Id__c</fullName>
        <label>Intake Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Issue_Date__c</fullName>
        <label>Legal Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Licensor_Name__c</fullName>
        <label>Licensor Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licensor__c</fullName>
        <label>Licensor</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Modification_Date__c</fullName>
        <label>Modification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Id__c</fullName>
        <label>Program Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refer_to_Legal_Date__c</fullName>
        <label>Refer to Legal Date</label>
        <type>Date</type>
    </fields>
    <label>Historical Follow Staging</label>
    <nameField>
        <displayFormat>HF-{0000000}</displayFormat>
        <label>Historical Follow Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Follow Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_Batch_ProcessLegacyFollow.cls
global class EEC_Batch_ProcessLegacyFollow implements Database.Batchable<sObject>{
    
    global List<Historical_Follow_Staging__c> dataListSize = null;
      
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([Select Id,name,Follow_Processed__c,Completed_Date__c,Due_Date__c,Created_Date__c,Description__c,Error_Text__c,FollowUp_Code__c,FollowUp_Id__c,Intake_Id__c,
                                         Legal_Issue_Date__c,Licensor__c,Licensor_Name__c,Modification_Date__c,Program_Id__c,Refer_to_Legal_Date__c,Duplicate_Rule__c
                                         From Historical_Follow_Staging__c WHERE Follow_Processed__c = false]);
        
    }

    global void execute(Database.BatchableContext BC,List<Historical_Follow_Staging__c> scope){
        
        dataListSize = scope;
        
        for(Historical_Follow_Staging__c v : scope){
             EEC_ProcessLegacyInvestigationData.processLegacyFollow(v);
        }
        update scope; 
        
    }

    global void finish(Database.BatchableContext BC){
        
        try{ 
            if(dataListSize != null){
                AsyncApexJob batchJob = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
           
                Integer jobs = [Select count() From AsyncApexJob Where JobType = 'BatchApex' and ( Status = 'Queued' or Status = 'Processing' or Status = 'Preparing' )];   
                
                if(jobs <= 1){
                    EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyFollow'); 
                }
        
                //If NumberOfErrors is "0" - if the execute method processed all records without errors - then call next contact batch.
                if (batchJob.NumberOfErrors == 0)
                {     
                    EEC_Batch_ProcessLegacyFollow batchLegacyFollow = new EEC_Batch_ProcessLegacyFollow();   
                    Id batchProcessId = Database.executeBatch(batchLegacyFollow,1);    //finish method logic here
                }
                else
                {
                    //process other code
                    if ((batchJob.NumberOfErrors == 0) && (jobs < 5)){
        
                         EEC_Batch_ProcessLegacyFollow batchLegacyFollow = new EEC_Batch_ProcessLegacyFollow();   
                         Id batchProcessId = Database.executeBatch(batchLegacyFollow,1);    //finish method logic here
                        }
                    else{
                        //wait for 1 hour
                    }
                }
             }
             else{
                EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyFollow'); 
             }
        }
        catch(exception ex){
            System.debug('----> Error Processing the EEC_Batch_ProcessLegacyFollow job: ' + ex.getMessage());
        }
    }
    
}