phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Historical_Unlicen_Providers_Staging__c.object
<CustomObject>
    <fields>
        <fullName>ErrorText__c</fullName>
        <label>ErrorText</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Provider Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unlicensed_Address1__c</fullName>
        <label>Unlicensed Address1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unlicensed_City__c</fullName>
        <label>Unlicensed City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unlicensed_ID__c</fullName>
        <label>Unlicensed ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unlicensed_Licensor_Name__c</fullName>
        <label>Unlicensed Licensor Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unlicensed_Licensor__c</fullName>
        <label>Unlicensed Licensor</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unlicensed_Name__c</fullName>
        <label>Unlicensed Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unlicensed_Phone__c</fullName>
        <label>Unlicensed Phone</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unlicensed_ZipCode__c</fullName>
        <label>Unlicensed ZipCode</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Historical Unlicen Providers Staging</label>
    <nameField>
        <displayFormat>LP-{0000000}</displayFormat>
        <label>Legacy Unlicensed Provider Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Unlicen Providers Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_Batch_ProcessLegacyUnlicencdProvider.cls
//Author - Latha Davuluri
//Batch job to process Legacy Cases - LEAD-4375

global class EEC_Batch_ProcessLegacyUnlicencdProvider implements Database.Batchable<sObject>{

    global List<Historical_Unlicen_Providers_Staging__c> dataListSize = null;
      
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([Select Id, Name, Unlicensed_Name__c, Unlicensed_Address1__c, Unlicensed_City__c, Unlicensed_ZipCode__c, Unlicensed_Phone__c, Unlicensed_ID__c, Unlicensed_Licensor__c, Unlicensed_Licensor_Name__c, ErrorText__c, Provider_Processed__c From Historical_Unlicen_Providers_Staging__c h WHERE h.Provider_Processed__c = false]);        
    }

    global void execute(Database.BatchableContext BC,List<Historical_Unlicen_Providers_Staging__c> scope){
    	
        dataListSize = scope;
        
        for(Historical_Unlicen_Providers_Staging__c v : scope){
       	   EEC_ProcessLegacyCaseData.processLegacyUnlicensdProviders(v);
        }
        update scope; 
        
    }

    global void finish(Database.BatchableContext BC){
    	
    	try{
	    	if(dataListSize != null){
		    	AsyncApexJob batchJob = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
	       
		        Integer jobs = [Select count() From AsyncApexJob Where JobType = 'BatchApex' and ( Status = 'Queued' or Status = 'Processing' or Status = 'Preparing' )];   
		        
		        if(jobs <= 1){
		            EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyUnlicencdProvider'); 
		        }
		
		        //If NumberOfErrors is "0" - if the execute method processed all records without errors - then call next contact batch.
			    if (batchJob.NumberOfErrors == 0)
			    {     
			        EEC_Batch_ProcessLegacyUnlicencdProvider batchLegacyProviders = new EEC_Batch_ProcessLegacyUnlicencdProvider();   
			        Id batchProcessId = Database.executeBatch(batchLegacyProviders,1);    //finish method logic here
			    }
			    else
			    {
			        //process other code
			        if ((batchJob.NumberOfErrors == 0) && (jobs < 5)){
		
		        		 EEC_Batch_ProcessLegacyUnlicencdProvider batchLegacyProviders = new EEC_Batch_ProcessLegacyUnlicencdProvider();   
			             Id batchProcessId = Database.executeBatch(batchLegacyProviders,1);    //finish method logic here
		         		}
		        	else{
		         		//wait for 1 hour
		          	}
			    }
	         }
	         else{
	         	EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyUnlicencdProvider'); 
	         }
    	}
    	catch(exception ex){
    		System.debug('----> Error Processing the EEC_Batch_ProcessLegacyUnlicencdProvider job: ' + ex.getMessage());
    	}
    }

}