phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Assessed_Date__c</fullName>
        <inlineHelpText>Date the visit item was assessed (= mark compliant / non compliant / not applicable) by the licensor. This date is automatically filled by the system when a result is added for the first time.</inlineHelpText>
        <label>Assessed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Category_additional__c</fullName>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care of Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Child Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Home Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General records/logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health/Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy System Non Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personnel Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Indoors</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TestInvGenerateCoverLetterExtension.cls
@isTest
public with sharing class EEC_TestInvGenerateCoverLetterExtension {
    
    @isTest 
    static void testGetDirectorContact() { 
        Account a = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
      // Contact c = EEC_TestUtil.mockDirectorContact(a);
        //AccountContactRole acr = EEC_TestUtil.mockAccountContactRole('Director', c, a);
        Investigation__c i = EEC_TestUtil.mockInvestigation(a);
        
        EEC_GenerateInvCoverLetterExtension ext = new EEC_GenerateInvCoverLetterExtension  (new ApexPages.StandardController(i));
         
        Contact co = ext.getDirectorContact();
                 
       // System.assertEquals(c.FirstName, co.FirstName);
      //  System.assertEquals(c.LastName, co.LastName); 
      //  System.assertEquals(c.Salutation, co.Salutation); 
        
        ext.getOldestCaseDate();
        ext.getCaseNumbers();
        ext.getProviderName();
        ext.getInvestigationNumber();
        ext.getOustandingComplianceIssues();
        ext.getInspecitonItems();
        
    }
    @isTest 
    static void InvestigationVisitChecklistItemWrappertest() { 
      /*
            Inspection__c insp = EEC_TestUtil.loadInspectionSetup(); 
         Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
       Inspection_Item__c it1 = new Inspection_Item__c();
          DATE d1 = date.today();
        Date d2 = d1.addMonths(- 11);
        Recordtype rt = [select id,name from Recordtype where  (name = 'Standard Visit Item' OR name = 'Legacy System Import Visit / Non Compliance') AND SobjectType = 'Inspection_Item__c' ];
       // it1.RecordTypeId = rt.id;  
        it1.RecordTypeId  = Schema.SObjectType.Inspection_Item__c.getRecordTypeInfosByName().get('Standard Visit Item').getRecordTypeId();
        it1.Inspection_No__c = insp.id;
        it1.Inspection_Result__c = 'Non-Compliant';     
        it1.Observations__c = 'rtry';
        it1.Standard_Inspection_Item__c = stdIi.id;   
        it1.Assessed_Date__c = d2; 
        it1.Category_additional__c = 'Administration';
        
        Inspection_Item__c it2 = new Inspection_Item__c();
        Recordtype rt1 = [select id,name from Recordtype where  (name = 'Standard Visit Item' OR name = 'Legacy System Import Visit / Non Compliance') AND SobjectType = 'Inspection_Item__c' ];
        it2.RecordTypeId = rt.id;   
        it2.RecordTypeId  = Schema.SObjectType.Inspection_Item__c.getRecordTypeInfosByName().get('Non Standard Visit Item').getRecordTypeId();
        it2.Inspection_No__c = insp.id;  
        it2.Inspection_Result__c = 'Not Applicable';   
        it2.Observations__c = 'rty'; 
        it2.Standard_Inspection_Item__c = stdIi.id;   
        it2.Category_additional__c = 'Adoptive Children Records';
        
        List<Inspection_Item__c> ls1 = new List<Inspection_Item__c> (); 
        ls1.add(it1); 
        ls1.add(it2);
        
        insert ls1;   
        
       */
    }
}