phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Contact_Role__c.object
<CustomObject>
    <description>This is a junction object between a provider and contact. A single contact may play multiple roles for a provider like Owner, Administrator etc.</description>
    <label>Contact Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Transaction_Document__c.object
<CustomObject>
    <description>A junction between the Document and a transaction.</description>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Role</label>
        <referenceTo>Contact_Role__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Licensing_Transaction__c</fullName>
        <label>Licensing Transaction</label>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Document</label>
    <nameField>
        <displayFormat>TD- {0000000}</displayFormat>
        <label>Transaction Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_ContactRoleUtil.cls
public without sharing class EEC_ContactRoleUtil{

    public static list<Contact> insertContact(list<Contact> contactListtoInsert){
        insert contactListtoInsert;
        return contactListtoInsert;
    }
    
    public static list<Contact> updateContact(list<Contact> contactListtoUpdate){
        update contactListtoUpdate;
        return contactListtoUpdate;
    }
    public static list<Contact_Role__c> upsertContactRole(list<Contact_Role__c> listContactRole){
        upsert listContactRole;
        return listContactRole;
    }
    public static void deleteContactRole(list<Contact_Role__c> listContactRole){
        delete listContactRole;
    }
    public static void  upsertTransactionDocument(List<Transaction_Document__c>  listdocs){
        upsert listdocs;
    }

    public static void deleteTransactionDocument(Transaction_Document__c tdocument){
        delete tdocument;
    }
    
    public static void deleteTransactionDocuments(List<Transaction_Document__c> listdocument){
        delete listdocument;
    }
    
    public static Licensing_Transaction__c updateLicensingTransaction(Licensing_Transaction__c licenseTransaction){
        update licenseTransaction;
        return licenseTransaction;
    }
}