phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Historical_Cases_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Description__c</fullName>
        <label>Additional Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Allegation_Code__c</fullName>
        <label>Allegation Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allegation_Description__c</fullName>
        <label>Allegation Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case_Owner_Name__c</fullName>
        <label>Case Owner Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Owner__c</fullName>
        <label>Case Owner</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true if the legacy case was successfully processed</description>
        <label>Case Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complaint_Disposition__c</fullName>
        <label>Complaint Disposition</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DCF_File_Submission_Date__c</fullName>
        <label>DCF File Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DCF_File_Submitter__c</fullName>
        <label>DCF File Submitter</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Event_Occurred__c</fullName>
        <label>Date Event Occurred</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Opened__c</fullName>
        <label>Date Opened</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duplicate_Rule_1__c</fullName>
        <formula>Intake_ID__c + &apos;|&apos; +  Program_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Rule 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filed_with_DCF__c</fullName>
        <label>Filed with DCF</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intake_ID__c</fullName>
        <label>Intake ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intake_Method__c</fullName>
        <label>Intake Method</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nature_of_complaint_Description__c</fullName>
        <label>Nature of complaint - Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Nature_of_complaint__c</fullName>
        <label>Nature of complaint</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <label>Program ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Anonymous__c</fullName>
        <label>Reporter Anonymous</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_City__c</fullName>
        <label>Reporter City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Data_Entry__c</fullName>
        <label>Reporter Data Entry</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reporter_First_Name__c</fullName>
        <label>Reporter First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Home_Phone__c</fullName>
        <label>Reporter Home Phone</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_ID__c</fullName>
        <label>Reporter ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Last_Name__c</fullName>
        <label>Reporter Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Relationship_To_Provider__c</fullName>
        <label>Reporter Relationship To Provider</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_State__c</fullName>
        <label>Reporter State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Street__c</fullName>
        <label>Reporter Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Work_Phone__c</fullName>
        <label>Reporter Work Phone</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_ZipCode__c</fullName>
        <label>Reporter ZipCode</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsible__c</fullName>
        <label>Responsible</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Summary_Type_of_case__c</fullName>
        <label>Summary/Type of case</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary_of_Allegation__c</fullName>
        <label>Summary of Allegation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unlicensed_ID__c</fullName>
        <label>Unlicensed ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Historical Cases Staging</label>
    <nameField>
        <displayFormat>HC-{0000000}</displayFormat>
        <label>Historical Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Cases Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_Batch_ProcessLegacyCases.cls
//Author - Latha Davuluri
//Batch job to process Legacy Cases - LEAD-4375

global class EEC_Batch_ProcessLegacyCases implements Database.Batchable<sObject>{

    global List<Historical_Cases_Staging__c> dataListSize = null;
      
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([Select h.Unlicensed_ID__c, h.Summary_of_Allegation__c, h.Summary_Type_of_case__c, h.Status__c, h.Responsible__c, h.Reporter_ZipCode__c, 
                                                h.Reporter_Work_Phone__c, h.Reporter_Street__c, h.Reporter_State__c, h.Reporter_Relationship_To_Provider__c, h.Reporter_Last_Name__c, 
                                                h.Reporter_ID__c, h.Reporter_Home_Phone__c, h.Reporter_First_Name__c, h.Reporter_Data_Entry__c, h.Reporter_City__c, h.Reporter_Anonymous__c, 
                                                h.Program_ID__c, h.Nature_of_complaint__c, h.Nature_of_complaint_Description__c, h.Name, h.IsDeleted, h.Intake_Method__c, h.Intake_ID__c, 
                                                h.Id, h.Filed_with_DCF__c, h.Duplicate_Rule_1__c, h.Date_Opened__c, h.Date_Event_Occurred__c, h.Date_Closed__c, h.DCF_File_Submitter__c, h.DCF_File_Submission_Date__c, 
                                                h.Complaint_Disposition__c, h.Case_Processed__c, h.Case_Owner__c, h.Allegation_Description__c, h.Allegation_Code__c, h.Case_Owner_Name__c,
                                                h.Additional_Description__c From Historical_Cases_Staging__c h WHERE h.Case_Processed__c = false]);
        
    }

    global void execute(Database.BatchableContext BC,List<Historical_Cases_Staging__c> scope){
    	
        dataListSize = scope;
        
        for(Historical_Cases_Staging__c v : scope){
        	 EEC_ProcessLegacyCaseData.processLegacyCases(v);
        }
        update scope; 
        
    }

    global void finish(Database.BatchableContext BC){
    	
    	try{
	    	if(dataListSize != null){
		    	AsyncApexJob batchJob = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
	       
		        Integer jobs = [Select count() From AsyncApexJob Where JobType = 'BatchApex' and ( Status = 'Queued' or Status = 'Processing' or Status = 'Preparing' )];   
		        
		        if(jobs <= 1){
		            EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyCases'); 
		        }
		
		        //If NumberOfErrors is "0" - if the execute method processed all records without errors - then call next contact batch.
			    if (batchJob.NumberOfErrors == 0)
			    {     
			        EEC_Batch_ProcessLegacyCases batchLegacyCases = new EEC_Batch_ProcessLegacyCases();   
			        Id batchProcessId = Database.executeBatch(batchLegacyCases,1);    //finish method logic here
			    }
			    else
			    {
			        //process other code
			        if ((batchJob.NumberOfErrors == 0) && (jobs < 5)){
		
		        		 EEC_Batch_ProcessLegacyCases batchLegacyCases = new EEC_Batch_ProcessLegacyCases();   
			             Id batchProcessId = Database.executeBatch(batchLegacyCases,1);    //finish method logic here
		         		}
		        	else{
		         		//wait for 1 hour
		          	}
			    }
	         }
	         else{
	         	EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyCases'); 
	         }
    	}
    	catch(exception ex){
    		System.debug('----> Error Processing the EEC_Batch_ProcessLegacyCases job: ' + ex.getMessage());
    	}
    }

}