phase2_Dev/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document__c.object
<CustomObject>
    <description>A custom object to be used for non-Salesforce reference documents.</description>
    <fields>
        <fullName>Approved_for_Future_Usage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved for Future Usage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attachment_Status__c</fullName>
        <label>Attachment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attachment(s) Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Attachment</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <formula>If(

OR(

AND(ISBLANK(Valid_From__c), ISBLANK(Valid_To__c)),


AND(OR(ISBLANK(Valid_From__c), Valid_From__c &lt;= Now()),
OR(ISBLANK(Valid_To__c), Valid_To__c &gt;= Now()))

),

true, 

false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Type</label>
        <referenceTo>Document_Type__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes relating to the document.</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>DateTime</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC- {0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Document_Type__c.object
<CustomObject>
    <description>An object for storing all document types. This is not to be confused with document prototypes (i.e. image/jpeg, document/pdf, etc)</description>
    <fields>
        <fullName>Allow_use_of_Umbrella_Level_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Use of Umbrella Level Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>A description for the document type.</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Individual_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Individual Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEAD_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related to Provider Type</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Document Types</relationshipLabel>
        <relationshipName>Document_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Library_Level__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If check, this document type will appear in the library of all providers this document type is defined on - per type of provider</inlineHelpText>
        <label>Library Level</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Need_to_be_Updated_at_each_new_Transacti__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Update Each New Transaction</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Optional_for_Transactio_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Optional for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Related_Role__c</fullName>
        <label>Related Role</label>
        <picklist>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Director / Administrative Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infant / Toddler Responsible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Contact</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Required_for_Transaction_Type__c</fullName>
        <globalPicklist>Transaction_Types</globalPicklist>
        <label>Required for Transaction Type</label>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Document Type</label>
    <nameField>
        <label>Document Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Library_Introduction__c</fullName>
        <inlineHelpText>Introduction text that will be displayed on the View Library Page - the main page of the Library. This text should explain the purpose of the library. This is only for Umbrella, GSA, and R&amp;P providers</inlineHelpText>
        <label>Library Introduction</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_DocumentLibraryController.cls
public with sharing class EEC_DocumentLibraryController {	
    public LEAD_Configuration__c leadConfiguration {get;set;}
    public List<Document__c> listDocument{get;set;}
    public string selectedDocumentId{get;set;}
    
    private string accountId{get;set;}
    
    public EEC_DocumentLibraryController() {
    	User loggedUser = [select Id, Name, contactId from User where Id = :UserInfo.getUserId()];    	
    	Contact contact = [select Id, Account.Id, Account.RecordType.Name from Contact where Id =: loggedUser.contactId];    	
    	string providerRecordType = contact.Account.RecordType.Name;
    	List<Lead_Configuration__c> listleadConfiguration = [Select Id, Library_Introduction__c from LEAD_Configuration__c where 
    												Name = :providerRecordType];
    												
		if(listleadConfiguration.size() > 0)    												
    		leadConfiguration = listleadConfiguration[0];
    	
    	accountId = contact.Account.Id;
    	listDocument = new List<Document__c>();
    }
    
    public void doCreateDocs(){    	
    	if(leadConfiguration != null){
	    	List<Document_Type__c> listDocumentType = [select Id, Allow_use_of_Umbrella_Level_Document__c,
	    	Description__c,Name,Individual_Document__c,Library_Level__c,
	    	Need_to_be_Updated_at_each_new_Transacti__c,Optional_for_Transactio_Type__c,Related_Role__c,
	    	Required_For_Transaction_Type__c from Document_Type__c where 
	    	LEAD_Configuration__c =: leadConfiguration.Id and Library_Level__c = true];
	    	
	    	List<Document__c> listExistingDocuments = [select Id, Document_Name__c, Document_Type__c, Document_Type__r.Name,
	    	Document_Type__r.Description__c, Attachment_Status__c, Notes__c,Valid_From__c,Valid_To__c from 
	    	Document__c where Provider__c=: accountId];
	    	
	    	Map<Id, List<Document__c>> mapDocumentTypeDocs = new Map<Id, List<Document__c>>();
	    	
	    	for(Document__c document : listExistingDocuments){
	    		List<Document__c> listDocs;
	    		if(mapDocumentTypeDocs.get(document.Document_Type__c) == null){
	    			listDocs = new List<Document__c>();
	    		}
	    		else{
	    			listDocs = mapDocumentTypeDocs.get(document.Document_Type__c);
	    		}
	    		listDocs.add(document);
	    		mapDocumentTypeDocs.put(document.Document_Type__c, listDocs);
	    	}
	    	List<Document__c> listNewDocs = new List<Document__c>();
	    	
	    	boolean isDocumentExist = false;
	    	for(Document_Type__c documentType : listDocumentType){
	    		isDocumentExist = false;
	    		List<Document__c> listDocs = mapDocumentTypeDocs.get(documentType.Id);
	    		if(listDocs != null){
	    			for(Document__c document : listDocs){
	    				if(document.Valid_To__c == null){
	    					isDocumentExist = true;
	    					break;
	    				}
	    			}
	    			if(isDocumentExist == false){
	    				Document__c newDocument = createDocument(documentType.Id , accountId);
		    			listNewDocs.add(newDocument);
	    			}
	    		}
	    		else{
	    			Document__c newDocument = createDocument(documentType.Id , accountId);
	    			listNewDocs.add(newDocument);
	    		}
	    	}
	    	if(listNewDocs.size() > 0){
	    		insert listNewDocs;
	    	}
    	}
		listDocument = [select Id, Document_Name__c, Document_Type__c, Document_Type__r.Name,
			Document_Type__r.Description__c, Attachment_Status__c, Notes__c,Valid_From__c,Valid_To__c from 
			Document__c where Provider__c=: accountId and Current__c = true and Document_Type__r.Library_Level__c = true];
    }
    
    public void doMarkAsOutOfDate(){
    	Document__c documents = [select Id, Valid_To__c, Document_Type__c, Approved_for_Future_Usage__c from 
        Document__c where Id =: selectedDocumentId];

        documents.Valid_To__c = datetime.now();
        documents.Approved_for_Future_Usage__c = false;    
        update documents;
        
        Document__c newDocument = createDocument(documents.Document_Type__c , accountId);
        insert newDocument;
        
        listDocument = [select Id, Document_Name__c, Document_Type__c, Document_Type__r.Name,
			Document_Type__r.Description__c, Attachment_Status__c, Notes__c,Valid_From__c,Valid_To__c from 
			Document__c where Provider__c=: accountId and Current__c = true and Document_Type__r.Library_Level__c = true];
    }
    
    private  Document__c createDocument(string documentType, string accountId){    	
        Document__c newDocument = new Document__c();
        newDocument.Document_Type__c = documentType;
		newDocument.Provider__c = accountId;
	    return newDocument;	    
    }
    
    public PageReference doBack(){
    	PageReference pageReference = Page.EEC_PortalLandingPage_2;
    	pageReference.setRedirect(true);
    	return pageReference;
    }
}