phase2_Dev/src/objects/Document__c.object
<CustomObject>
    <description>A custom object to be used for non-Salesforce reference documents.</description>
    <fields>
        <fullName>Attachment_Status__c</fullName>
        <label>Attachment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attachment(s) Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Attachment</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC- {0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/S3_File__c.object
<CustomObject>
    <description>This is an object for storing S3 file representations.</description>
    <fields>
        <fullName>Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection between the S3 File reference and the Document__c object.</description>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>S3 Files</relationshipLabel>
        <relationshipName>S3_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_S3FileTriggerHandler.cls
public with sharing class EEC_S3FileTriggerHandler {
    public static void doAfterInsert(List<S3_File__c> listS3File){
    	updateAttachmentStatus(listS3File);	
    }
    
    public static void doAfterUpdate(List<S3_File__c> listS3File){
    	updateAttachmentStatus(listS3File);
    }
    
    public static void doAfterUnDelete(List<S3_File__c> listS3File){
    	updateAttachmentStatus(listS3File);
    }
    
    public static void doAfterDelete(List<S3_File__c> listS3File){
    	updateAttachmentStatus(listS3File);
    }
    
    private static void updateAttachmentStatus(List<S3_File__c> listS3File){
    	

		Set<Id> setDocumentIds = new Set<Id>();
    	for(S3_File__c s3File : listS3File){
    		if(s3File.Document__c != null){
    			setDocumentIds.add(s3File.Document__c);
    		}
    	}
    	
		

    	Map<Id,AggregateResult> mapS3Files = new Map<id,AggregateResult>
    	([select Document__c Id, count(Id) from S3_File__c where
    									Document__c in : setDocumentIds group by Document__c]);
    									
    	List<Document__c> listDocuments = [select Id, Attachment_Status__c from Document__c where Id in : setDocumentIds];
    	
    	for(Document__c document : listDocuments){
    		AggregateResult aggregate = mapS3Files.get(document.Id);

			if(aggregate != null)
			{
				integer fileCount = (integer)aggregate.get('expr0');
				if(fileCount > 0){
					document.Attachment_Status__c = 'Attachment(s) Available';
				}
				else{
					document.Attachment_Status__c = 'No Attachment';
				}
			}
			else
			{
				document.Attachment_Status__c = 'No Attachment';
			}
    		
    	}
    	update listDocuments;
    }
}