phase2_Dev/src/objects/Document__c.object
<CustomObject>
    <description>A custom object to be used for non-Salesforce reference documents.</description>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>The file&apos;s content meta type.</description>
        <label>Content Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC- {0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/S3_File__c.object
<CustomObject>
    <description>This is an object for storing S3 file representations.</description>
    <fields>
        <fullName>Acl__c</fullName>
        <description>The access control level of the file.</description>
        <label>Acl</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>The name of the bucket the file is contained in.</description>
        <label>Bucket</label>
        <length>125</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>The content type of the file.</description>
        <label>Content_Type</label>
        <length>125</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A connection between the S3 File reference and the Document__c object.</description>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>S3 Files</relationshipLabel>
        <relationshipName>S3_Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <description>The name of the file.</description>
        <label>Filename</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This determines if the file is deemed to be locked from changes.</description>
        <label>Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <label>Object Id</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prefix__c</fullName>
        <description>The prefix for the file.</description>
        <inlineHelpText>The originating object&apos;s ID typically.</inlineHelpText>
        <label>Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Transaction_Document__c.object
<CustomObject>
    <description>A junction between the Document and a transaction.</description>
    <fields>
        <fullName>Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document</label>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Transaction Documents (Document)</relationshipLabel>
        <relationshipName>Transaction_Documents1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>S3_File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>S3 File</label>
        <referenceTo>S3_File__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction Document</label>
    <nameField>
        <displayFormat>TD- {0000000}</displayFormat>
        <label>Transaction Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TransactionDocumentAttachController.cls
public with sharing class EEC_TransactionDocumentAttachController{
  public List<S3_File__c> attachments { get; set; }
  public string generateFileId{get;set;}
  public Transaction_Document__c transactionDocument{get;set;}
       
  public EEC_TransactionDocumentAttachController(ApexPages.StandardController std){
    try {
      transactionDocument = [select Id, Document__c from Transaction_Document__c where Id=: std.getId()];
      attachments = [Select Id, Acl__c, Bucket__c, Content_Type__c, Description__c, Document__c,
      Filename__c,Locked__c,Object_Id__c,Object_Name__c,Prefix__c, CreatedDate
       From S3_File__c Where Document__c = :transactionDocument.Document__c];
    } catch(Exception e) {
      System.debug('----> Error: ' + e.getMessage());
    }
  }
    
  public String genetateS3Link() {
   	String filename = '';
    S3_File__c file = [Select Id, Filename__c, Prefix__c, Bucket__c From S3_File__c Where Id = :generateFileId];

    if (!String.isBlank(file.Prefix__c)) {
      filename += file.Prefix__c + '/';
    }
    filename += file.Filename__c;

    return EEC_S3ComponentCtrl.generateTempS3Url(file.Bucket__c, filename);
  }
}