phase2_Dev/src/objects/FCC_Provider_Assistants__c.object
<CustomObject>
    <description>Junction object between 2 Account objects (FCC Provider Recordtype and FCC Assistant Recordtype)</description>
    <fields>
        <fullName>FCC_Provider__c</fullName>
        <label>FCC Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Family Child Care</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assistants Working for this Provider</relationshipLabel>
        <relationshipName>FCC_Provider_Assistants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Licensing_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Transaction</label>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>FCC Provider Assistants</relationshipLabel>
        <relationshipName>FCC_Provider_Assistants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCC Provider Assistants</label>
    <nameField>
        <displayFormat>Asst-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCC Provider Assistants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Transaction Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_Closed_Cancelled__c</fullName>
        <label>Reason Transaction Closed / Cancelled</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Provider Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Licensing_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>FCC_Provider_Assistant_Update</fullName>
        <active>true</active>
        <description>Request for a change in the list of Assistant working for the FCC Provider</description>
        <label>FCC Provider Assistant Update</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_AssistantUpdateListCtrl.cls
public class EEC_AssistantUpdateListCtrl implements EEC_AssistantInterface {

  public Account account { get; set; }
  public String errorMessage { get; set; }

  private List<EEC_AssistantListCtrl.AssistantInfoWrap> providerAssistantWrappers { get; set; }

  public EEC_AssistantUpdateListCtrl() {
    try {
      String accountId = EEC_Util.decryptGetParam(EncodingUtil.urlDecode(ApexPages.currentPage().getParameters().get('param'), 'UTF-8'));
      List<Account> accountList = [Select Id From Account Where Id = :accountId];

      if (accountList != null && accountList.size() == 1) {
        account = accountList.get(0);
      }
    } catch(Exception e) {
      System.debug('----> Error getting account for Page: ' + e.getMessage());
      errorMessage = 'Unable to retrieve list of Assistants. Please try again later.';
    }
  }

  /**
   * Save
   *
   * @description This function will be used to save a new transaction with all then edited information.
   * @author Darkis
   * @created 8 Feb 2016
   */
  public PageReference Save() {
    List<FCC_Provider_Assistants__c> assistantsToUpsert = new List<FCC_Provider_Assistants__c> ();
    Savepoint sp = Database.setSavepoint();

    try {
      Licensing_Transaction__c newUpdateAssistantTransaction = new Licensing_Transaction__c
      (
       Provider__c = account.Id,
       Status__c = 'Closed (Processed)',
       Submission_Date__c = Date.today(),
       Submitter__c = UserInfo.getUserId(),
       Source__c = 'Provider Portal',
       Date_Closed__c = Date.today(),
       Reason_Closed_Cancelled__c = 'Processed'
      );
      newUpdateAssistantTransaction.RecordTypeId = EEC_RecordTypeUtil.findByName('Licensing_Transaction__c.FCC_Provider_Assistant_Update').Id;
      System.debug('----> New Transaction: ' + newUpdateAssistantTransaction);
      insert newUpdateAssistantTransaction;

      System.debug('----> providerAssistantWrappers: ' + providerAssistantWrappers);
      if (providerAssistantWrappers != null && providerAssistantWrappers.size() > 0) {
        for (EEC_AssistantListCtrl.AssistantInfoWrap wrapper : providerAssistantWrappers) {
          FCC_Provider_Assistants__c tempProvAssist = wrapper.providerAssistant.clone(false, true);
          tempProvAssist.Licensing_Transaction__c = newUpdateAssistantTransaction.Id;
          tempProvAssist.FCC_Provider__c = account.Id;
          assistantsToUpsert.add(tempProvAssist);
        }
        System.debug('----> assistantsToUpsert: ' + assistantsToUpsert);
        insert assistantsToUpsert;
      }
    } catch(Exception e) {
      System.debug('----> Error has occured saving assistants: ' + e.getMessage());
      Database.rollback(sp);
    }
    
    PageReference pPage = Page.EEC_PortalProviderPage;
    pPage.setRedirect(true);
    return pPage;
  }

  /**
   * getCtrlInstance
   * 
   * This function will return an instance of this controller with interface reference.
   * @author Darkis
   * @return EEC_AssistantInfoStepCtrl
   */
  public EEC_AssistantUpdateListCtrl getCtrlInstance() {
    return this;
  }

  /*-----Interface Methods-----*/
  public void updateAssistantWrapperList(List<EEC_AssistantListCtrl.AssistantInfoWrap> providerAssistantWrappers) {
    this.providerAssistantWrappers = providerAssistantWrappers;
  }

  public Licensing_Transaction__c getBaseLicenseTransaction() {
    return null;
  }

  public String getBaseLicenseRecordTypeName() {
    return null;
  }
}