phase2_Dev/src/objects/FormComponent__c.object
<CustomObject>
    <label>Form Component</label>
    <nameField>
        <displayFormat>FC-{0}</displayFormat>
        <label>Form Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Intake__c.object
<CustomObject>
    <label>Intake</label>
    <nameField>
        <displayFormat>INTAKE-{0}</displayFormat>
        <label>Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/ProcessingStepResult__c.object
<CustomObject>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>ErrorMessage</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Intake__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Processing Step Results</relationshipLabel>
        <relationshipName>ProcessingStepResults</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failure</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Processing Step Result</label>
    <nameField>
        <label>ProcessingStepResult Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processing Step Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Response__c.object
<CustomObject>
    <fields>
        <fullName>FormComponent__c</fullName>
        <label>Form Component</label>
        <referenceTo>FormComponent__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intake__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <label>Value</label>
        <length>8042</length>
        <type>LongTextArea</type>
    </fields>
    <label>Response</label>
    <nameField>
        <displayFormat>RESP-{0}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/ProcessingStepValue.cls
public with sharing class ProcessingStepValue implements ProcessingStep{
  public ProcessingStepValue() {}

  public ProcessingStepResult__c process(Intake__c intake, Map<String, List<Response__c>> intakeResponseMap, String jsonConfig) {
    ProcessingStepResult__c result = new ProcessingStepResult__c(Intake__c = intake.Id);

    try {
      Map<String, MetaConfig> configs = (Map<String, MetaConfig>) JSON.deserialize(jsonConfig, Map<String, MetaConfig>.class);
      List<Response__c> responseListToInsert = new List<Response__c>();
      // Loop through the configs returned from the parsed Json.
      for (String key : configs.keySet()) {
        Response__c tempResp = new Response__c();
        // Get the config based on the current key.
        MetaConfig config = configs.get(key);
        // Set the intake id and form component id to the new response.
        tempResp.Intake__c = intake.Id;
        tempResp.FormComponent__c = key;
        // If the type is value then simply insert the value as the response value.
        if (config.type != null && config.type.equalsIgnoreCase('value')) {
          tempResp.Value__c = config.value;
        } else if (config.type != null && config.type.equalsIgnoreCase('expression')) {
          // TODO: Grab the value based on the expression.
        }        
        // Once completed then add the obj to the upsert list.
        responseListToInsert.add(tempResp);
      }
      // Upsert the list into the DB.
      if (responseListToInsert != null && responseListToInsert.size() > 0) {
        insert responseListToInsert;
      }
      result.Result__c = 'Success';
    } catch (Exception e) {
      result.Result__c = 'Failure';
      result.ErrorMessage__c = e.getMessage();
    }
    return result;
  }

  private class MetaConfig {
    public String type { get; set; }
    public String value { get; set; }
  }
}