phase2_Dev/src/objects/FormVersion__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Form Version</label>
    <nameField>
        <label>Form Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Intake__c.object
<CustomObject>
    <fields>
        <fullName>FormVersion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Form Version</label>
        <referenceTo>FormVersion__c</referenceTo>
        <relationshipLabel>Intakes</relationshipLabel>
        <relationshipName>Intakes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>INTAKE-{0}</displayFormat>
        <label>Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Response__c.object
<CustomObject>
    <fields>
        <fullName>Intake__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intake</label>
        <referenceTo>Intake__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Response</label>
    <nameField>
        <displayFormat>RESP-{0}</displayFormat>
        <label>Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/IntakeTriggerTest.cls
@isTest
private class IntakeTriggerTest {

  @isTest static void testPreProcessing() {
    FormVersion__c testFormVersion = BatchTestUtil.loadData();
    
    Intake__c testIntake = new Intake__c(FormVersion__c = testFormVersion.Id);
    insert testIntake;

    List<Response__c> responses = [Select Id From Response__c];
    System.assertNotEquals(null, responses);
    System.assertEquals(2, responses.size());
  }
  
  @isTest static void testPostProcessing() {
    FormVersion__c testFormVersion = BatchTestUtil.loadData();
    
    Intake__c testIntake = new Intake__c(FormVersion__c = testFormVersion.Id);
    insert testIntake;

    Test.startTest();
    testIntake.Status__c = 'Submitted'; 
    update testIntake;
    Test.stopTest();
  }
}