phase2_Dev/src/objects/Form__c.object
<CustomObject>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/FormVersion__c.object
<CustomObject>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Form that this Form Version belongs to.</description>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Versions</relationshipLabel>
        <relationshipName>FormVersions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Form Version</label>
    <nameField>
        <label>Form Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Intake__c.object
<CustomObject>
    <fields>
        <fullName>FormVersion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Form Version</label>
        <referenceTo>FormVersion__c</referenceTo>
        <relationshipLabel>Intakes</relationshipLabel>
        <relationshipName>Intakes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>INTAKE-{0}</displayFormat>
        <label>Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/ProcessingStepBatchableTest.cls
@isTest
private class ProcessingStepBatchableTest {

  @isTest static void testProcessingStepBatchable() {
    FormVersion__c testFormVersion = BatchTestUtil.loadData();
    
    Intake__c testIntake = new Intake__c(FormVersion__c = testFormVersion.Id);
    insert testIntake;

    Set<Id> mIntakeList = new Set<Id>();
    mIntakeList.add(testIntake.Id);
    String queryStr = 'Select Id, Name, Status__c, FormVersion__c, FormVersion__r.Name, FormVersion__r.Status__c, FormVersion__r.Form__c, FormVersion__r.Form__r.Name From Intake__c';

    ProcessingStepBatchable batch = new ProcessingStepBatchable(0, mIntakeList);
    batch.currentCronJobName = BatchableUtil.generateBatchableName('Intake', 0, UserInfo.getUserId());

    Test.startTest();
    testIntake.Status__c = 'Submitted'; 
    update testIntake;

    Database.executebatch(batch, 200);
    Test.stopTest();

    Integer i = [Select Count() From Case];
    System.assertEquals(i, 1);
  }
}