phase2_Dev/src/objects/FormVersion__c.object
<CustomObject>
    <label>Form Version</label>
    <nameField>
        <label>Form Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Intake__c.object
<CustomObject>
    <fields>
        <fullName>FormVersion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Form Version</label>
        <referenceTo>FormVersion__c</referenceTo>
        <relationshipLabel>Intakes</relationshipLabel>
        <relationshipName>Intakes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Intake</label>
    <nameField>
        <displayFormat>INTAKE-{0}</displayFormat>
        <label>Intake Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/IntakeTriggerHandler.cls
public class IntakeTriggerHandler {

  public static void PreProcessingFlow(List<Intake__c> newIntakeList) {
    Set<Id> formVersionIdList = new Set<Id>();

    for (Intake__c intake : newIntakeList) {
      formVersionIdList.add(intake.FormVersion__c);
    }
    BatchableUtil.processSteps(newIntakeList, 'Pre', null, formVersionIdList);    
  }

  public static void VerifyAndScheduleIntakeResponseBatch(Set<Id> mIntakeLst) {
    if (mIntakeLst != null && mIntakeLst.size() > 0) {      
      // Create the scheduable and send it the required data processing.
      ProcessingStepSchedulable scheduable = new ProcessingStepSchedulable(mIntakeLst);
      
      // Generate new batch name.
      String newBatchName = BatchableUtil.generateBatchableName('Intake', 0, UserInfo.getUserId());
      scheduable.batchableName = newBatchName;
      
      // Prep the cron to run 60 Seconds from now.
      Datetime sysTime = System.now().addSeconds(10);
      String cronTiming = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();
      
      // Schedule the cron under the new batch name to run.
      System.schedule(newBatchName, cronTiming, scheduable);
    }
  }
}