phase2_Dev/src/objects/HistoryOfNonCompliance__c.object
<CustomObject>
    <fields>
        <fullName>Citation__c</fullName>
        <label>Citation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InteractionDate__c</fullName>
        <label>InteractionDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interaction__c</fullName>
        <label>Interaction</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>HistoryOfNonCompliance</label>
    <nameField>
        <label>ProgramID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HistoryOfNonCompliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/HistoryOfNonComplianceTriggerHelperTest.cls
@isTest
public with sharing class HistoryOfNonComplianceTriggerHelperTest {
     
     @isTest static void bulkVisitInsertTest() {
     	
     	HistoryOfNonCompliance__c nc = new HistoryOfNonCompliance__c();
     	
     	nc.Name = '603735';
     	nc.Interaction__c = '1179 - Monitoring Visit';
     	nc.InteractionDate__c = Date.parse('10/14/2014');
     	nc.citation__c = '7.08';
     	
     	insert nc;
     	
     	HistoryOfNonCompliance__c ncResult = [Select Id,Name From HistoryOfNonCompliance__c Where name ='603735'];
     	
     	system.assert(ncResult != null);
     	

     }
}