phase2_Dev/src/objects/Historical_Follow_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duplicate_Rule__c</fullName>
        <formula>Intake_Id__c + &apos;|&apos; + Program_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Rule</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Text__c</fullName>
        <label>Error Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Intake_Id__c</fullName>
        <label>Intake Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licensor_Name__c</fullName>
        <label>Licensor Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Id__c</fullName>
        <label>Program Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Historical Follow Staging</label>
    <nameField>
        <displayFormat>HF-{0000000}</displayFormat>
        <label>Historical Follow Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Follow Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Historical_Intervention_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Duplicate_Rule__c</fullName>
        <formula>Intake_Id__c + &apos;|&apos; + Program_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Rule</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Text__c</fullName>
        <label>Error Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Intake_Id__c</fullName>
        <label>Intake Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intervention_Code__c</fullName>
        <label>Intervention Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intervention_Type__c</fullName>
        <label>Intervention Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Id__c</fullName>
        <label>Program Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Historical Intervention Staging</label>
    <nameField>
        <displayFormat>HIN-{0000000}</displayFormat>
        <label>Historical Intervention Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Intervention Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Historical_Investigation_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Agencies_Involved__c</fullName>
        <formula>IF(OR(AG1__c = &quot;None&quot;,ISBLANK(AG1__c)),&quot;&quot;,AG1__c)  + &quot;;&quot; +   IF(OR(AG2__c = &quot;None&quot;,ISBLANK(AG2__c)),&quot;&quot;,AG2__c) + &quot;;&quot; +   IF(OR(AG3__c = &quot;None&quot;,ISBLANK(AG3__c)),&quot;&quot;,AG3__c)</formula>
        <label>Agencies Involved</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_Due_Days__c</fullName>
        <label>Corrective Action Due Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_CC_List__c</fullName>
        <label>Cover Letter Custom CC List</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_From_Name__c</fullName>
        <label>Cover Letter Custom From Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_From_Title__c</fullName>
        <label>Cover Letter Custom From Title</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_Text__c</fullName>
        <label>Cover Letter Custom Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Custom_To_Name__c</fullName>
        <label>Cover Letter Custom To Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duplicate_Rule__c</fullName>
        <formula>Intake_Id__c + &apos;|&apos; + Program_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Rule</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Text__c</fullName>
        <label>Error Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Intake_Id__c</fullName>
        <label>Intake Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation_Number__c</fullName>
        <label>Investigation Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Investigation_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Investigation Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Id__c</fullName>
        <label>Program Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_to_51A__c</fullName>
        <label>Related to 51A</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Historical Investigation Staging</label>
    <nameField>
        <displayFormat>HI-{0000000}</displayFormat>
        <label>Historical Investigation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Investigation Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Historical_Staff_Staging__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Assigned__c</fullName>
        <label>Date Assigned</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duplicate_Rule__c</fullName>
        <formula>Intake_Id__c + &apos;|&apos; + Program_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Rule</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Text__c</fullName>
        <label>Error Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Intake_Id__c</fullName>
        <label>Intake Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licensor_Name__c</fullName>
        <label>Licensor Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licensor_Number__c</fullName>
        <label>Licensor Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Id__c</fullName>
        <label>Program Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staff_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Staff Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>Historical Staff Staging</label>
    <nameField>
        <displayFormat>HS-{0000000}</displayFormat>
        <label>Historical Staff Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Staff Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Intervention__c.object
<CustomObject>
    <description>List the intervention needed for a given investigation</description>
    <fields>
        <fullName>Intervention_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Intervention Type</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Internal Investigation</value>
            </filterItems>
            <filterItems>
                <field>Intervention_Type__c.Name</field>
                <operation>equals</operation>
                <value>Internal Investigation</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Internal Investigation</value>
            </filterItems>
            <filterItems>
                <field>Intervention_Type__c.Name</field>
                <operation>notEqual</operation>
                <value>Internal Investigation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Intervention_Type__c</referenceTo>
        <relationshipLabel>Interventions</relationshipLabel>
        <relationshipName>Interventions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Interventions</relationshipLabel>
        <relationshipName>Interventions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Intervention</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Intervention ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interventions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Agencies_Involved__c</fullName>
        <label>Agencies Involved</label>
        <picklist>
            <picklistValues>
                <fullName>DMH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DPH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DYS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Assigned_Date__c</fullName>
        <inlineHelpText>Date the Investigation was assigned to an investigator</inlineHelpText>
        <label>Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation can be assigned to a Licensor, Supervisor or Inspector</description>
        <inlineHelpText>User who will take the lead on the investigation.</inlineHelpText>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User that will be used as backup on this case. This user will receive / have the same access than the lead.</inlineHelpText>
        <label>Backup</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations_Backup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Narrative__c</fullName>
        <inlineHelpText>This text will compose the cover letter. Salutations and signatures will be added by the system and does not need to be added here. To get the default text, please click on &quot;Set Narrative Default Values&quot; button.</inlineHelpText>
        <label>Cover Letter Narrative</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Investigation Type, Due Date and Intervention Type must be filled out when an Investigation is assigned</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duplicate_Rule__c</fullName>
        <formula>Legacy_IntakeID__c + &apos;|&apos; + Provider_No__r.Provider_No__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duplicate Rule</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_IntakeID__c</fullName>
        <label>Legacy IntakeID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Investigation_Number__c</fullName>
        <label>Legacy Investigation Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Staff_Info__c</fullName>
        <label>Legacy Staff Info</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_to_Receive_Response__c</fullName>
        <inlineHelpText>Number of days given to the provider to receive corrective actions plan.</inlineHelpText>
        <label>Number of Days to Receive Response</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_To_Complaint_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Related To Complaint Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_to_51A__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this investigation is associated to a 51A Report.</inlineHelpText>
        <label>Related to DCF/51A Report</label>
        <type>Checkbox</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Historic_Licensor_No__c</fullName>
        <description>This field allows matching of the user in DWH.</description>
        <externalId>true</externalId>
        <inlineHelpText>Licensor ID as used in legacy systems.</inlineHelpText>
        <label>Historic Licensor No</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_ProcessLegacyInvestigationData.cls
public with sharing class EEC_ProcessLegacyInvestigationData {
	
	//LEAD-4961
	public static void processLegacyInvestigations(Historical_Investigation_Staging__c Ins){
	   
	    try{
			   string dupRule1 = Ins.Duplicate_Rule__c;
			   string Intakeid = Ins.Intake_Id__c;
			   string Relatedto = Ins.Related_to_51A__c;
			   if(Ins.Related_to_51A__c == null){
			    Relatedto = 'False';
			   }
			    
			   List<Investigation__c> Inv = [Select Id,Legacy_IntakeID__c,Due_Date__c,Number_of_Days_to_Receive_Response__c,Related_to_51A__c,Related_To_Complaint_Case__c,
			                                 Cover_Letter_Narrative__c,Agencies_Involved__c,Legacy_Investigation_Number__c  From Investigation__c Where Legacy_IntakeID__c =: Intakeid limit 1];
			   
			   if(Inv.size() > 0){
			     Inv[0].Due_Date__c = Ins.Due_Date__c;
			     Inv[0].Number_of_Days_to_Receive_Response__c = Ins.Corrective_Action_Due_Days__c;
			     if(Inv[0].Related_to_51A__c == false ){
			     Inv[0].Related_to_51A__c = boolean.valueof(Relatedto);
			     }
			     Inv[0].Related_To_Complaint_Case__c = true;
			     //Inv[0].Duplicate_Rule__c = Ins.Duplicate_Rule__c;
			     Inv[0].Cover_Letter_Narrative__c = 'Cover Letter fields from Legacy Systems: \n From:' + Ins.Cover_Letter_Custom_From_Name__c + ',' + Ins.Cover_Letter_Custom_From_Title__c + ', \n cc:'+ Ins.Cover_Letter_Custom_CC_List__c
			                                         + '|'+Ins.Cover_Letter_Custom_To_Name__c + ': \n '+ Ins.Cover_Letter_Custom_Text__c;
			     Inv[0].Legacy_Investigation_Number__c = Ins.Investigation_Number__c;
			     Inv[0].Agencies_Involved__c = Ins.Agencies_Involved__c;
			     system.debug('Investigation Being Updated'+Inv[0].id+Inv[0].Legacy_IntakeID__c+Ins.id);
			     
			     update Inv[0];
			     
			     Ins.Investigation_Processed__c= true;
	     }else{
	          Ins.Error_Text__c = 'Intake ID not found in LEAD';
	     }
	  } 
	  catch(Exception e){
	      system.debug('******** Error occured updating Investigation*******'+ e.getMessage());			
		   Ins.Error_Text__c = e.getMessage();
	  }
	}
	
	public static void processLegacyStaff(Historical_Staff_Staging__c SS){
		
		try{
			//Duplicate Algorithm : Intake ID + ProgramId is considered as duplicate
			string dupRule = Ss.Duplicate_Rule__c;
			boolean licensorExists = false;		
	        
	        List<User> Licensor = [Select Id,Name From User Where Historic_Licensor_No__c = :Ss.Licensor_Number__c limit 1];
	        Id LEADUserId = [Select Id, Name From User Where Name = 'LEAD System_Batch_User'].Id;
			
			List<Investigation__c> processedInvestigation = [Select Id, Duplicate_Rule__c,Assigned_To__c,Backup__c,Assigned_Date__c,Legacy_Staff_Info__c From Investigation__c Where Duplicate_Rule__c = :dupRule limit 1];
			
			if (processedInvestigation.size() > 0){
				system.debug('MMMMM'+processedInvestigation.size()+processedInvestigation[0].Assigned_To__c);
				  if(Ss.Active__c == '1' && processedInvestigation[0].Assigned_To__c == null && Ss.Role__c == 'Lead'){
				  	if (Licensor.size() > 0){
				  	    processedInvestigation[0].Assigned_To__c = Licensor[0].id;
				  	    licensorExists = true;
				  	 }
				   }
				   else if(Ss.Active__c == '1' && processedInvestigation[0].Backup__c == null && Ss.Role__c == 'Assist'){
				  	 if (Licensor.size() > 0){ 
				       processedInvestigation[0].Backup__c = Licensor[0].id;
				       licensorExists = true;
				  	  }
				   }
				   
				   if (!licensorExists){
				      processedInvestigation[0].Assigned_Date__c = Ss.Date_Assigned__c;
				      if(string.isBlank(processedInvestigation[0].Legacy_Staff_Info__c)){
				          processedInvestigation[0].Legacy_Staff_Info__c = 'Investigation Staff Info: \n Staff Id:' +(Ss.Licensor_Number__c != null? Ss.Licensor_Number__c :'Not Provided')+ '\n Name :' + (Ss.Licensor_Name__c != null? Ss.Licensor_Name__c:'Not Provided') + '\n Date Assigned :';
				      }
				      else{
				      	 processedInvestigation[0].Legacy_Staff_Info__c += '\n\n Staff Id:' +(Ss.Licensor_Number__c != null? Ss.Licensor_Number__c :'Not Provided')+ '\n Name :' + (Ss.Licensor_Name__c != null? Ss.Licensor_Name__c:'Not Provided') + '\n Date Assigned :';
				      }                                                  
				      if (Ss.Date_Assigned__c != null){
					      processedInvestigation[0].Legacy_Staff_Info__c += Ss.Date_Assigned__c+'\n Role : '+(Ss.Role__c != null? Ss.Role__c:'Not Provided');
				       } 
					    else{
					      processedInvestigation[0].Legacy_Staff_Info__c += 'not provided'+'\n Role : '+(Ss.Role__c != null? Ss.Role__c:'Not Provided'); 
					    }
				      processedInvestigation[0].Legacy_Staff_Info__c += (Ss.Active__c != '1'? ' And is not active' : '');
			      }
			      system.debug('Investigation Being Updated'+processedInvestigation[0].id+'..Staff id'+LEADUserId+'..'+Ss.id+dupRule);
				  update processedInvestigation[0];
				  Ss.Staff_Processed__c = true;
			}			  	
			else{
			  Ss.Error_Text__c = 'Matching record \' '+Ss.Intake_Id__c+'|'+ Ss.Program_Id__c+'\' '+ 'not found in LEAD';
			}
		}
		catch(Exception e){
			system.debug('******** Error occured Updating Staff on Investigation*******'+ e.getMessage());			
			Ss.Error_Text__c = e.getMessage();
		}
	
	}
	
	public static void processLegacyIntervention(Historical_Intervention_Staging__c Is){
	  
		try{
			//Duplicate Algorithm : Intake ID + ProgramId is considered as duplicate
			string dupRule = Is.Duplicate_Rule__c;
			string InterventionType	= Is.Intervention_Code__c;
			if(Is.Intervention_Code__c == 'Documentation Review'){
			 InterventionType = 'Document Review';
			}	
	
			List<Investigation__c> processedInvestigation = [Select Id, Duplicate_Rule__c From Investigation__c Where Duplicate_Rule__c = :dupRule limit 1];
			
			if (processedInvestigation.size() > 0){	
				if (!string.isBlank(Is.Intervention_Type__c)){			
					Intervention__c intvn = new Intervention__c();
					intvn.Investigation__c = processedInvestigation[0].Id;
					intvn.Intervention_Type__c = [select id,name from Intervention_Type__c where name =: InterventionType].id;
					intvn.RecordTypeId = [Select Id from RecordType where sObjectType='Intervention__c' and name like 'Other Intervention'].Id;
					intvn.Date_Completed__c = Is.Date_Completed__c;
					intvn.Status__c = 'Done';
					intvn.Additional_Description__c = 'This is a Legacy Intervention with Intervention Type '+ Is.Intervention_Type__c;
					
					insert intvn;
					Is.Intervention_Processed__c = true;
				}
			}
			else{
			    Is.Error_Text__c = 'Matching record \' '+Is.Intake_Id__c+'|'+ Is.Program_Id__c+'\' '+ 'not found in LEAD';
			}			
		}
		catch(Exception e){
			system.debug('******** Error occured Creating Intervention on Investigation*******'+ e.getMessage());			
			Is.Error_Text__c = e.getMessage();
		}
		
	
	}
	
	public static void processLegacyFollow(Historical_Follow_Staging__c Hf){
	
	try{
			//Duplicate Algorithm : Intake ID + ProgramId is considered as duplicate
			string dupRule = Hf.Duplicate_Rule__c;		
	
			List<Investigation__c> processedInvestigation = [Select Id, Duplicate_Rule__c,Legacy_IntakeID__c From Investigation__c Where Duplicate_Rule__c = :dupRule limit 1];
			List<User> Licensor = [Select Id,Name From User Where Historic_Licensor_No__c = :Hf.Licensor__c limit 1];
			Id LEADUserId = [Select Id, Name From User Where Name = 'LEAD System_Batch_User'].Id;
			
			if (processedInvestigation.size() > 0){	
				Task Tsk = new Task();
				Tsk.WhatId = processedInvestigation[0].id;
				Tsk.RecordTypeId = [Select Id from RecordType where sObjectType='Task' and name like 'Investigation Follow-Up Actions'].Id;
				tsk.Status = 'Completed';
                tsk.Priority = 'Normal';
                tsk.ActivityDate = Hf.Due_Date__c;
                tsk.Subject = 'Legacy Investigation Follow-Up Action';
                tsk.Description = (Hf.Description__c != null?Hf.Description__c:'') + '\n'+'Additional Data :\n' +'Refer To Legal date :';
                if (Hf.Refer_to_Legal_Date__c != null){
				    tsk.Description += Hf.Refer_to_Legal_Date__c+'\n Legal Issue Date :';
			    } 
				else{
				   tsk.Description += 'not provided'+'\n Legal Issue Date :'; 
				}
				if (Hf.Legal_Issue_Date__c != null){
				    tsk.Description += Hf.Legal_Issue_Date__c+'\n Modification Date :';
			    } 
				else{
				   tsk.Description += 'not provided'+'\n Modification Date :'; 
				}
				if (Hf.Modification_Date__c != null){
				    tsk.Description += Hf.Modification_Date__c+'\n Follow Up Code :';
			    } 
				else{
				   tsk.Description += 'not provided'+'\n Follow Up Code :'; 
				}
                tsk.Description += (Hf.FollowUp_Code__c != null?Hf.FollowUp_Code__c:'Not Provided') + '\n Follow Up Id : '+(Hf.FollowUp_Id__c != null?Hf.FollowUp_Id__c:'Not Provided') +'\n Completed Date :';
                if (Hf.Completed_Date__c != null){
				    tsk.Description += Hf.Completed_Date__c;
			    } 
				else{
				   tsk.Description += 'not provided'; 
				}
                
                if (Licensor.size() > 0){
			     tsk.Ownerid = Licensor[0].Id;
			    }
			       else{
			     tsk.OwnerId = LEADUserId;
			     tsk.Description += '\n'+'Legacy Follow:- Licensor Id :' + Hf.Licensor__c + '\n Licensor Name :' + Hf.Licensor_Name__c;
			    }
                 system.debug('Investigation Being Updated'+processedInvestigation[0].id+processedInvestigation[0].Legacy_IntakeID__c+Hf.id+dupRule);
                insert tsk;
                Hf.Follow_Processed__c = true;
			}else{
			    Hf.Error_Text__c = 'Matching record \' '+Hf.Intake_Id__c+'|'+ Hf.Program_Id__c+'\' '+ 'not found in LEAD';
			}			
		}
		catch(Exception e){
			system.debug('******** Error occured Creating FollowUp on Investigation*******'+ e.getMessage());			
			Hf.Error_Text__c = e.getMessage();
		}
		
	}
    
}