phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Type_of_Visit__c</fullName>
        <description>Reason of Visit</description>
        <label>Reason of Visit</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Licensing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License 90-day Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Full Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Activate Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy System Import</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Change</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Visit_Best_Practices__c.object
<CustomObject>
    <label>Visit Best Practices</label>
    <nameField>
        <displayFormat>VBP-{0000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Best Practices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_TestGenerateVisitChecklistExtension.cls
@isTest
public with sharing class EEC_TestGenerateVisitChecklistExtension {

  @isTest static void testVisitChecklistItemWrapperConstruct() {
    Inspection_Item__c i = new Inspection_Item__c();
    String s = 'test';

    EEC_GeneratePDFBase.VisitChecklistItemWrapper vciwc = new
    EEC_GeneratePDFBase.VisitChecklistItemWrapper(i, s);

    System.assertEquals(vciwc.inspectionItem, i);
    System.assertEquals(vciwc.standardRegulations, s);
  }

  @isTest static void testAugmentStandardInspectionItems() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    Standard_Inspection_Item__c sii1 = EEC_TestUtil.mockStdInspectionItem();
    Regulation__c reg1 = EEC_TestUtil.mockRegulation();
    Regulation__c reg2 = EEC_TestUtil.mockRegulation();
    EEC_TestUtil.mockRegStdInsp(reg1, sii1);
    EEC_TestUtil.mockRegStdInsp(reg2, sii1);
    Inspection_Item__c ii1 = EEC_TestUtil.mockInspectionItem(i, sii1, 'Non-Compliant', false, null);
    Inspection_Item__c ii2 = EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null);
    List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = EEC_GeneratePDFBase.augmentStandardInspectionItems(new List<Inspection_Item__c> { ii1, ii2 });

    System.assertEquals(2, l.size());
    System.assertEquals(reg1.Name + ', ' + reg2.Name, l.get(0).standardRegulations);
    System.assertEquals('', l.get(1).standardRegulations);
  } 

  @isTest static void testGetAssessedStandardInspectionItems() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
    List<Inspection_Item__c> iItemsList = new List<Inspection_Item__c>();

    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, 'HJelp'));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, EEC_TestUtil.mockRegulation(), null, true, null));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, stdIi, 'Non-Compliant', false, null));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, stdIi, 'Non-Compliant', false, 'Helo'));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, stdIi, 'Compliant', true, null));
    upsert iItemsList;
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    Test.startTest();
    List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = ext.getAssessedStandardInspectionItems();
    System.assertEquals(4, l.size());
    Test.stopTest();
  }

  @isTest static void testGetUnassessedStandardInspectionItems() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
    List<Inspection_Item__c> iItemsList = new List<Inspection_Item__c>();

    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, 'HJelp'));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, EEC_TestUtil.mockRegulation(), null, true, null));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, stdIi, 'Non-Compliant', false, null));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, stdIi, 'Non-Compliant', false, 'Helo'));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, stdIi, null, false, null));
    upsert iItemsList;
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    Test.startTest();
    List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = ext.getUnassessedStandardInspectionItems();
    System.assertEquals(1, l.size());
    Test.stopTest();
  }

  @isTest static void testGetAdditionalInspectionItems() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
    List<Inspection_Item__c> iItemsList = new List<Inspection_Item__c>();

    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, 'HJelp'));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, EEC_TestUtil.mockRegulation(), null, true, null));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, stdIi, 'Non-Compliant', false, null));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, stdIi, 'Non-Compliant', false, 'Helo'));
    iItemsList.add(EEC_TestUtil.mockInspectionItemWithoutInsert(i, stdIi, null, true, null));
    upsert iItemsList;

    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    Test.startTest();
    List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = ext.getAdditionalInspectionItems();

    System.assertEquals(2, l.size(), 2);
    Test.stopTest();
  }

  @isTest static void testGetHasNonCompliantTrue() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null);
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null);
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Not Applicable', false, null);
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    System.assertEquals(true, ext.getHasNonCompliant());
  }
  @isTest static void testGetHasNonCompliantFalse() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null);
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Not Applicable', false, null);
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    System.assertEquals(false, ext.getHasNonCompliant());
  }

  @isTest static void testGetVisitBestPracticesFalse() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    System.assertEquals(0, ext.getVisitBestPractices().size());
  }

  @isTest static void testGetVisitBestPracticesTrue() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    Visit_Best_Practices__c vbp = EEC_TestUtil.mockVisitBestPractice(i, EEC_TestUtil.mockStdBestPractice());
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    System.assertEquals(1, ext.getVisitBestPractices().size());
  }

  @isTest static void testGetVisitOutcomesSummary() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null);
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null);
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Not Applicable', false, null);
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    System.assertEquals(new Set<String>{null}, ext.getVisitOutcomesSummary());  
  }

  @isTest static void testAvailablities() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null);
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null);
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Not Applicable', false, null);
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    System.assert(!ext.getTechnicalAssistanceAvailable()); 
    System.assert(ext.getComplaintAvailable()); 
    System.assert(ext.getNonComplaintAvailable()); 
  }

  @isTest static void testGetTypeOfVisitHeaderTextMonitoring() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    i.Type_of_Visit__c = 'Enhanced Monitoring';
    update i;
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    System.assertEquals('', ext.getTypeOfVisitHeaderText());
  }

  @isTest static void testGetTypeOfVisitHeaderTextRenewal() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    i.Type_of_Visit__c = 'Provisional License Renewal';
    update i;
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    System.assertEquals('Renewal -', ext.getTypeOfVisitHeaderText());
  }

  @isTest static void testGetTypeOfVisitHeaderTextDefault() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    i.Type_of_Visit__c = 'Follow-up';
    update i;
    EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));

    System.assertEquals('Follow-up -', ext.getTypeOfVisitHeaderText());
  }
}