phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_UploadExcelControllerTest.cls
@IsTest
public class EEC_UploadExcelControllerTest {
 
    Static testMethod void testEEC_UploadExcelController(){
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        // Call constructor.
        EEC_UploadExcelController uExcel = new EEC_UploadExcelController(sc);
        uExcel.uploadExcel();
    }
     static testmethod void excelcntrl(){
         Inspection__c inspec = EEC_TestUtil.loadInspectionSetup();
         test.startTest();
        	  
        	  
        	  ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(inspec);
         	  ApexPages.currentPage().getParameters().put('Id',inspec.id);
         
         EEC_DocumentAttachmentsExtension atach = new EEC_DocumentAttachmentsExtension(sc);
         atach.getCtrlInstance();
         test.stopTest();
         
     }
    static testmethod void testSplitCsvEOL(){
        String csv = '"Visit Item Name","Visit Item No","Visit No","Domain (list)","Description (list)","Result","Observations","Technical Assistance","Correction Plan","Date Implemented","Non-Assessed Item","Provider: Name"\n"Electric outlets covered, no frayed electrical cords","VI-019919","Visit# 000625","Physical Facility - Indoors","","","","","","","0","My FCC Provider"';
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        EEC_UploadExcelController uExcel = new EEC_UploadExcelController(sc);
        uExcel.csvFileBody = Blob.valueof(csv);
        uExcel.uploadExcel();
   }
   static testmethod void testSplitCsv(){
        String csv = '"Visit Item Name","Visit Item No","Visit No","Domain (list)","Description (list)","Result","Observations","Technical Assistance","Correction Plan","Date Implemented","Non-Assessed Item","Provider: Name"\n';
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        List<Inspection_Item__c> iiList = [Select Name From Inspection_Item__c where Inspection_No__c = :insp.id] ;
        csv = csv + '"' + iiList[0].Name + '","' + iiList[0].Name + '",,,C,"everything is fine","Installed tubes",,,,,\n';
        csv = csv + '"' + iiList[1].Name + '","' + iiList[1].Name + '",,,NC,"everything is fine","Installed tubes",,,,,\n';
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        EEC_UploadExcelController uExcel = new EEC_UploadExcelController(sc);
        uExcel.csvFileBody = Blob.valueof(csv);
        uExcel.uploadExcel();
   }
}