phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Can_be_Edited__c</fullName>
        <formula>!AND(OR(ISPICKVAL(Status__c,&apos;Cancelled&apos;), ISPICKVAL(Status__c,&apos;Closed&apos;)),!ISBLANK($UserRole.Name),$UserRole.Name !=&apos;Executive_and_Directors&apos;,$UserRole.Name!=&apos;Regional_Director&apos;,OR(NOT(OR(CONTAINS($UserRole.DeveloperName,&apos;Director&apos;),CONTAINS($UserRole.DeveloperName,&apos;Supervisor&apos;))),AND($UserRole.DeveloperName==&apos;FCC_Supervisor&apos;, Provider_No__r.RecordType.Name != &apos;Family Child Care&apos;), AND($UserRole.DeveloperName==&apos;SLGSA_Supervisor&apos;,Provider_No__r.RecordType.Name != &apos;Large Group&apos;,Provider_No__r.RecordType.Name != &apos;Small Group&apos;), AND($UserRole.DeveloperName==&apos;R_P_Supervisor&apos;, Provider_No__r.RecordType.Name != &apos;Group Care&apos;,Provider_No__r.RecordType.Name != &apos;Temporary Shelter&apos;,Provider_No__r.RecordType.Name != &apos;Adoption Agency&apos;,Provider_No__r.RecordType.Name != &apos;Foster Care Agency&apos;)))</formula>
        <label>Can be Edited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mater_Visit_for_Res_Cluster_of_Visits__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select here the visit that will serve as Primary Visit. Being defined as a &apos;dependent associated&apos; visit, this visit will follow the same process than the Primary for the following steps: visit scheduling, selection of visit checklist, and report creation.</inlineHelpText>
        <label>Primary Visit (for Cluster of Visit)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Inspector_del__c</field>
                <operation>equals</operation>
                <valueField>Inspection__c.Inspector_del__c</valueField>
            </filterItems>
            <filterItems>
                <field>Inspection__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Is_Residential__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Mater_Visit_for_Res_Cluster_of_Visits__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Umbrella_Members__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Dependent Associated Visits (for Res. Cluster of Visits)</relationshipLabel>
        <relationshipName>Slave_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Additional_Inspection_Item_Name__c</fullName>
        <description>Allow user to name this additional inspection item</description>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Associated_regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For non standard items, this lookup allows the user to select the regulation associated with this inspection item.</description>
        <label>Associated regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_list__c</fullName>
        <description>Domain(Category) used for list.</description>
        <formula>TEXT( Category_additional__c ) &amp; IF(ISPICKVAL(Category_additional__c,&quot;&quot;) , Category_standard__c , &quot;&quot;)</formula>
        <label>Domain (list)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Correction_Plan_Status__c</fullName>
        <label>Correction Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Collect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider Submitted, EEC to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEC Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy Non-compliance</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <description>Will be filled by the corrective actions taken by the provider in case of non-compliance</description>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Fill this field if the corrective action submitted by the provider is not appropriate. By updating this field, Providers using electronic communication will be informed by email and will be able to update the correction plan on the portal.</inlineHelpText>
        <label>Corrective Action EEC Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Actions_Submitter__c</fullName>
        <inlineHelpText>User who added the corrective actions</inlineHelpText>
        <label>Corrective Actions Submitter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <description>Date the corrective actions were or will be implemented. This information should be provided by the provider when filling the answer of statement of non-compliance.</description>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description_of_inspection__c</fullName>
        <formula>Standard_Inspection_Item__r.Description__c</formula>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discussed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Discussed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inspection_Item_Name__c</fullName>
        <formula>Standard_Inspection_Item__r.Name</formula>
        <label>Visit Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Assistance__c</fullName>
        <label>Technical Assistance</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Article__c</fullName>
        <description>Regulation article</description>
        <label>Article</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Regulation_Number__c</fullName>
        <formula>IF(CONTAINS(Name,&quot;_&quot;),LEFT(Name,LEN(Name)-9),Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Regulation Number</label>
        <type>Text</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_CorrectiveActionReviewControllerTest.cls
/**
 * EEC_CorrectiveActionReviewControllerTest 
 * 
 * This class contains all the unit test behaviour for the EEC_CorrectiveActionReviewController class.
 * @author Darkis
 */

@isTest
private class EEC_CorrectiveActionReviewControllerTest {
    
    static ApexPages.StandardController setupTest() {
        // Setup basic defaults.
        ApexPages.StandardController sc = new ApexPages.StandardController(EEC_TestUtil.loadInspectionSetup());
        return sc;
    }

/*    static testMethod void testGetInspectionItemData() {
        ApexPages.StandardController sc = EEC_CorrectiveActionReviewControllerTest.setupTest();
        // Call constructor
        new EEC_CorrectiveActionReviewController(sc);
        // Check apex messages for failed message.
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
		System.assertNotEquals(0, pageMessages.size());
		// Check that the error message you are expecting is in pageMessages
		Boolean messageFound = false;
		// Loop through the page messages to assert the one we are looking for is found.
		for(ApexPages.Message message : pageMessages) {
    		if(message.getSummary() == 'This functionality is not available for a Closed or Cancelled Visit, Visit must first be re-opened by a Supervisor or Director.' 
               && message.getSeverity() == ApexPages.Severity.ERROR) {
        		messageFound = true;        
    		}
		}	
        // Assert the message.
		//System.assert(messageFound);
    }*/
    
    static testMethod void testGetInspectionItemData(){
        ApexPages.StandardController sc = EEC_CorrectiveActionReviewControllerTest.setupTest();
        EEC_CorrectiveActionReviewController ctrl = new EEC_CorrectiveActionReviewController(sc);
        PageReference p = ctrl.getInspectionItemData();
    }

    static testMethod void testSortExpression() {
        ApexPages.StandardController sc = EEC_CorrectiveActionReviewControllerTest.setupTest();
        EEC_CorrectiveActionReviewController ctrl = new EEC_CorrectiveActionReviewController(sc);
        // Test setting and getting sortExpression.
        ctrl.sortExpression = 'ASC';
        System.assertEquals('ASC', ctrl.getSortDirection());
        // Check alternate flow for identical values.
        ctrl.sortExpression = 'ASC';
        System.assertEquals('DESC', ctrl.getSortDirection());
    }
    
    static testMethod void testSortDirection() {
        ApexPages.StandardController sc = EEC_CorrectiveActionReviewControllerTest.setupTest();
        EEC_CorrectiveActionReviewController ctrl = new EEC_CorrectiveActionReviewController(sc);
        // Test the sort direction default when no expression is present.
        ctrl.sortExpression = null;
        System.assertEquals(ctrl.getSortDirection(), 'ASC');
        // Set direction to DESC but expression is still null forcing ASC.
        ctrl.setSortDirection('DESC');
        System.assertEquals('ASC', ctrl.getSortDirection());
        // Set the sort expression to allow direction to proceed without being defaulted to ASC.
        ctrl.sortExpression = 'DESC';
        ctrl.setSortDirection('DESC');
        System.assertEquals('DESC', ctrl.getSortDirection());
    }
    

    static testMethod void testSave() {
        ApexPages.StandardController sc = EEC_CorrectiveActionReviewControllerTest.setupTest();
        EEC_CorrectiveActionReviewController ctrl = new EEC_CorrectiveActionReviewController(sc);
        // Call the save method.
        ctrl.Save();
    }
    
    static testMethod void testSaveAndCloseVisitMode() {
        ApexPages.StandardController sc = EEC_CorrectiveActionReviewControllerTest.setupTest();
        EEC_CorrectiveActionReviewController ctrl = new EEC_CorrectiveActionReviewController(sc);
        // Call the save and close visit method.
        ctrl.SaveAndCloseVisitMode();
    }
    
    @isTest static void testSaveInspectionItems() {
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        
        Test.startTest();
        Inspection_Item__c inspItem = [SELECT Id,Name,Inspection_No__r.Name, Inspection_No__r.Provider_No__c,Correction_Plan_Status__c,
                                       Inspection_No__c,RecordType.Name,Inspection_Item_Name__c,Additional_Inspection_Item_Name__c,Associated_regulation__c,
                                       Associated_regulation__r.name, Associated_regulation__r.Regulation_Number__c, Category_list__c,Description_of_inspection__c,Inspection_Result__c,Discussed__c,
                                       technical_assistance__c,observations__c,correction_plan__c,Corrective_Actions_Submitter__c,
                                       Corrective_Action_EEC_Feedback__c,Standard_Inspection_Item__c,Date_Implemented__c
                                       FROM Inspection_Item__c 
                                       WHERE Inspection_Result__c = 'Non-Compliant' AND Standard_Inspection_Item__c != null LIMIT 1];
        Inspection_Item__c inspItemDeleted = [SELECT Id,Name,Inspection_No__r.Name, Inspection_No__r.Provider_No__c,
                                       Correction_Plan_Status__c,
                                       Inspection_No__c,RecordType.Name,Inspection_Item_Name__c,Additional_Inspection_Item_Name__c,Associated_regulation__c,
                                       Associated_regulation__r.name, Associated_regulation__r.Regulation_Number__c, Category_list__c,Description_of_inspection__c,Inspection_Result__c,Discussed__c,
                                       technical_assistance__c,observations__c,correction_plan__c,Corrective_Actions_Submitter__c,
                                       Corrective_Action_EEC_Feedback__c,Standard_Inspection_Item__c,Date_Implemented__c
                                       FROM Inspection_Item__c
                                       WHERE Inspection_Result__c = 'Compliant' AND Standard_Inspection_Item__c != null
                                       AND Inspection_No__r.Provider_No__c =: inspItem.Inspection_No__r.Provider_No__c 
                                       LIMIT 1];
        
        insp = [SELECT Id,RecordType.Name,Mater_Visit_for_Res_Cluster_of_Visits__c,Provider_No__c,Can_be_Edited__c,Name
                           FROM Inspection__c WHERE ID =: inspItem.Inspection_No__c LIMIT 1];
        
        List<EEC_CorrectiveActionReviewController.InspectionListWrapper> iiWrapperList = new List<EEC_CorrectiveActionReviewController.InspectionListWrapper>();
        Set<Id> siSet = new Set<Id>();
        siSet.add(inspItem.Standard_Inspection_Item__c);
        siSet.add(inspItemDeleted.Standard_Inspection_Item__c);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        EEC_CorrectiveActionReviewController ctrl = new EEC_CorrectiveActionReviewController(sc);
        Map<Id, Map<String,String>> iRegMap = new Map<Id, Map<String,String>>();
        for(Junction_InspReg__c jir : [select Id,Regulation__c,Regulation__r.name, Regulation__r.Regulation_Number__c, Regulation__r.article__c,Standard_Inspection_Item__c from Junction_InspReg__c where Standard_Inspection_Item__c in :siSet]){
            Map<String,String> jiMap = new Map<String,String>();
            jiMap.put(jir.Regulation__r.Regulation_Number__c+',', jir.Regulation__c);
            iRegMap.put(jir.Standard_Inspection_Item__c,jiMap);    
        }
            
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<EEC_CorrectiveActionReviewController.InspectionListWrapper>();
        // Create and add a new InspectionListWrapper.
        EEC_CorrectiveActionReviewController.InspectionListWrapper ilw = new EEC_CorrectiveActionReviewController.InspectionListWrapper(0, inspItem, iRegMap);
        iiWrapperList.add(ilw);
        // Create and add a new InspectionListWrapper that is expected to be deleted.
        EEC_CorrectiveActionReviewController.InspectionListWrapper ilwDeleted = new EEC_CorrectiveActionReviewController.InspectionListWrapper(0, inspItemDeleted, iRegMap);
        ilwDeleted.isDeleted = true;
        iiWrapperList.add(ilwDeleted);
        // Set the wrapper list in the controller.
        ctrl.iiWrapperList = iiWrapperList;
        // Attempt to update and save the items.
        ctrl.Save();
        Test.stopTest();
    }
    
    static testMethod void testInspectionListWrapper() {
        new EEC_CorrectiveActionReviewController.InspectionListWrapper(0, new Inspection_Item__c(), null);
    }
}