phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Statement_of_non_compliance__c</fullName>
        <inlineHelpText>Date the statement of non-compliance was last generated</inlineHelpText>
        <label>Statement of non-compliance Issue Date</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_GenerateNonCompPDFControllerTest.cls
/**
 * EEC_GenerateNonCompPDFControllerTest
 * 
 * This class contains all the unit tests relating to the EEC_GenerateNonCompPDFController class.
 * @author Darkis
 * 
 */

@isTest
private class EEC_GenerateNonCompPDFControllerTest {

    static testMethod void testEEC_GenerateNonCompPDFController() {
        // Setup basic defaults.
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        // Call constructor.
        new EEC_GenerateNonCompPDFController(sc);
    }
    
    static testMethod void testGeneratePDF() {
        // Setup basic defaults.
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        
        Inspection__c i = [SELECT Id,Statement_of_non_compliance__c FROM Inspection__c LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(insp);
        EEC_GenerateNonCompPDFController controller = new EEC_GenerateNonCompPDFController(sc);        
        // Call the controller method.
        controller.GeneratePDF();   
        
        List<Attachment> attachments = [SELECT Name FROM Attachment WHERE ParentID = :i.Id]; 
        
        //controller.createAndInsertAttachment(insp); 
    }
}