phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3)</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family Child Care, Adoption Agency, Foster Care Agency, Group Care, Large Group, Small Group, Temporary Shelter, Unlicensed Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>FCC Assistant</value>
            </filterItems>
            <filterItems>
                <field>Account.Allow_New_Application_as_Provider__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_VisitReportControllerTest.cls
/**
 * EEC_VisitReportControllerTest
 * 
 */

@isTest
public class EEC_VisitReportControllerTest {
    static testMethod void testInitializeVisitReportController() {
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        test.startTest();
        PageReference pg = Page.EEC_PortalProviderPage;
        test.setCurrentPage(pg);        
        ApexPages.currentPage().getParameters().put('visitID',insp.Id);
        EEC_VisitReportController vr = new EEC_VisitReportController();
        ApexPages.currentPage().getParameters().put('member',insp.Provider_No__c);
        vr = new EEC_VisitReportController();
        vr.returnProvider();
        test.stopTest();
    }
}