phase2_Dev/src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Announced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Announced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Announcement_Type__c</fullName>
        <inlineHelpText>Type of announcement given to the provider. For announced, the system will automatically email the provider (if email is known) with confirmation and reminders. For semi-announced, the system will create a task for the licensor to announce to the provider</inlineHelpText>
        <label>Announcement Type</label>
        <picklist>
            <picklistValues>
                <fullName>Unannounced</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Announced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-announced</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Type__c</fullName>
        <formula>Provider_No__r.RecordType.Name</formula>
        <label>Provider Type</label>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_BatchUpdateLicensingVisitRecordType.cls
global class EEC_BatchUpdateLicensingVisitRecordType implements Database.Batchable<sObject> {
	
	String query;
	
	global EEC_BatchUpdateLicensingVisitRecordType() {
		query = 'Select Id, Announced__c, Provider_Type__c from Inspection__c where RecordType.Name = \'Licensing Visits\' limit 100';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Inspection__c> scope) {
		List<Inspection__c> toBeUpdated = new List<Inspection__c>();
		List<RecordType> licensingVisitRecordTypes = [SELECT Description, DeveloperName, Id, IsActive, Name, SobjectType
																							FROM RecordType
																							WHERE SobjectType = 'Inspection__c'];
		String fccVisitRecordType = '';
		String gsaVisitRecordType = '';
		String placementVisitRecordType = '';
		String residentialVisitRecordType = '';

		for (RecordType rt : licensingVisitRecordTypes){
			if (rt.Name.contains('FCC')){
				fccVisitRecordType = rt.Id;
			} else if (rt.Name.contains('GSA')){
				gsaVisitRecordType = rt.Id;
			} else if (rt.Name.contains('Residential')){
				residentialVisitRecordType = rt.Id;
			} else if (rt.Name.contains('Placement')){
				placementVisitRecordType = rt.Id;
			}
		}
		System.debug('----FCC RT: ' + fccVisitRecordType + ' - GSA RT: ' + gsaVisitRecordType + ' - Residential RT: ' + residentialVisitRecordType + ' - Placement RT: ' + placementVisitRecordType);
		for (Inspection__c i : scope){
			System.debug('-----> VisitToBeUpdate before: ' + i);
			if (i.Provider_Type__c == 'Family Child Care'){
				i.RecordTypeID = fccVisitRecordType;
			} else if (i.Provider_Type__c == 'Large Group' || i.Provider_Type__c == 'Small Group'){
				i.RecordTypeID = gsaVisitRecordType;
			} else if (i.Provider_Type__c == 'Group Care' || i.Provider_Type__c == 'Temporary Shelter'){
				i.RecordTypeID = residentialVisitRecordType;
			} else if (i.Provider_Type__c == 'Foster Care Agency' || i.Provider_Type__c == 'Adoption Agency'){
				i.RecordTypeID = placementVisitRecordType;
			} 
			if(i.Announced__c){
				i.Announcement_Type__c = 'Announced';
			} else {
				i.Announcement_Type__c = 'Unannounced';
			}
			System.debug('-----> VisitToBeUpdate: ' + i);
			toBeUpdated.add(i);
		}

		Update toBeUpdated;
	}
	
	global void finish(Database.BatchableContext BC) {
		Integer remainingVisits = [Select Count() from Inspection__c where RecordType.Name = 'Licensing Visits'];
		if(remainingVisits != null && remainingVisits > 0){
			EEC_BatchUpdateLicensingVisitRecordType visitBatch = new EEC_BatchUpdateLicensingVisitRecordType();
			String cronId = System.scheduleBatch(visitBatch, 'updateVisitRecordType', 1);
			System.debug(cronId);
		}
	}
}