phase2_Dev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Parent_GSA_Potential_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent GSA Potential Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Lead.RecordType.Name</field>
                <operation>equals</operation>
                <value>Potential Provider GSA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Provider_Meeting__c.object
<CustomObject>
    <label>Provider Meeting</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Provider Meeting No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Provider_Meeting_Participant__c.object
<CustomObject>
    <fields>
        <fullName>GSA_Renewal_Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If checked, it means that it&apos;s the latest information available for this provider</description>
        <label>GSA Renewal Participant</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2</booleanFilter>
            <filterItems>
                <field>Contact.Account.License_Status__c</field>
                <operation>equals</operation>
                <value>Licensed</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.Is_GSA__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Provider Meeting Participants</relationshipLabel>
        <relationshipName>Provider_Meeting_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation_Status__c</fullName>
        <description>Status of the registration / participation</description>
        <label>Participation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Potential_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For PPM meeting, potential provider that is registered / attended to this meeting</description>
        <label>Potential Provider</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Provider Meeting Participants</relationshipLabel>
        <relationshipName>Provider_Meeting_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Meeting__c</fullName>
        <description>Meeting the participant is registered / attended to</description>
        <label>Provider Meeting</label>
        <referenceTo>Provider_Meeting__c</referenceTo>
        <relationshipLabel>Provider Meeting Participants</relationshipLabel>
        <relationshipName>Provider_Meeting_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Provider Meeting Participant</label>
    <nameField>
        <displayFormat>PMA-{0000000}</displayFormat>
        <label>Provider Meeting Participant No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_PotentialProviderController.cls
public with sharing class EEC_PotentialProviderController {	
	public string contactFirstName{get;set;}
	public string contactLastName{get;set;}
	public string parentLeadId{get;set;}
	public Lead lead {get;set;}
	
    public EEC_PotentialProviderController(ApexPages.StandardController std){
    	parentLeadId = std.getId();
    	lead = [select Id, Company from Lead where id =: parentLeadId];
    }
     
    public PageReference doSave(){
    	RecordType rt = [select Id from RecordType where Name = 'Potential Provider (Additional Participant)' and SobjectType = 'Lead' limit 1];
    	
    	Lead potentialProvider = new Lead();
    	potentialProvider.RecordTypeId = rt.Id;
    	potentialProvider.FirstName = contactFirstName;
    	potentialProvider.LastName = contactLastName;
    	potentialProvider.Parent_GSA_Potential_Provider__c = parentLeadId;
    	potentialProvider.Company = lead.Company;

    	insert potentialProvider;
    	
    	List<Provider_Meeting_Participant__c> listMeetingParticipant = new List<Provider_Meeting_Participant__c>();
    	
    	for(Provider_Meeting_Participant__c participant: [select Id, Provider_Meeting__c,
		    	Participation_Status__c, GSA_Renewal_Participant__c from Provider_Meeting_Participant__c where 
		    	Potential_Provider__c =: parentLeadId]){
    		Provider_Meeting_Participant__c newParticipant = new Provider_Meeting_Participant__c();
    		newParticipant.Provider_Meeting__c = participant.Provider_Meeting__c;
    		newParticipant.Potential_Provider__c = potentialProvider.Id;
    		newParticipant.Participation_Status__c = participant.Participation_Status__c;
    		listMeetingParticipant.add(newParticipant);
    	}
    	
    	if(listMeetingParticipant.size() > 0)
    		insert listMeetingParticipant;
    	
    	PageReference pg = new PageReference('/' + potentialProvider.Id);
    	return pg;
    } 
    
    public PageReference doCancel(){
    	PageReference pg = new PageReference('/' + parentLeadId);
    	return pg; 
    }
}