phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Attachments_Returned_for_Revision__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attachments Returned for Revision</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EEC_Note_For_Revision__c</fullName>
        <label>EEC Note For Revision</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Returned_for_Revision__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transaction Returned for Revision</label>
        <type>Checkbox</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Transaction_Document__c.object
<CustomObject>
    <description>A junction between the Document and a transaction.</description>
    <fields>
        <fullName>Licensing_Transaction__c</fullName>
        <label>Licensing Transaction</label>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Upload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - EEC to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Attachment</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction Document</label>
    <nameField>
        <displayFormat>TD- {0000000}</displayFormat>
        <label>Transaction Document ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_SendTransactionToProviderController.cls
public with sharing class EEC_SendTransactionToProviderController {
	public Licensing_Transaction__c licensingTransaction{get;set;}
	public string mode{get;set;}
	public string parent{get;set;}
	
    public EEC_SendTransactionToProviderController(ApexPages.StandardController std){
    try {
      licensingTransaction = [select Id, EEC_Note_For_Revision__c, 
      Attachments_Returned_for_Revision__c, Transaction_Returned_for_Revision__c from Licensing_Transaction__c where Id=: std.getId()];
      mode = ApexPages.currentPage().getParameters().get('mode');
      parent = ApexPages.currentPage().getParameters().get('parent');
    } catch(Exception e) {
      System.debug('----> Error: ' + e.getMessage());
    }
  }
  
  public void sendForRevision(){
  	try{
  		licensingTransaction.Transaction_Returned_for_Revision__c = true;
  		update licensingTransaction;
  		
  		List<Transaction_Document__c> listTransactionDocument = [select Id, Status__c from Transaction_Document__c where
  		Status__c = 'Rejected' and Licensing_Transaction__c=: licensingTransaction.Id];
  		
  		system.debug('listTransactionDocument: ' + listTransactionDocument);
  		for(Transaction_Document__c transactionDocument : listTransactionDocument){
  			transactionDocument.Status__c = 'Returned for Revision';
  		}
  		update listTransactionDocument;
  		
  		system.debug('listTransactionDocument: ' + listTransactionDocument);
  	}
  	catch(Exception ex){
  		system.debug('error from sendForRevision: ' + ex.getMessage());
  	}
  }
  
  public void sendRejectedDocuments(){
  	try{
  		licensingTransaction.Attachments_Returned_for_Revision__c = true;
  		update licensingTransaction;
  		
  		List<Transaction_Document__c> listTransactionDocument = [select Id, Status__c from Transaction_Document__c where
  		Status__c = 'Rejected' and Licensing_Transaction__c=: licensingTransaction.Id];
  		
  		system.debug('listTransactionDocument: ' + listTransactionDocument);
  		for(Transaction_Document__c transactionDocument : listTransactionDocument){
  			transactionDocument.Status__c = 'Returned for Revision';
  		}
  		update listTransactionDocument;
  		
  		system.debug('listTransactionDocument: ' + listTransactionDocument);
  	}
  	catch(Exception ex){
  		system.debug('error from sendRejectedDocuments: ' + ex.getMessage());
  	}
  }
}