phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Last_Reached_Step__c</fullName>
        <inlineHelpText>Last steps reached by Portal User.</inlineHelpText>
        <label>Last Reached Step</label>
        <picklist>
            <picklistValues>
                <fullName>Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction / Provider Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Members</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Status and Capacity / Assistant Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEC Involvement Experience &amp; Professional Exp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Background Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indoor / Outdoor space information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Routing Activities / Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attachments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Summary and Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensing Status and Capacity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Variance_on_Regulation__c.object
<CustomObject>
    <description>Variance on regulation can be requested by a provider when it can not be in compliance with a specific regulation. Every variance should be associated to 1 reg.</description>
    <label>Variance on Regulation</label>
    <nameField>
        <displayFormat>VAR- {000000}</displayFormat>
        <label>Variance No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Variance on Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_VarianceInfoStepCtrl.cls
public class EEC_VarianceInfoStepCtrl extends EEC_BaseTransactionStep implements EEC_VarianceInterface {

  private List<EEC_VarianceListCtrl.VarianceInfoWrap> varianceInfoWrappers { get; set; }

  /**
   * Constructor
   *
   * @description The constructor for the class.
   * @author Latha Davuluri
   * @created 18 Jan 2017
   * @return EEC_VarianceInfoStepCtrl 
   */
  public EEC_VarianceInfoStepCtrl() {
    super();
    // Set defaults.
  }
  
  /**
   * getCtrlInstance
   * 
   * This function will return an instance of this controller with interface reference.
   * @author Latha Davuluri
   * @return EEC_VarianceInfoStepCtrl
   */
  public EEC_VarianceInfoStepCtrl getCtrlInstance() {
    return this;
  }

  /**
   * VarianceInfoSave
   *
   * @description A one stop location for all traversal paths for Variance Information.
   * @authour Latha Davuluri
   * @param saveType Integer The save type attempted.
   * @return PageReference 
   */
  public PageReference VarianceInfoSave() {
    PageReference pPage;
    Integer saveType = Integer.valueOf(ApexPages.currentPage().getParameters().get('saveType'));
    List<Variance_on_Regulation__c> variancesToUpsert = new List<Variance_on_Regulation__c> ();

    System.debug('----> varianceInfoWrappers: ' + varianceInfoWrappers);
    if (varianceInfoWrappers != null && varianceInfoWrappers.size() > 0) {
      for (EEC_VarianceListCtrl.VarianceInfoWrap wrapper : varianceInfoWrappers) {
        variancesToUpsert.add(wrapper.varianceReg);
      }
      System.debug('----> variancesToUpsert: ' + variancesToUpsert);
      upsert variancesToUpsert;
    }

    if (saveType == SAVE_AND_NEXT) {
      // Change the last step.
      licenseTransaction.Last_Reached_Step__c = 'Attachments';
      // Setup the page.
      pPage.getParameters().put('ltId', licenseTransaction.Id);
    } else if (saveType == SAVE_AND_PREVIOUS) {
      // Change the last step.
      licenseTransaction.Last_Reached_Step__c = 'Technical Assistance';
      // Setup the page.
      pPage = Page.EEC_LicenseStatusCapacityInfo;
      pPage.getParameters().put('ltId', licenseTransaction.Id);
    } else if (saveType == SAVE_AND_RETURN) {
      // Change the last step.
      licenseTransaction.Last_Reached_Step__c = 'Technical Assistance';
      // Setup the page.
      pPage = page.EEC_PortalProviderPage;
    }
    update licenseTransaction;

    if (pPage != null) {
      EEC_Util.addMemberIDPageParameter(memberId, pPage, false);
      pPage.setRedirect(true);
    }
    
    return pPage;
  }

  /*-----Interface Methods-----*/
  public void updateVarianceWrapperList(List<EEC_VarianceListCtrl.VarianceInfoWrap> varianceInfoWrappers) {
    System.debug('----> varianceInfoWrappers: ' + varianceInfoWrappers);
    System.debug('----> this.varianceInfoWrappers: ' + this.varianceInfoWrappers);
    this.varianceInfoWrappers = varianceInfoWrappers;
    System.debug('----> this.varianceInfoWrappers: ' + this.varianceInfoWrappers);
  }

  public Licensing_Transaction__c getBaseLicenseTransaction() {
    return licenseTransaction;
  }

  public String getBaseLicenseRecordTypeName() {
    return LicenseRecordTypeName;
  }
}