phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Last_Reached_Step__c</fullName>
        <inlineHelpText>Last steps reached by Portal User.</inlineHelpText>
        <label>Last Reached Step</label>
        <picklist>
            <picklistValues>
                <fullName>Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction / Provider Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Members</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Status and Capacity / Assistant Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEC Involvement Experience &amp; Professional Exp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Background Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indoor / Outdoor space information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Routing Activities / Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attachments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Summary and Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensing Status and Capacity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>FCC_Renewal</fullName>
        <active>true</active>
        <label>FCC Renewal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_AssistantInfoStepCtrlTest.cls
@isTest
public class EEC_AssistantInfoStepCtrlTest {

  public static Account loadTestData(PageReference lPageRef, String buttonLabel, String index) {
    Account accnt = EEC_TestUtil.loadLicenseTransaction();
    PageReference pageRef = lPageRef;
    pageRef.getParameters().put('accountId', accnt.Id);
    pageRef.getParameters().put('buttonLabel', buttonLabel);
    pageRef.getParameters().put('index', index);
    Test.setCurrentPage(pageRef);
    EEC_TestUtil.mockAWSKeys();
    return accnt;
  }
  
  public static testmethod void testAssistantListCtrl(){
        Account acc = EEC_AssistantListCtrlTest.loadTestData(Page.EEC_Transaction_AssistantInfo, 'Apply for a New License', '1');
      	System.assertNotEquals(null, acc);
  }  

  public static testMethod void testGetCtrlInstance() {
    Account accnt = loadTestData(Page.EEC_Transaction_AssistantInfo, 'Apply for a New License', '1');
    Licensing_Transaction__c lic = [select Id from Licensing_Transaction__c where Provider__c = :accnt.Id limit 1];
    ApexPages.currentPage().getParameters().put('ltId', lic.Id);

    EEC_AssistantInfoStepCtrl ctrl = new EEC_AssistantInfoStepCtrl();
    System.assertEquals(ctrl, ctrl.getCtrlInstance());
  }

  static testmethod void testAssistantInfoSave() {
      Test.startTest();
      Account accnt = loadTestData(Page.EEC_Transaction_AssistantInfo,'Apply for a New License','1');
      Licensing_Transaction__c lic = [select Id from Licensing_Transaction__c where Provider__c = :accnt.Id limit 1];
      ApexPages.currentPage().getParameters().put('saveType', '1');
      ApexPages.currentPage().getParameters().put('ltId', lic.Id);

      EEC_AssistantInfoStepCtrl controller = new EEC_AssistantInfoStepCtrl();
      controller.AssistantInfoSave();
      System.assertEquals('Background Information', controller.getBaseLicenseTransaction().Last_Reached_Step__c);

      ApexPages.currentPage().getParameters().put('saveType', '3');
      controller.AssistantInfoSave();
      System.assertEquals('Assistant Information', controller.getBaseLicenseTransaction().Last_Reached_Step__c);

      // This flow needs to have the page reference tested as well due to multiple conditions.
      ApexPages.currentPage().getParameters().put('saveType', '2');
      controller.AssistantInfoSave();
      System.assertEquals('Assistant Information', controller.getBaseLicenseTransaction().Last_Reached_Step__c);
    }

    public static testmethod void testInterfaceMethods() {
      Account accnt = loadTestData(Page.EEC_Transaction_AssistantInfo, 'Apply for a New License', '1');
      Licensing_Transaction__c lic = [select Id from Licensing_Transaction__c where Provider__c = :accnt.Id limit 1];
      ApexPages.currentPage().getParameters().put('ltId', lic.Id);

      EEC_AssistantInfoStepCtrl ctrl = new EEC_AssistantInfoStepCtrl();
      System.assertEquals(ctrl.getBaseLicenseRecordTypeName(), 'FCC_Renewal');

      List<EEC_AssistantListCtrl.AssistantInfoWrap> tempList = new List<EEC_AssistantListCtrl.AssistantInfoWrap>();
      ctrl.updateAssistantWrapperList(tempList);
    }
}