phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Licensing_Transactions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Transaction Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Reached_Step__c</fullName>
        <inlineHelpText>Last steps reached by Portal User.</inlineHelpText>
        <label>Last Reached Step</label>
        <picklist>
            <picklistValues>
                <fullName>Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction / Provider Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Household Members</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Status and Capacity / Assistant Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEC Involvement Experience &amp; Professional Exp.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Background Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indoor / Outdoor space information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily Routing Activities / Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attachments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Summary and Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensing Status and Capacity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Information</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_Closed_Cancelled__c</fullName>
        <label>Reason Transaction Closed / Cancelled</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Provider Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Licensing_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Special_Requests_Comments__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <label>Transaction Special Requests / Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Variance_on_Regulation__c.object
<CustomObject>
    <description>Variance on regulation can be requested by a provider when it can not be in compliance with a specific regulation. Every variance should be associated to 1 reg.</description>
    <fields>
        <fullName>Associated_Regulation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Regulation</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Regulation__c.Date_Active__c</field>
                <operation>lessOrEqual</operation>
                <valueField>$Source.Date_today__c</valueField>
            </filterItems>
            <filterItems>
                <field>Regulation__c.Date_Removed__c</field>
                <operation>greaterOrEqual</operation>
                <valueField>$Source.Date_today__c</valueField>
            </filterItems>
            <filterItems>
                <field>Regulation__c.Date_Removed__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Variance on Regulations</relationshipLabel>
        <relationshipName>Variance_on_Regulations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Alternative_Method_to_Comply__c</fullName>
        <label>Provider Alternative Method to Comply</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Understanding_of_Regulation__c</fullName>
        <label>Provider Understanding of Regulation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Variance on Regulations</relationshipLabel>
        <relationshipName>Variance_on_Regulations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_Transaction__c</fullName>
        <label>Source Transaction</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Licensing_Transaction__c.Provider__r.Id</field>
                <operation>equals</operation>
                <value>Variance on Regulation: Provider</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Variance on Regulations</relationshipLabel>
        <relationshipName>Variance_on_Regulations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Variance on Regulation</label>
    <nameField>
        <displayFormat>VAR- {000000}</displayFormat>
        <label>Variance No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Variance on Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_ViewVarianceTransactionController.cls
public without sharing class EEC_ViewVarianceTransactionController implements EEC_AssistantInterface{
  public Id ltId { get; set; }
  public Licensing_Transaction__c licenseTransation { get; set; }
  public String licenseRecordTypeName { get; set; }
  public String licenseRecordTypeLabel { get; set; }
  public String memberId { get; set; }
  
  public EEC_ViewVarianceTransactionController() {
    ltId = ApexPages.currentPage().getParameters().get('ltID');
    memberId = ApexPages.currentPage().getParameters().get('member');
    getLicenseTrans();
  }

  public void getLicenseTrans() {
    List<Licensing_Transaction__c> ltList = [Select Provider__r.Name, RecordType.DeveloperName, RecordType.Name, Name,
    										Status__c,Last_Reached_Step__c,
    										Submission_Date__c,Submitter__r.FirstName,
    										Submitter__r.LastName,Source__c,Date_Closed__c,
											Reason_Closed_Cancelled__c,
											Assigned_To__r.FirstName,Assigned_To__r.LastName,
											Assigned_To__r.Phone,Assigned_To__r.Email,
											Transaction_Special_Requests_Comments__c,    										
											(Select Id,Associated_Regulation__c,Associated_Regulation__r.Name,Associated_Regulation__r.Regulation_Number__c,
											Associated_Regulation__r.Article__c,Provider_Alternative_Method_to_Comply__c,
											Provider_Understanding_of_Regulation__c From Variance_on_Regulations__r)											
											 From Licensing_Transaction__c where Id = :ltId];

    if (ltList != null && ltList.size() > 0) {
      licenseTransation = ltList.get(0);
      licenseRecordTypeName = licenseTransation.RecordType.DeveloperName;
      licenseRecordTypeLabel = licenseTransation.RecordType.Name;
    }
    else{
      ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please Provide a valid Licensing Transaction Id');
      ApexPages.addMessage(msg);
      return;
    }
  }
  
  public List<SelectOption> getItems() {
    List<SelectOption> options = new List<SelectOption> ();
    options.add(new SelectOption('True', 'Yes'));
    options.add(new SelectOption('False', 'No'));
    return options;
  }
  
  public List<SelectOption> getPickItems() {
    List<SelectOption> options = new List<SelectOption> ();
    options.add(new SelectOption('Yes', 'Yes'));
    options.add(new SelectOption('No', 'No'));
    return options;
  }
  
  public Pagereference CancelTransaction() {
    licenseTransation.Status__c = 'Cancelled';
    licenseTransation.Reason_Closed_Cancelled__c = 'Cancelled by portal user';

	licenseTransation = EEC_ContactRoleUtil.updateLicensingTransaction(licenseTransation);
	
    PageReference pPage = page.EEC_PortalProviderPage;
    if (memberId != null)
    pPage.getParameters().put('member', EEC_Util.encryptGetParam(memberId));
    return pPage;
  }

  public Pagereference backInstruction() {
    PageReference pPage = page.EEC_PortalProviderPage;
    if (memberId != null)
    pPage.getParameters().put('member', EEC_Util.encryptGetParam(memberId));
    return pPage;
  }

  public Pagereference editInstruction() {
    PageReference pPage = EEC_Util.lastStepMap.get(licenseTransation.Last_Reached_Step__c);
    pPage.getParameters().put('ltId', licenseTransation.Id);
    pPage.getParameters().put('accountId', memberId);
    return pPage;
  }

  /**
   * getCtrlInstance
   * 
   * This function will return an instance of this controller with interface reference.
   * @author Darkis
   * @return EEC_ViewTransactionController
   */
  public EEC_ViewVarianceTransactionController getCtrlInstance() {
    return this;
  }

  /*-----Interface Methods-----*/
  public void updateAssistantWrapperList(List<EEC_AssistantListCtrl.AssistantInfoWrap> providerAssistantWrappers) {
    
   }

  public Licensing_Transaction__c getBaseLicenseTransaction() {
    return licenseTransation;
  }

  public String getBaseLicenseRecordTypeName() {
    return licenseRecordTypeName;
  }
 }