phase2_Dev/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>MissingElementsUpdateNoDisplay__c</fullName>
        <label>MissingElementsUpdateNoDisplay</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by Applicant)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled (by EEC User)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (EEC Application Incomplete / Denied)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_LicenseTransactionMissingElements.cls
public with sharing class EEC_LicenseTransactionMissingElements {

    public Licensing_Transaction__c lt;
    public Boolean reload {get; set;}

    public EEC_LicenseTransactionMissingElements(ApexPages.StandardController sc) {
        this.reload = false;
        this.lt = (Licensing_Transaction__c)sc.getRecord();
        Long timeSinceLastUpdate;
        lt = [SELECT Id, Provider__c, Status__c
                    , MissingElementsUpdateNoDisplay__c, lastModifiedDate
                FROM Licensing_Transaction__c 
                WHERE Id = :lt.Id];
        if(lt.MissingElementsUpdateNoDisplay__c <> null ){
            timeSinceLastUpdate = Datetime.now().getTime() - lt.MissingElementsUpdateNoDisplay__c.getTime();
        }
        Boolean transactionUpdated = timeSinceLastUpdate > 5000 //This is to break page refresh loop
                                    || lt.MissingElementsUpdateNoDisplay__c == null
                                    || lt.lastModifiedDate.getTime() - lt.MissingElementsUpdateNoDisplay__c.getTime() > 5000;
        if(lt.Status__c != 'To Submit' && !lt.Status__c.contains('closed') && transactionUpdated){
            reload = true;
            lt.MissingElementsUpdateNoDisplay__c = Datetime.now();
        }
        
    }

    public void updateMissingElements(){
        if(reload){
            update lt;
        }
    }
}