phase2_Dev/src/objects/Login_History__c.object
<CustomObject>
    <fields>
        <fullName>Browser__c</fullName>
        <label>Browser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoginTime__c</fullName>
        <label>LoginTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LoginType__c</fullName>
        <label>LoginType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <externalId>true</externalId>
        <label>UserId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Login History</label>
    <nameField>
        <label>Login History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_GenerateLoginHistoryExtension.cls
public class EEC_GenerateLoginHistoryExtension {

    private Id conId;

    public EEC_GenerateLoginHistoryExtension(ApexPages.StandardController ctr){
        this.conId = ctr.getId();
    } 
    
    public List<Login_History__c> getLoginHistory(){
        
        List<Login_History__c> lHistory = new List<Login_History__c>();
        User[] user = [SELECT Id FROM User WHERE IsActive = true AND IsPortalEnabled = true AND contactId = :conId];
        if(user.size() > 0){
            lHistory = [
                SELECT Browser__c, LoginType__c, Platform__c, Status__c, Id, LoginTime__c 
                  FROM Login_History__c 
                WHERE UserId__c =: user[0].Id
                AND LoginTime__c = LAST_N_DAYS:120 
                ORDER BY LoginTime__c DESC
            ]; 
        }
        
        return lHistory;

    }
}