phase2_Dev/src/objects/Login_History__c.object
<CustomObject>
    <fields>
        <fullName>Browser__c</fullName>
        <label>Browser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoginTime__c</fullName>
        <label>LoginTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LoginType__c</fullName>
        <label>LoginType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <externalId>true</externalId>
        <label>UserId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Login History</label>
    <nameField>
        <label>Login History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_BatchLoginHistoryUpdate.cls
global class EEC_BatchLoginHistoryUpdate implements Database.Batchable <sObject>{

    String pQuery = '';
    global EEC_BatchLoginHistoryUpdate(String query) 
    {
        this.pQuery =  query;
    }
    
    global EEC_BatchLoginHistoryUpdate()
    {
        this.pQuery =  'SELECT Browser, LoginType, Platform, Status, Id, LoginTime,UserId ' +
            		   'FROM LoginHistory ' +
            		   'WHERE UserId IN (SELECT Id FROM User WHERE IsActive = true AND IsPortalEnabled = true) ' +
            		   ' AND LoginTime = LAST_N_DAYS:120 ORDER BY LoginTime DESC';
    }
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator(pQuery);
    } 
    global void execute(Database.BatchableContext BC, List<LoginHistory> loginHistory)
    {
        List<Login_History__c> loginHistoryInsertList = new List<Login_History__c>();
        
        List<Login_History__c> lHist = [SELECT Id,Name FROM Login_History__c WHERE CreatedDate <> TODAY];
        if(lHist <> null && lHist.size() > 0)
            Database.delete(lHist);
                
        for(LoginHistory h : loginHistory){
           Login_History__c lh = new Login_History__c();
           lh.Browser__c = h.Browser;
           lh.LoginTime__c = h.LoginTime;
           lh.Status__c = h.Status;
           lh.Platform__c = h.Platform;
           lh.LoginType__c = h.LoginType;
           lh.UserId__c = h.UserId; 
            
           loginHistoryInsertList.add(lh); 
       }
       
       if (loginHistoryInsertList <> null && loginHistoryInsertList.size() > 0){
           Database.insert(loginHistoryInsertList);
       }
    }
    global void finish(Database.BatchableContext BC)
    {
        
    }
  }