phase2_Dev/src/objects/Provider_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Meeting_Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region the meeting will be hold</description>
        <label>Meeting Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Provider Meetings</relationshipLabel>
        <relationshipName>Provider_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <description>Type of meeting that will be conducted</description>
        <label>Meeting Type</label>
        <picklist>
            <picklistValues>
                <fullName>PPM (FCC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPM (GSA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal (GSA)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start__c</fullName>
        <description>Start Time of the meeting</description>
        <label>Scheduled Start</label>
        <type>DateTime</type>
    </fields>
    <label>Provider Meeting</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Provider Meeting No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Provider_Meeting_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <formula>GSA_Renewal_Participant__r.Name_text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Region__c</fullName>
        <formula>Provider_Meeting__r.Meeting_Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <formula>TEXT( Provider_Meeting__r.Meeting_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participation_Status__c</fullName>
        <description>Status of the registration / participation</description>
        <label>Participation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Potential_Provider_Name__c</fullName>
        <formula>Potential_Provider__r.Name_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Potential Provider Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Meeting__c</fullName>
        <description>Meeting the participant is registered / attended to</description>
        <label>Provider Meeting</label>
        <referenceTo>Provider_Meeting__c</referenceTo>
        <relationshipLabel>Provider Meeting Participants</relationshipLabel>
        <relationshipName>Provider_Meeting_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Time__c</fullName>
        <formula>Provider_Meeting__r.Scheduled_Start__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scheduled Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Provider Meeting Participant</label>
    <nameField>
        <displayFormat>PMA-{0000000}</displayFormat>
        <label>Provider Meeting Participant No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provider Meeting Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_PPMAttachmentCertificatePDF.cls
public with sharing class EEC_PPMAttachmentCertificatePDF {
     public Provider_Meeting__c providerMeeting{get;set;}
     public string meetingType{get;set;}
     
     public EEC_PPMAttachmentCertificatePDF(ApexPages.StandardController std){
        Id id = std.getId();
        providerMeeting = [SELECT Id,Name, Meeting_Type__c,Meeting_Region__c,Scheduled_Start__c, (select Id, Potential_Provider_Name__c, Meeting_Type__c, Meeting_Region__c, Scheduled_Start_Time__c, Contact_Name__c, Participation_Status__c from Provider_Meeting_Participants__r where Participation_Status__c='Attended') FROM Provider_Meeting__c WHERE Id = :id];
        
        if(providerMeeting.Meeting_Type__c == 'PPM (FCC)'){
        	meetingType = 'Family Child Care Potential Provider Meeting';
        }
        else if(providerMeeting.Meeting_Type__c == 'PPM (GSA)'){
        	meetingType = 'Group and School Age Potential Provider Meeting';
        }
        else if(providerMeeting.Meeting_Type__c == 'Renewal (GSA)'){
        	meetingType = 'Group and School Age Renewal Meeting';
        } 
    }
    
     public PageReference savePDF(){
        PageReference pagePdf = pdfPageReference();
        pagePdf.getParameters().put('id', providerMeeting.id); 
             
        
        Attachment a = new Attachment();
        a.Body = Test.isRunningTest() ? Blob.valueOf('UNIT.TEST') : pagePdf.getContentAsPdf();
        a.ParentID = providerMeeting.ID;
        a.Name = 'Attendance Certificate-' + providerMeeting.Name + '.pdf';
        
        insert a;
                 
        return new PageReference('/' + providerMeeting.Id);
    }
    
     public PageReference pdfPageReference(){
        return Page.EEC_PPMAttendanceGenerateCertificatePDF;
    } 
}