phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this regulation applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Variance_on_Regulation__c.object
<CustomObject>
    <description>Variance on regulation can be requested by a provider when it can not be in compliance with a specific regulation. Every variance should be associated to 1 reg.</description>
    <fields>
        <fullName>Associated_Regulation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Associated Regulation</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>Regulation__c.Date_Active__c</field>
                <operation>lessOrEqual</operation>
                <valueField>$Source.Date_today__c</valueField>
            </filterItems>
            <filterItems>
                <field>Regulation__c.Date_Removed__c</field>
                <operation>greaterOrEqual</operation>
                <valueField>$Source.Date_today__c</valueField>
            </filterItems>
            <filterItems>
                <field>Regulation__c.Date_Removed__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Variance on Regulations</relationshipLabel>
        <relationshipName>Variance_on_Regulations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Variance on Regulations</relationshipLabel>
        <relationshipName>Variance_on_Regulations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Variance on Regulation</label>
    <nameField>
        <displayFormat>VAR- {000000}</displayFormat>
        <label>Variance No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Variance on Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_VarianceOnRegulationTriggerHandler.cls
public class EEC_VarianceOnRegulationTriggerHandler {
    
    List<Variance_on_Regulation__c> newVRList;
    Map<Id, Variance_on_Regulation__c> oldVRMap;
    Map<Id, Regulation__c> arMap;
    Map<Id, Account> providerMap;
    List<ID> arIDs = new List<ID>();
    List<ID> providerIDs = new List<ID>();
    public EEC_VarianceOnRegulationTriggerHandler(List<Variance_on_Regulation__c > newList, Map<Id, Variance_on_Regulation__c > oldList){
        this.newVRList = newList;
        this.oldVRMap = oldList;
        
        for(Variance_on_Regulation__c vr : newVRList){
            arIDs.add(vr.Associated_Regulation__c);
            providerIDs.add(vr.Provider__c);
        }
        if(arIDs.size() > 0){
            arMap = new Map<Id, Regulation__c>([SELECT ID,Applicable_To__c FROM Regulation__c  WHERE ID IN : arIDs]);
        }
        if(providerIds.size() > 0){
            providerMap = new Map<Id,Account>([SELECT ID, RecordType.Name FROM Account WHERE ID IN: providerIds]);
        }
                
    }
    
    
    public void checkRegulationProvider(){
        for(Variance_on_Regulation__c vr : newVRList){
            if(arMap.size() > 0){
                Regulation__c  ar = arMap.get(vr.Associated_Regulation__c);
                Account acc = providerMap.get(vr.Provider__c);
                System.debug('Regulation--->' + acc.RecordType.Name);
                System.debug('Regulation--->' + ar.Applicable_To__c.Contains(acc.RecordType.Name));
                if(!ar.Applicable_To__c.Contains(acc.RecordType.Name)){
                    vr.addError('Regulations should be applicable to the Provider type associated to the variance');
                }
            }
        }
    }
    
    
}