phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this regulation applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Date_Active__c</fullName>
        <description>Date this regulation must be applied</description>
        <inlineHelpText>Date this regulation must be applied by Provider</inlineHelpText>
        <label>Date Active</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reg_key__c</fullName>
        <description>Regulation key from external system (EECRS)</description>
        <label>Reg_key</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Checklist_Reference__c.object
<CustomObject>
    <description>Standard Checklist Reference object manages standard inspection checklists for all Provider Types</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this checklist applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Available_for__c</fullName>
        <inlineHelpText>List of visit reasons that could use this visit tool. If a reason is selected, then this tool should be available as a selection for this type of visits.</inlineHelpText>
        <label>Available for</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Licensing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License 90-day Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Full Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Activate Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Change</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of how and when this checklist should be used.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Recommended_for__c</fullName>
        <label>Recommended for</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Licensing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Full Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Activate Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License 90-day Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Change</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Visit Tool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this inspection item applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Provide information related to the category of inspection items that could be used later to organize inspection items during a visit</description>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care of Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Child Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Home Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General records/logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health/Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personnel Records</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the items to inspect</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Guidance__c</fullName>
        <label>Guidance</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StdVisitItemReg__c</fullName>
        <description>the value in this field is used to create visit item regs on the stdvisitItem.</description>
        <label>StdVisitItemReg</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StdVisitItemTool__c</fullName>
        <description>Used to tag the standard visit Item to a Visit Tool</description>
        <label>StdVisitItemTool</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/VisitItemsStaging__c.object
<CustomObject>
    <description>Staging object used to load Differential Licensing Tools</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guidance__c</fullName>
        <label>Guidance</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>VisitItemsStaging</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VisitItemsStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/VisitItemStagingTriggerTest.cls
@isTest
public with sharing class VisitItemStagingTriggerTest {
	
	 @isTest static void bulkInsertStandardVisitItemsTest() {
	 	
	    Standard_Checklist_Reference__c visitTool = new Standard_Checklist_Reference__c ();
        visitTool.Name = 'FCC Progress Tool';
        visitTool.Applicable_To__c = 'Family Child Care';
        visitTool.Recommended_for__c = 'Progress';
        visitTool.Available_for__c = 'Progress';
        insert visitTool;
         
        system.debug('***VisitTool'+visitTool); 
         
        Regulation__c reg = new Regulation__c();
        reg.Applicable_To__c = 'Family Child Care';
        reg.Name = '14.14';
        reg.Date_Active__c = system.today();
        reg.Reg_key__c = 'FGS-18';
        insert reg;
         
        Standard_Inspection_Item__c stdVItm = new Standard_Inspection_Item__c();
         
	 	stdVItm.Name = 'Test Name';
	 	stdVItm.Description__c = 'Test Description';
	 	stdVItm.Guidance__c = 'This is a test Guidance';
	 	stdVItm.Category__c ='Inspections';
	 	stdVItm.StdVisitItemReg__c = '14.14';
	 	stdVItm.StdVisitItemTool__c = 'FCC Progress Tool';
	 	
	   insert stdVItm;
         
       
       Standard_Inspection_Item__c stdVItm2 = stdVItm.clone();
       stdVItm2.Category__c ='Inspections2';  
       insert stdVItm2;
         
       Junction_ChklInsp__c visitToolAssgn = new Junction_ChklInsp__c();
       visitToolAssgn.Standard_Checklist_Reference__c = visitTool.Id;
       visitToolAssgn.Standard_Inspection_Item__c = stdVItm.Id;  
       
       insert visitToolAssgn;  
         
       visitItemsStaging__c vts = new visitItemsStaging__c();
	   vts.Name = 'Test Name';
	   vts.Description__c ='Test Description';
	   vts.Guidance__c ='This is a test guidance';
	   vts.IsRandomItem__c = true;
	   vts.RandomItemDomain__c ='Administration';
	   vts.ProviderType__c = 'Family Child Care';
	   vts.VisitItemDomain__c = 'Inspections';
	   vts.VisitItemRegulation__c ='14.14';
	   vts.VisitItemToolAssignment__c = 'FCC Progress Tool';
       vts.Override__c = false; 
        	
       insert vts;
         
       visitItemsStaging__c vts2 = vts.clone(); 
       vts2.VisitItemDomain__c = 'TestDomain2';
       insert vts2;  
       
       VisitItemsStaging__c vtsResult = [Select Id,Name,VisitItemRegulation__c,IsRandomItem__c From VisitItemsStaging__c Where id = :vts.Id];
         
       Standard_Inspection_Item__c stdVisitItm = [Select Id,Name,StdVisitItemReg__c,StdVisitItemRandom__c From Standard_Inspection_Item__c Where Name='Test Name' and Category__c ='TestDomain2'];
       
       Junction_InspReg__c vItmRegResult = [Select Standard_Inspection_Item__c, Regulation__c From Junction_InspReg__c Where Standard_Inspection_Item__c = :stdVItm2.Id];
	 
       system.debug('****visitTool.Id'+visitTool.Id);  
       Junction_ChklInsp__c visitToolResult = [Select Standard_Inspection_Item__c, Standard_Checklist_Reference__c  From  Junction_ChklInsp__c Where Standard_Inspection_Item__c = :stdVItm.Id and Standard_Checklist_Reference__c = :visitTool.Id];
           
       system.assert(vItmRegResult != null);  
       system.assert(stdVisitItm != null);
       //system.debug(visitToolResult != null);  
            
        //system.debug('***stdVisitItm.StdVisitItemRandom__c:'+stdVisitItm.StdVisitItemRandom__c);
        //system.debug('***vtsResult.IsRandomItem__c:'+vtsResult.IsRandomItem__c);
        system.assertEquals(stdVisitItm.StdVisitItemRandom__c, vtsResult.IsRandomItem__c); 
        
        VisitItemsStaging__c VIResult = [Select Id,Name From VisitItemsStaging__c Where name ='Test Name' and VisitItemDomain__c ='TestDomain2'];
     	
     	system.assert(VIResult != null);
     		
        Test.startTest();
     	  string SOQL = 'Select Id from VisitItemsStaging__c';
    	  Database.executeBatch(new Batch_CleanVisitItemStaging(SOQL),200); 
        Test.stopTest();
        List<VisitItemsStaging__c> VIResult2 = [Select Id,Name From VisitItemsStaging__c Where name = 'Test Name'];
        
     	system.assert(VIResult2.isEmpty());

     
         
	 	
	 }
	 

}