phase2_Dev/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF( 
    AND(NOT(ISBLANK( Date_Active__c )),
        TODAY() &gt;= Date_Active__c   ,
        OR( ISBLANK( Date_Removed__c ) , (Date_Removed__c  &gt;=  TODAY()) ) ) , 
        TRUE, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this regulation applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Checklist_Reference__c.object
<CustomObject>
    <description>Standard Checklist Reference object manages standard inspection checklists for all Provider Types</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this checklist is active and can be used.</description>
        <inlineHelpText>If checked, this checklist is active and can be used. If not checked, it will not be available for use.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this checklist applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of how and when this checklist should be used.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Visit Tool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this inspection item applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Provide information related to the category of inspection items that could be used later to organize inspection items during a visit</description>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care of Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Child Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Home Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General records/logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health/Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personnel Records</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the items to inspect</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Guidance__c</fullName>
        <label>Guidance</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/VisitItemsStaging__c.object
<CustomObject>
    <description>Staging object used to load Differential Licensing Tools</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guidance__c</fullName>
        <label>Guidance</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsRandomItem__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRandomItem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProviderType__c</fullName>
        <label>ProviderType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RandomItemDomain__c</fullName>
        <label>RandomItemDomain</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisitItemDomain__c</fullName>
        <label>VisitItemDomain</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisitItemRegulation__c</fullName>
        <label>VisitItemRegulation</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisitItemToolAssignment__c</fullName>
        <label>VisitItemToolAssignment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>VisitItemsStaging</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VisitItemsStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_LoadDLTools.cls
//Author: Latha Davuluri
public with sharing class EEC_LoadDLTools {
	
	public static void loadFCCDLTools(VisitItemsStaging__c visitItm){
		List<String> applicableToList = new List<String>(); 
        
        applicableToList.add(visitItm.ProviderType__c);

        //stdVisitItemsMap
        Map<string,Standard_Inspection_Item__c> stdVisitItemsMap = new Map<string,Standard_Inspection_Item__c>();
        List<Standard_Inspection_Item__c> stdVisitItemsList = new List<Standard_Inspection_Item__c>([Select Id,Name, Category__c From Standard_Inspection_Item__c Where applicable_to__c in :applicableToList]);
        for(Standard_Inspection_Item__c sv: stdVisitItemsList){
            stdVisitItemsMap.put(sv.Name, sv);
        }
        
        system.debug('##### applicableToList...'+ applicableToList);
        
        system.debug('##### Std Visit Items Map...'+ stdVisitItemsMap);
    
        List<Standard_Inspection_Item__c> stdVisitItemsToInsert = new List<Standard_Inspection_Item__c>();
        List<Standard_Inspection_Item__c> stdVisitItemsToUpdate = new List<Standard_Inspection_Item__c>();
        
        if (!string.isBlank(visitItm.Name)){
            Standard_Inspection_Item__c sv = stdVisitItemsMap.get(visitItm.Name.trim());
            system.debug('*** sv***'+ sv);
            system.debug('****visitItm.Override__c *****'+visitItm.Override__c);
           // system.debug('*****3'+sv.Category__c);
            system.debug('***4'+ visitItm.VisitItemDomain__c);
            
             if (sv != null && !visitItm.Override__c && sv.Category__c == visitItm.VisitItemDomain__c){
                system.debug('##### Visit Item Found in Map...'+ sv);
                sv.Description__c = visitItm.Description__c;
                sv.Guidance__c = visitItm.Guidance__c; 
                createOrUpdateJuncObjects(sv.Id,visitItm,false);
                stdVisitItemsToUpdate.add(sv);
             }
             else{
             	system.debug('##### Visit Item NOT Found in Map...');
             	Standard_Inspection_Item__c svItm = new Standard_Inspection_Item__c();
             	 
             	svItm.Name = visitItm.Name.trim();
                svItm.Description__c = visitItm.Description__c;
                svItm.Category__c = visitItm.VisitItemDomain__c;
                svItm.Guidance__c = visitItm.Guidance__c;
                svItm.Applicable_To__c = visitItm.ProviderType__c;
                stdVisitItemsToInsert.add(svItm);
             }
   
	    }
	    	    
	    if (stdVisitItemsToInsert.size() > 0){
            insert stdVisitItemsToInsert;          
            createOrUpdateJuncObjects(stdVisitItemsToInsert[0].Id,visitItm,true);
         } 
         
         if(stdVisitItemsToUpdate.size()>0){
         	update stdVisitItemsToUpdate;
         }
	}
	
	private static void createOrUpdateJuncObjects(Id stdVisitItemId,VisitItemsStaging__c visitItm, boolean createRegs){
		//Regulations Map
		Map<string,Id> regMap = new Map<string,Id>();
	    // Tools Map 
		Map<string,Id> vistToolsMap = new Map<string,Id>();
		List<String> stdVisitItmRegList;  
		Id regId;
		Id visitToolId;
		 /** Code to insert into ToolAssignments and ToolRegulations objects */
             List<Junction_InspReg__c> visitItmRegsToCreate = new List<Junction_InspReg__c>();
			 List<Junction_ChklInsp__c> toolVisitItemsToCreate = new List<Junction_ChklInsp__c>();
		
			  
			 List<Regulation__c> regList = new List<Regulation__c>([Select Id,Name From Regulation__c]);
			 for(Regulation__c rg : regList){
			  	  regMap.put(rg.Name,rg.Id);
			   }
			   
			 List<Standard_Checklist_Reference__c> vistToolsList = new List<Standard_Checklist_Reference__c>([Select Id,Name From Standard_Checklist_Reference__c Where Active__c = true]);
			 for(Standard_Checklist_Reference__c chkRef : vistToolsList){
			  	 vistToolsMap.put(chkRef.Name, chkRef.Id);
			  }
				   				  	  
		  	  //Insert into Visit Items Regulation ONLY if createRegs = true
		  	  if (createRegs){
			  	  if (!string.isBlank(visitItm.VisitItemRegulation__c)){	
			  	  	 
			  	  	 stdVisitItmRegList = visitItm.VisitItemRegulation__c.split(';');		  	  	 		  	  	
			  	  	 
			  	  	 for(string vistItmReg : stdVisitItmRegList){
			  	  	    
			  	  	    regId = regMap.get(vistItmReg.trim());
			  	  	 	
			  	  	 	if(regId != null){
			  	  	 		
			  	  	 		Junction_InspReg__c vItmReg = new Junction_InspReg__c();
			  	  	 		
				  	  	 	vItmReg.Standard_Inspection_Item__c = stdVisitItemId;
					        vItmReg.Regulation__c = regId;
					        visitItmRegsToCreate.add(vItmReg);	
			  	  	 	  }  		  	  	      	  	 	 	  	 	
			  	  	   } // for loop for Regs List
			  	    }
		  	  }
				  	     
	  	     //Insert into Tool Assignments		  	     
	  	     if (!string.isBlank(visitItm.VisitItemToolAssignment__c)){
	  	  	   
	  	  	    visitToolId = vistToolsMap.get(visitItm.VisitItemToolAssignment__c.trim());
	  	  	 	
	  	  	 	if(visitToolId != null){
	  	  	 		
	  	  	 		Junction_ChklInsp__c toolVisitItem = new Junction_ChklInsp__c();
	  	  	 		
		  	  	 	toolVisitItem.Standard_Checklist_Reference__c = visitToolId; 	
		  	  	 	toolVisitItem.Standard_Inspection_Item__c = stdVisitItemId;
		  	  	 	toolVisitItem.Random_Item__c = visitItm.IsRandomItem__c;
		  	  	 	if(toolVisitItem.Random_Item__c){
		  	  	 	   toolVisitItem.Random_Item_Domain__c = visitItm.RandomItemDomain__c;
		  	  	 	}
		  	  	 	toolVisitItemsToCreate.add(toolVisitItem);
	  	  	 	}	
	  	     }
			  	 	  		  	 
			  
			 if (visitItmRegsToCreate.size() > 0) {
			  	 insert visitItmRegsToCreate; 
			   }
			  
			 if (toolVisitItemsToCreate.size() > 0){
			  	insert toolVisitItemsToCreate;
			  } 
            
            /**ends here **/
	}

}