phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the items to inspect</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/VisitItemsStaging__c.object
<CustomObject>
    <description>Staging object used to load Differential Licensing Tools</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisitItemRegulation__c</fullName>
        <label>VisitItemRegulation</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisitItemToolAssignment__c</fullName>
        <label>VisitItemToolAssignment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>VisitItemsStaging</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VisitItemsStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/EEC_LoadDLToolsTest.cls
@isTest 
public class EEC_LoadDLToolsTest {
   
    static testMethod void eecloaddltools(){
        test.startTest();
    	List<VisitItemsStaging__c> visit = new List <VisitItemsStaging__c>();
         VisitItemsStaging__c visit1 = new VisitItemsStaging__c();
         visit1.Name = 'test';
         visit1.Description__c = 'testd';
         visit1.VisitItemToolAssignment__c = 'Residential gertg';
         visit1.VisitItemRegulation__c = 'regulation';
         Junction_InspReg__c vItmReg = new Junction_InspReg__c();
         vItmReg.Standard_Inspection_Item__c = visit1.Id; 
        
         visit.add(visit1); 
       		
         
         EEC_LoadDLTools.loadFCCDLTools(visit1);   
        test.stopTest();
  		    
}
    
}