phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Provide information related to the category of inspection items that could be used later to organize inspection items during a visit</description>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care of Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Child Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Home Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General records/logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health/Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personnel Records</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the items to inspect</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Guidance__c</fullName>
        <label>Guidance</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StdVisitItemRandomDomainName__c</fullName>
        <label>StdVisitItemRandomDomainName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StdVisitItemRandom__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to flag Random/Non-Random on Visit Tool</description>
        <label>StdVisitItemRandom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StdVisitItemReg__c</fullName>
        <description>the value in this field is used to create visit item regs on the stdvisitItem.</description>
        <label>StdVisitItemReg</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StdVisitItemTool__c</fullName>
        <description>Used to tag the standard visit Item to a Visit Tool</description>
        <label>StdVisitItemTool</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/StandardVisitItemTriggerTest.cls
@isTest
public with sharing class StandardVisitItemTriggerTest {
	
	@isTest static void bulkInsertStandardVisitItemsTest() {
	 	
	 	Standard_Inspection_Item__c stdVisitItm = new Standard_Inspection_Item__c();
	 	stdVisitItm.Name = 'Test Name';
	 	stdVisitItm.Description__c = 'Test Desc';
	 	stdVisitItm.Guidance__c = 'This is a test Guidance';
	 	stdVisitItm.Category__c ='Inspections';
	 	stdVisitItm.StdVisitItemRandom__c = false;
	 	stdVisitItm.StdVisitItemRandomDomainName__c = '';
	 	stdVisitItm.StdVisitItemReg__c = '7.27;7.27(a)';
	 	stdVisitItm.StdVisitItemTool__c = 'FCC Progress Tool';
	 	
	 	insert stdVisitItm;
	 	
	 	stdVisitItm.StdVisitItemRandom__c = true;
	 	stdVisitItm.StdVisitItemRandomDomainName__c = 'Administration';
	 	
	 	update stdVisitItm;
        
       
	 }

}