phase2_Dev/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this inspection item applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Provide information related to the category of inspection items that could be used later to organize inspection items during a visit</description>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care of Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Child Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Home Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General records/logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health/Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personnel Records</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the items to inspect</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Guidance__c</fullName>
        <label>Guidance</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StdVisitItemRandomDomainName__c</fullName>
        <label>StdVisitItemRandomDomainName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StdVisitItemRandom__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to flag Random/Non-Random on Visit Tool</description>
        <label>StdVisitItemRandom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StdVisitItemReg__c</fullName>
        <description>the value in this field is used to create visit item regs on the stdvisitItem.</description>
        <label>StdVisitItemReg</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StdVisitItemTool__c</fullName>
        <description>Used to tag the standard visit Item to a Visit Tool</description>
        <label>StdVisitItemTool</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/objects/VisitItemsStaging__c.object
<CustomObject>
    <description>Staging object used to load Differential Licensing Tools</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guidance__c</fullName>
        <label>Guidance</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsRandomItem__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRandomItem</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProviderType__c</fullName>
        <label>ProviderType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RandomItemDomain__c</fullName>
        <label>RandomItemDomain</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisitItemDomain__c</fullName>
        <label>VisitItemDomain</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisitItemRegulation__c</fullName>
        <label>VisitItemRegulation</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisitItemToolAssignment__c</fullName>
        <label>VisitItemToolAssignment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>VisitItemsStaging</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VisitItemsStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

phase2_Dev/src/classes/VisitItemStagingTriggerHelper.cls
public with sharing class VisitItemStagingTriggerHelper {   
    
    public static void bulkInsertStandardVisitItems(List<VisitItemsStaging__c> triggerNew){
      
        List<String> applicableToList = new List<String>();
        for(VisitItemsStaging__c v : triggerNew){
            applicableToList.add(v.ProviderType__c);
        }
        
        //stdVisitItemsMap
        Map<string,Standard_Inspection_Item__c> stdVisitItemsMap = new Map<string,Standard_Inspection_Item__c>();
        List<Standard_Inspection_Item__c> stdVisitItemsList = new List<Standard_Inspection_Item__c>([Select Id,Name, Category__c From Standard_Inspection_Item__c Where applicable_to__c in :applicableToList]);
        for(Standard_Inspection_Item__c sv: stdVisitItemsList){
            stdVisitItemsMap.put(sv.Name, sv);
        }
        
        system.debug('##### applicableToList...'+ applicableToList);
        
        system.debug('##### Std Visit Items Map...'+ stdVisitItemsMap);
    
        Map<Id,Standard_Inspection_Item__c> stdVisitItemsToUpdate = new Map<Id,Standard_Inspection_Item__c>();
        List<Standard_Inspection_Item__c> stdVisitItemsToInsert = new List<Standard_Inspection_Item__c>();
    
        for(VisitItemsStaging__c visitItm : triggerNew){
            Standard_Inspection_Item__c sv = stdVisitItemsMap.get(visitItm.Name);
            
             //system.debug('##### Item Found in Map...'+ sv);
             
            
            Standard_Inspection_Item__c svItm = new Standard_Inspection_Item__c();
                        
            if (sv != null && visitItm.Override__c == false){
                //or(Standard_Inspection_Item__c sv : svList){
                    //Update the Existing Standard Visit Item to flag as Random Item and Set the Random Domain name
                    if (sv.Name.trim() == visitItm.Name.trim() && sv.Category__c.trim() == visitItm.VisitItemDomain__c.trim()){ //&& visitItm.IsRandomItem__c)
                        system.debug('##### In Update...'+ sv);
                        svItm.Id = sv.Id;
                        
                        if (visitItm.IsRandomItem__c){
                            svItm.StdVisitItemRandom__c = visitItm.IsRandomItem__c;
                            svItm.StdVisitItemRandomDomainName__c = visitItm.RandomItemDomain__c;
                        }
                        svItm.StdVisitItemTool__c = visitItm.VisitItemToolAssignment__c;
                        stdVisitItemsToUpdate.put(svItm.Id,svItm);
                    }
                    else if (sv.Name.trim() == visitItm.Name.trim() && sv.Category__c.trim() != visitItm.VisitItemDomain__c.trim()){// && visitItm.IsRandomItem__c == false)
                        
                        system.debug('##### In Update..ELSE....'+ sv);
                        system.debug('##### In Update..ELSE....'+ visitItm);
                        
                        svItm.Name = visitItm.Name.trim();
                        svItm.Description__c = visitItm.Description__c;
                        svItm.Category__c = visitItm.VisitItemDomain__c;
                        svItm.Guidance__c = visitItm.Guidance__c;
                        svItm.StdVisitItemRandom__c = visitItm.IsRandomItem__c;
                        svItm.StdVisitItemRandomDomainName__c = visitItm.RandomItemDomain__c;
                        svItm.StdVisitItemReg__c = visitItm.VisitItemRegulation__c;
                        svItm.StdVisitItemTool__c = visitItm.VisitItemToolAssignment__c;
                        svItm.Applicable_To__c = visitItm.ProviderType__c;
                        stdVisitItemsToInsert.add(svItm);                   
                    }
                //}         
            }
            else{
                system.debug('##### In Insert..ELSE....'+ visitItm);
                svItm.Name = visitItm.Name.trim();
                svItm.Description__c = visitItm.Description__c;
                svItm.Category__c = visitItm.VisitItemDomain__c;
                svItm.Guidance__c = visitItm.Guidance__c;
                svItm.StdVisitItemRandom__c = visitItm.IsRandomItem__c;
                svItm.StdVisitItemRandomDomainName__c = visitItm.RandomItemDomain__c;
                svItm.StdVisitItemReg__c = visitItm.VisitItemRegulation__c;
                svItm.StdVisitItemTool__c = visitItm.VisitItemToolAssignment__c;
                svItm.Applicable_To__c = visitItm.ProviderType__c;
                stdVisitItemsToInsert.add(svItm);
            }
            
        }
        
        if (stdVisitItemsToUpdate.size() > 0) {
            
            system.debug('##### stdVisitItemsToUpdate...'+ stdVisitItemsToUpdate.values());
             update stdVisitItemsToUpdate.values(); 
        } 
          
        if (stdVisitItemsToInsert.size() > 0){
            insert stdVisitItemsToInsert;
         } 
         
        // Call Batch to cleanup VisitItemsStaging 
        string SOQL = 'Select Id from VisitItemsStaging__c';
        Database.executeBatch(new Batch_CleanVisitItemStaging(SOQL),200); 
             
     }
 
}